// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Vulkan\VK\VK10;

class VK10
{
    public static function vkCreateInstance(int pCreateInfo, int pAllocator, int pInstance) -> int
    {
        return vk10_vkcreateinstance(pCreateInfo, pAllocator, pInstance);
    }

    public static function vkDestroyInstance(int instance, int pAllocator) -> void
    {
        vk10_vkdestroyinstance(instance, pAllocator);
    }

    public static function vkEnumeratePhysicalDevices(int instance, int pPhysicalDeviceCount, int pPhysicalDevices) -> int
    {
        return vk10_vkenumeratephysicaldevices(instance, pPhysicalDeviceCount, pPhysicalDevices);
    }

    public static function vkGetPhysicalDeviceFeatures(int physicalDevice, int pFeatures) -> void
    {
        vk10_vkgetphysicaldevicefeatures(physicalDevice, pFeatures);
    }

    public static function vkGetPhysicalDeviceFormatProperties(int physicalDevice, int format, int pFormatProperties) -> void
    {
        vk10_vkgetphysicaldeviceformatproperties(physicalDevice, format, pFormatProperties);
    }

    public static function vkGetPhysicalDeviceImageFormatProperties(int physicalDevice, int format, int type, int tiling, int usage, int flags, int pImageFormatProperties) -> int
    {
        return vk10_vkgetphysicaldeviceimageformatproperties(physicalDevice, format, type, tiling, usage, flags, pImageFormatProperties);
    }

    public static function vkGetPhysicalDeviceProperties(int physicalDevice, int pProperties) -> void
    {
        vk10_vkgetphysicaldeviceproperties(physicalDevice, pProperties);
    }

    public static function vkGetPhysicalDeviceQueueFamilyProperties(int physicalDevice, int pQueueFamilyPropertyCount, int pQueueFamilyProperties) -> void
    {
        vk10_vkgetphysicaldevicequeuefamilyproperties(physicalDevice, pQueueFamilyPropertyCount, pQueueFamilyProperties);
    }

    public static function vkGetPhysicalDeviceMemoryProperties(int physicalDevice, int pMemoryProperties) -> void
    {
        vk10_vkgetphysicaldevicememoryproperties(physicalDevice, pMemoryProperties);
    }

    public static function vkGetInstanceProcAddr(int instance, string pName) -> int
    {
        return vk10_vkgetinstanceprocaddr(instance, pName);
    }

    public static function vkGetDeviceProcAddr(int device, string pName) -> int
    {
        return vk10_vkgetdeviceprocaddr(device, pName);
    }

    public static function vkCreateDevice(int physicalDevice, int pCreateInfo, int pAllocator, int pDevice) -> int
    {
        return vk10_vkcreatedevice(physicalDevice, pCreateInfo, pAllocator, pDevice);
    }

    public static function vkDestroyDevice(int device, int pAllocator) -> void
    {
        vk10_vkdestroydevice(device, pAllocator);
    }

    public static function vkEnumerateInstanceExtensionProperties(string pLayerName, int pPropertyCount, int pProperties) -> int
    {
        return vk10_vkenumerateinstanceextensionproperties(pLayerName, pPropertyCount, pProperties);
    }

    public static function vkEnumerateDeviceExtensionProperties(int physicalDevice, string pLayerName, int pPropertyCount, int pProperties) -> int
    {
        return vk10_vkenumeratedeviceextensionproperties(physicalDevice, pLayerName, pPropertyCount, pProperties);
    }

    public static function vkEnumerateInstanceLayerProperties(int pPropertyCount, int pProperties) -> int
    {
        return vk10_vkenumerateinstancelayerproperties(pPropertyCount, pProperties);
    }

    public static function vkEnumerateDeviceLayerProperties(int physicalDevice, int pPropertyCount, int pProperties) -> int
    {
        return vk10_vkenumeratedevicelayerproperties(physicalDevice, pPropertyCount, pProperties);
    }

    public static function vkGetDeviceQueue(int device, int queueFamilyIndex, int queueIndex, int pQueue) -> void
    {
        vk10_vkgetdevicequeue(device, queueFamilyIndex, queueIndex, pQueue);
    }

    public static function vkQueueSubmit(int queue, int submitCount, int pSubmits, int fence) -> int
    {
        return vk10_vkqueuesubmit(queue, submitCount, pSubmits, fence);
    }

    public static function vkQueueWaitIdle(int queue) -> int
    {
        return vk10_vkqueuewaitidle(queue);
    }

    public static function vkDeviceWaitIdle(int device) -> int
    {
        return vk10_vkdevicewaitidle(device);
    }

    public static function vkAllocateMemory(int device, int pAllocateInfo, int pAllocator, int pMemory) -> int
    {
        return vk10_vkallocatememory(device, pAllocateInfo, pAllocator, pMemory);
    }

    public static function vkFreeMemory(int device, int memory, int pAllocator) -> void
    {
        vk10_vkfreememory(device, memory, pAllocator);
    }

    public static function vkMapMemory(int device, int memory, int offset, int size, int flags, int ppData) -> int
    {
        return vk10_vkmapmemory(device, memory, offset, size, flags, ppData);
    }

    public static function vkUnmapMemory(int device, int memory) -> void
    {
        vk10_vkunmapmemory(device, memory);
    }

    public static function vkFlushMappedMemoryRanges(int device, int memoryRangeCount, int pMemoryRanges) -> int
    {
        return vk10_vkflushmappedmemoryranges(device, memoryRangeCount, pMemoryRanges);
    }

    public static function vkInvalidateMappedMemoryRanges(int device, int memoryRangeCount, int pMemoryRanges) -> int
    {
        return vk10_vkinvalidatemappedmemoryranges(device, memoryRangeCount, pMemoryRanges);
    }

    public static function vkGetDeviceMemoryCommitment(int device, int memory, int pCommittedMemoryInBytes) -> void
    {
        vk10_vkgetdevicememorycommitment(device, memory, pCommittedMemoryInBytes);
    }

    public static function vkBindBufferMemory(int device, int buffer, int memory, int memoryOffset) -> int
    {
        return vk10_vkbindbuffermemory(device, buffer, memory, memoryOffset);
    }

    public static function vkBindImageMemory(int device, int image, int memory, int memoryOffset) -> int
    {
        return vk10_vkbindimagememory(device, image, memory, memoryOffset);
    }

    public static function vkGetBufferMemoryRequirements(int device, int buffer, int pMemoryRequirements) -> void
    {
        vk10_vkgetbuffermemoryrequirements(device, buffer, pMemoryRequirements);
    }

    public static function vkGetImageMemoryRequirements(int device, int image, int pMemoryRequirements) -> void
    {
        vk10_vkgetimagememoryrequirements(device, image, pMemoryRequirements);
    }

    public static function vkGetImageSparseMemoryRequirements(int device, int image, int pSparseMemoryRequirementCount, int pSparseMemoryRequirements) -> void
    {
        vk10_vkgetimagesparsememoryrequirements(device, image, pSparseMemoryRequirementCount, pSparseMemoryRequirements);
    }

    public static function vkGetPhysicalDeviceSparseImageFormatProperties(int physicalDevice, int format, int type, int samples, int usage, int tiling, int pPropertyCount, int pProperties) -> void
    {
        vk10_vkgetphysicaldevicesparseimageformatproperties(physicalDevice, format, type, samples, usage, tiling, pPropertyCount, pProperties);
    }

    public static function vkQueueBindSparse(int queue, int bindInfoCount, int pBindInfo, int fence) -> int
    {
        return vk10_vkqueuebindsparse(queue, bindInfoCount, pBindInfo, fence);
    }

    public static function vkCreateFence(int device, int pCreateInfo, int pAllocator, int pFence) -> int
    {
        return vk10_vkcreatefence(device, pCreateInfo, pAllocator, pFence);
    }

    public static function vkDestroyFence(int device, int fence, int pAllocator) -> void
    {
        vk10_vkdestroyfence(device, fence, pAllocator);
    }

    public static function vkResetFences(int device, int fenceCount, int pFences) -> int
    {
        return vk10_vkresetfences(device, fenceCount, pFences);
    }

    public static function vkGetFenceStatus(int device, int fence) -> int
    {
        return vk10_vkgetfencestatus(device, fence);
    }

    public static function vkWaitForFences(int device, int fenceCount, int pFences, bool waitAll, int timeout) -> int
    {
        return vk10_vkwaitforfences(device, fenceCount, pFences, waitAll, timeout);
    }

    public static function vkCreateSemaphore(int device, int pCreateInfo, int pAllocator, int pSemaphore) -> int
    {
        return vk10_vkcreatesemaphore(device, pCreateInfo, pAllocator, pSemaphore);
    }

    public static function vkDestroySemaphore(int device, int semaphore, int pAllocator) -> void
    {
        vk10_vkdestroysemaphore(device, semaphore, pAllocator);
    }

    public static function vkCreateQueryPool(int device, int pCreateInfo, int pAllocator, int pQueryPool) -> int
    {
        return vk10_vkcreatequerypool(device, pCreateInfo, pAllocator, pQueryPool);
    }

    public static function vkDestroyQueryPool(int device, int queryPool, int pAllocator) -> void
    {
        vk10_vkdestroyquerypool(device, queryPool, pAllocator);
    }

    public static function vkGetQueryPoolResults(int device, int queryPool, int firstQuery, int queryCount, int dataSize, int pData, int stride, int flags) -> int
    {
        return vk10_vkgetquerypoolresults(device, queryPool, firstQuery, queryCount, dataSize, pData, stride, flags);
    }

    public static function vkCreateBuffer(int device, int pCreateInfo, int pAllocator, int pBuffer) -> int
    {
        return vk10_vkcreatebuffer(device, pCreateInfo, pAllocator, pBuffer);
    }

    public static function vkDestroyBuffer(int device, int buffer, int pAllocator) -> void
    {
        vk10_vkdestroybuffer(device, buffer, pAllocator);
    }

    public static function vkCreateImage(int device, int pCreateInfo, int pAllocator, int pImage) -> int
    {
        return vk10_vkcreateimage(device, pCreateInfo, pAllocator, pImage);
    }

    public static function vkDestroyImage(int device, int image, int pAllocator) -> void
    {
        vk10_vkdestroyimage(device, image, pAllocator);
    }

    public static function vkGetImageSubresourceLayout(int device, int image, int pSubresource, int pLayout) -> void
    {
        vk10_vkgetimagesubresourcelayout(device, image, pSubresource, pLayout);
    }

    public static function vkCreateImageView(int device, int pCreateInfo, int pAllocator, int pView) -> int
    {
        return vk10_vkcreateimageview(device, pCreateInfo, pAllocator, pView);
    }

    public static function vkDestroyImageView(int device, int imageView, int pAllocator) -> void
    {
        vk10_vkdestroyimageview(device, imageView, pAllocator);
    }

    public static function vkCreateCommandPool(int device, int pCreateInfo, int pAllocator, int pCommandPool) -> int
    {
        return vk10_vkcreatecommandpool(device, pCreateInfo, pAllocator, pCommandPool);
    }

    public static function vkDestroyCommandPool(int device, int commandPool, int pAllocator) -> void
    {
        vk10_vkdestroycommandpool(device, commandPool, pAllocator);
    }

    public static function vkResetCommandPool(int device, int commandPool, int flags) -> int
    {
        return vk10_vkresetcommandpool(device, commandPool, flags);
    }

    public static function vkAllocateCommandBuffers(int device, int pAllocateInfo, int pCommandBuffers) -> int
    {
        return vk10_vkallocatecommandbuffers(device, pAllocateInfo, pCommandBuffers);
    }

    public static function vkFreeCommandBuffers(int device, int commandPool, int commandBufferCount, int pCommandBuffers) -> void
    {
        vk10_vkfreecommandbuffers(device, commandPool, commandBufferCount, pCommandBuffers);
    }

    public static function vkBeginCommandBuffer(int commandBuffer, int pBeginInfo) -> int
    {
        return vk10_vkbegincommandbuffer(commandBuffer, pBeginInfo);
    }

    public static function vkEndCommandBuffer(int commandBuffer) -> int
    {
        return vk10_vkendcommandbuffer(commandBuffer);
    }

    public static function vkResetCommandBuffer(int commandBuffer, int flags) -> int
    {
        return vk10_vkresetcommandbuffer(commandBuffer, flags);
    }

    public static function vkCmdCopyBuffer(int commandBuffer, int srcBuffer, int dstBuffer, int regionCount, int pRegions) -> void
    {
        vk10_vkcmdcopybuffer(commandBuffer, srcBuffer, dstBuffer, regionCount, pRegions);
    }

    public static function vkCmdCopyImage(int commandBuffer, int srcImage, int srcImageLayout, int dstImage, int dstImageLayout, int regionCount, int pRegions) -> void
    {
        vk10_vkcmdcopyimage(commandBuffer, srcImage, srcImageLayout, dstImage, dstImageLayout, regionCount, pRegions);
    }

    public static function vkCmdCopyBufferToImage(int commandBuffer, int srcBuffer, int dstImage, int dstImageLayout, int regionCount, int pRegions) -> void
    {
        vk10_vkcmdcopybuffertoimage(commandBuffer, srcBuffer, dstImage, dstImageLayout, regionCount, pRegions);
    }

    public static function vkCmdCopyImageToBuffer(int commandBuffer, int srcImage, int srcImageLayout, int dstBuffer, int regionCount, int pRegions) -> void
    {
        vk10_vkcmdcopyimagetobuffer(commandBuffer, srcImage, srcImageLayout, dstBuffer, regionCount, pRegions);
    }

    public static function vkCmdUpdateBuffer(int commandBuffer, int dstBuffer, int dstOffset, int dataSize, int pData) -> void
    {
        vk10_vkcmdupdatebuffer(commandBuffer, dstBuffer, dstOffset, dataSize, pData);
    }

    public static function vkCmdFillBuffer(int commandBuffer, int dstBuffer, int dstOffset, int size, int data) -> void
    {
        vk10_vkcmdfillbuffer(commandBuffer, dstBuffer, dstOffset, size, data);
    }

    public static function vkCmdPipelineBarrier(int commandBuffer, int srcStageMask, int dstStageMask, int dependencyFlags, int memoryBarrierCount, int pMemoryBarriers, int bufferMemoryBarrierCount, int pBufferMemoryBarriers, int imageMemoryBarrierCount, int pImageMemoryBarriers) -> void
    {
        vk10_vkcmdpipelinebarrier(commandBuffer, srcStageMask, dstStageMask, dependencyFlags, memoryBarrierCount, pMemoryBarriers, bufferMemoryBarrierCount, pBufferMemoryBarriers, imageMemoryBarrierCount, pImageMemoryBarriers);
    }

    public static function vkCmdBeginQuery(int commandBuffer, int queryPool, int query, int flags) -> void
    {
        vk10_vkcmdbeginquery(commandBuffer, queryPool, query, flags);
    }

    public static function vkCmdEndQuery(int commandBuffer, int queryPool, int query) -> void
    {
        vk10_vkcmdendquery(commandBuffer, queryPool, query);
    }

    public static function vkCmdResetQueryPool(int commandBuffer, int queryPool, int firstQuery, int queryCount) -> void
    {
        vk10_vkcmdresetquerypool(commandBuffer, queryPool, firstQuery, queryCount);
    }

    public static function vkCmdWriteTimestamp(int commandBuffer, int pipelineStage, int queryPool, int query) -> void
    {
        vk10_vkcmdwritetimestamp(commandBuffer, pipelineStage, queryPool, query);
    }

    public static function vkCmdCopyQueryPoolResults(int commandBuffer, int queryPool, int firstQuery, int queryCount, int dstBuffer, int dstOffset, int stride, int flags) -> void
    {
        vk10_vkcmdcopyquerypoolresults(commandBuffer, queryPool, firstQuery, queryCount, dstBuffer, dstOffset, stride, flags);
    }

    public static function vkCmdExecuteCommands(int commandBuffer, int commandBufferCount, int pCommandBuffers) -> void
    {
        vk10_vkcmdexecutecommands(commandBuffer, commandBufferCount, pCommandBuffers);
    }

    public static function vkCreateEvent(int device, int pCreateInfo, int pAllocator, int pEvent) -> int
    {
        return vk10_vkcreateevent(device, pCreateInfo, pAllocator, pEvent);
    }

    public static function vkDestroyEvent(int device, int event, int pAllocator) -> void
    {
        vk10_vkdestroyevent(device, event, pAllocator);
    }

    public static function vkGetEventStatus(int device, int event) -> int
    {
        return vk10_vkgeteventstatus(device, event);
    }

    public static function vkSetEvent(int device, int event) -> int
    {
        return vk10_vksetevent(device, event);
    }

    public static function vkResetEvent(int device, int event) -> int
    {
        return vk10_vkresetevent(device, event);
    }

    public static function vkCreateBufferView(int device, int pCreateInfo, int pAllocator, int pView) -> int
    {
        return vk10_vkcreatebufferview(device, pCreateInfo, pAllocator, pView);
    }

    public static function vkDestroyBufferView(int device, int bufferView, int pAllocator) -> void
    {
        vk10_vkdestroybufferview(device, bufferView, pAllocator);
    }

    public static function vkCreateShaderModule(int device, int pCreateInfo, int pAllocator, int pShaderModule) -> int
    {
        return vk10_vkcreateshadermodule(device, pCreateInfo, pAllocator, pShaderModule);
    }

    public static function vkDestroyShaderModule(int device, int shaderModule, int pAllocator) -> void
    {
        vk10_vkdestroyshadermodule(device, shaderModule, pAllocator);
    }

    public static function vkCreatePipelineCache(int device, int pCreateInfo, int pAllocator, int pPipelineCache) -> int
    {
        return vk10_vkcreatepipelinecache(device, pCreateInfo, pAllocator, pPipelineCache);
    }

    public static function vkDestroyPipelineCache(int device, int pipelineCache, int pAllocator) -> void
    {
        vk10_vkdestroypipelinecache(device, pipelineCache, pAllocator);
    }

    public static function vkGetPipelineCacheData(int device, int pipelineCache, int pDataSize, int pData) -> int
    {
        return vk10_vkgetpipelinecachedata(device, pipelineCache, pDataSize, pData);
    }

    public static function vkMergePipelineCaches(int device, int dstCache, int srcCacheCount, int pSrcCaches) -> int
    {
        return vk10_vkmergepipelinecaches(device, dstCache, srcCacheCount, pSrcCaches);
    }

    public static function vkCreateComputePipelines(int device, int pipelineCache, int createInfoCount, int pCreateInfos, int pAllocator, int pPipelines) -> int
    {
        return vk10_vkcreatecomputepipelines(device, pipelineCache, createInfoCount, pCreateInfos, pAllocator, pPipelines);
    }

    public static function vkDestroyPipeline(int device, int pipeline, int pAllocator) -> void
    {
        vk10_vkdestroypipeline(device, pipeline, pAllocator);
    }

    public static function vkCreatePipelineLayout(int device, int pCreateInfo, int pAllocator, int pPipelineLayout) -> int
    {
        return vk10_vkcreatepipelinelayout(device, pCreateInfo, pAllocator, pPipelineLayout);
    }

    public static function vkDestroyPipelineLayout(int device, int pipelineLayout, int pAllocator) -> void
    {
        vk10_vkdestroypipelinelayout(device, pipelineLayout, pAllocator);
    }

    public static function vkCreateSampler(int device, int pCreateInfo, int pAllocator, int pSampler) -> int
    {
        return vk10_vkcreatesampler(device, pCreateInfo, pAllocator, pSampler);
    }

    public static function vkDestroySampler(int device, int sampler, int pAllocator) -> void
    {
        vk10_vkdestroysampler(device, sampler, pAllocator);
    }

    public static function vkCreateDescriptorSetLayout(int device, int pCreateInfo, int pAllocator, int pSetLayout) -> int
    {
        return vk10_vkcreatedescriptorsetlayout(device, pCreateInfo, pAllocator, pSetLayout);
    }

    public static function vkDestroyDescriptorSetLayout(int device, int descriptorSetLayout, int pAllocator) -> void
    {
        vk10_vkdestroydescriptorsetlayout(device, descriptorSetLayout, pAllocator);
    }

    public static function vkCreateDescriptorPool(int device, int pCreateInfo, int pAllocator, int pDescriptorPool) -> int
    {
        return vk10_vkcreatedescriptorpool(device, pCreateInfo, pAllocator, pDescriptorPool);
    }

    public static function vkDestroyDescriptorPool(int device, int descriptorPool, int pAllocator) -> void
    {
        vk10_vkdestroydescriptorpool(device, descriptorPool, pAllocator);
    }

    public static function vkResetDescriptorPool(int device, int descriptorPool, int flags) -> int
    {
        return vk10_vkresetdescriptorpool(device, descriptorPool, flags);
    }

    public static function vkAllocateDescriptorSets(int device, int pAllocateInfo, int pDescriptorSets) -> int
    {
        return vk10_vkallocatedescriptorsets(device, pAllocateInfo, pDescriptorSets);
    }

    public static function vkFreeDescriptorSets(int device, int descriptorPool, int descriptorSetCount, int pDescriptorSets) -> int
    {
        return vk10_vkfreedescriptorsets(device, descriptorPool, descriptorSetCount, pDescriptorSets);
    }

    public static function vkUpdateDescriptorSets(int device, int descriptorWriteCount, int pDescriptorWrites, int descriptorCopyCount, int pDescriptorCopies) -> void
    {
        vk10_vkupdatedescriptorsets(device, descriptorWriteCount, pDescriptorWrites, descriptorCopyCount, pDescriptorCopies);
    }

    public static function vkCmdBindPipeline(int commandBuffer, int pipelineBindPoint, int pipeline) -> void
    {
        vk10_vkcmdbindpipeline(commandBuffer, pipelineBindPoint, pipeline);
    }

    public static function vkCmdBindDescriptorSets(int commandBuffer, int pipelineBindPoint, int layout, int firstSet, int descriptorSetCount, int pDescriptorSets, int dynamicOffsetCount, int pDynamicOffsets) -> void
    {
        vk10_vkcmdbinddescriptorsets(commandBuffer, pipelineBindPoint, layout, firstSet, descriptorSetCount, pDescriptorSets, dynamicOffsetCount, pDynamicOffsets);
    }

    public static function vkCmdClearColorImage(int commandBuffer, int image, int imageLayout, int pColor, int rangeCount, int pRanges) -> void
    {
        vk10_vkcmdclearcolorimage(commandBuffer, image, imageLayout, pColor, rangeCount, pRanges);
    }

    public static function vkCmdDispatch(int commandBuffer, int groupCountX, int groupCountY, int groupCountZ) -> void
    {
        vk10_vkcmddispatch(commandBuffer, groupCountX, groupCountY, groupCountZ);
    }

    public static function vkCmdDispatchIndirect(int commandBuffer, int buffer, int offset) -> void
    {
        vk10_vkcmddispatchindirect(commandBuffer, buffer, offset);
    }

    public static function vkCmdSetEvent(int commandBuffer, int event, int stageMask) -> void
    {
        vk10_vkcmdsetevent(commandBuffer, event, stageMask);
    }

    public static function vkCmdResetEvent(int commandBuffer, int event, int stageMask) -> void
    {
        vk10_vkcmdresetevent(commandBuffer, event, stageMask);
    }

    public static function vkCmdWaitEvents(int commandBuffer, int eventCount, int pEvents, int srcStageMask, int dstStageMask, int memoryBarrierCount, int pMemoryBarriers, int bufferMemoryBarrierCount, int pBufferMemoryBarriers, int imageMemoryBarrierCount, int pImageMemoryBarriers) -> void
    {
        vk10_vkcmdwaitevents(commandBuffer, eventCount, pEvents, srcStageMask, dstStageMask, memoryBarrierCount, pMemoryBarriers, bufferMemoryBarrierCount, pBufferMemoryBarriers, imageMemoryBarrierCount, pImageMemoryBarriers);
    }

    public static function vkCmdPushConstants(int commandBuffer, int layout, int stageFlags, int offset, int size, int pValues) -> void
    {
        vk10_vkcmdpushconstants(commandBuffer, layout, stageFlags, offset, size, pValues);
    }

    public static function vkCreateGraphicsPipelines(int device, int pipelineCache, int createInfoCount, int pCreateInfos, int pAllocator, int pPipelines) -> int
    {
        return vk10_vkcreategraphicspipelines(device, pipelineCache, createInfoCount, pCreateInfos, pAllocator, pPipelines);
    }

    public static function vkCreateFramebuffer(int device, int pCreateInfo, int pAllocator, int pFramebuffer) -> int
    {
        return vk10_vkcreateframebuffer(device, pCreateInfo, pAllocator, pFramebuffer);
    }

    public static function vkDestroyFramebuffer(int device, int framebuffer, int pAllocator) -> void
    {
        vk10_vkdestroyframebuffer(device, framebuffer, pAllocator);
    }

    public static function vkCreateRenderPass(int device, int pCreateInfo, int pAllocator, int pRenderPass) -> int
    {
        return vk10_vkcreaterenderpass(device, pCreateInfo, pAllocator, pRenderPass);
    }

    public static function vkDestroyRenderPass(int device, int renderPass, int pAllocator) -> void
    {
        vk10_vkdestroyrenderpass(device, renderPass, pAllocator);
    }

    public static function vkGetRenderAreaGranularity(int device, int renderPass, int pGranularity) -> void
    {
        vk10_vkgetrenderareagranularity(device, renderPass, pGranularity);
    }

    public static function vkCmdSetViewport(int commandBuffer, int firstViewport, int viewportCount, int pViewports) -> void
    {
        vk10_vkcmdsetviewport(commandBuffer, firstViewport, viewportCount, pViewports);
    }

    public static function vkCmdSetScissor(int commandBuffer, int firstScissor, int scissorCount, int pScissors) -> void
    {
        vk10_vkcmdsetscissor(commandBuffer, firstScissor, scissorCount, pScissors);
    }

    public static function vkCmdSetLineWidth(int commandBuffer, double lineWidth) -> void
    {
        vk10_vkcmdsetlinewidth(commandBuffer, lineWidth);
    }

    public static function vkCmdSetDepthBias(int commandBuffer, double depthBiasConstantFactor, double depthBiasClamp, double depthBiasSlopeFactor) -> void
    {
        vk10_vkcmdsetdepthbias(commandBuffer, depthBiasConstantFactor, depthBiasClamp, depthBiasSlopeFactor);
    }

    public static function vkCmdSetBlendConstants(int commandBuffer, int blendConstants) -> void
    {
        vk10_vkcmdsetblendconstants(commandBuffer, blendConstants);
    }

    public static function vkCmdSetDepthBounds(int commandBuffer, double minDepthBounds, double maxDepthBounds) -> void
    {
        vk10_vkcmdsetdepthbounds(commandBuffer, minDepthBounds, maxDepthBounds);
    }

    public static function vkCmdSetStencilCompareMask(int commandBuffer, int faceMask, int compareMask) -> void
    {
        vk10_vkcmdsetstencilcomparemask(commandBuffer, faceMask, compareMask);
    }

    public static function vkCmdSetStencilWriteMask(int commandBuffer, int faceMask, int writeMask) -> void
    {
        vk10_vkcmdsetstencilwritemask(commandBuffer, faceMask, writeMask);
    }

    public static function vkCmdSetStencilReference(int commandBuffer, int faceMask, int reference) -> void
    {
        vk10_vkcmdsetstencilreference(commandBuffer, faceMask, reference);
    }

    public static function vkCmdBindIndexBuffer(int commandBuffer, int buffer, int offset, int indexType) -> void
    {
        vk10_vkcmdbindindexbuffer(commandBuffer, buffer, offset, indexType);
    }

    public static function vkCmdBindVertexBuffers(int commandBuffer, int firstBinding, int bindingCount, int pBuffers, int pOffsets) -> void
    {
        vk10_vkcmdbindvertexbuffers(commandBuffer, firstBinding, bindingCount, pBuffers, pOffsets);
    }

    public static function vkCmdDraw(int commandBuffer, int vertexCount, int instanceCount, int firstVertex, int firstInstance) -> void
    {
        vk10_vkcmddraw(commandBuffer, vertexCount, instanceCount, firstVertex, firstInstance);
    }

    public static function vkCmdDrawIndexed(int commandBuffer, int indexCount, int instanceCount, int firstIndex, int vertexOffset, int firstInstance) -> void
    {
        vk10_vkcmddrawindexed(commandBuffer, indexCount, instanceCount, firstIndex, vertexOffset, firstInstance);
    }

    public static function vkCmdDrawIndirect(int commandBuffer, int buffer, int offset, int drawCount, int stride) -> void
    {
        vk10_vkcmddrawindirect(commandBuffer, buffer, offset, drawCount, stride);
    }

    public static function vkCmdDrawIndexedIndirect(int commandBuffer, int buffer, int offset, int drawCount, int stride) -> void
    {
        vk10_vkcmddrawindexedindirect(commandBuffer, buffer, offset, drawCount, stride);
    }

    public static function vkCmdBlitImage(int commandBuffer, int srcImage, int srcImageLayout, int dstImage, int dstImageLayout, int regionCount, int pRegions, int filter) -> void
    {
        vk10_vkcmdblitimage(commandBuffer, srcImage, srcImageLayout, dstImage, dstImageLayout, regionCount, pRegions, filter);
    }

    public static function vkCmdClearDepthStencilImage(int commandBuffer, int image, int imageLayout, int pDepthStencil, int rangeCount, int pRanges) -> void
    {
        vk10_vkcmdcleardepthstencilimage(commandBuffer, image, imageLayout, pDepthStencil, rangeCount, pRanges);
    }

    public static function vkCmdClearAttachments(int commandBuffer, int attachmentCount, int pAttachments, int rectCount, int pRects) -> void
    {
        vk10_vkcmdclearattachments(commandBuffer, attachmentCount, pAttachments, rectCount, pRects);
    }

    public static function vkCmdResolveImage(int commandBuffer, int srcImage, int srcImageLayout, int dstImage, int dstImageLayout, int regionCount, int pRegions) -> void
    {
        vk10_vkcmdresolveimage(commandBuffer, srcImage, srcImageLayout, dstImage, dstImageLayout, regionCount, pRegions);
    }

    public static function vkCmdBeginRenderPass(int commandBuffer, int pRenderPassBegin, int contents) -> void
    {
        vk10_vkcmdbeginrenderpass(commandBuffer, pRenderPassBegin, contents);
    }

    public static function vkCmdNextSubpass(int commandBuffer, int contents) -> void
    {
        vk10_vkcmdnextsubpass(commandBuffer, contents);
    }

    public static function vkCmdEndRenderPass(int commandBuffer) -> void
    {
        vk10_vkcmdendrenderpass(commandBuffer);
    }
}
