
extern zend_class_entry *vulkan_struct_vkprivatedataslotcreateinfo_vkprivatedataslotcreateinfo_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkPrivateDataSlotCreateInfo_VkPrivateDataSlotCreateInfo);

PHP_METHOD(Vulkan_Struct_VkPrivateDataSlotCreateInfo_VkPrivateDataSlotCreateInfo, pack);
PHP_METHOD(Vulkan_Struct_VkPrivateDataSlotCreateInfo_VkPrivateDataSlotCreateInfo, packInto);
PHP_METHOD(Vulkan_Struct_VkPrivateDataSlotCreateInfo_VkPrivateDataSlotCreateInfo, unpack);
PHP_METHOD(Vulkan_Struct_VkPrivateDataSlotCreateInfo_VkPrivateDataSlotCreateInfo, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkprivatedataslotcreateinfo_vkprivatedataslotcreateinfo_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkprivatedataslotcreateinfo_vkprivatedataslotcreateinfo_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkprivatedataslotcreateinfo_vkprivatedataslotcreateinfo_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkprivatedataslotcreateinfo_vkprivatedataslotcreateinfo_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkprivatedataslotcreateinfo_vkprivatedataslotcreateinfo_method_entry) {
	PHP_ME(Vulkan_Struct_VkPrivateDataSlotCreateInfo_VkPrivateDataSlotCreateInfo, pack, arginfo_vulkan_struct_vkprivatedataslotcreateinfo_vkprivatedataslotcreateinfo_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPrivateDataSlotCreateInfo_VkPrivateDataSlotCreateInfo, packInto, arginfo_vulkan_struct_vkprivatedataslotcreateinfo_vkprivatedataslotcreateinfo_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPrivateDataSlotCreateInfo_VkPrivateDataSlotCreateInfo, unpack, arginfo_vulkan_struct_vkprivatedataslotcreateinfo_vkprivatedataslotcreateinfo_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPrivateDataSlotCreateInfo_VkPrivateDataSlotCreateInfo, size, arginfo_vulkan_struct_vkprivatedataslotcreateinfo_vkprivatedataslotcreateinfo_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
