
extern zend_class_entry *vulkan_struct_vkdescriptorupdatetemplatecreateinfo_vkdescriptorupdatetemplatecreateinfo_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkDescriptorUpdateTemplateCreateInfo_VkDescriptorUpdateTemplateCreateInfo);

PHP_METHOD(Vulkan_Struct_VkDescriptorUpdateTemplateCreateInfo_VkDescriptorUpdateTemplateCreateInfo, pack);
PHP_METHOD(Vulkan_Struct_VkDescriptorUpdateTemplateCreateInfo_VkDescriptorUpdateTemplateCreateInfo, packInto);
PHP_METHOD(Vulkan_Struct_VkDescriptorUpdateTemplateCreateInfo_VkDescriptorUpdateTemplateCreateInfo, unpack);
PHP_METHOD(Vulkan_Struct_VkDescriptorUpdateTemplateCreateInfo_VkDescriptorUpdateTemplateCreateInfo, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkdescriptorupdatetemplatecreateinfo_vkdescriptorupdatetemplatecreateinfo_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkdescriptorupdatetemplatecreateinfo_vkdescriptorupdatetemplatecreateinfo_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkdescriptorupdatetemplatecreateinfo_vkdescriptorupdatetemplatecreateinfo_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkdescriptorupdatetemplatecreateinfo_vkdescriptorupdatetemplatecreateinfo_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkdescriptorupdatetemplatecreateinfo_vkdescriptorupdatetemplatecreateinfo_method_entry) {
	PHP_ME(Vulkan_Struct_VkDescriptorUpdateTemplateCreateInfo_VkDescriptorUpdateTemplateCreateInfo, pack, arginfo_vulkan_struct_vkdescriptorupdatetemplatecreateinfo_vkdescriptorupdatetemplatecreateinfo_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkDescriptorUpdateTemplateCreateInfo_VkDescriptorUpdateTemplateCreateInfo, packInto, arginfo_vulkan_struct_vkdescriptorupdatetemplatecreateinfo_vkdescriptorupdatetemplatecreateinfo_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkDescriptorUpdateTemplateCreateInfo_VkDescriptorUpdateTemplateCreateInfo, unpack, arginfo_vulkan_struct_vkdescriptorupdatetemplatecreateinfo_vkdescriptorupdatetemplatecreateinfo_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkDescriptorUpdateTemplateCreateInfo_VkDescriptorUpdateTemplateCreateInfo, size, arginfo_vulkan_struct_vkdescriptorupdatetemplatecreateinfo_vkdescriptorupdatetemplatecreateinfo_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
