// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Vulkan\Ext\KHRXlibSurface;

class KHRXlibSurface
{
    public static function vkCreateXlibSurfaceKHR(int instance, int pCreateInfo, int pAllocator, int pSurface) -> int
    {
        return khrxlibsurface_vkcreatexlibsurfacekhr(instance, pCreateInfo, pAllocator, pSurface);
    }

    public static function vkGetPhysicalDeviceXlibPresentationSupportKHR(int physicalDevice, int queueFamilyIndex, int dpy, int visualID) -> bool
    {
        int r;

        let r = khrxlibsurface_vkgetphysicaldevicexlibpresentationsupportkhr(physicalDevice, queueFamilyIndex, dpy, visualID);

        return r == 1;
    }
}
