
extern zend_class_entry *vulkan_struct_vkexternalmemoryproperties_vkexternalmemoryproperties_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkExternalMemoryProperties_VkExternalMemoryProperties);

PHP_METHOD(Vulkan_Struct_VkExternalMemoryProperties_VkExternalMemoryProperties, pack);
PHP_METHOD(Vulkan_Struct_VkExternalMemoryProperties_VkExternalMemoryProperties, packInto);
PHP_METHOD(Vulkan_Struct_VkExternalMemoryProperties_VkExternalMemoryProperties, unpack);
PHP_METHOD(Vulkan_Struct_VkExternalMemoryProperties_VkExternalMemoryProperties, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkexternalmemoryproperties_vkexternalmemoryproperties_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkexternalmemoryproperties_vkexternalmemoryproperties_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkexternalmemoryproperties_vkexternalmemoryproperties_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkexternalmemoryproperties_vkexternalmemoryproperties_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkexternalmemoryproperties_vkexternalmemoryproperties_method_entry) {
	PHP_ME(Vulkan_Struct_VkExternalMemoryProperties_VkExternalMemoryProperties, pack, arginfo_vulkan_struct_vkexternalmemoryproperties_vkexternalmemoryproperties_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkExternalMemoryProperties_VkExternalMemoryProperties, packInto, arginfo_vulkan_struct_vkexternalmemoryproperties_vkexternalmemoryproperties_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkExternalMemoryProperties_VkExternalMemoryProperties, unpack, arginfo_vulkan_struct_vkexternalmemoryproperties_vkexternalmemoryproperties_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkExternalMemoryProperties_VkExternalMemoryProperties, size, arginfo_vulkan_struct_vkexternalmemoryproperties_vkexternalmemoryproperties_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
