
extern zend_class_entry *vulkan_struct_vkpipelinecacheheaderversionone_vkpipelinecacheheaderversionone_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkPipelineCacheHeaderVersionOne_VkPipelineCacheHeaderVersionOne);

PHP_METHOD(Vulkan_Struct_VkPipelineCacheHeaderVersionOne_VkPipelineCacheHeaderVersionOne, pack);
PHP_METHOD(Vulkan_Struct_VkPipelineCacheHeaderVersionOne_VkPipelineCacheHeaderVersionOne, packInto);
PHP_METHOD(Vulkan_Struct_VkPipelineCacheHeaderVersionOne_VkPipelineCacheHeaderVersionOne, unpack);
PHP_METHOD(Vulkan_Struct_VkPipelineCacheHeaderVersionOne_VkPipelineCacheHeaderVersionOne, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkpipelinecacheheaderversionone_vkpipelinecacheheaderversionone_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkpipelinecacheheaderversionone_vkpipelinecacheheaderversionone_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkpipelinecacheheaderversionone_vkpipelinecacheheaderversionone_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkpipelinecacheheaderversionone_vkpipelinecacheheaderversionone_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkpipelinecacheheaderversionone_vkpipelinecacheheaderversionone_method_entry) {
	PHP_ME(Vulkan_Struct_VkPipelineCacheHeaderVersionOne_VkPipelineCacheHeaderVersionOne, pack, arginfo_vulkan_struct_vkpipelinecacheheaderversionone_vkpipelinecacheheaderversionone_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPipelineCacheHeaderVersionOne_VkPipelineCacheHeaderVersionOne, packInto, arginfo_vulkan_struct_vkpipelinecacheheaderversionone_vkpipelinecacheheaderversionone_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPipelineCacheHeaderVersionOne_VkPipelineCacheHeaderVersionOne, unpack, arginfo_vulkan_struct_vkpipelinecacheheaderversionone_vkpipelinecacheheaderversionone_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPipelineCacheHeaderVersionOne_VkPipelineCacheHeaderVersionOne, size, arginfo_vulkan_struct_vkpipelinecacheheaderversionone_vkpipelinecacheheaderversionone_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
