
extern zend_class_entry *vulkan_struct_vkphysicaldevicesamplerfilterminmaxproperties_vkphysicaldevicesamplerfilterminmaxproperties_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkPhysicalDeviceSamplerFilterMinmaxProperties_VkPhysicalDeviceSamplerFilterMinmaxProperties);

PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceSamplerFilterMinmaxProperties_VkPhysicalDeviceSamplerFilterMinmaxProperties, pack);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceSamplerFilterMinmaxProperties_VkPhysicalDeviceSamplerFilterMinmaxProperties, packInto);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceSamplerFilterMinmaxProperties_VkPhysicalDeviceSamplerFilterMinmaxProperties, unpack);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceSamplerFilterMinmaxProperties_VkPhysicalDeviceSamplerFilterMinmaxProperties, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldevicesamplerfilterminmaxproperties_vkphysicaldevicesamplerfilterminmaxproperties_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldevicesamplerfilterminmaxproperties_vkphysicaldevicesamplerfilterminmaxproperties_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldevicesamplerfilterminmaxproperties_vkphysicaldevicesamplerfilterminmaxproperties_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldevicesamplerfilterminmaxproperties_vkphysicaldevicesamplerfilterminmaxproperties_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkphysicaldevicesamplerfilterminmaxproperties_vkphysicaldevicesamplerfilterminmaxproperties_method_entry) {
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceSamplerFilterMinmaxProperties_VkPhysicalDeviceSamplerFilterMinmaxProperties, pack, arginfo_vulkan_struct_vkphysicaldevicesamplerfilterminmaxproperties_vkphysicaldevicesamplerfilterminmaxproperties_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceSamplerFilterMinmaxProperties_VkPhysicalDeviceSamplerFilterMinmaxProperties, packInto, arginfo_vulkan_struct_vkphysicaldevicesamplerfilterminmaxproperties_vkphysicaldevicesamplerfilterminmaxproperties_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceSamplerFilterMinmaxProperties_VkPhysicalDeviceSamplerFilterMinmaxProperties, unpack, arginfo_vulkan_struct_vkphysicaldevicesamplerfilterminmaxproperties_vkphysicaldevicesamplerfilterminmaxproperties_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceSamplerFilterMinmaxProperties_VkPhysicalDeviceSamplerFilterMinmaxProperties, size, arginfo_vulkan_struct_vkphysicaldevicesamplerfilterminmaxproperties_vkphysicaldevicesamplerfilterminmaxproperties_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
