// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Vulkan\Struct\VkPhysicalDeviceDynamicRenderingFeatures;

class VkPhysicalDeviceDynamicRenderingFeatures
{
    public static function pack(array members) -> int
    {
        return struct_vkphysicaldevicedynamicrenderingfeatures_pack(members);
    }

    public static function packInto(int ptr, array members) -> void
    {
        struct_vkphysicaldevicedynamicrenderingfeatures_packinto(ptr, members);
    }

    public static function unpack(int ptr) -> array
    {
        var result;

        let result = struct_vkphysicaldevicedynamicrenderingfeatures_unpack(ptr);

        return result;
    }

    public static function size() -> int
    {
        return struct_vkphysicaldevicedynamicrenderingfeatures_size();
    }
}
