
extern zend_class_entry *vulkan_struct_vkdescriptorsetlayoutbinding_vkdescriptorsetlayoutbinding_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkDescriptorSetLayoutBinding_VkDescriptorSetLayoutBinding);

PHP_METHOD(Vulkan_Struct_VkDescriptorSetLayoutBinding_VkDescriptorSetLayoutBinding, pack);
PHP_METHOD(Vulkan_Struct_VkDescriptorSetLayoutBinding_VkDescriptorSetLayoutBinding, packInto);
PHP_METHOD(Vulkan_Struct_VkDescriptorSetLayoutBinding_VkDescriptorSetLayoutBinding, unpack);
PHP_METHOD(Vulkan_Struct_VkDescriptorSetLayoutBinding_VkDescriptorSetLayoutBinding, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkdescriptorsetlayoutbinding_vkdescriptorsetlayoutbinding_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkdescriptorsetlayoutbinding_vkdescriptorsetlayoutbinding_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkdescriptorsetlayoutbinding_vkdescriptorsetlayoutbinding_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkdescriptorsetlayoutbinding_vkdescriptorsetlayoutbinding_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkdescriptorsetlayoutbinding_vkdescriptorsetlayoutbinding_method_entry) {
	PHP_ME(Vulkan_Struct_VkDescriptorSetLayoutBinding_VkDescriptorSetLayoutBinding, pack, arginfo_vulkan_struct_vkdescriptorsetlayoutbinding_vkdescriptorsetlayoutbinding_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkDescriptorSetLayoutBinding_VkDescriptorSetLayoutBinding, packInto, arginfo_vulkan_struct_vkdescriptorsetlayoutbinding_vkdescriptorsetlayoutbinding_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkDescriptorSetLayoutBinding_VkDescriptorSetLayoutBinding, unpack, arginfo_vulkan_struct_vkdescriptorsetlayoutbinding_vkdescriptorsetlayoutbinding_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkDescriptorSetLayoutBinding_VkDescriptorSetLayoutBinding, size, arginfo_vulkan_struct_vkdescriptorsetlayoutbinding_vkdescriptorsetlayoutbinding_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
