
extern zend_class_entry *vulkan_struct_vkbindimagememorydevicegroupinfo_vkbindimagememorydevicegroupinfo_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkBindImageMemoryDeviceGroupInfo_VkBindImageMemoryDeviceGroupInfo);

PHP_METHOD(Vulkan_Struct_VkBindImageMemoryDeviceGroupInfo_VkBindImageMemoryDeviceGroupInfo, pack);
PHP_METHOD(Vulkan_Struct_VkBindImageMemoryDeviceGroupInfo_VkBindImageMemoryDeviceGroupInfo, packInto);
PHP_METHOD(Vulkan_Struct_VkBindImageMemoryDeviceGroupInfo_VkBindImageMemoryDeviceGroupInfo, unpack);
PHP_METHOD(Vulkan_Struct_VkBindImageMemoryDeviceGroupInfo_VkBindImageMemoryDeviceGroupInfo, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkbindimagememorydevicegroupinfo_vkbindimagememorydevicegroupinfo_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkbindimagememorydevicegroupinfo_vkbindimagememorydevicegroupinfo_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkbindimagememorydevicegroupinfo_vkbindimagememorydevicegroupinfo_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkbindimagememorydevicegroupinfo_vkbindimagememorydevicegroupinfo_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkbindimagememorydevicegroupinfo_vkbindimagememorydevicegroupinfo_method_entry) {
	PHP_ME(Vulkan_Struct_VkBindImageMemoryDeviceGroupInfo_VkBindImageMemoryDeviceGroupInfo, pack, arginfo_vulkan_struct_vkbindimagememorydevicegroupinfo_vkbindimagememorydevicegroupinfo_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkBindImageMemoryDeviceGroupInfo_VkBindImageMemoryDeviceGroupInfo, packInto, arginfo_vulkan_struct_vkbindimagememorydevicegroupinfo_vkbindimagememorydevicegroupinfo_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkBindImageMemoryDeviceGroupInfo_VkBindImageMemoryDeviceGroupInfo, unpack, arginfo_vulkan_struct_vkbindimagememorydevicegroupinfo_vkbindimagememorydevicegroupinfo_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkBindImageMemoryDeviceGroupInfo_VkBindImageMemoryDeviceGroupInfo, size, arginfo_vulkan_struct_vkbindimagememorydevicegroupinfo_vkbindimagememorydevicegroupinfo_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
