
extern zend_class_entry *vulkan_struct_vkrenderinginputattachmentindexinfo_vkrenderinginputattachmentindexinfo_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkRenderingInputAttachmentIndexInfo_VkRenderingInputAttachmentIndexInfo);

PHP_METHOD(Vulkan_Struct_VkRenderingInputAttachmentIndexInfo_VkRenderingInputAttachmentIndexInfo, pack);
PHP_METHOD(Vulkan_Struct_VkRenderingInputAttachmentIndexInfo_VkRenderingInputAttachmentIndexInfo, packInto);
PHP_METHOD(Vulkan_Struct_VkRenderingInputAttachmentIndexInfo_VkRenderingInputAttachmentIndexInfo, unpack);
PHP_METHOD(Vulkan_Struct_VkRenderingInputAttachmentIndexInfo_VkRenderingInputAttachmentIndexInfo, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkrenderinginputattachmentindexinfo_vkrenderinginputattachmentindexinfo_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkrenderinginputattachmentindexinfo_vkrenderinginputattachmentindexinfo_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkrenderinginputattachmentindexinfo_vkrenderinginputattachmentindexinfo_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkrenderinginputattachmentindexinfo_vkrenderinginputattachmentindexinfo_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkrenderinginputattachmentindexinfo_vkrenderinginputattachmentindexinfo_method_entry) {
	PHP_ME(Vulkan_Struct_VkRenderingInputAttachmentIndexInfo_VkRenderingInputAttachmentIndexInfo, pack, arginfo_vulkan_struct_vkrenderinginputattachmentindexinfo_vkrenderinginputattachmentindexinfo_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkRenderingInputAttachmentIndexInfo_VkRenderingInputAttachmentIndexInfo, packInto, arginfo_vulkan_struct_vkrenderinginputattachmentindexinfo_vkrenderinginputattachmentindexinfo_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkRenderingInputAttachmentIndexInfo_VkRenderingInputAttachmentIndexInfo, unpack, arginfo_vulkan_struct_vkrenderinginputattachmentindexinfo_vkrenderinginputattachmentindexinfo_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkRenderingInputAttachmentIndexInfo_VkRenderingInputAttachmentIndexInfo, size, arginfo_vulkan_struct_vkrenderinginputattachmentindexinfo_vkrenderinginputattachmentindexinfo_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
