
extern zend_class_entry *vulkan_struct_vkphysicaldevice8bitstoragefeatures_vkphysicaldevice8bitstoragefeatures_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkPhysicalDevice8BitStorageFeatures_VkPhysicalDevice8BitStorageFeatures);

PHP_METHOD(Vulkan_Struct_VkPhysicalDevice8BitStorageFeatures_VkPhysicalDevice8BitStorageFeatures, pack);
PHP_METHOD(Vulkan_Struct_VkPhysicalDevice8BitStorageFeatures_VkPhysicalDevice8BitStorageFeatures, packInto);
PHP_METHOD(Vulkan_Struct_VkPhysicalDevice8BitStorageFeatures_VkPhysicalDevice8BitStorageFeatures, unpack);
PHP_METHOD(Vulkan_Struct_VkPhysicalDevice8BitStorageFeatures_VkPhysicalDevice8BitStorageFeatures, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldevice8bitstoragefeatures_vkphysicaldevice8bitstoragefeatures_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldevice8bitstoragefeatures_vkphysicaldevice8bitstoragefeatures_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldevice8bitstoragefeatures_vkphysicaldevice8bitstoragefeatures_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldevice8bitstoragefeatures_vkphysicaldevice8bitstoragefeatures_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkphysicaldevice8bitstoragefeatures_vkphysicaldevice8bitstoragefeatures_method_entry) {
	PHP_ME(Vulkan_Struct_VkPhysicalDevice8BitStorageFeatures_VkPhysicalDevice8BitStorageFeatures, pack, arginfo_vulkan_struct_vkphysicaldevice8bitstoragefeatures_vkphysicaldevice8bitstoragefeatures_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDevice8BitStorageFeatures_VkPhysicalDevice8BitStorageFeatures, packInto, arginfo_vulkan_struct_vkphysicaldevice8bitstoragefeatures_vkphysicaldevice8bitstoragefeatures_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDevice8BitStorageFeatures_VkPhysicalDevice8BitStorageFeatures, unpack, arginfo_vulkan_struct_vkphysicaldevice8bitstoragefeatures_vkphysicaldevice8bitstoragefeatures_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDevice8BitStorageFeatures_VkPhysicalDevice8BitStorageFeatures, size, arginfo_vulkan_struct_vkphysicaldevice8bitstoragefeatures_vkphysicaldevice8bitstoragefeatures_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
