/*
 * vk-11.h — Vulkan\VK\VK11 bound 1:1.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_VERSION_1_1 (28 commands)
 */

#ifndef PHPVK_VK_11_H
#define PHPVK_VK_11_H

#include <php.h>

/*@audit feature VK\VK11 VK_VERSION_1_1 28 */

/*@zep VK\VK11 vkEnumerateInstanceVersion(int pApiVersion) -> int */
zend_long phpvk_vk11_vkenumerateinstanceversion(zval *pApiVersion);

/*@zep VK\VK11 vkBindBufferMemory2(int device, int bindInfoCount, int pBindInfos) -> int */
zend_long phpvk_vk11_vkbindbuffermemory2(zval *device, zval *bindInfoCount, zval *pBindInfos);

/*@zep VK\VK11 vkBindImageMemory2(int device, int bindInfoCount, int pBindInfos) -> int */
zend_long phpvk_vk11_vkbindimagememory2(zval *device, zval *bindInfoCount, zval *pBindInfos);

/*@zep VK\VK11 vkGetDeviceGroupPeerMemoryFeatures(int device, int heapIndex, int localDeviceIndex, int remoteDeviceIndex, int pPeerMemoryFeatures) -> void */
void phpvk_vk11_vkgetdevicegrouppeermemoryfeatures(zval *device, zval *heapIndex, zval *localDeviceIndex, zval *remoteDeviceIndex, zval *pPeerMemoryFeatures);

/*@zep VK\VK11 vkCmdSetDeviceMask(int commandBuffer, int deviceMask) -> void */
void phpvk_vk11_vkcmdsetdevicemask(zval *commandBuffer, zval *deviceMask);

/*@zep VK\VK11 vkEnumeratePhysicalDeviceGroups(int instance, int pPhysicalDeviceGroupCount, int pPhysicalDeviceGroupProperties) -> int */
zend_long phpvk_vk11_vkenumeratephysicaldevicegroups(zval *instance, zval *pPhysicalDeviceGroupCount, zval *pPhysicalDeviceGroupProperties);

/*@zep VK\VK11 vkGetImageMemoryRequirements2(int device, int pInfo, int pMemoryRequirements) -> void */
void phpvk_vk11_vkgetimagememoryrequirements2(zval *device, zval *pInfo, zval *pMemoryRequirements);

/*@zep VK\VK11 vkGetBufferMemoryRequirements2(int device, int pInfo, int pMemoryRequirements) -> void */
void phpvk_vk11_vkgetbuffermemoryrequirements2(zval *device, zval *pInfo, zval *pMemoryRequirements);

/*@zep VK\VK11 vkGetImageSparseMemoryRequirements2(int device, int pInfo, int pSparseMemoryRequirementCount, int pSparseMemoryRequirements) -> void */
void phpvk_vk11_vkgetimagesparsememoryrequirements2(zval *device, zval *pInfo, zval *pSparseMemoryRequirementCount, zval *pSparseMemoryRequirements);

/*@zep VK\VK11 vkGetPhysicalDeviceFeatures2(int physicalDevice, int pFeatures) -> void */
void phpvk_vk11_vkgetphysicaldevicefeatures2(zval *physicalDevice, zval *pFeatures);

/*@zep VK\VK11 vkGetPhysicalDeviceProperties2(int physicalDevice, int pProperties) -> void */
void phpvk_vk11_vkgetphysicaldeviceproperties2(zval *physicalDevice, zval *pProperties);

/*@zep VK\VK11 vkGetPhysicalDeviceFormatProperties2(int physicalDevice, int format, int pFormatProperties) -> void */
void phpvk_vk11_vkgetphysicaldeviceformatproperties2(zval *physicalDevice, zval *format, zval *pFormatProperties);

/*@zep VK\VK11 vkGetPhysicalDeviceImageFormatProperties2(int physicalDevice, int pImageFormatInfo, int pImageFormatProperties) -> int */
zend_long phpvk_vk11_vkgetphysicaldeviceimageformatproperties2(zval *physicalDevice, zval *pImageFormatInfo, zval *pImageFormatProperties);

/*@zep VK\VK11 vkGetPhysicalDeviceQueueFamilyProperties2(int physicalDevice, int pQueueFamilyPropertyCount, int pQueueFamilyProperties) -> void */
void phpvk_vk11_vkgetphysicaldevicequeuefamilyproperties2(zval *physicalDevice, zval *pQueueFamilyPropertyCount, zval *pQueueFamilyProperties);

/*@zep VK\VK11 vkGetPhysicalDeviceMemoryProperties2(int physicalDevice, int pMemoryProperties) -> void */
void phpvk_vk11_vkgetphysicaldevicememoryproperties2(zval *physicalDevice, zval *pMemoryProperties);

/*@zep VK\VK11 vkGetPhysicalDeviceSparseImageFormatProperties2(int physicalDevice, int pFormatInfo, int pPropertyCount, int pProperties) -> void */
void phpvk_vk11_vkgetphysicaldevicesparseimageformatproperties2(zval *physicalDevice, zval *pFormatInfo, zval *pPropertyCount, zval *pProperties);

/*@zep VK\VK11 vkTrimCommandPool(int device, int commandPool, int flags) -> void */
void phpvk_vk11_vktrimcommandpool(zval *device, zval *commandPool, zval *flags);

/*@zep VK\VK11 vkGetDeviceQueue2(int device, int pQueueInfo, int pQueue) -> void */
void phpvk_vk11_vkgetdevicequeue2(zval *device, zval *pQueueInfo, zval *pQueue);

/*@zep VK\VK11 vkGetPhysicalDeviceExternalBufferProperties(int physicalDevice, int pExternalBufferInfo, int pExternalBufferProperties) -> void */
void phpvk_vk11_vkgetphysicaldeviceexternalbufferproperties(zval *physicalDevice, zval *pExternalBufferInfo, zval *pExternalBufferProperties);

/*@zep VK\VK11 vkGetPhysicalDeviceExternalFenceProperties(int physicalDevice, int pExternalFenceInfo, int pExternalFenceProperties) -> void */
void phpvk_vk11_vkgetphysicaldeviceexternalfenceproperties(zval *physicalDevice, zval *pExternalFenceInfo, zval *pExternalFenceProperties);

/*@zep VK\VK11 vkGetPhysicalDeviceExternalSemaphoreProperties(int physicalDevice, int pExternalSemaphoreInfo, int pExternalSemaphoreProperties) -> void */
void phpvk_vk11_vkgetphysicaldeviceexternalsemaphoreproperties(zval *physicalDevice, zval *pExternalSemaphoreInfo, zval *pExternalSemaphoreProperties);

/*@zep VK\VK11 vkCmdDispatchBase(int commandBuffer, int baseGroupX, int baseGroupY, int baseGroupZ, int groupCountX, int groupCountY, int groupCountZ) -> void */
void phpvk_vk11_vkcmddispatchbase(zval *commandBuffer, zval *baseGroupX, zval *baseGroupY, zval *baseGroupZ, zval *groupCountX, zval *groupCountY, zval *groupCountZ);

/*@zep VK\VK11 vkCreateDescriptorUpdateTemplate(int device, int pCreateInfo, int pAllocator, int pDescriptorUpdateTemplate) -> int */
zend_long phpvk_vk11_vkcreatedescriptorupdatetemplate(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pDescriptorUpdateTemplate);

/*@zep VK\VK11 vkDestroyDescriptorUpdateTemplate(int device, int descriptorUpdateTemplate, int pAllocator) -> void */
void phpvk_vk11_vkdestroydescriptorupdatetemplate(zval *device, zval *descriptorUpdateTemplate, zval *pAllocator);

/*@zep VK\VK11 vkUpdateDescriptorSetWithTemplate(int device, int descriptorSet, int descriptorUpdateTemplate, int pData) -> void */
void phpvk_vk11_vkupdatedescriptorsetwithtemplate(zval *device, zval *descriptorSet, zval *descriptorUpdateTemplate, zval *pData);

/*@zep VK\VK11 vkGetDescriptorSetLayoutSupport(int device, int pCreateInfo, int pSupport) -> void */
void phpvk_vk11_vkgetdescriptorsetlayoutsupport(zval *device, zval *pCreateInfo, zval *pSupport);

/*@zep VK\VK11 vkCreateSamplerYcbcrConversion(int device, int pCreateInfo, int pAllocator, int pYcbcrConversion) -> int */
zend_long phpvk_vk11_vkcreatesamplerycbcrconversion(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pYcbcrConversion);

/*@zep VK\VK11 vkDestroySamplerYcbcrConversion(int device, int ycbcrConversion, int pAllocator) -> void */
void phpvk_vk11_vkdestroysamplerycbcrconversion(zval *device, zval *ycbcrConversion, zval *pAllocator);

#endif
