/*
 * vk-14.h — Vulkan\VK\VK14 bound 1:1.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_VERSION_1_4 (19 commands)
 */

#ifndef PHPVK_VK_14_H
#define PHPVK_VK_14_H

#include <php.h>

/*@audit feature VK\VK14 VK_VERSION_1_4 19 */

/*@zep VK\VK14 vkMapMemory2(int device, int pMemoryMapInfo, int ppData) -> int */
zend_long phpvk_vk14_vkmapmemory2(zval *device, zval *pMemoryMapInfo, zval *ppData);

/*@zep VK\VK14 vkUnmapMemory2(int device, int pMemoryUnmapInfo) -> int */
zend_long phpvk_vk14_vkunmapmemory2(zval *device, zval *pMemoryUnmapInfo);

/*@zep VK\VK14 vkGetDeviceImageSubresourceLayout(int device, int pInfo, int pLayout) -> void */
void phpvk_vk14_vkgetdeviceimagesubresourcelayout(zval *device, zval *pInfo, zval *pLayout);

/*@zep VK\VK14 vkGetImageSubresourceLayout2(int device, int image, int pSubresource, int pLayout) -> void */
void phpvk_vk14_vkgetimagesubresourcelayout2(zval *device, zval *image, zval *pSubresource, zval *pLayout);

/*@zep VK\VK14 vkCopyMemoryToImage(int device, int pCopyMemoryToImageInfo) -> int */
zend_long phpvk_vk14_vkcopymemorytoimage(zval *device, zval *pCopyMemoryToImageInfo);

/*@zep VK\VK14 vkCopyImageToMemory(int device, int pCopyImageToMemoryInfo) -> int */
zend_long phpvk_vk14_vkcopyimagetomemory(zval *device, zval *pCopyImageToMemoryInfo);

/*@zep VK\VK14 vkCopyImageToImage(int device, int pCopyImageToImageInfo) -> int */
zend_long phpvk_vk14_vkcopyimagetoimage(zval *device, zval *pCopyImageToImageInfo);

/*@zep VK\VK14 vkTransitionImageLayout(int device, int transitionCount, int pTransitions) -> int */
zend_long phpvk_vk14_vktransitionimagelayout(zval *device, zval *transitionCount, zval *pTransitions);

/*@zep VK\VK14 vkCmdPushDescriptorSet(int commandBuffer, int pipelineBindPoint, int layout, int set, int descriptorWriteCount, int pDescriptorWrites) -> void */
void phpvk_vk14_vkcmdpushdescriptorset(zval *commandBuffer, zval *pipelineBindPoint, zval *layout, zval *set, zval *descriptorWriteCount, zval *pDescriptorWrites);

/*@zep VK\VK14 vkCmdPushDescriptorSetWithTemplate(int commandBuffer, int descriptorUpdateTemplate, int layout, int set, int pData) -> void */
void phpvk_vk14_vkcmdpushdescriptorsetwithtemplate(zval *commandBuffer, zval *descriptorUpdateTemplate, zval *layout, zval *set, zval *pData);

/*@zep VK\VK14 vkCmdBindDescriptorSets2(int commandBuffer, int pBindDescriptorSetsInfo) -> void */
void phpvk_vk14_vkcmdbinddescriptorsets2(zval *commandBuffer, zval *pBindDescriptorSetsInfo);

/*@zep VK\VK14 vkCmdPushConstants2(int commandBuffer, int pPushConstantsInfo) -> void */
void phpvk_vk14_vkcmdpushconstants2(zval *commandBuffer, zval *pPushConstantsInfo);

/*@zep VK\VK14 vkCmdPushDescriptorSet2(int commandBuffer, int pPushDescriptorSetInfo) -> void */
void phpvk_vk14_vkcmdpushdescriptorset2(zval *commandBuffer, zval *pPushDescriptorSetInfo);

/*@zep VK\VK14 vkCmdPushDescriptorSetWithTemplate2(int commandBuffer, int pPushDescriptorSetWithTemplateInfo) -> void */
void phpvk_vk14_vkcmdpushdescriptorsetwithtemplate2(zval *commandBuffer, zval *pPushDescriptorSetWithTemplateInfo);

/*@zep VK\VK14 vkCmdSetLineStipple(int commandBuffer, int lineStippleFactor, int lineStipplePattern) -> void */
void phpvk_vk14_vkcmdsetlinestipple(zval *commandBuffer, zval *lineStippleFactor, zval *lineStipplePattern);

/*@zep VK\VK14 vkCmdBindIndexBuffer2(int commandBuffer, int buffer, int offset, int size, int indexType) -> void */
void phpvk_vk14_vkcmdbindindexbuffer2(zval *commandBuffer, zval *buffer, zval *offset, zval *size, zval *indexType);

/*@zep VK\VK14 vkGetRenderingAreaGranularity(int device, int pRenderingAreaInfo, int pGranularity) -> void */
void phpvk_vk14_vkgetrenderingareagranularity(zval *device, zval *pRenderingAreaInfo, zval *pGranularity);

/*@zep VK\VK14 vkCmdSetRenderingAttachmentLocations(int commandBuffer, int pLocationInfo) -> void */
void phpvk_vk14_vkcmdsetrenderingattachmentlocations(zval *commandBuffer, zval *pLocationInfo);

/*@zep VK\VK14 vkCmdSetRenderingInputAttachmentIndices(int commandBuffer, int pInputAttachmentIndexInfo) -> void */
void phpvk_vk14_vkcmdsetrenderinginputattachmentindices(zval *commandBuffer, zval *pInputAttachmentIndexInfo);

#endif
