/*
 * vk-12.h — Vulkan\VK\VK12 bound 1:1.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_VERSION_1_2 (13 commands)
 */

#ifndef PHPVK_VK_12_H
#define PHPVK_VK_12_H

#include <php.h>

/*@audit feature VK\VK12 VK_VERSION_1_2 13 */

/*@zep VK\VK12 vkResetQueryPool(int device, int queryPool, int firstQuery, int queryCount) -> void */
void phpvk_vk12_vkresetquerypool(zval *device, zval *queryPool, zval *firstQuery, zval *queryCount);

/*@zep VK\VK12 vkGetSemaphoreCounterValue(int device, int semaphore, int pValue) -> int */
zend_long phpvk_vk12_vkgetsemaphorecountervalue(zval *device, zval *semaphore, zval *pValue);

/*@zep VK\VK12 vkWaitSemaphores(int device, int pWaitInfo, int timeout) -> int */
zend_long phpvk_vk12_vkwaitsemaphores(zval *device, zval *pWaitInfo, zval *timeout);

/*@zep VK\VK12 vkSignalSemaphore(int device, int pSignalInfo) -> int */
zend_long phpvk_vk12_vksignalsemaphore(zval *device, zval *pSignalInfo);

/*@zep VK\VK12 vkGetBufferDeviceAddress(int device, int pInfo) -> int */
zend_long phpvk_vk12_vkgetbufferdeviceaddress(zval *device, zval *pInfo);

/*@zep VK\VK12 vkGetBufferOpaqueCaptureAddress(int device, int pInfo) -> int */
zend_long phpvk_vk12_vkgetbufferopaquecaptureaddress(zval *device, zval *pInfo);

/*@zep VK\VK12 vkGetDeviceMemoryOpaqueCaptureAddress(int device, int pInfo) -> int */
zend_long phpvk_vk12_vkgetdevicememoryopaquecaptureaddress(zval *device, zval *pInfo);

/*@zep VK\VK12 vkCmdDrawIndirectCount(int commandBuffer, int buffer, int offset, int countBuffer, int countBufferOffset, int maxDrawCount, int stride) -> void */
void phpvk_vk12_vkcmddrawindirectcount(zval *commandBuffer, zval *buffer, zval *offset, zval *countBuffer, zval *countBufferOffset, zval *maxDrawCount, zval *stride);

/*@zep VK\VK12 vkCmdDrawIndexedIndirectCount(int commandBuffer, int buffer, int offset, int countBuffer, int countBufferOffset, int maxDrawCount, int stride) -> void */
void phpvk_vk12_vkcmddrawindexedindirectcount(zval *commandBuffer, zval *buffer, zval *offset, zval *countBuffer, zval *countBufferOffset, zval *maxDrawCount, zval *stride);

/*@zep VK\VK12 vkCreateRenderPass2(int device, int pCreateInfo, int pAllocator, int pRenderPass) -> int */
zend_long phpvk_vk12_vkcreaterenderpass2(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pRenderPass);

/*@zep VK\VK12 vkCmdBeginRenderPass2(int commandBuffer, int pRenderPassBegin, int pSubpassBeginInfo) -> void */
void phpvk_vk12_vkcmdbeginrenderpass2(zval *commandBuffer, zval *pRenderPassBegin, zval *pSubpassBeginInfo);

/*@zep VK\VK12 vkCmdNextSubpass2(int commandBuffer, int pSubpassBeginInfo, int pSubpassEndInfo) -> void */
void phpvk_vk12_vkcmdnextsubpass2(zval *commandBuffer, zval *pSubpassBeginInfo, zval *pSubpassEndInfo);

/*@zep VK\VK12 vkCmdEndRenderPass2(int commandBuffer, int pSubpassEndInfo) -> void */
void phpvk_vk12_vkcmdendrenderpass2(zval *commandBuffer, zval *pSubpassEndInfo);

#endif
