/*
 * vk-13.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_VERSION_1_3
 */

#include "vk-13.h"
#include "phpvk-platform.h"
#include "phpvk-bridge.h"
#include "phpvk-support.h"

zend_long phpvk_vk13_vkgetphysicaldevicetoolproperties(zval *physicalDevice, zval *pToolCount, zval *pToolProperties)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetPhysicalDeviceToolProperties fn = (PFN_vkGetPhysicalDeviceToolProperties) phpvk_entry("vkGetPhysicalDeviceToolProperties", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkPhysicalDevice) phpvk_arg_ptr(physicalDevice), (uint32_t *) phpvk_arg_ptr(pToolCount), (VkPhysicalDeviceToolProperties *) phpvk_arg_ptr(pToolProperties));
}

zend_long phpvk_vk13_vkcreateprivatedataslot(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pPrivateDataSlot)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreatePrivateDataSlot fn = (PFN_vkCreatePrivateDataSlot) phpvk_entry("vkCreatePrivateDataSlot", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkPrivateDataSlotCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkPrivateDataSlot *) phpvk_arg_ptr(pPrivateDataSlot));
}

void phpvk_vk13_vkdestroyprivatedataslot(zval *device, zval *privateDataSlot, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyPrivateDataSlot fn = (PFN_vkDestroyPrivateDataSlot) phpvk_entry("vkDestroyPrivateDataSlot", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkPrivateDataSlot) (uintptr_t) phpvk_arg_u64(privateDataSlot), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk13_vksetprivatedata(zval *device, zval *objectType, zval *objectHandle, zval *privateDataSlot, zval *data)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkSetPrivateData fn = (PFN_vkSetPrivateData) phpvk_entry("vkSetPrivateData", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkObjectType) phpvk_arg_long(objectType), (uint64_t) phpvk_arg_u64(objectHandle), (VkPrivateDataSlot) (uintptr_t) phpvk_arg_u64(privateDataSlot), (uint64_t) phpvk_arg_u64(data));
}

void phpvk_vk13_vkgetprivatedata(zval *device, zval *objectType, zval *objectHandle, zval *privateDataSlot, zval *pData)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetPrivateData fn = (PFN_vkGetPrivateData) phpvk_entry("vkGetPrivateData", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkObjectType) phpvk_arg_long(objectType), (uint64_t) phpvk_arg_u64(objectHandle), (VkPrivateDataSlot) (uintptr_t) phpvk_arg_u64(privateDataSlot), (uint64_t *) phpvk_arg_ptr(pData));
}

void phpvk_vk13_vkcmdpipelinebarrier2(zval *commandBuffer, zval *pDependencyInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdPipelineBarrier2 fn = (PFN_vkCmdPipelineBarrier2) phpvk_entry("vkCmdPipelineBarrier2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkDependencyInfo *) phpvk_arg_ptr(pDependencyInfo));
}

void phpvk_vk13_vkcmdwritetimestamp2(zval *commandBuffer, zval *stage, zval *queryPool, zval *query)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdWriteTimestamp2 fn = (PFN_vkCmdWriteTimestamp2) phpvk_entry("vkCmdWriteTimestamp2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkPipelineStageFlags2) phpvk_arg_u64(stage), (VkQueryPool) (uintptr_t) phpvk_arg_u64(queryPool), (uint32_t) phpvk_arg_long(query));
}

zend_long phpvk_vk13_vkqueuesubmit2(zval *queue, zval *submitCount, zval *pSubmits, zval *fence)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkQueueSubmit2 fn = (PFN_vkQueueSubmit2) phpvk_entry("vkQueueSubmit2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkQueue) phpvk_arg_ptr(queue), (uint32_t) phpvk_arg_long(submitCount), (const VkSubmitInfo2 *) phpvk_arg_ptr(pSubmits), (VkFence) (uintptr_t) phpvk_arg_u64(fence));
}

void phpvk_vk13_vkcmdcopybuffer2(zval *commandBuffer, zval *pCopyBufferInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdCopyBuffer2 fn = (PFN_vkCmdCopyBuffer2) phpvk_entry("vkCmdCopyBuffer2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkCopyBufferInfo2 *) phpvk_arg_ptr(pCopyBufferInfo));
}

void phpvk_vk13_vkcmdcopyimage2(zval *commandBuffer, zval *pCopyImageInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdCopyImage2 fn = (PFN_vkCmdCopyImage2) phpvk_entry("vkCmdCopyImage2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkCopyImageInfo2 *) phpvk_arg_ptr(pCopyImageInfo));
}

void phpvk_vk13_vkcmdcopybuffertoimage2(zval *commandBuffer, zval *pCopyBufferToImageInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdCopyBufferToImage2 fn = (PFN_vkCmdCopyBufferToImage2) phpvk_entry("vkCmdCopyBufferToImage2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkCopyBufferToImageInfo2 *) phpvk_arg_ptr(pCopyBufferToImageInfo));
}

void phpvk_vk13_vkcmdcopyimagetobuffer2(zval *commandBuffer, zval *pCopyImageToBufferInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdCopyImageToBuffer2 fn = (PFN_vkCmdCopyImageToBuffer2) phpvk_entry("vkCmdCopyImageToBuffer2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkCopyImageToBufferInfo2 *) phpvk_arg_ptr(pCopyImageToBufferInfo));
}

void phpvk_vk13_vkgetdevicebuffermemoryrequirements(zval *device, zval *pInfo, zval *pMemoryRequirements)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetDeviceBufferMemoryRequirements fn = (PFN_vkGetDeviceBufferMemoryRequirements) phpvk_entry("vkGetDeviceBufferMemoryRequirements", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (const VkDeviceBufferMemoryRequirements *) phpvk_arg_ptr(pInfo), (VkMemoryRequirements2 *) phpvk_arg_ptr(pMemoryRequirements));
}

void phpvk_vk13_vkgetdeviceimagememoryrequirements(zval *device, zval *pInfo, zval *pMemoryRequirements)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetDeviceImageMemoryRequirements fn = (PFN_vkGetDeviceImageMemoryRequirements) phpvk_entry("vkGetDeviceImageMemoryRequirements", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (const VkDeviceImageMemoryRequirements *) phpvk_arg_ptr(pInfo), (VkMemoryRequirements2 *) phpvk_arg_ptr(pMemoryRequirements));
}

void phpvk_vk13_vkgetdeviceimagesparsememoryrequirements(zval *device, zval *pInfo, zval *pSparseMemoryRequirementCount, zval *pSparseMemoryRequirements)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetDeviceImageSparseMemoryRequirements fn = (PFN_vkGetDeviceImageSparseMemoryRequirements) phpvk_entry("vkGetDeviceImageSparseMemoryRequirements", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (const VkDeviceImageMemoryRequirements *) phpvk_arg_ptr(pInfo), (uint32_t *) phpvk_arg_ptr(pSparseMemoryRequirementCount), (VkSparseImageMemoryRequirements2 *) phpvk_arg_ptr(pSparseMemoryRequirements));
}

void phpvk_vk13_vkcmdsetevent2(zval *commandBuffer, zval *event, zval *pDependencyInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetEvent2 fn = (PFN_vkCmdSetEvent2) phpvk_entry("vkCmdSetEvent2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkEvent) (uintptr_t) phpvk_arg_u64(event), (const VkDependencyInfo *) phpvk_arg_ptr(pDependencyInfo));
}

void phpvk_vk13_vkcmdresetevent2(zval *commandBuffer, zval *event, zval *stageMask)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdResetEvent2 fn = (PFN_vkCmdResetEvent2) phpvk_entry("vkCmdResetEvent2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkEvent) (uintptr_t) phpvk_arg_u64(event), (VkPipelineStageFlags2) phpvk_arg_u64(stageMask));
}

void phpvk_vk13_vkcmdwaitevents2(zval *commandBuffer, zval *eventCount, zval *pEvents, zval *pDependencyInfos)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdWaitEvents2 fn = (PFN_vkCmdWaitEvents2) phpvk_entry("vkCmdWaitEvents2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (uint32_t) phpvk_arg_long(eventCount), (const VkEvent *) phpvk_arg_ptr(pEvents), (const VkDependencyInfo *) phpvk_arg_ptr(pDependencyInfos));
}

void phpvk_vk13_vkcmdblitimage2(zval *commandBuffer, zval *pBlitImageInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdBlitImage2 fn = (PFN_vkCmdBlitImage2) phpvk_entry("vkCmdBlitImage2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkBlitImageInfo2 *) phpvk_arg_ptr(pBlitImageInfo));
}

void phpvk_vk13_vkcmdresolveimage2(zval *commandBuffer, zval *pResolveImageInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdResolveImage2 fn = (PFN_vkCmdResolveImage2) phpvk_entry("vkCmdResolveImage2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkResolveImageInfo2 *) phpvk_arg_ptr(pResolveImageInfo));
}

void phpvk_vk13_vkcmdbeginrendering(zval *commandBuffer, zval *pRenderingInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdBeginRendering fn = (PFN_vkCmdBeginRendering) phpvk_entry("vkCmdBeginRendering", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkRenderingInfo *) phpvk_arg_ptr(pRenderingInfo));
}

void phpvk_vk13_vkcmdendrendering(zval *commandBuffer)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdEndRendering fn = (PFN_vkCmdEndRendering) phpvk_entry("vkCmdEndRendering", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer));
}

void phpvk_vk13_vkcmdsetcullmode(zval *commandBuffer, zval *cullMode)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetCullMode fn = (PFN_vkCmdSetCullMode) phpvk_entry("vkCmdSetCullMode", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkCullModeFlags) phpvk_arg_long(cullMode));
}

void phpvk_vk13_vkcmdsetfrontface(zval *commandBuffer, zval *frontFace)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetFrontFace fn = (PFN_vkCmdSetFrontFace) phpvk_entry("vkCmdSetFrontFace", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkFrontFace) phpvk_arg_long(frontFace));
}

void phpvk_vk13_vkcmdsetprimitivetopology(zval *commandBuffer, zval *primitiveTopology)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetPrimitiveTopology fn = (PFN_vkCmdSetPrimitiveTopology) phpvk_entry("vkCmdSetPrimitiveTopology", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkPrimitiveTopology) phpvk_arg_long(primitiveTopology));
}

void phpvk_vk13_vkcmdsetviewportwithcount(zval *commandBuffer, zval *viewportCount, zval *pViewports)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetViewportWithCount fn = (PFN_vkCmdSetViewportWithCount) phpvk_entry("vkCmdSetViewportWithCount", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (uint32_t) phpvk_arg_long(viewportCount), (const VkViewport *) phpvk_arg_ptr(pViewports));
}

void phpvk_vk13_vkcmdsetscissorwithcount(zval *commandBuffer, zval *scissorCount, zval *pScissors)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetScissorWithCount fn = (PFN_vkCmdSetScissorWithCount) phpvk_entry("vkCmdSetScissorWithCount", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (uint32_t) phpvk_arg_long(scissorCount), (const VkRect2D *) phpvk_arg_ptr(pScissors));
}

void phpvk_vk13_vkcmdbindvertexbuffers2(zval *commandBuffer, zval *firstBinding, zval *bindingCount, zval *pBuffers, zval *pOffsets, zval *pSizes, zval *pStrides)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdBindVertexBuffers2 fn = (PFN_vkCmdBindVertexBuffers2) phpvk_entry("vkCmdBindVertexBuffers2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (uint32_t) phpvk_arg_long(firstBinding), (uint32_t) phpvk_arg_long(bindingCount), (const VkBuffer *) phpvk_arg_ptr(pBuffers), (const VkDeviceSize *) phpvk_arg_ptr(pOffsets), (const VkDeviceSize *) phpvk_arg_ptr(pSizes), (const VkDeviceSize *) phpvk_arg_ptr(pStrides));
}

void phpvk_vk13_vkcmdsetdepthtestenable(zval *commandBuffer, zval *depthTestEnable)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetDepthTestEnable fn = (PFN_vkCmdSetDepthTestEnable) phpvk_entry("vkCmdSetDepthTestEnable", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBool32) phpvk_arg_bool(depthTestEnable));
}

void phpvk_vk13_vkcmdsetdepthwriteenable(zval *commandBuffer, zval *depthWriteEnable)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetDepthWriteEnable fn = (PFN_vkCmdSetDepthWriteEnable) phpvk_entry("vkCmdSetDepthWriteEnable", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBool32) phpvk_arg_bool(depthWriteEnable));
}

void phpvk_vk13_vkcmdsetdepthcompareop(zval *commandBuffer, zval *depthCompareOp)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetDepthCompareOp fn = (PFN_vkCmdSetDepthCompareOp) phpvk_entry("vkCmdSetDepthCompareOp", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkCompareOp) phpvk_arg_long(depthCompareOp));
}

void phpvk_vk13_vkcmdsetdepthboundstestenable(zval *commandBuffer, zval *depthBoundsTestEnable)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetDepthBoundsTestEnable fn = (PFN_vkCmdSetDepthBoundsTestEnable) phpvk_entry("vkCmdSetDepthBoundsTestEnable", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBool32) phpvk_arg_bool(depthBoundsTestEnable));
}

void phpvk_vk13_vkcmdsetstenciltestenable(zval *commandBuffer, zval *stencilTestEnable)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetStencilTestEnable fn = (PFN_vkCmdSetStencilTestEnable) phpvk_entry("vkCmdSetStencilTestEnable", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBool32) phpvk_arg_bool(stencilTestEnable));
}

void phpvk_vk13_vkcmdsetstencilop(zval *commandBuffer, zval *faceMask, zval *failOp, zval *passOp, zval *depthFailOp, zval *compareOp)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetStencilOp fn = (PFN_vkCmdSetStencilOp) phpvk_entry("vkCmdSetStencilOp", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkStencilFaceFlags) phpvk_arg_long(faceMask), (VkStencilOp) phpvk_arg_long(failOp), (VkStencilOp) phpvk_arg_long(passOp), (VkStencilOp) phpvk_arg_long(depthFailOp), (VkCompareOp) phpvk_arg_long(compareOp));
}

void phpvk_vk13_vkcmdsetrasterizerdiscardenable(zval *commandBuffer, zval *rasterizerDiscardEnable)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetRasterizerDiscardEnable fn = (PFN_vkCmdSetRasterizerDiscardEnable) phpvk_entry("vkCmdSetRasterizerDiscardEnable", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBool32) phpvk_arg_bool(rasterizerDiscardEnable));
}

void phpvk_vk13_vkcmdsetdepthbiasenable(zval *commandBuffer, zval *depthBiasEnable)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetDepthBiasEnable fn = (PFN_vkCmdSetDepthBiasEnable) phpvk_entry("vkCmdSetDepthBiasEnable", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBool32) phpvk_arg_bool(depthBiasEnable));
}

void phpvk_vk13_vkcmdsetprimitiverestartenable(zval *commandBuffer, zval *primitiveRestartEnable)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetPrimitiveRestartEnable fn = (PFN_vkCmdSetPrimitiveRestartEnable) phpvk_entry("vkCmdSetPrimitiveRestartEnable", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBool32) phpvk_arg_bool(primitiveRestartEnable));
}

