/*
 * vk-ext-extmetalobjects.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_EXT_metal_objects
 */

#include "vk-ext-extmetalobjects.h"
#include "phpvk-platform.h"
#include "phpvk-bridge.h"
#include "phpvk-support.h"

void phpvk_extmetalobjects_vkexportmetalobjectsext(zval *device, zval *pMetalObjectsInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkExportMetalObjectsEXT fn = (PFN_vkExportMetalObjectsEXT) phpvk_entry("vkExportMetalObjectsEXT", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkExportMetalObjectsInfoEXT *) phpvk_arg_ptr(pMetalObjectsInfo));
}

