/*
 * vk-ext-khrsurface.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_KHR_surface
 */

#include "vk-ext-khrsurface.h"
#include "phpvk-platform.h"
#include "phpvk-bridge.h"
#include "phpvk-support.h"

void phpvk_khrsurface_vkdestroysurfacekhr(zval *instance, zval *surface, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroySurfaceKHR fn = (PFN_vkDestroySurfaceKHR) phpvk_entry("vkDestroySurfaceKHR", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return;
    }

    fn((VkInstance) phpvk_arg_ptr(instance), (VkSurfaceKHR) (uintptr_t) phpvk_arg_u64(surface), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_khrsurface_vkgetphysicaldevicesurfacesupportkhr(zval *physicalDevice, zval *queueFamilyIndex, zval *surface, zval *pSupported)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetPhysicalDeviceSurfaceSupportKHR fn = (PFN_vkGetPhysicalDeviceSurfaceSupportKHR) phpvk_entry("vkGetPhysicalDeviceSurfaceSupportKHR", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkPhysicalDevice) phpvk_arg_ptr(physicalDevice), (uint32_t) phpvk_arg_long(queueFamilyIndex), (VkSurfaceKHR) (uintptr_t) phpvk_arg_u64(surface), (VkBool32 *) phpvk_arg_ptr(pSupported));
}

zend_long phpvk_khrsurface_vkgetphysicaldevicesurfacecapabilitieskhr(zval *physicalDevice, zval *surface, zval *pSurfaceCapabilities)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR fn = (PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR) phpvk_entry("vkGetPhysicalDeviceSurfaceCapabilitiesKHR", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkPhysicalDevice) phpvk_arg_ptr(physicalDevice), (VkSurfaceKHR) (uintptr_t) phpvk_arg_u64(surface), (VkSurfaceCapabilitiesKHR *) phpvk_arg_ptr(pSurfaceCapabilities));
}

zend_long phpvk_khrsurface_vkgetphysicaldevicesurfaceformatskhr(zval *physicalDevice, zval *surface, zval *pSurfaceFormatCount, zval *pSurfaceFormats)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetPhysicalDeviceSurfaceFormatsKHR fn = (PFN_vkGetPhysicalDeviceSurfaceFormatsKHR) phpvk_entry("vkGetPhysicalDeviceSurfaceFormatsKHR", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkPhysicalDevice) phpvk_arg_ptr(physicalDevice), (VkSurfaceKHR) (uintptr_t) phpvk_arg_u64(surface), (uint32_t *) phpvk_arg_ptr(pSurfaceFormatCount), (VkSurfaceFormatKHR *) phpvk_arg_ptr(pSurfaceFormats));
}

zend_long phpvk_khrsurface_vkgetphysicaldevicesurfacepresentmodeskhr(zval *physicalDevice, zval *surface, zval *pPresentModeCount, zval *pPresentModes)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetPhysicalDeviceSurfacePresentModesKHR fn = (PFN_vkGetPhysicalDeviceSurfacePresentModesKHR) phpvk_entry("vkGetPhysicalDeviceSurfacePresentModesKHR", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkPhysicalDevice) phpvk_arg_ptr(physicalDevice), (VkSurfaceKHR) (uintptr_t) phpvk_arg_u64(surface), (uint32_t *) phpvk_arg_ptr(pPresentModeCount), (VkPresentModeKHR *) phpvk_arg_ptr(pPresentModes));
}

