/*
 * vk-ext-khrxlibsurface.h — Vulkan\Ext\KHRXlibSurface bound 1:1.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_KHR_xlib_surface (2 commands)
 */

#ifndef PHPVK_VK_EXT_KHRXLIBSURFACE_H
#define PHPVK_VK_EXT_KHRXLIBSURFACE_H

#include <php.h>

/*@audit extension Ext\KHRXlibSurface VK_KHR_xlib_surface 2 */

/*@zep Ext\KHRXlibSurface vkCreateXlibSurfaceKHR(int instance, int pCreateInfo, int pAllocator, int pSurface) -> int */
zend_long phpvk_khrxlibsurface_vkcreatexlibsurfacekhr(zval *instance, zval *pCreateInfo, zval *pAllocator, zval *pSurface);

/*@zep Ext\KHRXlibSurface vkGetPhysicalDeviceXlibPresentationSupportKHR(int physicalDevice, int queueFamilyIndex, int dpy, int visualID) -> bool */
zend_long phpvk_khrxlibsurface_vkgetphysicaldevicexlibpresentationsupportkhr(zval *physicalDevice, zval *queueFamilyIndex, zval *dpy, zval *visualID);

#endif
