/*
 * vk-ext-extdebugutils.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_EXT_debug_utils
 */

#include "vk-ext-extdebugutils.h"
#include "phpvk-platform.h"
#include "phpvk-bridge.h"
#include "phpvk-support.h"

zend_long phpvk_extdebugutils_vksetdebugutilsobjectnameext(zval *device, zval *pNameInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkSetDebugUtilsObjectNameEXT fn = (PFN_vkSetDebugUtilsObjectNameEXT) phpvk_entry("vkSetDebugUtilsObjectNameEXT", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkDebugUtilsObjectNameInfoEXT *) phpvk_arg_ptr(pNameInfo));
}

zend_long phpvk_extdebugutils_vksetdebugutilsobjecttagext(zval *device, zval *pTagInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkSetDebugUtilsObjectTagEXT fn = (PFN_vkSetDebugUtilsObjectTagEXT) phpvk_entry("vkSetDebugUtilsObjectTagEXT", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkDebugUtilsObjectTagInfoEXT *) phpvk_arg_ptr(pTagInfo));
}

void phpvk_extdebugutils_vkqueuebegindebugutilslabelext(zval *queue, zval *pLabelInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkQueueBeginDebugUtilsLabelEXT fn = (PFN_vkQueueBeginDebugUtilsLabelEXT) phpvk_entry("vkQueueBeginDebugUtilsLabelEXT", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkQueue) phpvk_arg_ptr(queue), (const VkDebugUtilsLabelEXT *) phpvk_arg_ptr(pLabelInfo));
}

void phpvk_extdebugutils_vkqueueenddebugutilslabelext(zval *queue)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkQueueEndDebugUtilsLabelEXT fn = (PFN_vkQueueEndDebugUtilsLabelEXT) phpvk_entry("vkQueueEndDebugUtilsLabelEXT", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkQueue) phpvk_arg_ptr(queue));
}

void phpvk_extdebugutils_vkqueueinsertdebugutilslabelext(zval *queue, zval *pLabelInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkQueueInsertDebugUtilsLabelEXT fn = (PFN_vkQueueInsertDebugUtilsLabelEXT) phpvk_entry("vkQueueInsertDebugUtilsLabelEXT", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkQueue) phpvk_arg_ptr(queue), (const VkDebugUtilsLabelEXT *) phpvk_arg_ptr(pLabelInfo));
}

void phpvk_extdebugutils_vkcmdbegindebugutilslabelext(zval *commandBuffer, zval *pLabelInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdBeginDebugUtilsLabelEXT fn = (PFN_vkCmdBeginDebugUtilsLabelEXT) phpvk_entry("vkCmdBeginDebugUtilsLabelEXT", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkDebugUtilsLabelEXT *) phpvk_arg_ptr(pLabelInfo));
}

void phpvk_extdebugutils_vkcmdenddebugutilslabelext(zval *commandBuffer)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdEndDebugUtilsLabelEXT fn = (PFN_vkCmdEndDebugUtilsLabelEXT) phpvk_entry("vkCmdEndDebugUtilsLabelEXT", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer));
}

void phpvk_extdebugutils_vkcmdinsertdebugutilslabelext(zval *commandBuffer, zval *pLabelInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdInsertDebugUtilsLabelEXT fn = (PFN_vkCmdInsertDebugUtilsLabelEXT) phpvk_entry("vkCmdInsertDebugUtilsLabelEXT", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkDebugUtilsLabelEXT *) phpvk_arg_ptr(pLabelInfo));
}

zend_long phpvk_extdebugutils_vkcreatedebugutilsmessengerext(zval *instance, zval *pCreateInfo, zval *pAllocator, zval *pMessenger)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateDebugUtilsMessengerEXT fn = (PFN_vkCreateDebugUtilsMessengerEXT) phpvk_entry("vkCreateDebugUtilsMessengerEXT", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkInstance) phpvk_arg_ptr(instance), (const VkDebugUtilsMessengerCreateInfoEXT *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkDebugUtilsMessengerEXT *) phpvk_arg_ptr(pMessenger));
}

void phpvk_extdebugutils_vkdestroydebugutilsmessengerext(zval *instance, zval *messenger, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyDebugUtilsMessengerEXT fn = (PFN_vkDestroyDebugUtilsMessengerEXT) phpvk_entry("vkDestroyDebugUtilsMessengerEXT", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return;
    }

    fn((VkInstance) phpvk_arg_ptr(instance), (VkDebugUtilsMessengerEXT) (uintptr_t) phpvk_arg_u64(messenger), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

void phpvk_extdebugutils_vksubmitdebugutilsmessageext(zval *instance, zval *messageSeverity, zval *messageTypes, zval *pCallbackData)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkSubmitDebugUtilsMessageEXT fn = (PFN_vkSubmitDebugUtilsMessageEXT) phpvk_entry("vkSubmitDebugUtilsMessageEXT", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return;
    }

    fn((VkInstance) phpvk_arg_ptr(instance), (VkDebugUtilsMessageSeverityFlagBitsEXT) phpvk_arg_long(messageSeverity), (VkDebugUtilsMessageTypeFlagsEXT) phpvk_arg_long(messageTypes), (const VkDebugUtilsMessengerCallbackDataEXT *) phpvk_arg_ptr(pCallbackData));
}

