
extern zend_class_entry *vulkan_struct_vkdescriptorpoolcreateinfo_vkdescriptorpoolcreateinfo_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkDescriptorPoolCreateInfo_VkDescriptorPoolCreateInfo);

PHP_METHOD(Vulkan_Struct_VkDescriptorPoolCreateInfo_VkDescriptorPoolCreateInfo, pack);
PHP_METHOD(Vulkan_Struct_VkDescriptorPoolCreateInfo_VkDescriptorPoolCreateInfo, packInto);
PHP_METHOD(Vulkan_Struct_VkDescriptorPoolCreateInfo_VkDescriptorPoolCreateInfo, unpack);
PHP_METHOD(Vulkan_Struct_VkDescriptorPoolCreateInfo_VkDescriptorPoolCreateInfo, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkdescriptorpoolcreateinfo_vkdescriptorpoolcreateinfo_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkdescriptorpoolcreateinfo_vkdescriptorpoolcreateinfo_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkdescriptorpoolcreateinfo_vkdescriptorpoolcreateinfo_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkdescriptorpoolcreateinfo_vkdescriptorpoolcreateinfo_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkdescriptorpoolcreateinfo_vkdescriptorpoolcreateinfo_method_entry) {
	PHP_ME(Vulkan_Struct_VkDescriptorPoolCreateInfo_VkDescriptorPoolCreateInfo, pack, arginfo_vulkan_struct_vkdescriptorpoolcreateinfo_vkdescriptorpoolcreateinfo_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkDescriptorPoolCreateInfo_VkDescriptorPoolCreateInfo, packInto, arginfo_vulkan_struct_vkdescriptorpoolcreateinfo_vkdescriptorpoolcreateinfo_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkDescriptorPoolCreateInfo_VkDescriptorPoolCreateInfo, unpack, arginfo_vulkan_struct_vkdescriptorpoolcreateinfo_vkdescriptorpoolcreateinfo_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkDescriptorPoolCreateInfo_VkDescriptorPoolCreateInfo, size, arginfo_vulkan_struct_vkdescriptorpoolcreateinfo_vkdescriptorpoolcreateinfo_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
