
extern zend_class_entry *vulkan_struct_vkphysicaldeviceshadersubgrouprotatefeatures_vkphysicaldeviceshadersubgrouprotatefeatures_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkPhysicalDeviceShaderSubgroupRotateFeatures_VkPhysicalDeviceShaderSubgroupRotateFeatures);

PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceShaderSubgroupRotateFeatures_VkPhysicalDeviceShaderSubgroupRotateFeatures, pack);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceShaderSubgroupRotateFeatures_VkPhysicalDeviceShaderSubgroupRotateFeatures, packInto);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceShaderSubgroupRotateFeatures_VkPhysicalDeviceShaderSubgroupRotateFeatures, unpack);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceShaderSubgroupRotateFeatures_VkPhysicalDeviceShaderSubgroupRotateFeatures, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceshadersubgrouprotatefeatures_vkphysicaldeviceshadersubgrouprotatefeatures_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceshadersubgrouprotatefeatures_vkphysicaldeviceshadersubgrouprotatefeatures_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceshadersubgrouprotatefeatures_vkphysicaldeviceshadersubgrouprotatefeatures_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceshadersubgrouprotatefeatures_vkphysicaldeviceshadersubgrouprotatefeatures_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkphysicaldeviceshadersubgrouprotatefeatures_vkphysicaldeviceshadersubgrouprotatefeatures_method_entry) {
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceShaderSubgroupRotateFeatures_VkPhysicalDeviceShaderSubgroupRotateFeatures, pack, arginfo_vulkan_struct_vkphysicaldeviceshadersubgrouprotatefeatures_vkphysicaldeviceshadersubgrouprotatefeatures_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceShaderSubgroupRotateFeatures_VkPhysicalDeviceShaderSubgroupRotateFeatures, packInto, arginfo_vulkan_struct_vkphysicaldeviceshadersubgrouprotatefeatures_vkphysicaldeviceshadersubgrouprotatefeatures_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceShaderSubgroupRotateFeatures_VkPhysicalDeviceShaderSubgroupRotateFeatures, unpack, arginfo_vulkan_struct_vkphysicaldeviceshadersubgrouprotatefeatures_vkphysicaldeviceshadersubgrouprotatefeatures_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceShaderSubgroupRotateFeatures_VkPhysicalDeviceShaderSubgroupRotateFeatures, size, arginfo_vulkan_struct_vkphysicaldeviceshadersubgrouprotatefeatures_vkphysicaldeviceshadersubgrouprotatefeatures_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
