
extern zend_class_entry *vulkan_struct_vkpipelinecolorblendstatecreateinfo_vkpipelinecolorblendstatecreateinfo_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkPipelineColorBlendStateCreateInfo_VkPipelineColorBlendStateCreateInfo);

PHP_METHOD(Vulkan_Struct_VkPipelineColorBlendStateCreateInfo_VkPipelineColorBlendStateCreateInfo, pack);
PHP_METHOD(Vulkan_Struct_VkPipelineColorBlendStateCreateInfo_VkPipelineColorBlendStateCreateInfo, packInto);
PHP_METHOD(Vulkan_Struct_VkPipelineColorBlendStateCreateInfo_VkPipelineColorBlendStateCreateInfo, unpack);
PHP_METHOD(Vulkan_Struct_VkPipelineColorBlendStateCreateInfo_VkPipelineColorBlendStateCreateInfo, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkpipelinecolorblendstatecreateinfo_vkpipelinecolorblendstatecreateinfo_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkpipelinecolorblendstatecreateinfo_vkpipelinecolorblendstatecreateinfo_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkpipelinecolorblendstatecreateinfo_vkpipelinecolorblendstatecreateinfo_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkpipelinecolorblendstatecreateinfo_vkpipelinecolorblendstatecreateinfo_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkpipelinecolorblendstatecreateinfo_vkpipelinecolorblendstatecreateinfo_method_entry) {
	PHP_ME(Vulkan_Struct_VkPipelineColorBlendStateCreateInfo_VkPipelineColorBlendStateCreateInfo, pack, arginfo_vulkan_struct_vkpipelinecolorblendstatecreateinfo_vkpipelinecolorblendstatecreateinfo_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPipelineColorBlendStateCreateInfo_VkPipelineColorBlendStateCreateInfo, packInto, arginfo_vulkan_struct_vkpipelinecolorblendstatecreateinfo_vkpipelinecolorblendstatecreateinfo_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPipelineColorBlendStateCreateInfo_VkPipelineColorBlendStateCreateInfo, unpack, arginfo_vulkan_struct_vkpipelinecolorblendstatecreateinfo_vkpipelinecolorblendstatecreateinfo_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPipelineColorBlendStateCreateInfo_VkPipelineColorBlendStateCreateInfo, size, arginfo_vulkan_struct_vkpipelinecolorblendstatecreateinfo_vkpipelinecolorblendstatecreateinfo_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
