
extern zend_class_entry *vulkan_struct_vkpipelinedepthstencilstatecreateinfo_vkpipelinedepthstencilstatecreateinfo_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkPipelineDepthStencilStateCreateInfo_VkPipelineDepthStencilStateCreateInfo);

PHP_METHOD(Vulkan_Struct_VkPipelineDepthStencilStateCreateInfo_VkPipelineDepthStencilStateCreateInfo, pack);
PHP_METHOD(Vulkan_Struct_VkPipelineDepthStencilStateCreateInfo_VkPipelineDepthStencilStateCreateInfo, packInto);
PHP_METHOD(Vulkan_Struct_VkPipelineDepthStencilStateCreateInfo_VkPipelineDepthStencilStateCreateInfo, unpack);
PHP_METHOD(Vulkan_Struct_VkPipelineDepthStencilStateCreateInfo_VkPipelineDepthStencilStateCreateInfo, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkpipelinedepthstencilstatecreateinfo_vkpipelinedepthstencilstatecreateinfo_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkpipelinedepthstencilstatecreateinfo_vkpipelinedepthstencilstatecreateinfo_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkpipelinedepthstencilstatecreateinfo_vkpipelinedepthstencilstatecreateinfo_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkpipelinedepthstencilstatecreateinfo_vkpipelinedepthstencilstatecreateinfo_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkpipelinedepthstencilstatecreateinfo_vkpipelinedepthstencilstatecreateinfo_method_entry) {
	PHP_ME(Vulkan_Struct_VkPipelineDepthStencilStateCreateInfo_VkPipelineDepthStencilStateCreateInfo, pack, arginfo_vulkan_struct_vkpipelinedepthstencilstatecreateinfo_vkpipelinedepthstencilstatecreateinfo_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPipelineDepthStencilStateCreateInfo_VkPipelineDepthStencilStateCreateInfo, packInto, arginfo_vulkan_struct_vkpipelinedepthstencilstatecreateinfo_vkpipelinedepthstencilstatecreateinfo_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPipelineDepthStencilStateCreateInfo_VkPipelineDepthStencilStateCreateInfo, unpack, arginfo_vulkan_struct_vkpipelinedepthstencilstatecreateinfo_vkpipelinedepthstencilstatecreateinfo_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPipelineDepthStencilStateCreateInfo_VkPipelineDepthStencilStateCreateInfo, size, arginfo_vulkan_struct_vkpipelinedepthstencilstatecreateinfo_vkpipelinedepthstencilstatecreateinfo_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
