
extern zend_class_entry *vulkan_struct_vkexportmetalsharedeventinfoext_vkexportmetalsharedeventinfoext_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkExportMetalSharedEventInfoEXT_VkExportMetalSharedEventInfoEXT);

PHP_METHOD(Vulkan_Struct_VkExportMetalSharedEventInfoEXT_VkExportMetalSharedEventInfoEXT, pack);
PHP_METHOD(Vulkan_Struct_VkExportMetalSharedEventInfoEXT_VkExportMetalSharedEventInfoEXT, packInto);
PHP_METHOD(Vulkan_Struct_VkExportMetalSharedEventInfoEXT_VkExportMetalSharedEventInfoEXT, unpack);
PHP_METHOD(Vulkan_Struct_VkExportMetalSharedEventInfoEXT_VkExportMetalSharedEventInfoEXT, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkexportmetalsharedeventinfoext_vkexportmetalsharedeventinfoext_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkexportmetalsharedeventinfoext_vkexportmetalsharedeventinfoext_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkexportmetalsharedeventinfoext_vkexportmetalsharedeventinfoext_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkexportmetalsharedeventinfoext_vkexportmetalsharedeventinfoext_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkexportmetalsharedeventinfoext_vkexportmetalsharedeventinfoext_method_entry) {
	PHP_ME(Vulkan_Struct_VkExportMetalSharedEventInfoEXT_VkExportMetalSharedEventInfoEXT, pack, arginfo_vulkan_struct_vkexportmetalsharedeventinfoext_vkexportmetalsharedeventinfoext_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkExportMetalSharedEventInfoEXT_VkExportMetalSharedEventInfoEXT, packInto, arginfo_vulkan_struct_vkexportmetalsharedeventinfoext_vkexportmetalsharedeventinfoext_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkExportMetalSharedEventInfoEXT_VkExportMetalSharedEventInfoEXT, unpack, arginfo_vulkan_struct_vkexportmetalsharedeventinfoext_vkexportmetalsharedeventinfoext_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkExportMetalSharedEventInfoEXT_VkExportMetalSharedEventInfoEXT, size, arginfo_vulkan_struct_vkexportmetalsharedeventinfoext_vkexportmetalsharedeventinfoext_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
