
extern zend_class_entry *vulkan_struct_vkwaylandsurfacecreateinfokhr_vkwaylandsurfacecreateinfokhr_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkWaylandSurfaceCreateInfoKHR_VkWaylandSurfaceCreateInfoKHR);

PHP_METHOD(Vulkan_Struct_VkWaylandSurfaceCreateInfoKHR_VkWaylandSurfaceCreateInfoKHR, pack);
PHP_METHOD(Vulkan_Struct_VkWaylandSurfaceCreateInfoKHR_VkWaylandSurfaceCreateInfoKHR, packInto);
PHP_METHOD(Vulkan_Struct_VkWaylandSurfaceCreateInfoKHR_VkWaylandSurfaceCreateInfoKHR, unpack);
PHP_METHOD(Vulkan_Struct_VkWaylandSurfaceCreateInfoKHR_VkWaylandSurfaceCreateInfoKHR, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkwaylandsurfacecreateinfokhr_vkwaylandsurfacecreateinfokhr_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkwaylandsurfacecreateinfokhr_vkwaylandsurfacecreateinfokhr_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkwaylandsurfacecreateinfokhr_vkwaylandsurfacecreateinfokhr_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkwaylandsurfacecreateinfokhr_vkwaylandsurfacecreateinfokhr_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkwaylandsurfacecreateinfokhr_vkwaylandsurfacecreateinfokhr_method_entry) {
	PHP_ME(Vulkan_Struct_VkWaylandSurfaceCreateInfoKHR_VkWaylandSurfaceCreateInfoKHR, pack, arginfo_vulkan_struct_vkwaylandsurfacecreateinfokhr_vkwaylandsurfacecreateinfokhr_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkWaylandSurfaceCreateInfoKHR_VkWaylandSurfaceCreateInfoKHR, packInto, arginfo_vulkan_struct_vkwaylandsurfacecreateinfokhr_vkwaylandsurfacecreateinfokhr_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkWaylandSurfaceCreateInfoKHR_VkWaylandSurfaceCreateInfoKHR, unpack, arginfo_vulkan_struct_vkwaylandsurfacecreateinfokhr_vkwaylandsurfacecreateinfokhr_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkWaylandSurfaceCreateInfoKHR_VkWaylandSurfaceCreateInfoKHR, size, arginfo_vulkan_struct_vkwaylandsurfacecreateinfokhr_vkwaylandsurfacecreateinfokhr_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
