
extern zend_class_entry *vulkan_struct_vkphysicaldeviceidproperties_vkphysicaldeviceidproperties_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkPhysicalDeviceIDProperties_VkPhysicalDeviceIDProperties);

PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceIDProperties_VkPhysicalDeviceIDProperties, pack);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceIDProperties_VkPhysicalDeviceIDProperties, packInto);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceIDProperties_VkPhysicalDeviceIDProperties, unpack);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceIDProperties_VkPhysicalDeviceIDProperties, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceidproperties_vkphysicaldeviceidproperties_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceidproperties_vkphysicaldeviceidproperties_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceidproperties_vkphysicaldeviceidproperties_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceidproperties_vkphysicaldeviceidproperties_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkphysicaldeviceidproperties_vkphysicaldeviceidproperties_method_entry) {
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceIDProperties_VkPhysicalDeviceIDProperties, pack, arginfo_vulkan_struct_vkphysicaldeviceidproperties_vkphysicaldeviceidproperties_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceIDProperties_VkPhysicalDeviceIDProperties, packInto, arginfo_vulkan_struct_vkphysicaldeviceidproperties_vkphysicaldeviceidproperties_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceIDProperties_VkPhysicalDeviceIDProperties, unpack, arginfo_vulkan_struct_vkphysicaldeviceidproperties_vkphysicaldeviceidproperties_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceIDProperties_VkPhysicalDeviceIDProperties, size, arginfo_vulkan_struct_vkphysicaldeviceidproperties_vkphysicaldeviceidproperties_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
