
extern zend_class_entry *vulkan_struct_vkrenderpassattachmentbegininfo_vkrenderpassattachmentbegininfo_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkRenderPassAttachmentBeginInfo_VkRenderPassAttachmentBeginInfo);

PHP_METHOD(Vulkan_Struct_VkRenderPassAttachmentBeginInfo_VkRenderPassAttachmentBeginInfo, pack);
PHP_METHOD(Vulkan_Struct_VkRenderPassAttachmentBeginInfo_VkRenderPassAttachmentBeginInfo, packInto);
PHP_METHOD(Vulkan_Struct_VkRenderPassAttachmentBeginInfo_VkRenderPassAttachmentBeginInfo, unpack);
PHP_METHOD(Vulkan_Struct_VkRenderPassAttachmentBeginInfo_VkRenderPassAttachmentBeginInfo, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkrenderpassattachmentbegininfo_vkrenderpassattachmentbegininfo_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkrenderpassattachmentbegininfo_vkrenderpassattachmentbegininfo_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkrenderpassattachmentbegininfo_vkrenderpassattachmentbegininfo_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkrenderpassattachmentbegininfo_vkrenderpassattachmentbegininfo_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkrenderpassattachmentbegininfo_vkrenderpassattachmentbegininfo_method_entry) {
	PHP_ME(Vulkan_Struct_VkRenderPassAttachmentBeginInfo_VkRenderPassAttachmentBeginInfo, pack, arginfo_vulkan_struct_vkrenderpassattachmentbegininfo_vkrenderpassattachmentbegininfo_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkRenderPassAttachmentBeginInfo_VkRenderPassAttachmentBeginInfo, packInto, arginfo_vulkan_struct_vkrenderpassattachmentbegininfo_vkrenderpassattachmentbegininfo_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkRenderPassAttachmentBeginInfo_VkRenderPassAttachmentBeginInfo, unpack, arginfo_vulkan_struct_vkrenderpassattachmentbegininfo_vkrenderpassattachmentbegininfo_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkRenderPassAttachmentBeginInfo_VkRenderPassAttachmentBeginInfo, size, arginfo_vulkan_struct_vkrenderpassattachmentbegininfo_vkrenderpassattachmentbegininfo_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
