<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class StructVkcopyimagetomemoryinfoSizeOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (isset($expression['parameters']) && count($expression['parameters']) !== 0) {
            throw new CompilerException("'struct_vkcopyimagetomemoryinfo_size' requires zero parameters", $expression);
        }

        $context->headersManager->add('src/vk-struct-14');


        return new CompiledExpression(
            'int',
            'phpvk_struct_vkcopyimagetomemoryinfo_size(' . ')',
            $expression
        );
    }
}
