<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class Vk10VkcmdwaiteventsOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 11) {
            throw new CompilerException("'vk10_vkcmdwaitevents' requires exactly 11 parameters", $expression);
        }

        $context->headersManager->add('src/vk-10');

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        $context->codePrinter->output('phpvk_vk10_vkcmdwaitevents(' . $resolvedParams[0] . ', ' . $resolvedParams[1] . ', ' . $resolvedParams[2] . ', ' . $resolvedParams[3] . ', ' . $resolvedParams[4] . ', ' . $resolvedParams[5] . ', ' . $resolvedParams[6] . ', ' . $resolvedParams[7] . ', ' . $resolvedParams[8] . ', ' . $resolvedParams[9] . ', ' . $resolvedParams[10] . ');');

        return new CompiledExpression('null', 'null', $expression);
    }
}
