// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Vulkan\Struct\VkPipelineCreateFlags2CreateInfo;

class VkPipelineCreateFlags2CreateInfo
{
    public static function pack(array members) -> int
    {
        return struct_vkpipelinecreateflags2createinfo_pack(members);
    }

    public static function packInto(int ptr, array members) -> void
    {
        struct_vkpipelinecreateflags2createinfo_packinto(ptr, members);
    }

    public static function unpack(int ptr) -> array
    {
        var result;

        let result = struct_vkpipelinecreateflags2createinfo_unpack(ptr);

        return result;
    }

    public static function size() -> int
    {
        return struct_vkpipelinecreateflags2createinfo_size();
    }
}
