// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Vulkan\Struct\VkBufferUsageFlags2CreateInfo;

class VkBufferUsageFlags2CreateInfo
{
    public static function pack(array members) -> int
    {
        return struct_vkbufferusageflags2createinfo_pack(members);
    }

    public static function packInto(int ptr, array members) -> void
    {
        struct_vkbufferusageflags2createinfo_packinto(ptr, members);
    }

    public static function unpack(int ptr) -> array
    {
        var result;

        let result = struct_vkbufferusageflags2createinfo_unpack(ptr);

        return result;
    }

    public static function size() -> int
    {
        return struct_vkbufferusageflags2createinfo_size();
    }
}
