// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Vulkan\VK\VK14;

class VK14
{
    public static function vkMapMemory2(int device, int pMemoryMapInfo, int ppData) -> int
    {
        return vk14_vkmapmemory2(device, pMemoryMapInfo, ppData);
    }

    public static function vkUnmapMemory2(int device, int pMemoryUnmapInfo) -> int
    {
        return vk14_vkunmapmemory2(device, pMemoryUnmapInfo);
    }

    public static function vkGetDeviceImageSubresourceLayout(int device, int pInfo, int pLayout) -> void
    {
        vk14_vkgetdeviceimagesubresourcelayout(device, pInfo, pLayout);
    }

    public static function vkGetImageSubresourceLayout2(int device, int image, int pSubresource, int pLayout) -> void
    {
        vk14_vkgetimagesubresourcelayout2(device, image, pSubresource, pLayout);
    }

    public static function vkCopyMemoryToImage(int device, int pCopyMemoryToImageInfo) -> int
    {
        return vk14_vkcopymemorytoimage(device, pCopyMemoryToImageInfo);
    }

    public static function vkCopyImageToMemory(int device, int pCopyImageToMemoryInfo) -> int
    {
        return vk14_vkcopyimagetomemory(device, pCopyImageToMemoryInfo);
    }

    public static function vkCopyImageToImage(int device, int pCopyImageToImageInfo) -> int
    {
        return vk14_vkcopyimagetoimage(device, pCopyImageToImageInfo);
    }

    public static function vkTransitionImageLayout(int device, int transitionCount, int pTransitions) -> int
    {
        return vk14_vktransitionimagelayout(device, transitionCount, pTransitions);
    }

    public static function vkCmdPushDescriptorSet(int commandBuffer, int pipelineBindPoint, int layout, int set, int descriptorWriteCount, int pDescriptorWrites) -> void
    {
        vk14_vkcmdpushdescriptorset(commandBuffer, pipelineBindPoint, layout, set, descriptorWriteCount, pDescriptorWrites);
    }

    public static function vkCmdPushDescriptorSetWithTemplate(int commandBuffer, int descriptorUpdateTemplate, int layout, int set, int pData) -> void
    {
        vk14_vkcmdpushdescriptorsetwithtemplate(commandBuffer, descriptorUpdateTemplate, layout, set, pData);
    }

    public static function vkCmdBindDescriptorSets2(int commandBuffer, int pBindDescriptorSetsInfo) -> void
    {
        vk14_vkcmdbinddescriptorsets2(commandBuffer, pBindDescriptorSetsInfo);
    }

    public static function vkCmdPushConstants2(int commandBuffer, int pPushConstantsInfo) -> void
    {
        vk14_vkcmdpushconstants2(commandBuffer, pPushConstantsInfo);
    }

    public static function vkCmdPushDescriptorSet2(int commandBuffer, int pPushDescriptorSetInfo) -> void
    {
        vk14_vkcmdpushdescriptorset2(commandBuffer, pPushDescriptorSetInfo);
    }

    public static function vkCmdPushDescriptorSetWithTemplate2(int commandBuffer, int pPushDescriptorSetWithTemplateInfo) -> void
    {
        vk14_vkcmdpushdescriptorsetwithtemplate2(commandBuffer, pPushDescriptorSetWithTemplateInfo);
    }

    public static function vkCmdSetLineStipple(int commandBuffer, int lineStippleFactor, int lineStipplePattern) -> void
    {
        vk14_vkcmdsetlinestipple(commandBuffer, lineStippleFactor, lineStipplePattern);
    }

    public static function vkCmdBindIndexBuffer2(int commandBuffer, int buffer, int offset, int size, int indexType) -> void
    {
        vk14_vkcmdbindindexbuffer2(commandBuffer, buffer, offset, size, indexType);
    }

    public static function vkGetRenderingAreaGranularity(int device, int pRenderingAreaInfo, int pGranularity) -> void
    {
        vk14_vkgetrenderingareagranularity(device, pRenderingAreaInfo, pGranularity);
    }

    public static function vkCmdSetRenderingAttachmentLocations(int commandBuffer, int pLocationInfo) -> void
    {
        vk14_vkcmdsetrenderingattachmentlocations(commandBuffer, pLocationInfo);
    }

    public static function vkCmdSetRenderingInputAttachmentIndices(int commandBuffer, int pInputAttachmentIndexInfo) -> void
    {
        vk14_vkcmdsetrenderinginputattachmentindices(commandBuffer, pInputAttachmentIndexInfo);
    }
}
