
extern zend_class_entry *vulkan_struct_vkdeviceimagesubresourceinfo_vkdeviceimagesubresourceinfo_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkDeviceImageSubresourceInfo_VkDeviceImageSubresourceInfo);

PHP_METHOD(Vulkan_Struct_VkDeviceImageSubresourceInfo_VkDeviceImageSubresourceInfo, pack);
PHP_METHOD(Vulkan_Struct_VkDeviceImageSubresourceInfo_VkDeviceImageSubresourceInfo, packInto);
PHP_METHOD(Vulkan_Struct_VkDeviceImageSubresourceInfo_VkDeviceImageSubresourceInfo, unpack);
PHP_METHOD(Vulkan_Struct_VkDeviceImageSubresourceInfo_VkDeviceImageSubresourceInfo, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkdeviceimagesubresourceinfo_vkdeviceimagesubresourceinfo_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkdeviceimagesubresourceinfo_vkdeviceimagesubresourceinfo_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkdeviceimagesubresourceinfo_vkdeviceimagesubresourceinfo_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkdeviceimagesubresourceinfo_vkdeviceimagesubresourceinfo_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkdeviceimagesubresourceinfo_vkdeviceimagesubresourceinfo_method_entry) {
	PHP_ME(Vulkan_Struct_VkDeviceImageSubresourceInfo_VkDeviceImageSubresourceInfo, pack, arginfo_vulkan_struct_vkdeviceimagesubresourceinfo_vkdeviceimagesubresourceinfo_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkDeviceImageSubresourceInfo_VkDeviceImageSubresourceInfo, packInto, arginfo_vulkan_struct_vkdeviceimagesubresourceinfo_vkdeviceimagesubresourceinfo_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkDeviceImageSubresourceInfo_VkDeviceImageSubresourceInfo, unpack, arginfo_vulkan_struct_vkdeviceimagesubresourceinfo_vkdeviceimagesubresourceinfo_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkDeviceImageSubresourceInfo_VkDeviceImageSubresourceInfo, size, arginfo_vulkan_struct_vkdeviceimagesubresourceinfo_vkdeviceimagesubresourceinfo_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
