// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Vulkan\Struct\VkPhysicalDeviceIndexTypeUint8Features;

class VkPhysicalDeviceIndexTypeUint8Features
{
    public static function pack(array members) -> int
    {
        return struct_vkphysicaldeviceindextypeuint8features_pack(members);
    }

    public static function packInto(int ptr, array members) -> void
    {
        struct_vkphysicaldeviceindextypeuint8features_packinto(ptr, members);
    }

    public static function unpack(int ptr) -> array
    {
        var result;

        let result = struct_vkphysicaldeviceindextypeuint8features_unpack(ptr);

        return result;
    }

    public static function size() -> int
    {
        return struct_vkphysicaldeviceindextypeuint8features_size();
    }
}
