
extern zend_class_entry *vulkan_struct_vkphysicaldeviceprotectedmemoryproperties_vkphysicaldeviceprotectedmemoryproperties_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkPhysicalDeviceProtectedMemoryProperties_VkPhysicalDeviceProtectedMemoryProperties);

PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceProtectedMemoryProperties_VkPhysicalDeviceProtectedMemoryProperties, pack);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceProtectedMemoryProperties_VkPhysicalDeviceProtectedMemoryProperties, packInto);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceProtectedMemoryProperties_VkPhysicalDeviceProtectedMemoryProperties, unpack);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceProtectedMemoryProperties_VkPhysicalDeviceProtectedMemoryProperties, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceprotectedmemoryproperties_vkphysicaldeviceprotectedmemoryproperties_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceprotectedmemoryproperties_vkphysicaldeviceprotectedmemoryproperties_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceprotectedmemoryproperties_vkphysicaldeviceprotectedmemoryproperties_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceprotectedmemoryproperties_vkphysicaldeviceprotectedmemoryproperties_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkphysicaldeviceprotectedmemoryproperties_vkphysicaldeviceprotectedmemoryproperties_method_entry) {
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceProtectedMemoryProperties_VkPhysicalDeviceProtectedMemoryProperties, pack, arginfo_vulkan_struct_vkphysicaldeviceprotectedmemoryproperties_vkphysicaldeviceprotectedmemoryproperties_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceProtectedMemoryProperties_VkPhysicalDeviceProtectedMemoryProperties, packInto, arginfo_vulkan_struct_vkphysicaldeviceprotectedmemoryproperties_vkphysicaldeviceprotectedmemoryproperties_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceProtectedMemoryProperties_VkPhysicalDeviceProtectedMemoryProperties, unpack, arginfo_vulkan_struct_vkphysicaldeviceprotectedmemoryproperties_vkphysicaldeviceprotectedmemoryproperties_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceProtectedMemoryProperties_VkPhysicalDeviceProtectedMemoryProperties, size, arginfo_vulkan_struct_vkphysicaldeviceprotectedmemoryproperties_vkphysicaldeviceprotectedmemoryproperties_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
