
/* This file was generated automatically by Zephir do not modify it! */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <php.h>

#include "php_ext.h"

/* PHPVK module teardown */
#include "src/phpvk-bridge.h"
#include "vulkan.h"

#include <ext/standard/info.h>

#include <Zend/zend_operators.h>
#include <Zend/zend_exceptions.h>
#include <Zend/zend_interfaces.h>

#include "kernel/globals.h"
#include "kernel/main.h"
#include "kernel/fcall.h"
#include "kernel/memory.h"



zend_class_entry *vulkan_bridge_bridge_ce;
zend_class_entry *vulkan_ext_extdebugutils_extdebugutils_ce;
zend_class_entry *vulkan_ext_extmetalobjects_extmetalobjects_ce;
zend_class_entry *vulkan_ext_extmetalsurface_extmetalsurface_ce;
zend_class_entry *vulkan_ext_khrsurface_khrsurface_ce;
zend_class_entry *vulkan_ext_khrswapchain_khrswapchain_ce;
zend_class_entry *vulkan_ext_khrwaylandsurface_khrwaylandsurface_ce;
zend_class_entry *vulkan_ext_khrxcbsurface_khrxcbsurface_ce;
zend_class_entry *vulkan_ext_khrxlibsurface_khrxlibsurface_ce;
zend_class_entry *vulkan_struct_vkacquirenextimageinfokhr_vkacquirenextimageinfokhr_ce;
zend_class_entry *vulkan_struct_vkallocationcallbacks_vkallocationcallbacks_ce;
zend_class_entry *vulkan_struct_vkapplicationinfo_vkapplicationinfo_ce;
zend_class_entry *vulkan_struct_vkattachmentdescription2_vkattachmentdescription2_ce;
zend_class_entry *vulkan_struct_vkattachmentdescription_vkattachmentdescription_ce;
zend_class_entry *vulkan_struct_vkattachmentdescriptionstencillayout_vkattachmentdescriptionstencillayout_ce;
zend_class_entry *vulkan_struct_vkattachmentreference2_vkattachmentreference2_ce;
zend_class_entry *vulkan_struct_vkattachmentreference_vkattachmentreference_ce;
zend_class_entry *vulkan_struct_vkattachmentreferencestencillayout_vkattachmentreferencestencillayout_ce;
zend_class_entry *vulkan_struct_vkbaseinstructure_vkbaseinstructure_ce;
zend_class_entry *vulkan_struct_vkbaseoutstructure_vkbaseoutstructure_ce;
zend_class_entry *vulkan_struct_vkbindbuffermemorydevicegroupinfo_vkbindbuffermemorydevicegroupinfo_ce;
zend_class_entry *vulkan_struct_vkbindbuffermemoryinfo_vkbindbuffermemoryinfo_ce;
zend_class_entry *vulkan_struct_vkbinddescriptorsetsinfo_vkbinddescriptorsetsinfo_ce;
zend_class_entry *vulkan_struct_vkbindimagememorydevicegroupinfo_vkbindimagememorydevicegroupinfo_ce;
zend_class_entry *vulkan_struct_vkbindimagememoryinfo_vkbindimagememoryinfo_ce;
zend_class_entry *vulkan_struct_vkbindimagememoryswapchaininfokhr_vkbindimagememoryswapchaininfokhr_ce;
zend_class_entry *vulkan_struct_vkbindimageplanememoryinfo_vkbindimageplanememoryinfo_ce;
zend_class_entry *vulkan_struct_vkbindmemorystatus_vkbindmemorystatus_ce;
zend_class_entry *vulkan_struct_vkbindsparseinfo_vkbindsparseinfo_ce;
zend_class_entry *vulkan_struct_vkblitimageinfo2_vkblitimageinfo2_ce;
zend_class_entry *vulkan_struct_vkbuffercopy2_vkbuffercopy2_ce;
zend_class_entry *vulkan_struct_vkbuffercopy_vkbuffercopy_ce;
zend_class_entry *vulkan_struct_vkbuffercreateinfo_vkbuffercreateinfo_ce;
zend_class_entry *vulkan_struct_vkbufferdeviceaddressinfo_vkbufferdeviceaddressinfo_ce;
zend_class_entry *vulkan_struct_vkbufferimagecopy2_vkbufferimagecopy2_ce;
zend_class_entry *vulkan_struct_vkbufferimagecopy_vkbufferimagecopy_ce;
zend_class_entry *vulkan_struct_vkbuffermemorybarrier2_vkbuffermemorybarrier2_ce;
zend_class_entry *vulkan_struct_vkbuffermemorybarrier_vkbuffermemorybarrier_ce;
zend_class_entry *vulkan_struct_vkbuffermemoryrequirementsinfo2_vkbuffermemoryrequirementsinfo2_ce;
zend_class_entry *vulkan_struct_vkbufferopaquecaptureaddresscreateinfo_vkbufferopaquecaptureaddresscreateinfo_ce;
zend_class_entry *vulkan_struct_vkbufferusageflags2createinfo_vkbufferusageflags2createinfo_ce;
zend_class_entry *vulkan_struct_vkbufferviewcreateinfo_vkbufferviewcreateinfo_ce;
zend_class_entry *vulkan_struct_vkclearattachment_vkclearattachment_ce;
zend_class_entry *vulkan_struct_vkclearcolorvalue_vkclearcolorvalue_ce;
zend_class_entry *vulkan_struct_vkcleardepthstencilvalue_vkcleardepthstencilvalue_ce;
zend_class_entry *vulkan_struct_vkclearrect_vkclearrect_ce;
zend_class_entry *vulkan_struct_vkclearvalue_vkclearvalue_ce;
zend_class_entry *vulkan_struct_vkcommandbufferallocateinfo_vkcommandbufferallocateinfo_ce;
zend_class_entry *vulkan_struct_vkcommandbufferbegininfo_vkcommandbufferbegininfo_ce;
zend_class_entry *vulkan_struct_vkcommandbufferinheritanceinfo_vkcommandbufferinheritanceinfo_ce;
zend_class_entry *vulkan_struct_vkcommandbufferinheritancerenderinginfo_vkcommandbufferinheritancerenderinginfo_ce;
zend_class_entry *vulkan_struct_vkcommandbuffersubmitinfo_vkcommandbuffersubmitinfo_ce;
zend_class_entry *vulkan_struct_vkcommandpoolcreateinfo_vkcommandpoolcreateinfo_ce;
zend_class_entry *vulkan_struct_vkcomponentmapping_vkcomponentmapping_ce;
zend_class_entry *vulkan_struct_vkcomputepipelinecreateinfo_vkcomputepipelinecreateinfo_ce;
zend_class_entry *vulkan_struct_vkconformanceversion_vkconformanceversion_ce;
zend_class_entry *vulkan_struct_vkcopybufferinfo2_vkcopybufferinfo2_ce;
zend_class_entry *vulkan_struct_vkcopybuffertoimageinfo2_vkcopybuffertoimageinfo2_ce;
zend_class_entry *vulkan_struct_vkcopydescriptorset_vkcopydescriptorset_ce;
zend_class_entry *vulkan_struct_vkcopyimageinfo2_vkcopyimageinfo2_ce;
zend_class_entry *vulkan_struct_vkcopyimagetobufferinfo2_vkcopyimagetobufferinfo2_ce;
zend_class_entry *vulkan_struct_vkcopyimagetoimageinfo_vkcopyimagetoimageinfo_ce;
zend_class_entry *vulkan_struct_vkcopyimagetomemoryinfo_vkcopyimagetomemoryinfo_ce;
zend_class_entry *vulkan_struct_vkcopymemorytoimageinfo_vkcopymemorytoimageinfo_ce;
zend_class_entry *vulkan_struct_vkdebugutilslabelext_vkdebugutilslabelext_ce;
zend_class_entry *vulkan_struct_vkdebugutilsmessengercallbackdataext_vkdebugutilsmessengercallbackdataext_ce;
zend_class_entry *vulkan_struct_vkdebugutilsmessengercreateinfoext_vkdebugutilsmessengercreateinfoext_ce;
zend_class_entry *vulkan_struct_vkdebugutilsobjectnameinfoext_vkdebugutilsobjectnameinfoext_ce;
zend_class_entry *vulkan_struct_vkdebugutilsobjecttaginfoext_vkdebugutilsobjecttaginfoext_ce;
zend_class_entry *vulkan_struct_vkdependencyinfo_vkdependencyinfo_ce;
zend_class_entry *vulkan_struct_vkdescriptorbufferinfo_vkdescriptorbufferinfo_ce;
zend_class_entry *vulkan_struct_vkdescriptorimageinfo_vkdescriptorimageinfo_ce;
zend_class_entry *vulkan_struct_vkdescriptorpoolcreateinfo_vkdescriptorpoolcreateinfo_ce;
zend_class_entry *vulkan_struct_vkdescriptorpoolinlineuniformblockcreateinfo_vkdescriptorpoolinlineuniformblockcreateinfo_ce;
zend_class_entry *vulkan_struct_vkdescriptorpoolsize_vkdescriptorpoolsize_ce;
zend_class_entry *vulkan_struct_vkdescriptorsetallocateinfo_vkdescriptorsetallocateinfo_ce;
zend_class_entry *vulkan_struct_vkdescriptorsetlayoutbinding_vkdescriptorsetlayoutbinding_ce;
zend_class_entry *vulkan_struct_vkdescriptorsetlayoutbindingflagscreateinfo_vkdescriptorsetlayoutbindingflagscreateinfo_ce;
zend_class_entry *vulkan_struct_vkdescriptorsetlayoutcreateinfo_vkdescriptorsetlayoutcreateinfo_ce;
zend_class_entry *vulkan_struct_vkdescriptorsetlayoutsupport_vkdescriptorsetlayoutsupport_ce;
zend_class_entry *vulkan_struct_vkdescriptorsetvariabledescriptorcountallocateinfo_vkdescriptorsetvariabledescriptorcountallocateinfo_ce;
zend_class_entry *vulkan_struct_vkdescriptorsetvariabledescriptorcountlayoutsupport_vkdescriptorsetvariabledescriptorcountlayoutsupport_ce;
zend_class_entry *vulkan_struct_vkdescriptorupdatetemplatecreateinfo_vkdescriptorupdatetemplatecreateinfo_ce;
zend_class_entry *vulkan_struct_vkdescriptorupdatetemplateentry_vkdescriptorupdatetemplateentry_ce;
zend_class_entry *vulkan_struct_vkdevicebuffermemoryrequirements_vkdevicebuffermemoryrequirements_ce;
zend_class_entry *vulkan_struct_vkdevicecreateinfo_vkdevicecreateinfo_ce;
zend_class_entry *vulkan_struct_vkdevicegroupbindsparseinfo_vkdevicegroupbindsparseinfo_ce;
zend_class_entry *vulkan_struct_vkdevicegroupcommandbufferbegininfo_vkdevicegroupcommandbufferbegininfo_ce;
zend_class_entry *vulkan_struct_vkdevicegroupdevicecreateinfo_vkdevicegroupdevicecreateinfo_ce;
zend_class_entry *vulkan_struct_vkdevicegrouppresentcapabilitieskhr_vkdevicegrouppresentcapabilitieskhr_ce;
zend_class_entry *vulkan_struct_vkdevicegrouppresentinfokhr_vkdevicegrouppresentinfokhr_ce;
zend_class_entry *vulkan_struct_vkdevicegrouprenderpassbegininfo_vkdevicegrouprenderpassbegininfo_ce;
zend_class_entry *vulkan_struct_vkdevicegroupsubmitinfo_vkdevicegroupsubmitinfo_ce;
zend_class_entry *vulkan_struct_vkdevicegroupswapchaincreateinfokhr_vkdevicegroupswapchaincreateinfokhr_ce;
zend_class_entry *vulkan_struct_vkdeviceimagememoryrequirements_vkdeviceimagememoryrequirements_ce;
zend_class_entry *vulkan_struct_vkdeviceimagesubresourceinfo_vkdeviceimagesubresourceinfo_ce;
zend_class_entry *vulkan_struct_vkdevicememoryopaquecaptureaddressinfo_vkdevicememoryopaquecaptureaddressinfo_ce;
zend_class_entry *vulkan_struct_vkdeviceprivatedatacreateinfo_vkdeviceprivatedatacreateinfo_ce;
zend_class_entry *vulkan_struct_vkdevicequeuecreateinfo_vkdevicequeuecreateinfo_ce;
zend_class_entry *vulkan_struct_vkdevicequeueglobalprioritycreateinfo_vkdevicequeueglobalprioritycreateinfo_ce;
zend_class_entry *vulkan_struct_vkdevicequeueinfo2_vkdevicequeueinfo2_ce;
zend_class_entry *vulkan_struct_vkdispatchindirectcommand_vkdispatchindirectcommand_ce;
zend_class_entry *vulkan_struct_vkdrawindexedindirectcommand_vkdrawindexedindirectcommand_ce;
zend_class_entry *vulkan_struct_vkdrawindirectcommand_vkdrawindirectcommand_ce;
zend_class_entry *vulkan_struct_vkeventcreateinfo_vkeventcreateinfo_ce;
zend_class_entry *vulkan_struct_vkexportfencecreateinfo_vkexportfencecreateinfo_ce;
zend_class_entry *vulkan_struct_vkexportmemoryallocateinfo_vkexportmemoryallocateinfo_ce;
zend_class_entry *vulkan_struct_vkexportmetalbufferinfoext_vkexportmetalbufferinfoext_ce;
zend_class_entry *vulkan_struct_vkexportmetalcommandqueueinfoext_vkexportmetalcommandqueueinfoext_ce;
zend_class_entry *vulkan_struct_vkexportmetaldeviceinfoext_vkexportmetaldeviceinfoext_ce;
zend_class_entry *vulkan_struct_vkexportmetaliosurfaceinfoext_vkexportmetaliosurfaceinfoext_ce;
zend_class_entry *vulkan_struct_vkexportmetalobjectcreateinfoext_vkexportmetalobjectcreateinfoext_ce;
zend_class_entry *vulkan_struct_vkexportmetalobjectsinfoext_vkexportmetalobjectsinfoext_ce;
zend_class_entry *vulkan_struct_vkexportmetalsharedeventinfoext_vkexportmetalsharedeventinfoext_ce;
zend_class_entry *vulkan_struct_vkexportmetaltextureinfoext_vkexportmetaltextureinfoext_ce;
zend_class_entry *vulkan_struct_vkexportsemaphorecreateinfo_vkexportsemaphorecreateinfo_ce;
zend_class_entry *vulkan_struct_vkextensionproperties_vkextensionproperties_ce;
zend_class_entry *vulkan_struct_vkextent2d_vkextent2d_ce;
zend_class_entry *vulkan_struct_vkextent3d_vkextent3d_ce;
zend_class_entry *vulkan_struct_vkexternalbufferproperties_vkexternalbufferproperties_ce;
zend_class_entry *vulkan_struct_vkexternalfenceproperties_vkexternalfenceproperties_ce;
zend_class_entry *vulkan_struct_vkexternalimageformatproperties_vkexternalimageformatproperties_ce;
zend_class_entry *vulkan_struct_vkexternalmemorybuffercreateinfo_vkexternalmemorybuffercreateinfo_ce;
zend_class_entry *vulkan_struct_vkexternalmemoryimagecreateinfo_vkexternalmemoryimagecreateinfo_ce;
zend_class_entry *vulkan_struct_vkexternalmemoryproperties_vkexternalmemoryproperties_ce;
zend_class_entry *vulkan_struct_vkexternalsemaphoreproperties_vkexternalsemaphoreproperties_ce;
zend_class_entry *vulkan_struct_vkfencecreateinfo_vkfencecreateinfo_ce;
zend_class_entry *vulkan_struct_vkformatproperties2_vkformatproperties2_ce;
zend_class_entry *vulkan_struct_vkformatproperties3_vkformatproperties3_ce;
zend_class_entry *vulkan_struct_vkformatproperties_vkformatproperties_ce;
zend_class_entry *vulkan_struct_vkframebufferattachmentimageinfo_vkframebufferattachmentimageinfo_ce;
zend_class_entry *vulkan_struct_vkframebufferattachmentscreateinfo_vkframebufferattachmentscreateinfo_ce;
zend_class_entry *vulkan_struct_vkframebuffercreateinfo_vkframebuffercreateinfo_ce;
zend_class_entry *vulkan_struct_vkgraphicspipelinecreateinfo_vkgraphicspipelinecreateinfo_ce;
zend_class_entry *vulkan_struct_vkhostimagecopydeviceperformancequery_vkhostimagecopydeviceperformancequery_ce;
zend_class_entry *vulkan_struct_vkhostimagelayouttransitioninfo_vkhostimagelayouttransitioninfo_ce;
zend_class_entry *vulkan_struct_vkimageblit2_vkimageblit2_ce;
zend_class_entry *vulkan_struct_vkimageblit_vkimageblit_ce;
zend_class_entry *vulkan_struct_vkimagecopy2_vkimagecopy2_ce;
zend_class_entry *vulkan_struct_vkimagecopy_vkimagecopy_ce;
zend_class_entry *vulkan_struct_vkimagecreateinfo_vkimagecreateinfo_ce;
zend_class_entry *vulkan_struct_vkimageformatlistcreateinfo_vkimageformatlistcreateinfo_ce;
zend_class_entry *vulkan_struct_vkimageformatproperties2_vkimageformatproperties2_ce;
zend_class_entry *vulkan_struct_vkimageformatproperties_vkimageformatproperties_ce;
zend_class_entry *vulkan_struct_vkimagememorybarrier2_vkimagememorybarrier2_ce;
zend_class_entry *vulkan_struct_vkimagememorybarrier_vkimagememorybarrier_ce;
zend_class_entry *vulkan_struct_vkimagememoryrequirementsinfo2_vkimagememoryrequirementsinfo2_ce;
zend_class_entry *vulkan_struct_vkimageplanememoryrequirementsinfo_vkimageplanememoryrequirementsinfo_ce;
zend_class_entry *vulkan_struct_vkimageresolve2_vkimageresolve2_ce;
zend_class_entry *vulkan_struct_vkimageresolve_vkimageresolve_ce;
zend_class_entry *vulkan_struct_vkimagesparsememoryrequirementsinfo2_vkimagesparsememoryrequirementsinfo2_ce;
zend_class_entry *vulkan_struct_vkimagestencilusagecreateinfo_vkimagestencilusagecreateinfo_ce;
zend_class_entry *vulkan_struct_vkimagesubresource2_vkimagesubresource2_ce;
zend_class_entry *vulkan_struct_vkimagesubresource_vkimagesubresource_ce;
zend_class_entry *vulkan_struct_vkimagesubresourcelayers_vkimagesubresourcelayers_ce;
zend_class_entry *vulkan_struct_vkimagesubresourcerange_vkimagesubresourcerange_ce;
zend_class_entry *vulkan_struct_vkimageswapchaincreateinfokhr_vkimageswapchaincreateinfokhr_ce;
zend_class_entry *vulkan_struct_vkimagetomemorycopy_vkimagetomemorycopy_ce;
zend_class_entry *vulkan_struct_vkimageviewcreateinfo_vkimageviewcreateinfo_ce;
zend_class_entry *vulkan_struct_vkimageviewusagecreateinfo_vkimageviewusagecreateinfo_ce;
zend_class_entry *vulkan_struct_vkimportmetalbufferinfoext_vkimportmetalbufferinfoext_ce;
zend_class_entry *vulkan_struct_vkimportmetaliosurfaceinfoext_vkimportmetaliosurfaceinfoext_ce;
zend_class_entry *vulkan_struct_vkimportmetalsharedeventinfoext_vkimportmetalsharedeventinfoext_ce;
zend_class_entry *vulkan_struct_vkimportmetaltextureinfoext_vkimportmetaltextureinfoext_ce;
zend_class_entry *vulkan_struct_vkinputattachmentaspectreference_vkinputattachmentaspectreference_ce;
zend_class_entry *vulkan_struct_vkinstancecreateinfo_vkinstancecreateinfo_ce;
zend_class_entry *vulkan_struct_vklayerproperties_vklayerproperties_ce;
zend_class_entry *vulkan_struct_vklayersettingext_vklayersettingext_ce;
zend_class_entry *vulkan_struct_vklayersettingscreateinfoext_vklayersettingscreateinfoext_ce;
zend_class_entry *vulkan_struct_vkmappedmemoryrange_vkmappedmemoryrange_ce;
zend_class_entry *vulkan_struct_vkmemoryallocateflagsinfo_vkmemoryallocateflagsinfo_ce;
zend_class_entry *vulkan_struct_vkmemoryallocateinfo_vkmemoryallocateinfo_ce;
zend_class_entry *vulkan_struct_vkmemorybarrier2_vkmemorybarrier2_ce;
zend_class_entry *vulkan_struct_vkmemorybarrier_vkmemorybarrier_ce;
zend_class_entry *vulkan_struct_vkmemorydedicatedallocateinfo_vkmemorydedicatedallocateinfo_ce;
zend_class_entry *vulkan_struct_vkmemorydedicatedrequirements_vkmemorydedicatedrequirements_ce;
zend_class_entry *vulkan_struct_vkmemoryheap_vkmemoryheap_ce;
zend_class_entry *vulkan_struct_vkmemorymapinfo_vkmemorymapinfo_ce;
zend_class_entry *vulkan_struct_vkmemoryopaquecaptureaddressallocateinfo_vkmemoryopaquecaptureaddressallocateinfo_ce;
zend_class_entry *vulkan_struct_vkmemoryrequirements2_vkmemoryrequirements2_ce;
zend_class_entry *vulkan_struct_vkmemoryrequirements_vkmemoryrequirements_ce;
zend_class_entry *vulkan_struct_vkmemorytoimagecopy_vkmemorytoimagecopy_ce;
zend_class_entry *vulkan_struct_vkmemorytype_vkmemorytype_ce;
zend_class_entry *vulkan_struct_vkmemoryunmapinfo_vkmemoryunmapinfo_ce;
zend_class_entry *vulkan_struct_vkmetalsurfacecreateinfoext_vkmetalsurfacecreateinfoext_ce;
zend_class_entry *vulkan_struct_vkoffset2d_vkoffset2d_ce;
zend_class_entry *vulkan_struct_vkoffset3d_vkoffset3d_ce;
zend_class_entry *vulkan_struct_vkphysicaldevice16bitstoragefeatures_vkphysicaldevice16bitstoragefeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevice8bitstoragefeatures_vkphysicaldevice8bitstoragefeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicebufferdeviceaddressfeatures_vkphysicaldevicebufferdeviceaddressfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicedepthstencilresolveproperties_vkphysicaldevicedepthstencilresolveproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicedescriptorindexingfeatures_vkphysicaldevicedescriptorindexingfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicedescriptorindexingproperties_vkphysicaldevicedescriptorindexingproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicedriverproperties_vkphysicaldevicedriverproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicedynamicrenderingfeatures_vkphysicaldevicedynamicrenderingfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicedynamicrenderinglocalreadfeatures_vkphysicaldevicedynamicrenderinglocalreadfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceexternalbufferinfo_vkphysicaldeviceexternalbufferinfo_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceexternalfenceinfo_vkphysicaldeviceexternalfenceinfo_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceexternalimageformatinfo_vkphysicaldeviceexternalimageformatinfo_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceexternalsemaphoreinfo_vkphysicaldeviceexternalsemaphoreinfo_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicefeatures2_vkphysicaldevicefeatures2_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicefeatures_vkphysicaldevicefeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicefloatcontrolsproperties_vkphysicaldevicefloatcontrolsproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceglobalpriorityqueryfeatures_vkphysicaldeviceglobalpriorityqueryfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicegroupproperties_vkphysicaldevicegroupproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicehostimagecopyfeatures_vkphysicaldevicehostimagecopyfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicehostimagecopyproperties_vkphysicaldevicehostimagecopyproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicehostqueryresetfeatures_vkphysicaldevicehostqueryresetfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceidproperties_vkphysicaldeviceidproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceimageformatinfo2_vkphysicaldeviceimageformatinfo2_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceimagelessframebufferfeatures_vkphysicaldeviceimagelessframebufferfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceimagerobustnessfeatures_vkphysicaldeviceimagerobustnessfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceindextypeuint8features_vkphysicaldeviceindextypeuint8features_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceinlineuniformblockfeatures_vkphysicaldeviceinlineuniformblockfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceinlineuniformblockproperties_vkphysicaldeviceinlineuniformblockproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicelimits_vkphysicaldevicelimits_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicelinerasterizationfeatures_vkphysicaldevicelinerasterizationfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicelinerasterizationproperties_vkphysicaldevicelinerasterizationproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicemaintenance3properties_vkphysicaldevicemaintenance3properties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicemaintenance4features_vkphysicaldevicemaintenance4features_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicemaintenance4properties_vkphysicaldevicemaintenance4properties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicemaintenance5features_vkphysicaldevicemaintenance5features_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicemaintenance5properties_vkphysicaldevicemaintenance5properties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicemaintenance6features_vkphysicaldevicemaintenance6features_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicemaintenance6properties_vkphysicaldevicemaintenance6properties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicememoryproperties2_vkphysicaldevicememoryproperties2_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicememoryproperties_vkphysicaldevicememoryproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicemultiviewfeatures_vkphysicaldevicemultiviewfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicemultiviewproperties_vkphysicaldevicemultiviewproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicepipelinecreationcachecontrolfeatures_vkphysicaldevicepipelinecreationcachecontrolfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicepipelineprotectedaccessfeatures_vkphysicaldevicepipelineprotectedaccessfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicepipelinerobustnessfeatures_vkphysicaldevicepipelinerobustnessfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicepipelinerobustnessproperties_vkphysicaldevicepipelinerobustnessproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicepointclippingproperties_vkphysicaldevicepointclippingproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceportabilitysubsetfeatureskhr_vkphysicaldeviceportabilitysubsetfeatureskhr_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceportabilitysubsetpropertieskhr_vkphysicaldeviceportabilitysubsetpropertieskhr_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceprivatedatafeatures_vkphysicaldeviceprivatedatafeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceproperties2_vkphysicaldeviceproperties2_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceproperties_vkphysicaldeviceproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceprotectedmemoryfeatures_vkphysicaldeviceprotectedmemoryfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceprotectedmemoryproperties_vkphysicaldeviceprotectedmemoryproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicepushdescriptorproperties_vkphysicaldevicepushdescriptorproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicesamplerfilterminmaxproperties_vkphysicaldevicesamplerfilterminmaxproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicesamplerycbcrconversionfeatures_vkphysicaldevicesamplerycbcrconversionfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicescalarblocklayoutfeatures_vkphysicaldevicescalarblocklayoutfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceseparatedepthstencillayoutsfeatures_vkphysicaldeviceseparatedepthstencillayoutsfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceshaderatomicint64features_vkphysicaldeviceshaderatomicint64features_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceshaderdemotetohelperinvocationfeatures_vkphysicaldeviceshaderdemotetohelperinvocationfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceshaderdrawparametersfeatures_vkphysicaldeviceshaderdrawparametersfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceshaderexpectassumefeatures_vkphysicaldeviceshaderexpectassumefeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceshaderfloat16int8features_vkphysicaldeviceshaderfloat16int8features_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceshaderfloatcontrols2features_vkphysicaldeviceshaderfloatcontrols2features_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceshaderintegerdotproductfeatures_vkphysicaldeviceshaderintegerdotproductfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceshaderintegerdotproductproperties_vkphysicaldeviceshaderintegerdotproductproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceshadersubgroupextendedtypesfeatures_vkphysicaldeviceshadersubgroupextendedtypesfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceshadersubgrouprotatefeatures_vkphysicaldeviceshadersubgrouprotatefeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceshaderterminateinvocationfeatures_vkphysicaldeviceshaderterminateinvocationfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicesparseimageformatinfo2_vkphysicaldevicesparseimageformatinfo2_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicesparseproperties_vkphysicaldevicesparseproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicesubgroupproperties_vkphysicaldevicesubgroupproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicesubgroupsizecontrolfeatures_vkphysicaldevicesubgroupsizecontrolfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicesubgroupsizecontrolproperties_vkphysicaldevicesubgroupsizecontrolproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicesynchronization2features_vkphysicaldevicesynchronization2features_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicetexelbufferalignmentproperties_vkphysicaldevicetexelbufferalignmentproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicetexturecompressionastchdrfeatures_vkphysicaldevicetexturecompressionastchdrfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicetimelinesemaphorefeatures_vkphysicaldevicetimelinesemaphorefeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicetimelinesemaphoreproperties_vkphysicaldevicetimelinesemaphoreproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicetoolproperties_vkphysicaldevicetoolproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldeviceuniformbufferstandardlayoutfeatures_vkphysicaldeviceuniformbufferstandardlayoutfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicevariablepointersfeatures_vkphysicaldevicevariablepointersfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicevertexattributedivisorfeatures_vkphysicaldevicevertexattributedivisorfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicevertexattributedivisorproperties_vkphysicaldevicevertexattributedivisorproperties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicevulkan11features_vkphysicaldevicevulkan11features_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicevulkan11properties_vkphysicaldevicevulkan11properties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicevulkan12features_vkphysicaldevicevulkan12features_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicevulkan12properties_vkphysicaldevicevulkan12properties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicevulkan13features_vkphysicaldevicevulkan13features_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicevulkan13properties_vkphysicaldevicevulkan13properties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicevulkan14features_vkphysicaldevicevulkan14features_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicevulkan14properties_vkphysicaldevicevulkan14properties_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicevulkanmemorymodelfeatures_vkphysicaldevicevulkanmemorymodelfeatures_ce;
zend_class_entry *vulkan_struct_vkphysicaldevicezeroinitializeworkgroupmemoryfeatures_vkphysicaldevicezeroinitializeworkgroupmemoryfeatures_ce;
zend_class_entry *vulkan_struct_vkpipelinecachecreateinfo_vkpipelinecachecreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelinecacheheaderversionone_vkpipelinecacheheaderversionone_ce;
zend_class_entry *vulkan_struct_vkpipelinecolorblendattachmentstate_vkpipelinecolorblendattachmentstate_ce;
zend_class_entry *vulkan_struct_vkpipelinecolorblendstatecreateinfo_vkpipelinecolorblendstatecreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelinecreateflags2createinfo_vkpipelinecreateflags2createinfo_ce;
zend_class_entry *vulkan_struct_vkpipelinecreationfeedback_vkpipelinecreationfeedback_ce;
zend_class_entry *vulkan_struct_vkpipelinecreationfeedbackcreateinfo_vkpipelinecreationfeedbackcreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelinedepthstencilstatecreateinfo_vkpipelinedepthstencilstatecreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelinedynamicstatecreateinfo_vkpipelinedynamicstatecreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelineinputassemblystatecreateinfo_vkpipelineinputassemblystatecreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelinelayoutcreateinfo_vkpipelinelayoutcreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelinemultisamplestatecreateinfo_vkpipelinemultisamplestatecreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelinerasterizationlinestatecreateinfo_vkpipelinerasterizationlinestatecreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelinerasterizationstatecreateinfo_vkpipelinerasterizationstatecreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelinerenderingcreateinfo_vkpipelinerenderingcreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelinerobustnesscreateinfo_vkpipelinerobustnesscreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelineshaderstagecreateinfo_vkpipelineshaderstagecreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelineshaderstagerequiredsubgroupsizecreateinfo_vkpipelineshaderstagerequiredsubgroupsizecreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelinetessellationdomainoriginstatecreateinfo_vkpipelinetessellationdomainoriginstatecreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelinetessellationstatecreateinfo_vkpipelinetessellationstatecreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelinevertexinputdivisorstatecreateinfo_vkpipelinevertexinputdivisorstatecreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelinevertexinputstatecreateinfo_vkpipelinevertexinputstatecreateinfo_ce;
zend_class_entry *vulkan_struct_vkpipelineviewportstatecreateinfo_vkpipelineviewportstatecreateinfo_ce;
zend_class_entry *vulkan_struct_vkpresentinfokhr_vkpresentinfokhr_ce;
zend_class_entry *vulkan_struct_vkprivatedataslotcreateinfo_vkprivatedataslotcreateinfo_ce;
zend_class_entry *vulkan_struct_vkprotectedsubmitinfo_vkprotectedsubmitinfo_ce;
zend_class_entry *vulkan_struct_vkpushconstantrange_vkpushconstantrange_ce;
zend_class_entry *vulkan_struct_vkpushconstantsinfo_vkpushconstantsinfo_ce;
zend_class_entry *vulkan_struct_vkpushdescriptorsetinfo_vkpushdescriptorsetinfo_ce;
zend_class_entry *vulkan_struct_vkpushdescriptorsetwithtemplateinfo_vkpushdescriptorsetwithtemplateinfo_ce;
zend_class_entry *vulkan_struct_vkquerypoolcreateinfo_vkquerypoolcreateinfo_ce;
zend_class_entry *vulkan_struct_vkqueuefamilyglobalpriorityproperties_vkqueuefamilyglobalpriorityproperties_ce;
zend_class_entry *vulkan_struct_vkqueuefamilyproperties2_vkqueuefamilyproperties2_ce;
zend_class_entry *vulkan_struct_vkqueuefamilyproperties_vkqueuefamilyproperties_ce;
zend_class_entry *vulkan_struct_vkrect2d_vkrect2d_ce;
zend_class_entry *vulkan_struct_vkrenderingareainfo_vkrenderingareainfo_ce;
zend_class_entry *vulkan_struct_vkrenderingattachmentinfo_vkrenderingattachmentinfo_ce;
zend_class_entry *vulkan_struct_vkrenderingattachmentlocationinfo_vkrenderingattachmentlocationinfo_ce;
zend_class_entry *vulkan_struct_vkrenderinginfo_vkrenderinginfo_ce;
zend_class_entry *vulkan_struct_vkrenderinginputattachmentindexinfo_vkrenderinginputattachmentindexinfo_ce;
zend_class_entry *vulkan_struct_vkrenderpassattachmentbegininfo_vkrenderpassattachmentbegininfo_ce;
zend_class_entry *vulkan_struct_vkrenderpassbegininfo_vkrenderpassbegininfo_ce;
zend_class_entry *vulkan_struct_vkrenderpasscreateinfo2_vkrenderpasscreateinfo2_ce;
zend_class_entry *vulkan_struct_vkrenderpasscreateinfo_vkrenderpasscreateinfo_ce;
zend_class_entry *vulkan_struct_vkrenderpassinputattachmentaspectcreateinfo_vkrenderpassinputattachmentaspectcreateinfo_ce;
zend_class_entry *vulkan_struct_vkrenderpassmultiviewcreateinfo_vkrenderpassmultiviewcreateinfo_ce;
zend_class_entry *vulkan_struct_vkresolveimageinfo2_vkresolveimageinfo2_ce;
zend_class_entry *vulkan_struct_vksamplercreateinfo_vksamplercreateinfo_ce;
zend_class_entry *vulkan_struct_vksamplerreductionmodecreateinfo_vksamplerreductionmodecreateinfo_ce;
zend_class_entry *vulkan_struct_vksamplerycbcrconversioncreateinfo_vksamplerycbcrconversioncreateinfo_ce;
zend_class_entry *vulkan_struct_vksamplerycbcrconversionimageformatproperties_vksamplerycbcrconversionimageformatproperties_ce;
zend_class_entry *vulkan_struct_vksamplerycbcrconversioninfo_vksamplerycbcrconversioninfo_ce;
zend_class_entry *vulkan_struct_vksemaphorecreateinfo_vksemaphorecreateinfo_ce;
zend_class_entry *vulkan_struct_vksemaphoresignalinfo_vksemaphoresignalinfo_ce;
zend_class_entry *vulkan_struct_vksemaphoresubmitinfo_vksemaphoresubmitinfo_ce;
zend_class_entry *vulkan_struct_vksemaphoretypecreateinfo_vksemaphoretypecreateinfo_ce;
zend_class_entry *vulkan_struct_vksemaphorewaitinfo_vksemaphorewaitinfo_ce;
zend_class_entry *vulkan_struct_vkshadermodulecreateinfo_vkshadermodulecreateinfo_ce;
zend_class_entry *vulkan_struct_vksparsebuffermemorybindinfo_vksparsebuffermemorybindinfo_ce;
zend_class_entry *vulkan_struct_vksparseimageformatproperties2_vksparseimageformatproperties2_ce;
zend_class_entry *vulkan_struct_vksparseimageformatproperties_vksparseimageformatproperties_ce;
zend_class_entry *vulkan_struct_vksparseimagememorybind_vksparseimagememorybind_ce;
zend_class_entry *vulkan_struct_vksparseimagememorybindinfo_vksparseimagememorybindinfo_ce;
zend_class_entry *vulkan_struct_vksparseimagememoryrequirements2_vksparseimagememoryrequirements2_ce;
zend_class_entry *vulkan_struct_vksparseimagememoryrequirements_vksparseimagememoryrequirements_ce;
zend_class_entry *vulkan_struct_vksparseimageopaquememorybindinfo_vksparseimageopaquememorybindinfo_ce;
zend_class_entry *vulkan_struct_vksparsememorybind_vksparsememorybind_ce;
zend_class_entry *vulkan_struct_vkspecializationinfo_vkspecializationinfo_ce;
zend_class_entry *vulkan_struct_vkspecializationmapentry_vkspecializationmapentry_ce;
zend_class_entry *vulkan_struct_vkstencilopstate_vkstencilopstate_ce;
zend_class_entry *vulkan_struct_vksubmitinfo2_vksubmitinfo2_ce;
zend_class_entry *vulkan_struct_vksubmitinfo_vksubmitinfo_ce;
zend_class_entry *vulkan_struct_vksubpassbegininfo_vksubpassbegininfo_ce;
zend_class_entry *vulkan_struct_vksubpassdependency2_vksubpassdependency2_ce;
zend_class_entry *vulkan_struct_vksubpassdependency_vksubpassdependency_ce;
zend_class_entry *vulkan_struct_vksubpassdescription2_vksubpassdescription2_ce;
zend_class_entry *vulkan_struct_vksubpassdescription_vksubpassdescription_ce;
zend_class_entry *vulkan_struct_vksubpassdescriptiondepthstencilresolve_vksubpassdescriptiondepthstencilresolve_ce;
zend_class_entry *vulkan_struct_vksubpassendinfo_vksubpassendinfo_ce;
zend_class_entry *vulkan_struct_vksubresourcehostmemcpysize_vksubresourcehostmemcpysize_ce;
zend_class_entry *vulkan_struct_vksubresourcelayout2_vksubresourcelayout2_ce;
zend_class_entry *vulkan_struct_vksubresourcelayout_vksubresourcelayout_ce;
zend_class_entry *vulkan_struct_vksurfacecapabilitieskhr_vksurfacecapabilitieskhr_ce;
zend_class_entry *vulkan_struct_vksurfaceformatkhr_vksurfaceformatkhr_ce;
zend_class_entry *vulkan_struct_vkswapchaincreateinfokhr_vkswapchaincreateinfokhr_ce;
zend_class_entry *vulkan_struct_vktimelinesemaphoresubmitinfo_vktimelinesemaphoresubmitinfo_ce;
zend_class_entry *vulkan_struct_vkvertexinputattributedescription_vkvertexinputattributedescription_ce;
zend_class_entry *vulkan_struct_vkvertexinputbindingdescription_vkvertexinputbindingdescription_ce;
zend_class_entry *vulkan_struct_vkvertexinputbindingdivisordescription_vkvertexinputbindingdivisordescription_ce;
zend_class_entry *vulkan_struct_vkviewport_vkviewport_ce;
zend_class_entry *vulkan_struct_vkwaylandsurfacecreateinfokhr_vkwaylandsurfacecreateinfokhr_ce;
zend_class_entry *vulkan_struct_vkwritedescriptorset_vkwritedescriptorset_ce;
zend_class_entry *vulkan_struct_vkwritedescriptorsetinlineuniformblock_vkwritedescriptorsetinlineuniformblock_ce;
zend_class_entry *vulkan_struct_vkxcbsurfacecreateinfokhr_vkxcbsurfacecreateinfokhr_ce;
zend_class_entry *vulkan_struct_vkxlibsurfacecreateinfokhr_vkxlibsurfacecreateinfokhr_ce;
zend_class_entry *vulkan_vk_vk10_vk10_ce;
zend_class_entry *vulkan_vk_vk11_vk11_ce;
zend_class_entry *vulkan_vk_vk12_vk12_ce;
zend_class_entry *vulkan_vk_vk13_vk13_ce;
zend_class_entry *vulkan_vk_vk14_vk14_ce;

ZEND_DECLARE_MODULE_GLOBALS(vulkan)

PHP_INI_BEGIN()
	
PHP_INI_END()

static PHP_MINIT_FUNCTION(vulkan)
{
	REGISTER_INI_ENTRIES();
	zephir_module_init();
	ZEPHIR_INIT(Vulkan_Bridge_Bridge);
	ZEPHIR_INIT(Vulkan_Ext_EXTDebugUtils_EXTDebugUtils);
	ZEPHIR_INIT(Vulkan_Ext_EXTMetalObjects_EXTMetalObjects);
	ZEPHIR_INIT(Vulkan_Ext_EXTMetalSurface_EXTMetalSurface);
	ZEPHIR_INIT(Vulkan_Ext_KHRSurface_KHRSurface);
	ZEPHIR_INIT(Vulkan_Ext_KHRSwapchain_KHRSwapchain);
	ZEPHIR_INIT(Vulkan_Ext_KHRWaylandSurface_KHRWaylandSurface);
	ZEPHIR_INIT(Vulkan_Ext_KHRXcbSurface_KHRXcbSurface);
	ZEPHIR_INIT(Vulkan_Ext_KHRXlibSurface_KHRXlibSurface);
	ZEPHIR_INIT(Vulkan_Struct_VkAcquireNextImageInfoKHR_VkAcquireNextImageInfoKHR);
	ZEPHIR_INIT(Vulkan_Struct_VkAllocationCallbacks_VkAllocationCallbacks);
	ZEPHIR_INIT(Vulkan_Struct_VkApplicationInfo_VkApplicationInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkAttachmentDescription2_VkAttachmentDescription2);
	ZEPHIR_INIT(Vulkan_Struct_VkAttachmentDescriptionStencilLayout_VkAttachmentDescriptionStencilLayout);
	ZEPHIR_INIT(Vulkan_Struct_VkAttachmentDescription_VkAttachmentDescription);
	ZEPHIR_INIT(Vulkan_Struct_VkAttachmentReference2_VkAttachmentReference2);
	ZEPHIR_INIT(Vulkan_Struct_VkAttachmentReferenceStencilLayout_VkAttachmentReferenceStencilLayout);
	ZEPHIR_INIT(Vulkan_Struct_VkAttachmentReference_VkAttachmentReference);
	ZEPHIR_INIT(Vulkan_Struct_VkBaseInStructure_VkBaseInStructure);
	ZEPHIR_INIT(Vulkan_Struct_VkBaseOutStructure_VkBaseOutStructure);
	ZEPHIR_INIT(Vulkan_Struct_VkBindBufferMemoryDeviceGroupInfo_VkBindBufferMemoryDeviceGroupInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkBindBufferMemoryInfo_VkBindBufferMemoryInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkBindDescriptorSetsInfo_VkBindDescriptorSetsInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkBindImageMemoryDeviceGroupInfo_VkBindImageMemoryDeviceGroupInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkBindImageMemoryInfo_VkBindImageMemoryInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkBindImageMemorySwapchainInfoKHR_VkBindImageMemorySwapchainInfoKHR);
	ZEPHIR_INIT(Vulkan_Struct_VkBindImagePlaneMemoryInfo_VkBindImagePlaneMemoryInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkBindMemoryStatus_VkBindMemoryStatus);
	ZEPHIR_INIT(Vulkan_Struct_VkBindSparseInfo_VkBindSparseInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkBlitImageInfo2_VkBlitImageInfo2);
	ZEPHIR_INIT(Vulkan_Struct_VkBufferCopy2_VkBufferCopy2);
	ZEPHIR_INIT(Vulkan_Struct_VkBufferCopy_VkBufferCopy);
	ZEPHIR_INIT(Vulkan_Struct_VkBufferCreateInfo_VkBufferCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkBufferDeviceAddressInfo_VkBufferDeviceAddressInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkBufferImageCopy2_VkBufferImageCopy2);
	ZEPHIR_INIT(Vulkan_Struct_VkBufferImageCopy_VkBufferImageCopy);
	ZEPHIR_INIT(Vulkan_Struct_VkBufferMemoryBarrier2_VkBufferMemoryBarrier2);
	ZEPHIR_INIT(Vulkan_Struct_VkBufferMemoryBarrier_VkBufferMemoryBarrier);
	ZEPHIR_INIT(Vulkan_Struct_VkBufferMemoryRequirementsInfo2_VkBufferMemoryRequirementsInfo2);
	ZEPHIR_INIT(Vulkan_Struct_VkBufferOpaqueCaptureAddressCreateInfo_VkBufferOpaqueCaptureAddressCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkBufferUsageFlags2CreateInfo_VkBufferUsageFlags2CreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkBufferViewCreateInfo_VkBufferViewCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkClearAttachment_VkClearAttachment);
	ZEPHIR_INIT(Vulkan_Struct_VkClearColorValue_VkClearColorValue);
	ZEPHIR_INIT(Vulkan_Struct_VkClearDepthStencilValue_VkClearDepthStencilValue);
	ZEPHIR_INIT(Vulkan_Struct_VkClearRect_VkClearRect);
	ZEPHIR_INIT(Vulkan_Struct_VkClearValue_VkClearValue);
	ZEPHIR_INIT(Vulkan_Struct_VkCommandBufferAllocateInfo_VkCommandBufferAllocateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkCommandBufferBeginInfo_VkCommandBufferBeginInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkCommandBufferInheritanceInfo_VkCommandBufferInheritanceInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkCommandBufferInheritanceRenderingInfo_VkCommandBufferInheritanceRenderingInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkCommandBufferSubmitInfo_VkCommandBufferSubmitInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkCommandPoolCreateInfo_VkCommandPoolCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkComponentMapping_VkComponentMapping);
	ZEPHIR_INIT(Vulkan_Struct_VkComputePipelineCreateInfo_VkComputePipelineCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkConformanceVersion_VkConformanceVersion);
	ZEPHIR_INIT(Vulkan_Struct_VkCopyBufferInfo2_VkCopyBufferInfo2);
	ZEPHIR_INIT(Vulkan_Struct_VkCopyBufferToImageInfo2_VkCopyBufferToImageInfo2);
	ZEPHIR_INIT(Vulkan_Struct_VkCopyDescriptorSet_VkCopyDescriptorSet);
	ZEPHIR_INIT(Vulkan_Struct_VkCopyImageInfo2_VkCopyImageInfo2);
	ZEPHIR_INIT(Vulkan_Struct_VkCopyImageToBufferInfo2_VkCopyImageToBufferInfo2);
	ZEPHIR_INIT(Vulkan_Struct_VkCopyImageToImageInfo_VkCopyImageToImageInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkCopyImageToMemoryInfo_VkCopyImageToMemoryInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkCopyMemoryToImageInfo_VkCopyMemoryToImageInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDebugUtilsLabelEXT_VkDebugUtilsLabelEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkDebugUtilsMessengerCallbackDataEXT_VkDebugUtilsMessengerCallbackDataEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkDebugUtilsMessengerCreateInfoEXT_VkDebugUtilsMessengerCreateInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkDebugUtilsObjectNameInfoEXT_VkDebugUtilsObjectNameInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkDebugUtilsObjectTagInfoEXT_VkDebugUtilsObjectTagInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkDependencyInfo_VkDependencyInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDescriptorBufferInfo_VkDescriptorBufferInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDescriptorImageInfo_VkDescriptorImageInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDescriptorPoolCreateInfo_VkDescriptorPoolCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDescriptorPoolInlineUniformBlockCreateInfo_VkDescriptorPoolInlineUniformBlockCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDescriptorPoolSize_VkDescriptorPoolSize);
	ZEPHIR_INIT(Vulkan_Struct_VkDescriptorSetAllocateInfo_VkDescriptorSetAllocateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDescriptorSetLayoutBindingFlagsCreateInfo_VkDescriptorSetLayoutBindingFlagsCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDescriptorSetLayoutBinding_VkDescriptorSetLayoutBinding);
	ZEPHIR_INIT(Vulkan_Struct_VkDescriptorSetLayoutCreateInfo_VkDescriptorSetLayoutCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDescriptorSetLayoutSupport_VkDescriptorSetLayoutSupport);
	ZEPHIR_INIT(Vulkan_Struct_VkDescriptorSetVariableDescriptorCountAllocateInfo_VkDescriptorSetVariableDescriptorCountAllocateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDescriptorSetVariableDescriptorCountLayoutSupport_VkDescriptorSetVariableDescriptorCountLayoutSupport);
	ZEPHIR_INIT(Vulkan_Struct_VkDescriptorUpdateTemplateCreateInfo_VkDescriptorUpdateTemplateCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDescriptorUpdateTemplateEntry_VkDescriptorUpdateTemplateEntry);
	ZEPHIR_INIT(Vulkan_Struct_VkDeviceBufferMemoryRequirements_VkDeviceBufferMemoryRequirements);
	ZEPHIR_INIT(Vulkan_Struct_VkDeviceCreateInfo_VkDeviceCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDeviceGroupBindSparseInfo_VkDeviceGroupBindSparseInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDeviceGroupCommandBufferBeginInfo_VkDeviceGroupCommandBufferBeginInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDeviceGroupDeviceCreateInfo_VkDeviceGroupDeviceCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDeviceGroupPresentCapabilitiesKHR_VkDeviceGroupPresentCapabilitiesKHR);
	ZEPHIR_INIT(Vulkan_Struct_VkDeviceGroupPresentInfoKHR_VkDeviceGroupPresentInfoKHR);
	ZEPHIR_INIT(Vulkan_Struct_VkDeviceGroupRenderPassBeginInfo_VkDeviceGroupRenderPassBeginInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDeviceGroupSubmitInfo_VkDeviceGroupSubmitInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDeviceGroupSwapchainCreateInfoKHR_VkDeviceGroupSwapchainCreateInfoKHR);
	ZEPHIR_INIT(Vulkan_Struct_VkDeviceImageMemoryRequirements_VkDeviceImageMemoryRequirements);
	ZEPHIR_INIT(Vulkan_Struct_VkDeviceImageSubresourceInfo_VkDeviceImageSubresourceInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDeviceMemoryOpaqueCaptureAddressInfo_VkDeviceMemoryOpaqueCaptureAddressInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDevicePrivateDataCreateInfo_VkDevicePrivateDataCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDeviceQueueCreateInfo_VkDeviceQueueCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDeviceQueueGlobalPriorityCreateInfo_VkDeviceQueueGlobalPriorityCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkDeviceQueueInfo2_VkDeviceQueueInfo2);
	ZEPHIR_INIT(Vulkan_Struct_VkDispatchIndirectCommand_VkDispatchIndirectCommand);
	ZEPHIR_INIT(Vulkan_Struct_VkDrawIndexedIndirectCommand_VkDrawIndexedIndirectCommand);
	ZEPHIR_INIT(Vulkan_Struct_VkDrawIndirectCommand_VkDrawIndirectCommand);
	ZEPHIR_INIT(Vulkan_Struct_VkEventCreateInfo_VkEventCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkExportFenceCreateInfo_VkExportFenceCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkExportMemoryAllocateInfo_VkExportMemoryAllocateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkExportMetalBufferInfoEXT_VkExportMetalBufferInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkExportMetalCommandQueueInfoEXT_VkExportMetalCommandQueueInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkExportMetalDeviceInfoEXT_VkExportMetalDeviceInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkExportMetalIOSurfaceInfoEXT_VkExportMetalIOSurfaceInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkExportMetalObjectCreateInfoEXT_VkExportMetalObjectCreateInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkExportMetalObjectsInfoEXT_VkExportMetalObjectsInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkExportMetalSharedEventInfoEXT_VkExportMetalSharedEventInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkExportMetalTextureInfoEXT_VkExportMetalTextureInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkExportSemaphoreCreateInfo_VkExportSemaphoreCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkExtensionProperties_VkExtensionProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkExtent2D_VkExtent2D);
	ZEPHIR_INIT(Vulkan_Struct_VkExtent3D_VkExtent3D);
	ZEPHIR_INIT(Vulkan_Struct_VkExternalBufferProperties_VkExternalBufferProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkExternalFenceProperties_VkExternalFenceProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkExternalImageFormatProperties_VkExternalImageFormatProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkExternalMemoryBufferCreateInfo_VkExternalMemoryBufferCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkExternalMemoryImageCreateInfo_VkExternalMemoryImageCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkExternalMemoryProperties_VkExternalMemoryProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkExternalSemaphoreProperties_VkExternalSemaphoreProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkFenceCreateInfo_VkFenceCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkFormatProperties2_VkFormatProperties2);
	ZEPHIR_INIT(Vulkan_Struct_VkFormatProperties3_VkFormatProperties3);
	ZEPHIR_INIT(Vulkan_Struct_VkFormatProperties_VkFormatProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkFramebufferAttachmentImageInfo_VkFramebufferAttachmentImageInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkFramebufferAttachmentsCreateInfo_VkFramebufferAttachmentsCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkFramebufferCreateInfo_VkFramebufferCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkGraphicsPipelineCreateInfo_VkGraphicsPipelineCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkHostImageCopyDevicePerformanceQuery_VkHostImageCopyDevicePerformanceQuery);
	ZEPHIR_INIT(Vulkan_Struct_VkHostImageLayoutTransitionInfo_VkHostImageLayoutTransitionInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkImageBlit2_VkImageBlit2);
	ZEPHIR_INIT(Vulkan_Struct_VkImageBlit_VkImageBlit);
	ZEPHIR_INIT(Vulkan_Struct_VkImageCopy2_VkImageCopy2);
	ZEPHIR_INIT(Vulkan_Struct_VkImageCopy_VkImageCopy);
	ZEPHIR_INIT(Vulkan_Struct_VkImageCreateInfo_VkImageCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkImageFormatListCreateInfo_VkImageFormatListCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkImageFormatProperties2_VkImageFormatProperties2);
	ZEPHIR_INIT(Vulkan_Struct_VkImageFormatProperties_VkImageFormatProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkImageMemoryBarrier2_VkImageMemoryBarrier2);
	ZEPHIR_INIT(Vulkan_Struct_VkImageMemoryBarrier_VkImageMemoryBarrier);
	ZEPHIR_INIT(Vulkan_Struct_VkImageMemoryRequirementsInfo2_VkImageMemoryRequirementsInfo2);
	ZEPHIR_INIT(Vulkan_Struct_VkImagePlaneMemoryRequirementsInfo_VkImagePlaneMemoryRequirementsInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkImageResolve2_VkImageResolve2);
	ZEPHIR_INIT(Vulkan_Struct_VkImageResolve_VkImageResolve);
	ZEPHIR_INIT(Vulkan_Struct_VkImageSparseMemoryRequirementsInfo2_VkImageSparseMemoryRequirementsInfo2);
	ZEPHIR_INIT(Vulkan_Struct_VkImageStencilUsageCreateInfo_VkImageStencilUsageCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkImageSubresource2_VkImageSubresource2);
	ZEPHIR_INIT(Vulkan_Struct_VkImageSubresourceLayers_VkImageSubresourceLayers);
	ZEPHIR_INIT(Vulkan_Struct_VkImageSubresourceRange_VkImageSubresourceRange);
	ZEPHIR_INIT(Vulkan_Struct_VkImageSubresource_VkImageSubresource);
	ZEPHIR_INIT(Vulkan_Struct_VkImageSwapchainCreateInfoKHR_VkImageSwapchainCreateInfoKHR);
	ZEPHIR_INIT(Vulkan_Struct_VkImageToMemoryCopy_VkImageToMemoryCopy);
	ZEPHIR_INIT(Vulkan_Struct_VkImageViewCreateInfo_VkImageViewCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkImageViewUsageCreateInfo_VkImageViewUsageCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkImportMetalBufferInfoEXT_VkImportMetalBufferInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkImportMetalIOSurfaceInfoEXT_VkImportMetalIOSurfaceInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkImportMetalSharedEventInfoEXT_VkImportMetalSharedEventInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkImportMetalTextureInfoEXT_VkImportMetalTextureInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkInputAttachmentAspectReference_VkInputAttachmentAspectReference);
	ZEPHIR_INIT(Vulkan_Struct_VkInstanceCreateInfo_VkInstanceCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkLayerProperties_VkLayerProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkLayerSettingEXT_VkLayerSettingEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkLayerSettingsCreateInfoEXT_VkLayerSettingsCreateInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkMappedMemoryRange_VkMappedMemoryRange);
	ZEPHIR_INIT(Vulkan_Struct_VkMemoryAllocateFlagsInfo_VkMemoryAllocateFlagsInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkMemoryAllocateInfo_VkMemoryAllocateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkMemoryBarrier2_VkMemoryBarrier2);
	ZEPHIR_INIT(Vulkan_Struct_VkMemoryBarrier_VkMemoryBarrier);
	ZEPHIR_INIT(Vulkan_Struct_VkMemoryDedicatedAllocateInfo_VkMemoryDedicatedAllocateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkMemoryDedicatedRequirements_VkMemoryDedicatedRequirements);
	ZEPHIR_INIT(Vulkan_Struct_VkMemoryHeap_VkMemoryHeap);
	ZEPHIR_INIT(Vulkan_Struct_VkMemoryMapInfo_VkMemoryMapInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkMemoryOpaqueCaptureAddressAllocateInfo_VkMemoryOpaqueCaptureAddressAllocateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkMemoryRequirements2_VkMemoryRequirements2);
	ZEPHIR_INIT(Vulkan_Struct_VkMemoryRequirements_VkMemoryRequirements);
	ZEPHIR_INIT(Vulkan_Struct_VkMemoryToImageCopy_VkMemoryToImageCopy);
	ZEPHIR_INIT(Vulkan_Struct_VkMemoryType_VkMemoryType);
	ZEPHIR_INIT(Vulkan_Struct_VkMemoryUnmapInfo_VkMemoryUnmapInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkMetalSurfaceCreateInfoEXT_VkMetalSurfaceCreateInfoEXT);
	ZEPHIR_INIT(Vulkan_Struct_VkOffset2D_VkOffset2D);
	ZEPHIR_INIT(Vulkan_Struct_VkOffset3D_VkOffset3D);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDevice16BitStorageFeatures_VkPhysicalDevice16BitStorageFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDevice8BitStorageFeatures_VkPhysicalDevice8BitStorageFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceBufferDeviceAddressFeatures_VkPhysicalDeviceBufferDeviceAddressFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceDepthStencilResolveProperties_VkPhysicalDeviceDepthStencilResolveProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceDescriptorIndexingFeatures_VkPhysicalDeviceDescriptorIndexingFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceDescriptorIndexingProperties_VkPhysicalDeviceDescriptorIndexingProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceDriverProperties_VkPhysicalDeviceDriverProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceDynamicRenderingFeatures_VkPhysicalDeviceDynamicRenderingFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceDynamicRenderingLocalReadFeatures_VkPhysicalDeviceDynamicRenderingLocalReadFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceExternalBufferInfo_VkPhysicalDeviceExternalBufferInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceExternalFenceInfo_VkPhysicalDeviceExternalFenceInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceExternalImageFormatInfo_VkPhysicalDeviceExternalImageFormatInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceExternalSemaphoreInfo_VkPhysicalDeviceExternalSemaphoreInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceFeatures2_VkPhysicalDeviceFeatures2);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceFeatures_VkPhysicalDeviceFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceFloatControlsProperties_VkPhysicalDeviceFloatControlsProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceGlobalPriorityQueryFeatures_VkPhysicalDeviceGlobalPriorityQueryFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceGroupProperties_VkPhysicalDeviceGroupProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceHostImageCopyFeatures_VkPhysicalDeviceHostImageCopyFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceHostImageCopyProperties_VkPhysicalDeviceHostImageCopyProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceHostQueryResetFeatures_VkPhysicalDeviceHostQueryResetFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceIDProperties_VkPhysicalDeviceIDProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceImageFormatInfo2_VkPhysicalDeviceImageFormatInfo2);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceImageRobustnessFeatures_VkPhysicalDeviceImageRobustnessFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceImagelessFramebufferFeatures_VkPhysicalDeviceImagelessFramebufferFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceIndexTypeUint8Features_VkPhysicalDeviceIndexTypeUint8Features);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceInlineUniformBlockFeatures_VkPhysicalDeviceInlineUniformBlockFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceInlineUniformBlockProperties_VkPhysicalDeviceInlineUniformBlockProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceLimits_VkPhysicalDeviceLimits);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceLineRasterizationFeatures_VkPhysicalDeviceLineRasterizationFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceLineRasterizationProperties_VkPhysicalDeviceLineRasterizationProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceMaintenance3Properties_VkPhysicalDeviceMaintenance3Properties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceMaintenance4Features_VkPhysicalDeviceMaintenance4Features);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceMaintenance4Properties_VkPhysicalDeviceMaintenance4Properties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceMaintenance5Features_VkPhysicalDeviceMaintenance5Features);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceMaintenance5Properties_VkPhysicalDeviceMaintenance5Properties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceMaintenance6Features_VkPhysicalDeviceMaintenance6Features);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceMaintenance6Properties_VkPhysicalDeviceMaintenance6Properties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceMemoryProperties2_VkPhysicalDeviceMemoryProperties2);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceMemoryProperties_VkPhysicalDeviceMemoryProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceMultiviewFeatures_VkPhysicalDeviceMultiviewFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceMultiviewProperties_VkPhysicalDeviceMultiviewProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDevicePipelineCreationCacheControlFeatures_VkPhysicalDevicePipelineCreationCacheControlFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDevicePipelineProtectedAccessFeatures_VkPhysicalDevicePipelineProtectedAccessFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDevicePipelineRobustnessFeatures_VkPhysicalDevicePipelineRobustnessFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDevicePipelineRobustnessProperties_VkPhysicalDevicePipelineRobustnessProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDevicePointClippingProperties_VkPhysicalDevicePointClippingProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDevicePortabilitySubsetFeaturesKHR_VkPhysicalDevicePortabilitySubsetFeaturesKHR);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDevicePortabilitySubsetPropertiesKHR_VkPhysicalDevicePortabilitySubsetPropertiesKHR);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDevicePrivateDataFeatures_VkPhysicalDevicePrivateDataFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceProperties2_VkPhysicalDeviceProperties2);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceProperties_VkPhysicalDeviceProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceProtectedMemoryFeatures_VkPhysicalDeviceProtectedMemoryFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceProtectedMemoryProperties_VkPhysicalDeviceProtectedMemoryProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDevicePushDescriptorProperties_VkPhysicalDevicePushDescriptorProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceSamplerFilterMinmaxProperties_VkPhysicalDeviceSamplerFilterMinmaxProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceSamplerYcbcrConversionFeatures_VkPhysicalDeviceSamplerYcbcrConversionFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceScalarBlockLayoutFeatures_VkPhysicalDeviceScalarBlockLayoutFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures_VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceShaderAtomicInt64Features_VkPhysicalDeviceShaderAtomicInt64Features);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures_VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceShaderDrawParametersFeatures_VkPhysicalDeviceShaderDrawParametersFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceShaderExpectAssumeFeatures_VkPhysicalDeviceShaderExpectAssumeFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceShaderFloat16Int8Features_VkPhysicalDeviceShaderFloat16Int8Features);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceShaderFloatControls2Features_VkPhysicalDeviceShaderFloatControls2Features);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceShaderIntegerDotProductFeatures_VkPhysicalDeviceShaderIntegerDotProductFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceShaderIntegerDotProductProperties_VkPhysicalDeviceShaderIntegerDotProductProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures_VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceShaderSubgroupRotateFeatures_VkPhysicalDeviceShaderSubgroupRotateFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceShaderTerminateInvocationFeatures_VkPhysicalDeviceShaderTerminateInvocationFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceSparseImageFormatInfo2_VkPhysicalDeviceSparseImageFormatInfo2);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceSparseProperties_VkPhysicalDeviceSparseProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceSubgroupProperties_VkPhysicalDeviceSubgroupProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceSubgroupSizeControlFeatures_VkPhysicalDeviceSubgroupSizeControlFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceSubgroupSizeControlProperties_VkPhysicalDeviceSubgroupSizeControlProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceSynchronization2Features_VkPhysicalDeviceSynchronization2Features);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceTexelBufferAlignmentProperties_VkPhysicalDeviceTexelBufferAlignmentProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceTextureCompressionASTCHDRFeatures_VkPhysicalDeviceTextureCompressionASTCHDRFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceTimelineSemaphoreFeatures_VkPhysicalDeviceTimelineSemaphoreFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceTimelineSemaphoreProperties_VkPhysicalDeviceTimelineSemaphoreProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceToolProperties_VkPhysicalDeviceToolProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceUniformBufferStandardLayoutFeatures_VkPhysicalDeviceUniformBufferStandardLayoutFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceVariablePointersFeatures_VkPhysicalDeviceVariablePointersFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceVertexAttributeDivisorFeatures_VkPhysicalDeviceVertexAttributeDivisorFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceVertexAttributeDivisorProperties_VkPhysicalDeviceVertexAttributeDivisorProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceVulkan11Features_VkPhysicalDeviceVulkan11Features);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceVulkan11Properties_VkPhysicalDeviceVulkan11Properties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceVulkan12Features_VkPhysicalDeviceVulkan12Features);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceVulkan12Properties_VkPhysicalDeviceVulkan12Properties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceVulkan13Features_VkPhysicalDeviceVulkan13Features);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceVulkan13Properties_VkPhysicalDeviceVulkan13Properties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceVulkan14Features_VkPhysicalDeviceVulkan14Features);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceVulkan14Properties_VkPhysicalDeviceVulkan14Properties);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceVulkanMemoryModelFeatures_VkPhysicalDeviceVulkanMemoryModelFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures_VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineCacheCreateInfo_VkPipelineCacheCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineCacheHeaderVersionOne_VkPipelineCacheHeaderVersionOne);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineColorBlendAttachmentState_VkPipelineColorBlendAttachmentState);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineColorBlendStateCreateInfo_VkPipelineColorBlendStateCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineCreateFlags2CreateInfo_VkPipelineCreateFlags2CreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineCreationFeedbackCreateInfo_VkPipelineCreationFeedbackCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineCreationFeedback_VkPipelineCreationFeedback);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineDepthStencilStateCreateInfo_VkPipelineDepthStencilStateCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineDynamicStateCreateInfo_VkPipelineDynamicStateCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineInputAssemblyStateCreateInfo_VkPipelineInputAssemblyStateCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineLayoutCreateInfo_VkPipelineLayoutCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineMultisampleStateCreateInfo_VkPipelineMultisampleStateCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineRasterizationLineStateCreateInfo_VkPipelineRasterizationLineStateCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineRasterizationStateCreateInfo_VkPipelineRasterizationStateCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineRenderingCreateInfo_VkPipelineRenderingCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineRobustnessCreateInfo_VkPipelineRobustnessCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineShaderStageCreateInfo_VkPipelineShaderStageCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineShaderStageRequiredSubgroupSizeCreateInfo_VkPipelineShaderStageRequiredSubgroupSizeCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineTessellationDomainOriginStateCreateInfo_VkPipelineTessellationDomainOriginStateCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineTessellationStateCreateInfo_VkPipelineTessellationStateCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineVertexInputDivisorStateCreateInfo_VkPipelineVertexInputDivisorStateCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineVertexInputStateCreateInfo_VkPipelineVertexInputStateCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPipelineViewportStateCreateInfo_VkPipelineViewportStateCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPresentInfoKHR_VkPresentInfoKHR);
	ZEPHIR_INIT(Vulkan_Struct_VkPrivateDataSlotCreateInfo_VkPrivateDataSlotCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkProtectedSubmitInfo_VkProtectedSubmitInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPushConstantRange_VkPushConstantRange);
	ZEPHIR_INIT(Vulkan_Struct_VkPushConstantsInfo_VkPushConstantsInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPushDescriptorSetInfo_VkPushDescriptorSetInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkPushDescriptorSetWithTemplateInfo_VkPushDescriptorSetWithTemplateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkQueryPoolCreateInfo_VkQueryPoolCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkQueueFamilyGlobalPriorityProperties_VkQueueFamilyGlobalPriorityProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkQueueFamilyProperties2_VkQueueFamilyProperties2);
	ZEPHIR_INIT(Vulkan_Struct_VkQueueFamilyProperties_VkQueueFamilyProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkRect2D_VkRect2D);
	ZEPHIR_INIT(Vulkan_Struct_VkRenderPassAttachmentBeginInfo_VkRenderPassAttachmentBeginInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkRenderPassBeginInfo_VkRenderPassBeginInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkRenderPassCreateInfo2_VkRenderPassCreateInfo2);
	ZEPHIR_INIT(Vulkan_Struct_VkRenderPassCreateInfo_VkRenderPassCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkRenderPassInputAttachmentAspectCreateInfo_VkRenderPassInputAttachmentAspectCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkRenderPassMultiviewCreateInfo_VkRenderPassMultiviewCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkRenderingAreaInfo_VkRenderingAreaInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkRenderingAttachmentInfo_VkRenderingAttachmentInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkRenderingAttachmentLocationInfo_VkRenderingAttachmentLocationInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkRenderingInfo_VkRenderingInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkRenderingInputAttachmentIndexInfo_VkRenderingInputAttachmentIndexInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkResolveImageInfo2_VkResolveImageInfo2);
	ZEPHIR_INIT(Vulkan_Struct_VkSamplerCreateInfo_VkSamplerCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkSamplerReductionModeCreateInfo_VkSamplerReductionModeCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkSamplerYcbcrConversionCreateInfo_VkSamplerYcbcrConversionCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkSamplerYcbcrConversionImageFormatProperties_VkSamplerYcbcrConversionImageFormatProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkSamplerYcbcrConversionInfo_VkSamplerYcbcrConversionInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkSemaphoreCreateInfo_VkSemaphoreCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkSemaphoreSignalInfo_VkSemaphoreSignalInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkSemaphoreSubmitInfo_VkSemaphoreSubmitInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkSemaphoreTypeCreateInfo_VkSemaphoreTypeCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkSemaphoreWaitInfo_VkSemaphoreWaitInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkShaderModuleCreateInfo_VkShaderModuleCreateInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkSparseBufferMemoryBindInfo_VkSparseBufferMemoryBindInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkSparseImageFormatProperties2_VkSparseImageFormatProperties2);
	ZEPHIR_INIT(Vulkan_Struct_VkSparseImageFormatProperties_VkSparseImageFormatProperties);
	ZEPHIR_INIT(Vulkan_Struct_VkSparseImageMemoryBindInfo_VkSparseImageMemoryBindInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkSparseImageMemoryBind_VkSparseImageMemoryBind);
	ZEPHIR_INIT(Vulkan_Struct_VkSparseImageMemoryRequirements2_VkSparseImageMemoryRequirements2);
	ZEPHIR_INIT(Vulkan_Struct_VkSparseImageMemoryRequirements_VkSparseImageMemoryRequirements);
	ZEPHIR_INIT(Vulkan_Struct_VkSparseImageOpaqueMemoryBindInfo_VkSparseImageOpaqueMemoryBindInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkSparseMemoryBind_VkSparseMemoryBind);
	ZEPHIR_INIT(Vulkan_Struct_VkSpecializationInfo_VkSpecializationInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkSpecializationMapEntry_VkSpecializationMapEntry);
	ZEPHIR_INIT(Vulkan_Struct_VkStencilOpState_VkStencilOpState);
	ZEPHIR_INIT(Vulkan_Struct_VkSubmitInfo2_VkSubmitInfo2);
	ZEPHIR_INIT(Vulkan_Struct_VkSubmitInfo_VkSubmitInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkSubpassBeginInfo_VkSubpassBeginInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkSubpassDependency2_VkSubpassDependency2);
	ZEPHIR_INIT(Vulkan_Struct_VkSubpassDependency_VkSubpassDependency);
	ZEPHIR_INIT(Vulkan_Struct_VkSubpassDescription2_VkSubpassDescription2);
	ZEPHIR_INIT(Vulkan_Struct_VkSubpassDescriptionDepthStencilResolve_VkSubpassDescriptionDepthStencilResolve);
	ZEPHIR_INIT(Vulkan_Struct_VkSubpassDescription_VkSubpassDescription);
	ZEPHIR_INIT(Vulkan_Struct_VkSubpassEndInfo_VkSubpassEndInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkSubresourceHostMemcpySize_VkSubresourceHostMemcpySize);
	ZEPHIR_INIT(Vulkan_Struct_VkSubresourceLayout2_VkSubresourceLayout2);
	ZEPHIR_INIT(Vulkan_Struct_VkSubresourceLayout_VkSubresourceLayout);
	ZEPHIR_INIT(Vulkan_Struct_VkSurfaceCapabilitiesKHR_VkSurfaceCapabilitiesKHR);
	ZEPHIR_INIT(Vulkan_Struct_VkSurfaceFormatKHR_VkSurfaceFormatKHR);
	ZEPHIR_INIT(Vulkan_Struct_VkSwapchainCreateInfoKHR_VkSwapchainCreateInfoKHR);
	ZEPHIR_INIT(Vulkan_Struct_VkTimelineSemaphoreSubmitInfo_VkTimelineSemaphoreSubmitInfo);
	ZEPHIR_INIT(Vulkan_Struct_VkVertexInputAttributeDescription_VkVertexInputAttributeDescription);
	ZEPHIR_INIT(Vulkan_Struct_VkVertexInputBindingDescription_VkVertexInputBindingDescription);
	ZEPHIR_INIT(Vulkan_Struct_VkVertexInputBindingDivisorDescription_VkVertexInputBindingDivisorDescription);
	ZEPHIR_INIT(Vulkan_Struct_VkViewport_VkViewport);
	ZEPHIR_INIT(Vulkan_Struct_VkWaylandSurfaceCreateInfoKHR_VkWaylandSurfaceCreateInfoKHR);
	ZEPHIR_INIT(Vulkan_Struct_VkWriteDescriptorSetInlineUniformBlock_VkWriteDescriptorSetInlineUniformBlock);
	ZEPHIR_INIT(Vulkan_Struct_VkWriteDescriptorSet_VkWriteDescriptorSet);
	ZEPHIR_INIT(Vulkan_Struct_VkXcbSurfaceCreateInfoKHR_VkXcbSurfaceCreateInfoKHR);
	ZEPHIR_INIT(Vulkan_Struct_VkXlibSurfaceCreateInfoKHR_VkXlibSurfaceCreateInfoKHR);
	ZEPHIR_INIT(Vulkan_VK_VK10_VK10);
	ZEPHIR_INIT(Vulkan_VK_VK11_VK11);
	ZEPHIR_INIT(Vulkan_VK_VK12_VK12);
	ZEPHIR_INIT(Vulkan_VK_VK13_VK13);
	ZEPHIR_INIT(Vulkan_VK_VK14_VK14);
	
	return SUCCESS;
}

static PHP_MSHUTDOWN_FUNCTION(vulkan)
{
	/* PHPVK module teardown: free the byte buffers the caller did not,
	 * destroy the registry, and close the loader's dlopen handles. */
	phpvk_bridge_shutdown();
	
	zephir_deinitialize_memory();
	UNREGISTER_INI_ENTRIES();
	return SUCCESS;
}

/**
 * Initialize globals on each request or each thread started
 */
static void php_zephir_init_globals(zend_vulkan_globals *vulkan_globals)
{
	vulkan_globals->initialized = 0;

	/* Cache Enabled */
	vulkan_globals->cache_enabled = 1;

	/* Recursive Lock */
	vulkan_globals->recursive_lock = 0;

	/* Static cache */
	memset(vulkan_globals->scache, '\0', sizeof(zephir_fcall_cache_entry*) * ZEPHIR_MAX_CACHE_SLOTS);

	
	
}

/**
 * Initialize globals only on each thread started
 */
static void php_zephir_init_module_globals(zend_vulkan_globals *vulkan_globals)
{
	
}

static PHP_RINIT_FUNCTION(vulkan)
{
	zend_vulkan_globals *vulkan_globals_ptr;
	vulkan_globals_ptr = ZEPHIR_VGLOBAL;

	php_zephir_init_globals(vulkan_globals_ptr);
	zephir_initialize_memory(vulkan_globals_ptr);

	
	return SUCCESS;
}

static PHP_RSHUTDOWN_FUNCTION(vulkan)
{
	
	zephir_deinitialize_memory();
	return SUCCESS;
}



static PHP_MINFO_FUNCTION(vulkan)
{
	php_info_print_box_start(0);
	php_printf("%s", PHP_VULKAN_DESCRIPTION);
	php_info_print_box_end();

	php_info_print_table_start();
	php_info_print_table_header(2, PHP_VULKAN_NAME, "enabled");
	php_info_print_table_row(2, "Author", PHP_VULKAN_AUTHOR);
	php_info_print_table_row(2, "Version", PHP_VULKAN_VERSION);
	php_info_print_table_row(2, "Build Date", __DATE__ " " __TIME__ );
	php_info_print_table_row(2, "Powered by Zephir", "Version " PHP_VULKAN_ZEPVERSION);
	php_info_print_table_end();
	
	DISPLAY_INI_ENTRIES();
}

static PHP_GINIT_FUNCTION(vulkan)
{
#if defined(COMPILE_DL_VULKAN) && defined(ZTS)
	ZEND_TSRMLS_CACHE_UPDATE();
#endif

	php_zephir_init_globals(vulkan_globals);
	php_zephir_init_module_globals(vulkan_globals);
}

static PHP_GSHUTDOWN_FUNCTION(vulkan)
{
	
}


zend_function_entry php_vulkan_functions[] = {
	ZEND_FE_END

};

static const zend_module_dep php_vulkan_deps[] = {
	
	ZEND_MOD_END
};

zend_module_entry vulkan_module_entry = {
	STANDARD_MODULE_HEADER_EX,
	NULL,
	php_vulkan_deps,
	PHP_VULKAN_EXTNAME,
	php_vulkan_functions,
	PHP_MINIT(vulkan),
	PHP_MSHUTDOWN(vulkan),
	PHP_RINIT(vulkan),
	PHP_RSHUTDOWN(vulkan),
	PHP_MINFO(vulkan),
	PHP_VULKAN_VERSION,
	ZEND_MODULE_GLOBALS(vulkan),
	PHP_GINIT(vulkan),
	PHP_GSHUTDOWN(vulkan),
#ifdef ZEPHIR_POST_REQUEST
	PHP_PRSHUTDOWN(vulkan),
#else
	NULL,
#endif
	STANDARD_MODULE_PROPERTIES_EX
};

/* implement standard "stub" routine to introduce ourselves to Zend */
#ifdef COMPILE_DL_VULKAN
# ifdef ZTS
ZEND_TSRMLS_CACHE_DEFINE()
# endif
ZEND_GET_MODULE(vulkan)
#endif
