
extern zend_class_entry *vulkan_struct_vkphysicaldeviceinlineuniformblockfeatures_vkphysicaldeviceinlineuniformblockfeatures_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkPhysicalDeviceInlineUniformBlockFeatures_VkPhysicalDeviceInlineUniformBlockFeatures);

PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceInlineUniformBlockFeatures_VkPhysicalDeviceInlineUniformBlockFeatures, pack);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceInlineUniformBlockFeatures_VkPhysicalDeviceInlineUniformBlockFeatures, packInto);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceInlineUniformBlockFeatures_VkPhysicalDeviceInlineUniformBlockFeatures, unpack);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceInlineUniformBlockFeatures_VkPhysicalDeviceInlineUniformBlockFeatures, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceinlineuniformblockfeatures_vkphysicaldeviceinlineuniformblockfeatures_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceinlineuniformblockfeatures_vkphysicaldeviceinlineuniformblockfeatures_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceinlineuniformblockfeatures_vkphysicaldeviceinlineuniformblockfeatures_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceinlineuniformblockfeatures_vkphysicaldeviceinlineuniformblockfeatures_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkphysicaldeviceinlineuniformblockfeatures_vkphysicaldeviceinlineuniformblockfeatures_method_entry) {
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceInlineUniformBlockFeatures_VkPhysicalDeviceInlineUniformBlockFeatures, pack, arginfo_vulkan_struct_vkphysicaldeviceinlineuniformblockfeatures_vkphysicaldeviceinlineuniformblockfeatures_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceInlineUniformBlockFeatures_VkPhysicalDeviceInlineUniformBlockFeatures, packInto, arginfo_vulkan_struct_vkphysicaldeviceinlineuniformblockfeatures_vkphysicaldeviceinlineuniformblockfeatures_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceInlineUniformBlockFeatures_VkPhysicalDeviceInlineUniformBlockFeatures, unpack, arginfo_vulkan_struct_vkphysicaldeviceinlineuniformblockfeatures_vkphysicaldeviceinlineuniformblockfeatures_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceInlineUniformBlockFeatures_VkPhysicalDeviceInlineUniformBlockFeatures, size, arginfo_vulkan_struct_vkphysicaldeviceinlineuniformblockfeatures_vkphysicaldeviceinlineuniformblockfeatures_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
