// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Vulkan\Ext\EXTMetalObjects;

class EXTMetalObjects
{
    public static function vkExportMetalObjectsEXT(int device, int pMetalObjectsInfo) -> void
    {
        extmetalobjects_vkexportmetalobjectsext(device, pMetalObjectsInfo);
    }
}
