
extern zend_class_entry *vulkan_struct_vkphysicaldeviceimagelessframebufferfeatures_vkphysicaldeviceimagelessframebufferfeatures_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkPhysicalDeviceImagelessFramebufferFeatures_VkPhysicalDeviceImagelessFramebufferFeatures);

PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceImagelessFramebufferFeatures_VkPhysicalDeviceImagelessFramebufferFeatures, pack);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceImagelessFramebufferFeatures_VkPhysicalDeviceImagelessFramebufferFeatures, packInto);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceImagelessFramebufferFeatures_VkPhysicalDeviceImagelessFramebufferFeatures, unpack);
PHP_METHOD(Vulkan_Struct_VkPhysicalDeviceImagelessFramebufferFeatures_VkPhysicalDeviceImagelessFramebufferFeatures, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceimagelessframebufferfeatures_vkphysicaldeviceimagelessframebufferfeatures_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceimagelessframebufferfeatures_vkphysicaldeviceimagelessframebufferfeatures_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceimagelessframebufferfeatures_vkphysicaldeviceimagelessframebufferfeatures_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkphysicaldeviceimagelessframebufferfeatures_vkphysicaldeviceimagelessframebufferfeatures_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkphysicaldeviceimagelessframebufferfeatures_vkphysicaldeviceimagelessframebufferfeatures_method_entry) {
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceImagelessFramebufferFeatures_VkPhysicalDeviceImagelessFramebufferFeatures, pack, arginfo_vulkan_struct_vkphysicaldeviceimagelessframebufferfeatures_vkphysicaldeviceimagelessframebufferfeatures_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceImagelessFramebufferFeatures_VkPhysicalDeviceImagelessFramebufferFeatures, packInto, arginfo_vulkan_struct_vkphysicaldeviceimagelessframebufferfeatures_vkphysicaldeviceimagelessframebufferfeatures_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceImagelessFramebufferFeatures_VkPhysicalDeviceImagelessFramebufferFeatures, unpack, arginfo_vulkan_struct_vkphysicaldeviceimagelessframebufferfeatures_vkphysicaldeviceimagelessframebufferfeatures_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPhysicalDeviceImagelessFramebufferFeatures_VkPhysicalDeviceImagelessFramebufferFeatures, size, arginfo_vulkan_struct_vkphysicaldeviceimagelessframebufferfeatures_vkphysicaldeviceimagelessframebufferfeatures_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
