// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Vulkan\VK\VK13;

class VK13
{
    public static function vkGetPhysicalDeviceToolProperties(int physicalDevice, int pToolCount, int pToolProperties) -> int
    {
        return vk13_vkgetphysicaldevicetoolproperties(physicalDevice, pToolCount, pToolProperties);
    }

    public static function vkCreatePrivateDataSlot(int device, int pCreateInfo, int pAllocator, int pPrivateDataSlot) -> int
    {
        return vk13_vkcreateprivatedataslot(device, pCreateInfo, pAllocator, pPrivateDataSlot);
    }

    public static function vkDestroyPrivateDataSlot(int device, int privateDataSlot, int pAllocator) -> void
    {
        vk13_vkdestroyprivatedataslot(device, privateDataSlot, pAllocator);
    }

    public static function vkSetPrivateData(int device, int objectType, int objectHandle, int privateDataSlot, int data) -> int
    {
        return vk13_vksetprivatedata(device, objectType, objectHandle, privateDataSlot, data);
    }

    public static function vkGetPrivateData(int device, int objectType, int objectHandle, int privateDataSlot, int pData) -> void
    {
        vk13_vkgetprivatedata(device, objectType, objectHandle, privateDataSlot, pData);
    }

    public static function vkCmdPipelineBarrier2(int commandBuffer, int pDependencyInfo) -> void
    {
        vk13_vkcmdpipelinebarrier2(commandBuffer, pDependencyInfo);
    }

    public static function vkCmdWriteTimestamp2(int commandBuffer, int stage, int queryPool, int query) -> void
    {
        vk13_vkcmdwritetimestamp2(commandBuffer, stage, queryPool, query);
    }

    public static function vkQueueSubmit2(int queue, int submitCount, int pSubmits, int fence) -> int
    {
        return vk13_vkqueuesubmit2(queue, submitCount, pSubmits, fence);
    }

    public static function vkCmdCopyBuffer2(int commandBuffer, int pCopyBufferInfo) -> void
    {
        vk13_vkcmdcopybuffer2(commandBuffer, pCopyBufferInfo);
    }

    public static function vkCmdCopyImage2(int commandBuffer, int pCopyImageInfo) -> void
    {
        vk13_vkcmdcopyimage2(commandBuffer, pCopyImageInfo);
    }

    public static function vkCmdCopyBufferToImage2(int commandBuffer, int pCopyBufferToImageInfo) -> void
    {
        vk13_vkcmdcopybuffertoimage2(commandBuffer, pCopyBufferToImageInfo);
    }

    public static function vkCmdCopyImageToBuffer2(int commandBuffer, int pCopyImageToBufferInfo) -> void
    {
        vk13_vkcmdcopyimagetobuffer2(commandBuffer, pCopyImageToBufferInfo);
    }

    public static function vkGetDeviceBufferMemoryRequirements(int device, int pInfo, int pMemoryRequirements) -> void
    {
        vk13_vkgetdevicebuffermemoryrequirements(device, pInfo, pMemoryRequirements);
    }

    public static function vkGetDeviceImageMemoryRequirements(int device, int pInfo, int pMemoryRequirements) -> void
    {
        vk13_vkgetdeviceimagememoryrequirements(device, pInfo, pMemoryRequirements);
    }

    public static function vkGetDeviceImageSparseMemoryRequirements(int device, int pInfo, int pSparseMemoryRequirementCount, int pSparseMemoryRequirements) -> void
    {
        vk13_vkgetdeviceimagesparsememoryrequirements(device, pInfo, pSparseMemoryRequirementCount, pSparseMemoryRequirements);
    }

    public static function vkCmdSetEvent2(int commandBuffer, int event, int pDependencyInfo) -> void
    {
        vk13_vkcmdsetevent2(commandBuffer, event, pDependencyInfo);
    }

    public static function vkCmdResetEvent2(int commandBuffer, int event, int stageMask) -> void
    {
        vk13_vkcmdresetevent2(commandBuffer, event, stageMask);
    }

    public static function vkCmdWaitEvents2(int commandBuffer, int eventCount, int pEvents, int pDependencyInfos) -> void
    {
        vk13_vkcmdwaitevents2(commandBuffer, eventCount, pEvents, pDependencyInfos);
    }

    public static function vkCmdBlitImage2(int commandBuffer, int pBlitImageInfo) -> void
    {
        vk13_vkcmdblitimage2(commandBuffer, pBlitImageInfo);
    }

    public static function vkCmdResolveImage2(int commandBuffer, int pResolveImageInfo) -> void
    {
        vk13_vkcmdresolveimage2(commandBuffer, pResolveImageInfo);
    }

    public static function vkCmdBeginRendering(int commandBuffer, int pRenderingInfo) -> void
    {
        vk13_vkcmdbeginrendering(commandBuffer, pRenderingInfo);
    }

    public static function vkCmdEndRendering(int commandBuffer) -> void
    {
        vk13_vkcmdendrendering(commandBuffer);
    }

    public static function vkCmdSetCullMode(int commandBuffer, int cullMode) -> void
    {
        vk13_vkcmdsetcullmode(commandBuffer, cullMode);
    }

    public static function vkCmdSetFrontFace(int commandBuffer, int frontFace) -> void
    {
        vk13_vkcmdsetfrontface(commandBuffer, frontFace);
    }

    public static function vkCmdSetPrimitiveTopology(int commandBuffer, int primitiveTopology) -> void
    {
        vk13_vkcmdsetprimitivetopology(commandBuffer, primitiveTopology);
    }

    public static function vkCmdSetViewportWithCount(int commandBuffer, int viewportCount, int pViewports) -> void
    {
        vk13_vkcmdsetviewportwithcount(commandBuffer, viewportCount, pViewports);
    }

    public static function vkCmdSetScissorWithCount(int commandBuffer, int scissorCount, int pScissors) -> void
    {
        vk13_vkcmdsetscissorwithcount(commandBuffer, scissorCount, pScissors);
    }

    public static function vkCmdBindVertexBuffers2(int commandBuffer, int firstBinding, int bindingCount, int pBuffers, int pOffsets, int pSizes, int pStrides) -> void
    {
        vk13_vkcmdbindvertexbuffers2(commandBuffer, firstBinding, bindingCount, pBuffers, pOffsets, pSizes, pStrides);
    }

    public static function vkCmdSetDepthTestEnable(int commandBuffer, bool depthTestEnable) -> void
    {
        vk13_vkcmdsetdepthtestenable(commandBuffer, depthTestEnable);
    }

    public static function vkCmdSetDepthWriteEnable(int commandBuffer, bool depthWriteEnable) -> void
    {
        vk13_vkcmdsetdepthwriteenable(commandBuffer, depthWriteEnable);
    }

    public static function vkCmdSetDepthCompareOp(int commandBuffer, int depthCompareOp) -> void
    {
        vk13_vkcmdsetdepthcompareop(commandBuffer, depthCompareOp);
    }

    public static function vkCmdSetDepthBoundsTestEnable(int commandBuffer, bool depthBoundsTestEnable) -> void
    {
        vk13_vkcmdsetdepthboundstestenable(commandBuffer, depthBoundsTestEnable);
    }

    public static function vkCmdSetStencilTestEnable(int commandBuffer, bool stencilTestEnable) -> void
    {
        vk13_vkcmdsetstenciltestenable(commandBuffer, stencilTestEnable);
    }

    public static function vkCmdSetStencilOp(int commandBuffer, int faceMask, int failOp, int passOp, int depthFailOp, int compareOp) -> void
    {
        vk13_vkcmdsetstencilop(commandBuffer, faceMask, failOp, passOp, depthFailOp, compareOp);
    }

    public static function vkCmdSetRasterizerDiscardEnable(int commandBuffer, bool rasterizerDiscardEnable) -> void
    {
        vk13_vkcmdsetrasterizerdiscardenable(commandBuffer, rasterizerDiscardEnable);
    }

    public static function vkCmdSetDepthBiasEnable(int commandBuffer, bool depthBiasEnable) -> void
    {
        vk13_vkcmdsetdepthbiasenable(commandBuffer, depthBiasEnable);
    }

    public static function vkCmdSetPrimitiveRestartEnable(int commandBuffer, bool primitiveRestartEnable) -> void
    {
        vk13_vkcmdsetprimitiverestartenable(commandBuffer, primitiveRestartEnable);
    }
}
