// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Vulkan\Struct\VkBufferMemoryRequirementsInfo2;

class VkBufferMemoryRequirementsInfo2
{
    public static function pack(array members) -> int
    {
        return struct_vkbuffermemoryrequirementsinfo2_pack(members);
    }

    public static function packInto(int ptr, array members) -> void
    {
        struct_vkbuffermemoryrequirementsinfo2_packinto(ptr, members);
    }

    public static function unpack(int ptr) -> array
    {
        var result;

        let result = struct_vkbuffermemoryrequirementsinfo2_unpack(ptr);

        return result;
    }

    public static function size() -> int
    {
        return struct_vkbuffermemoryrequirementsinfo2_size();
    }
}
