// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Vulkan\Struct\VkPhysicalDeviceMaintenance4Properties;

class VkPhysicalDeviceMaintenance4Properties
{
    public static function pack(array members) -> int
    {
        return struct_vkphysicaldevicemaintenance4properties_pack(members);
    }

    public static function packInto(int ptr, array members) -> void
    {
        struct_vkphysicaldevicemaintenance4properties_packinto(ptr, members);
    }

    public static function unpack(int ptr) -> array
    {
        var result;

        let result = struct_vkphysicaldevicemaintenance4properties_unpack(ptr);

        return result;
    }

    public static function size() -> int
    {
        return struct_vkphysicaldevicemaintenance4properties_size();
    }
}
