// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Vulkan\Struct\VkPhysicalDeviceVulkan13Features;

class VkPhysicalDeviceVulkan13Features
{
    public static function pack(array members) -> int
    {
        return struct_vkphysicaldevicevulkan13features_pack(members);
    }

    public static function packInto(int ptr, array members) -> void
    {
        struct_vkphysicaldevicevulkan13features_packinto(ptr, members);
    }

    public static function unpack(int ptr) -> array
    {
        var result;

        let result = struct_vkphysicaldevicevulkan13features_unpack(ptr);

        return result;
    }

    public static function size() -> int
    {
        return struct_vkphysicaldevicevulkan13features_size();
    }
}
