#!/usr/bin/env php
<?php
/**
 * gen-vk-src.php — translate the vendored Khronos registry into src/*.{h,c}.
 *
 * Nothing in `src/vk-*.{h,c}` or `src/phpvk-registry.{h,c}` is hand-written.
 * `scripts/khronos/vk.xml` is the single source of truth for what exists;
 * this script is the single source of truth for how it crosses into PHP. The
 * annotations it emits are then the input to `scripts/gen-zep.php`.
 *
 * Two tiers, from one walk (scripts/lib/registry.php):
 *
 *   commands  one C body per command. It resolves its entry point through
 *             phpvk_entry() and makes exactly one call through it. No
 *             command is ever referenced at link time.
 *   structs   one fill/read pair per struct or union, plus the four binding
 *             methods (pack / packInto / unpack / size) over them. Flat: a
 *             pointer member is bits and is never followed.
 *
 * The struct tier also gets src/vk-struct-asserts.c: one
 * `_Static_assert(sizeof(T) == N)` per struct and one
 * `_Static_assert(offsetof(T, m) == off)` per member, measured here by a C
 * probe this script compiles and runs against the real Khronos headers. It
 * makes the generating box's layout a compile-time contract on every other
 * build box. `cc` is therefore a generation-box requirement (like `php`);
 * the boxes that only BUILD need nothing new.
 *
 * Marshalling — the whole table, no per-command judgement anywhere
 * (spec §4 for parameters, §5.1 for members):
 *
 *   dispatchable handle, any pointer (except const char* parameters)   -> int
 *                                              raw pointer bits, 0 = NULL
 *   non-dispatchable handle                                            -> int
 *   uint64_t, size_t, VkDeviceSize, VkDeviceAddress, VkFlags64         -> int
 *                                              -1 is UINT64_MAX
 *   every other integer, every enum, every VkFlags bitmask             -> int
 *   VkBool32                                                           -> bool
 *   float, double                                                      -> double
 *   const char * (command parameter)                                   -> string
 *   char[N] (member)                                                   -> string
 *   T[N] of scalars (member)                                           -> array
 *   struct/union by value (member), incl. T[N] of them                 -> array
 *
 * A command this table cannot express becomes a visible @reserved line,
 * counted by the audit toward its class's registry total — never a silent
 * absence. Exactly one kind qualifies (see reservationFor): a function
 * pointer PARAMETER, which PHP cannot be. Anything ELSE the table does not
 * cover is a hard failure that names the type, so a new spelling in a
 * re-vendored registry cannot quietly shrink the surface.
 *
 * Usage:  php scripts/gen-vk-src.php [--check]
 *   --check  generate into memory and diff against the tree; exit non-zero
 *            on any difference (idempotence guard).
 */

declare(strict_types=1);

require __DIR__ . '/lib/registry.php';

const GENERATED_MARK = 'GENERATED by scripts/gen-vk-src.php';

/** C keywords a registry parameter name may collide with. */
const C_RESERVED = [
    'auto', 'break', 'case', 'char', 'const', 'continue', 'default', 'do',
    'double', 'else', 'enum', 'extern', 'float', 'for', 'goto', 'if',
    'inline', 'int', 'long', 'register', 'restrict', 'return', 'short',
    'signed', 'sizeof', 'static', 'struct', 'switch', 'typedef', 'union',
    'unsigned', 'void', 'volatile', 'while',
];

/**
 * The window-system and Metal scalars, whose spelling the registry names but
 * whose definition it leaves to a platform header this binding deliberately
 * does not include (spec §5.4).
 *
 * Every entry here is the kind of the typedef `src/phpvk-platform.h` writes
 * for it, and those two must agree — the shim is what the compiler sees.
 * Anything not listed is still a hard failure by name, so a re-vendored
 * registry that introduces a new platform spelling stops the generator
 * instead of guessing.
 */
const PLATFORM_TYPES = [
    // xcb/xcb.h — uint32_t in phpvk-platform.h
    'xcb_visualid_t' => 'long',
    'xcb_window_t' => 'long',
    // X11/Xlib.h — unsigned long in phpvk-platform.h
    'Window' => 'u64',
    'VisualID' => 'u64',
    // vulkan_metal.h with __OBJC__ undefined — every id<MTL…> is void *
    'MTLDevice_id' => 'ptr',
    'MTLCommandQueue_id' => 'ptr',
    'MTLBuffer_id' => 'ptr',
    'MTLTexture_id' => 'ptr',
    'MTLSharedEvent_id' => 'ptr',
    'IOSurfaceRef' => 'ptr',
];

function fail(string $msg): never
{
    fwrite(STDERR, "gen-vk-src: {$msg}\n");
    exit(1);
}

function cName(string $name): string
{
    return in_array($name, C_RESERVED, true) ? $name . '_' : $name;
}

// ---------------------------------------------------------------- type table

/**
 * What kind of thing a scalar (non-pointer) registry type is.
 *
 * Returns one of: ptr (dispatchable handle / pointer basetype), nhandle
 * (non-dispatchable handle — a pointer under VK_USE_64_BIT_PTR_DEFINES, so
 * spelled through uintptr_t but valued as a 64-bit int), u64, long, bool,
 * double, struct, union, funcptr. null means the table does not know it,
 * which is always a hard failure at the call site.
 */
function vkScalarKind(string $type, array $types, array $seen = []): ?string
{
    if (isset($seen[$type])) {
        return null;
    }
    $seen[$type] = true;

    if (isset(PLATFORM_TYPES[$type])) {
        return PLATFORM_TYPES[$type];
    }

    $t = $types[$type] ?? null;
    if ($t !== null) {
        if ($t['alias'] !== null) {
            return vkScalarKind($t['alias'], $types, $seen);
        }
        switch ($t['category']) {
            case 'handle':
                return $t['dispatchable'] ? 'ptr' : 'nhandle';
            case 'enum':
                return 'long';
            case 'funcpointer':
                return 'funcptr';
            case 'struct':
                return 'struct';
            case 'union':
                return 'union';
            case 'bitmask':
            case 'basetype':
                if ($type === 'VkBool32') {
                    return 'bool';
                }
                if (($t['underlyingPtr'] ?? 0) > 0) {
                    return 'ptr';   // e.g. typedef void* VkRemoteAddressNV;
                }
                if ($t['underlying'] === null || $t['underlying'] === $type) {
                    return null;
                }

                return vkScalarKind($t['underlying'], $types, $seen);
        }
    }

    // Primitive spellings the registry inherits from <stdint.h> / vk_platform.h.
    return match ($type) {
        'uint64_t', 'size_t' => 'u64',
        'uint32_t', 'int32_t', 'uint16_t', 'int16_t', 'uint8_t', 'int8_t',
        'int', 'int64_t', 'char' => 'long',
        'float', 'double' => 'double',
        default => null,
    };
}

/** The Zephir parameter/return type one kind crosses as. */
function vkZepType(string $kind): string
{
    return match ($kind) {
        'bool' => 'bool',
        'double' => 'double',
        default => 'int',
    };
}

/**
 * The C expression that turns one command parameter's zval into its C value.
 *
 * @return array{zep: string, expr: string}
 */
function vkParamExpr(array $decl, array $types, string $cmd): array
{
    $arg = cName($decl['name']);

    /*
     * An array parameter is a pointer in C — `const float blendConstants[4]`
     * IS `const float *`. The registry spells the array because the
     * specification's length is useful to a validator; the ABI does not care,
     * and neither does the pointer rule.
     */
    if ($decl['dims'] !== []) {
        if ($decl['unsupported'] !== null) {
            fail("{$cmd}: parameter '{$decl['name']}' is a {$decl['unsupported']}, which the parameter table does not express");
        }
        $decl['ptr'] += 1;
        $decl['ctype'] = trim($decl['ctype'] . ' *');
        $decl['dims'] = [];
    }

    if ($decl['ptr'] > 0) {
        if ($decl['type'] === 'char' && $decl['const'] && $decl['ptr'] === 1) {
            return ['zep' => 'string', 'expr' => "({$decl['ctype']}) phpvk_arg_string({$arg})"];
        }

        return ['zep' => 'int', 'expr' => "({$decl['ctype']}) phpvk_arg_ptr({$arg})"];
    }

    $kind = vkScalarKind($decl['type'], $types);
    if ($kind === null) {
        fail("{$cmd}: unsupported parameter type '{$decl['type']}' ({$decl['name']})");
    }

    return match ($kind) {
        'ptr' => ['zep' => 'int', 'expr' => "({$decl['ctype']}) phpvk_arg_ptr({$arg})"],
        'nhandle' => ['zep' => 'int', 'expr' => "({$decl['ctype']}) (uintptr_t) phpvk_arg_u64({$arg})"],
        'u64' => ['zep' => 'int', 'expr' => "({$decl['ctype']}) phpvk_arg_u64({$arg})"],
        'long' => ['zep' => 'int', 'expr' => "({$decl['ctype']}) phpvk_arg_long({$arg})"],
        'bool' => ['zep' => 'bool', 'expr' => "({$decl['ctype']}) phpvk_arg_bool({$arg})"],
        'double' => ['zep' => 'double', 'expr' => "({$decl['ctype']}) phpvk_arg_double({$arg})"],
        'struct', 'union' => fail("{$cmd}: parameter '{$decl['name']}' is a by-value {$kind}, which the parameter table does not express"),
        default => fail("{$cmd}: unsupported parameter type '{$decl['type']}' ({$decl['name']})"),
    };
}

/**
 * How a command's return value crosses.
 *
 * @return array{zep: string, emit: string}  emit is a template for the call
 */
function vkReturnEmit(array $decl, array $types, string $cmd): array
{
    if ($decl['type'] === 'void' && $decl['ptr'] === 0) {
        return ['zep' => 'void', 'emit' => '    %s;'];
    }
    if ($decl['ptr'] > 0) {
        return ['zep' => 'int', 'emit' => '    return (zend_long) (uintptr_t) %s;'];
    }

    $kind = vkScalarKind($decl['type'], $types);
    if ($kind === null) {
        fail("{$cmd}: unsupported return type '{$decl['type']}'");
    }

    return match ($kind) {
        'ptr', 'nhandle', 'funcptr' => ['zep' => 'int', 'emit' => '    return (zend_long) (uintptr_t) %s;'],
        'u64', 'long' => ['zep' => 'int', 'emit' => '    return (zend_long) %s;'],
        'bool' => ['zep' => 'bool', 'emit' => '    return %s ? 1 : 0;'],
        'double' => ['zep' => 'double', 'emit' => '    return (double) %s;'],
        default => fail("{$cmd}: unsupported return type '{$decl['type']}'"),
    };
}

/**
 * Why this command cannot be bound, or null when it can.
 *
 * One kind of unbindable, and only one: a function-pointer PARAMETER. PHP
 * cannot be a C function pointer and this extension has no callback glue, so
 * such a command is reserved with its reason rather than bound. (A function
 * pointer RETURNED — vkGetInstanceProcAddr — is just bits and binds fine.)
 *
 * Anything else the type table does not cover is still a hard failure that
 * names the type.
 */
function reservationFor(array $command, array $types): ?string
{
    foreach ($command['params'] as $p) {
        if ($p['ptr'] > 0) {
            continue;
        }
        if (vkScalarKind($p['type'], $types) === 'funcptr') {
            return "{$p['type']} is a callback; PHP cannot be a C function pointer";
        }
    }

    return null;
}

// ------------------------------------------------------------ command tier

function commandSymbol(string $class, string $name): string
{
    return 'phpvk_' . strtolower($class) . '_' . strtolower($name);
}

function levelConstant(int $level): string
{
    return match ($level) {
        VK_LEVEL_DEVICE => 'PHPVK_LEVEL_DEVICE',
        VK_LEVEL_INSTANCE => 'PHPVK_LEVEL_INSTANCE',
        default => 'PHPVK_LEVEL_GLOBAL',
    };
}

function renderReserved(string $classPath, array $command, string $reason): string
{
    $args = [];
    foreach ($command['params'] as $p) {
        $args[] = trim($p['ctype'] . ' ' . $p['name'] . ($p['dims'] !== [] ? '[' . implode('][', $p['dims']) . ']' : ''));
    }
    $signature = $command['ret']['ctype'] . ' ' . $command['name']
        . '(' . ($args === [] ? 'void' : implode(', ', $args)) . ')';
    $signature = str_replace('*/', '* /', $signature);
    $reason = str_replace('*/', '* /', $reason);

    return sprintf('/*@reserved %s %s — %s */', $classPath, $signature, $reason);
}

/**
 * @return array{annotation: string, proto: string, body: string}
 */
function renderCommand(string $classPath, string $class, array $command, array $types, int $level): array
{
    $name = $command['name'];
    $symbol = commandSymbol($class, $name);
    $ret = vkReturnEmit($command['ret'], $types, $name);

    $zepParams = [];
    $cParams = [];
    $callArgs = [];
    foreach ($command['params'] as $p) {
        $mapped = vkParamExpr($p, $types, $name);
        $zepParams[] = $mapped['zep'] . ' ' . $p['name'];
        $cParams[] = 'zval *' . cName($p['name']);
        $callArgs[] = $mapped['expr'];
    }

    $annotation = sprintf(
        '/*@zep %s %s(%s) -> %s */',
        $classPath,
        $name,
        implode(', ', $zepParams),
        $ret['zep']
    );

    $cReturn = match ($ret['zep']) {
        'int', 'bool' => 'zend_long',
        'double' => 'double',
        default => 'void',
    };
    $protoParamSrc = $cParams === [] ? 'void' : implode(', ', $cParams);
    $proto = "{$cReturn} {$symbol}({$protoParamSrc});";

    $earlyReturn = match ($ret['zep']) {
        'int', 'bool' => '        return 0;',
        'double' => '        return 0.0;',
        default => '        return;',
    };

    $body = "{$cReturn} {$symbol}({$protoParamSrc})\n{\n"
        . "    static phpvk_slot slot = PHPVK_SLOT_INIT;\n"
        . "    PFN_{$name} fn = (PFN_{$name}) phpvk_entry(\"{$name}\", &slot, " . levelConstant($level) . ");\n"
        . "\n"
        . "    if (!fn) {\n{$earlyReturn}\n    }\n\n"
        . sprintf($ret['emit'], 'fn(' . implode(', ', $callArgs) . ')') . "\n"
        . "}\n";

    return ['annotation' => $annotation, 'proto' => $proto, 'body' => $body];
}

// ------------------------------------------------------------- struct tier

function structSymbol(string $name, string $method): string
{
    return 'phpvk_struct_' . strtolower($name) . '_' . strtolower($method);
}

/** `sizeof(s->m) / sizeof(s->m[0])` — the element count, straight from the ABI. */
function arrayCount(string $member): string
{
    return "sizeof(s->{$member}) / sizeof(s->{$member}[0])";
}

/**
 * The fill and read statements for one struct member.
 *
 * @return array{fill: string, read: string}
 */
function renderMember(string $struct, array $member, array $types, bool $isUnion): array
{
    $key = $member['name'];
    $ctx = $struct;
    $indent = $isUnion ? '        ' : '    ';

    if ($member['unsupported'] !== null) {
        fail("{$struct}.{$key}: {$member['unsupported']} members are not expressible by the member table");
    }
    if (count($member['dims']) > 1) {
        fail("{$struct}.{$key}: {$member['ctype']}["
            . implode('][', $member['dims'])
            . '] is a multi-dimensional array, which the member table does not express');
    }
    if ($member['ptr'] > 0 && $member['dims'] !== []) {
        fail("{$struct}.{$key}: an array of pointers is not expressible by the member table");
    }

    // ---- pointers (including pNext and every PFN_* member) ----
    if ($member['ptr'] > 0) {
        return [
            'fill' => "{$indent}s->{$key} = ({$member['ctype']}) phpvk_member_ptr(ht, \"{$key}\");\n",
            'read' => "    add_assoc_long(out, \"{$key}\", (zend_long) (uintptr_t) s->{$key});\n",
        ];
    }

    $kind = vkScalarKind($member['type'], $types);
    if ($kind === null) {
        fail("{$struct}.{$key}: unsupported member type '{$member['type']}'");
    }

    // ---- char[N] ----
    if ($member['dims'] !== [] && $member['type'] === 'char') {
        return [
            'fill' => "{$indent}if (phpvk_member_chars(ht, \"{$key}\", s->{$key}, sizeof(s->{$key}), ctx) < 0) {\n{$indent}    return 0;\n{$indent}}\n",
            'read' => "    add_assoc_stringl(out, \"{$key}\", s->{$key}, strnlen(s->{$key}, sizeof(s->{$key})));\n",
        ];
    }

    // ---- T[N] ----
    if ($member['dims'] !== []) {
        $count = arrayCount($key);
        $element = $kind === 'struct' || $kind === 'union'
            ? "            if (!phpvk_fill_{$member['type']}(&s->{$key}[i], phpvk_member_array_at(ht, \"{$key}\", (uint32_t) i), \"{$ctx}.{$key}\")) {\n                return 0;\n            }\n"
            : "            s->{$key}[i] = " . scalarFromZval($kind, $member['ctype'], "phpvk_member_array_at(ht, \"{$key}\", (uint32_t) i)") . ";\n";

        $fill = "{$indent}{\n"
            . "{$indent}    int n = phpvk_member_array_len(ht, \"{$key}\", {$count}, ctx);\n"
            . "{$indent}    int i;\n\n"
            . "{$indent}    if (n < 0) {\n{$indent}        return 0;\n{$indent}    }\n"
            . "{$indent}    for (i = 0; i < n; i++) {\n"
            . ($isUnion ? '    ' : '') . $element
            . "{$indent}    }\n"
            . "{$indent}}\n";

        $readElement = $kind === 'struct' || $kind === 'union'
            ? "            zval sub;\n\n            phpvk_read_{$member['type']}(&sub, &s->{$key}[i]);\n            add_next_index_zval(&item, &sub);\n"
            : '            ' . scalarToZval($kind, "s->{$key}[i]", '&item', null) . "\n";

        $read = "    {\n"
            . "        zval item;\n"
            . "        size_t i;\n\n"
            . "        array_init(&item);\n"
            . "        for (i = 0; i < ({$count}); i++) {\n"
            . $readElement
            . "        }\n"
            . "        add_assoc_zval(out, \"{$key}\", &item);\n"
            . "    }\n";

        return ['fill' => $fill, 'read' => $read];
    }

    // ---- by-value struct / union ----
    if ($kind === 'struct' || $kind === 'union') {
        return [
            'fill' => "{$indent}if (!phpvk_fill_{$member['type']}(&s->{$key}, phpvk_member_sub(ht, \"{$key}\"), \"{$ctx}.{$key}\")) {\n{$indent}    return 0;\n{$indent}}\n",
            'read' => "    {\n        zval sub;\n\n        phpvk_read_{$member['type']}(&sub, &s->{$key});\n        add_assoc_zval(out, \"{$key}\", &sub);\n    }\n",
        ];
    }

    // ---- scalars ----
    /*
     * A PFN_* member is bits like any other pointer. It is never called and
     * never produced; a caller that wants a real callback there is asking for
     * something this binding does not do.
     */
    if ($kind === 'funcptr') {
        return [
            'fill' => "{$indent}s->{$key} = ({$member['ctype']}) (uintptr_t) phpvk_member_u64(ht, \"{$key}\");\n",
            'read' => "    add_assoc_long(out, \"{$key}\", (zend_long) (uintptr_t) s->{$key});\n",
        ];
    }

    $source = match ($kind) {
        'ptr' => "({$member['ctype']}) phpvk_member_ptr(ht, \"{$key}\")",
        'nhandle' => "({$member['ctype']}) (uintptr_t) phpvk_member_u64(ht, \"{$key}\")",
        'u64' => "({$member['ctype']}) phpvk_member_u64(ht, \"{$key}\")",
        'long' => "({$member['ctype']}) phpvk_member_long(ht, \"{$key}\")",
        'bool' => "({$member['ctype']}) phpvk_member_bool(ht, \"{$key}\")",
        'double' => "({$member['ctype']}) phpvk_member_double(ht, \"{$key}\")",
        default => fail("{$struct}.{$key}: unsupported member type '{$member['type']}'"),
    };

    return [
        'fill' => "{$indent}s->{$key} = {$source};\n",
        'read' => '    ' . scalarToZval($kind, "s->{$key}", 'out', $key) . "\n",
    ];
}

/** One scalar array element, read out of a zval. */
function scalarFromZval(string $kind, string $ctype, string $zval): string
{
    return match ($kind) {
        'ptr' => "({$ctype}) phpvk_arg_ptr({$zval})",
        'nhandle' => "({$ctype}) (uintptr_t) phpvk_arg_u64({$zval})",
        'u64' => "({$ctype}) phpvk_arg_u64({$zval})",
        'long' => "({$ctype}) phpvk_arg_long({$zval})",
        'bool' => "({$ctype}) phpvk_arg_bool({$zval})",
        'double' => "({$ctype}) phpvk_arg_double({$zval})",
        default => fail("unsupported scalar kind '{$kind}'"),
    };
}

/** One scalar, written into a zval array — keyed when $key is given. */
function scalarToZval(string $kind, string $expr, string $target, ?string $key): string
{
    [$fn, $value] = match ($kind) {
        'ptr', 'nhandle' => ['long', "(zend_long) (uintptr_t) {$expr}"],
        'u64', 'long' => ['long', "(zend_long) {$expr}"],
        'bool' => ['bool', "{$expr} ? 1 : 0"],
        'double' => ['double', "(double) {$expr}"],
        default => fail("unsupported scalar kind '{$kind}'"),
    };

    return $key === null
        ? "add_next_index_{$fn}({$target}, {$value});"
        : "add_assoc_{$fn}({$target}, \"{$key}\", {$value});";
}

/**
 * @return array{decls: string, impl: string, internal: string}
 */
function renderStruct(string $name, array $types): array
{
    $t = $types[$name];
    $isUnion = $t['category'] === 'union';
    $members = $t['members'];
    if ($members === []) {
        fail("{$name}: struct has no members the vulkan API uses");
    }

    $names = array_map(static fn (array $m): string => '"' . $m['name'] . '"', $members);
    $count = count($members);

    $fill = '';
    $read = '';
    foreach ($members as $m) {
        $r = renderMember($name, $m, $types, $isUnion);
        if ($isUnion) {
            /*
             * A union holds one member at a time, so fill writes only the
             * members the caller supplied — later ones overwrite earlier
             * ones, in registry order. read emits every member, because
             * which one is live is not knowable from the bytes.
             */
            $fill .= "    if (phpvk_member_sub(ht, \"{$m['name']}\")) {\n" . $r['fill'] . "    }\n";
        } else {
            $fill .= $r['fill'];
        }
        $read .= $r['read'];
    }

    $internal = "int phpvk_fill_{$name}({$name} *s, zval *members, const char *ctx);\n"
        . "void phpvk_read_{$name}(zval *out, const {$name} *s);\n";

    $impl = "static const char *const phpvk_names_{$name}[] = {" . implode(', ', $names) . "};\n\n"
        . "int phpvk_fill_{$name}({$name} *s, zval *members, const char *ctx)\n"
        . "{\n"
        . "    HashTable *ht;\n\n"
        . "    memset(s, 0, sizeof(*s));\n"
        . "    if (!members || Z_TYPE_P(members) == IS_NULL) {\n"
        . "        return 1;\n"
        . "    }\n"
        . "    ht = phpvk_members(members, ctx);\n"
        . "    if (!ht || !phpvk_check_keys(ht, phpvk_names_{$name}, {$count}, ctx)) {\n"
        . "        return 0;\n"
        . "    }\n"
        . $fill
        . "\n    return 1;\n"
        . "}\n\n"
        . "void phpvk_read_{$name}(zval *out, const {$name} *s)\n"
        . "{\n"
        . "    array_init(out);\n"
        . $read
        . "}\n\n";

    $packSymbol = structSymbol($name, 'pack');
    $packIntoSymbol = structSymbol($name, 'packInto');
    $unpackSymbol = structSymbol($name, 'unpack');
    $sizeSymbol = structSymbol($name, 'size');

    $impl .= "zend_long {$packSymbol}(zval *members)\n"
        . "{\n"
        . "    {$name} *s = ({$name} *) malloc(sizeof({$name}));\n\n"
        . "    if (!s) {\n"
        . "        php_error_docref(NULL, E_WARNING, \"{$name}::pack: out of memory\");\n\n"
        . "        return 0;\n"
        . "    }\n"
        . "    if (!phpvk_fill_{$name}(s, members, \"{$name}\")) {\n"
        . "        free(s);\n\n"
        . "        return 0;\n"
        . "    }\n\n"
        . "    return (zend_long) (uintptr_t) phpvk_track(s, sizeof({$name}));\n"
        . "}\n\n"
        . "void {$packIntoSymbol}(zval *ptr, zval *members)\n"
        . "{\n"
        . "    {$name} *s = ({$name} *) phpvk_arg_ptr(ptr);\n"
        . "    {$name} staged;\n\n"
        . "    if (!s) {\n"
        . "        php_error_docref(NULL, E_WARNING, \"{$name}::packInto: ptr is NULL\");\n\n"
        . "        return;\n"
        . "    }\n"
        . "    /* Staged, because a refused fill must not write (spec §7): the\n"
        . "     * caller's memory is only touched once every member was accepted. */\n"
        . "    if (!phpvk_fill_{$name}(&staged, members, \"{$name}\")) {\n"
        . "        return;\n"
        . "    }\n"
        . "    memcpy(s, &staged, sizeof({$name}));\n"
        . "}\n\n"
        . "void {$unpackSymbol}(zval *return_value, zval *ptr)\n"
        . "{\n"
        . "    const {$name} *s = (const {$name} *) phpvk_arg_ptr(ptr);\n\n"
        . "    if (!s) {\n"
        . "        php_error_docref(NULL, E_WARNING, \"{$name}::unpack: ptr is NULL\");\n"
        . "        ZVAL_NULL(return_value);\n\n"
        . "        return;\n"
        . "    }\n"
        . "    phpvk_read_{$name}(return_value, s);\n"
        . "}\n\n"
        . "zend_long {$sizeSymbol}(void)\n"
        . "{\n"
        . "    return (zend_long) sizeof({$name});\n"
        . "}\n\n";

    $decls = "/*@zep Struct\\{$name} pack(array members) -> int */\n"
        . "zend_long {$packSymbol}(zval *members);\n\n"
        . "/*@zep Struct\\{$name} packInto(int ptr, array members) -> void */\n"
        . "void {$packIntoSymbol}(zval *ptr, zval *members);\n\n"
        . "/*@zep Struct\\{$name} unpack(int ptr) -> array */\n"
        . "void {$unpackSymbol}(zval *return_value, zval *ptr);\n\n"
        . "/*@zep Struct\\{$name} size() -> int */\n"
        . "zend_long {$sizeSymbol}(void);\n\n";

    return ['decls' => $decls, 'impl' => $impl, 'internal' => $internal];
}

// ------------------------------------------------------- layout asserts

/**
 * The C compiler this box generates with. The probe below is a
 * generation-box tool, exactly like `php` itself: the Pi never runs the
 * generator, it only compiles what the generator wrote.
 */
function probeCompiler(): string
{
    $cc = getenv('CC');

    return $cc !== false && $cc !== '' ? $cc : 'cc';
}

/**
 * Where the Khronos headers are on the generating box. The same answer
 * ext/config.m4 reaches (scripts/patch-config-m4.php): pkg-config when it
 * knows `vulkan`, Homebrew's prefix otherwise on Darwin.
 *
 * @return list<string>
 */
function probeIncludeFlags(): array
{
    $cflags = trim((string) @shell_exec('pkg-config --cflags vulkan 2>/dev/null'));
    if ($cflags !== '') {
        return array_values(array_filter(preg_split('/\s+/', $cflags) ?: []));
    }
    if (PHP_OS_FAMILY === 'Darwin') {
        return ['-I/opt/homebrew/include'];
    }

    return [];
}

/**
 * Measure `sizeof` and `offsetof` for every scoped struct and member by
 * compiling and running a probe against the real Khronos headers, then emit
 * those numbers as `_Static_assert`s.
 *
 * This is the struct tier's second platform proof. The tier's C bodies use
 * `s->member` and `sizeof(s->m)/sizeof(s->m[0])`, so they are correct by
 * construction on whatever box compiles them — which is exactly why nothing
 * in them would notice if the two boxes disagreed about a layout. The
 * asserts carry the generating box's measurement into every other build:
 * the Pi's arm64 Linux compile either agrees with the Mac's arm64 Darwin
 * measurement or it fails loudly, at compile time, naming the struct.
 *
 * Bit-fields would have no offset to assert; there are none in scope (the
 * registry parser marks them unsupported and renderMember fails by name on
 * one), so every member gets an offset. For an array or a nested struct the
 * member's own offset is asserted, not its elements'.
 *
 * @param list<string> $order struct names, in emission order
 */
function renderLayoutAsserts(array $order, array $types, string $root, string $provenance): string
{
    $platform = "{$root}/src/phpvk-platform.h";
    if (!is_file($platform)) {
        fail("the layout probe needs src/phpvk-platform.h and it is missing");
    }

    $probe = "/* Written and run by scripts/gen-vk-src.php. Not part of the build. */\n"
        . "#include \"phpvk-platform.h\"\n\n"
        . "#include <stddef.h>\n#include <stdio.h>\n\n"
        . "int main(void)\n{\n";
    foreach ($order as $name) {
        $probe .= "    printf(\"S {$name} %zu\\n\", sizeof({$name}));\n";
        foreach ($types[$name]['members'] as $m) {
            $probe .= "    printf(\"M {$name} {$m['name']} %zu\\n\", offsetof({$name}, {$m['name']}));\n";
        }
    }
    $probe .= "\n    return 0;\n}\n";

    $dir = sys_get_temp_dir() . '/phpvk-layout-probe-' . bin2hex(random_bytes(6));
    if (!mkdir($dir, 0755, true)) {
        fail("cannot create the probe scratch directory {$dir}");
    }
    $source = "{$dir}/probe.c";
    $binary = "{$dir}/probe";
    file_put_contents($source, $probe);

    $cc = probeCompiler();
    $cmd = escapeshellarg($cc);
    foreach (array_merge(probeIncludeFlags(), ['-I' . $root . '/src', '-O0', '-o', $binary, $source]) as $arg) {
        $cmd .= ' ' . escapeshellarg($arg);
    }
    $out = [];
    $code = 0;
    exec($cmd . ' 2>&1', $out, $code);
    if ($code !== 0) {
        $text = implode("\n", $out);
        removeProbeDir($dir);
        fail("the layout probe did not compile with '{$cc}' (it is a generation-box tool):\n{$text}");
    }

    $out = [];
    exec(escapeshellarg($binary) . ' 2>&1', $out, $code);
    if ($code !== 0) {
        $text = implode("\n", $out);
        removeProbeDir($dir);
        fail("the layout probe did not run:\n{$text}");
    }
    removeProbeDir($dir);

    $sizes = [];
    $offsets = [];
    foreach ($out as $line) {
        if (preg_match('/^S (\w+) (\d+)$/', $line, $m)) {
            $sizes[$m[1]] = (int) $m[2];
        } elseif (preg_match('/^M (\w+) (\w+) (\d+)$/', $line, $m)) {
            $offsets[$m[1]][$m[2]] = (int) $m[3];
        } else {
            fail("the layout probe printed a line this script cannot read: {$line}");
        }
    }

    $body = '';
    $asserts = 0;
    foreach ($order as $name) {
        if (!isset($sizes[$name])) {
            fail("the layout probe measured no sizeof({$name})");
        }
        $body .= "_Static_assert(sizeof({$name}) == {$sizes[$name]}, \"{$name}\");\n";
        $asserts++;
        foreach ($types[$name]['members'] as $m) {
            $key = $m['name'];
            if (!isset($offsets[$name][$key])) {
                fail("the layout probe measured no offsetof({$name}, {$key})");
            }
            $body .= "_Static_assert(offsetof({$name}, {$key}) == {$offsets[$name][$key]}, \"{$name}.{$key}\");\n";
            $asserts++;
        }
        $body .= "\n";
    }

    return headerBanner(
        'vk-struct-asserts.c — the struct tier\'s layout, measured and re-checked.',
        $provenance
    )
        . "/*\n"
        . " * Layout measured on the generating box by a C probe this file's\n"
        . " * generator compiled and ran against the real Khronos headers; the\n"
        . " * build box must agree. A mismatch is a compile error naming the\n"
        . " * struct, which is the whole point: the generated fill/read bodies\n"
        . " * are written in terms of `s->member` and so would silently adapt to\n"
        . " * a layout the other platform does not share.\n"
        . " *\n"
        . " * {$asserts} assertions: one sizeof per struct or union, one offsetof\n"
        . " * per member. No code, no data, nothing to call.\n"
        . " */\n\n"
        . "#include \"phpvk-platform.h\"\n\n"
        . "#include <stddef.h>\n\n"
        . $body;
}

function removeProbeDir(string $dir): void
{
    foreach (glob("{$dir}/*") ?: [] as $f) {
        @unlink($f);
    }
    @rmdir($dir);
}

// ------------------------------------------------------------------ banners

function headerBanner(string $title, string $provenance): string
{
    return "/*\n"
        . " * {$title}\n"
        . " *\n"
        . " * " . GENERATED_MARK . " — DO NOT EDIT.\n"
        . " * Source of truth: {$provenance}\n"
        . " */\n\n";
}

function guardOpen(string $stem): string
{
    $macro = 'PHPVK_' . strtoupper(str_replace('-', '_', $stem)) . '_H';

    return "#ifndef {$macro}\n#define {$macro}\n\n";
}

// ---------------------------------------------------------------------- main

$root = dirname(__DIR__);
$check = in_array('--check', array_slice($argv, 1), true);

$xmlPath = "{$root}/scripts/khronos/vk.xml";
$reg = vkRegistryLoad($xmlPath);
$scope = vkRegistryScope($reg);
$types = $reg['types'];

$files = [];
$boundRows = [];
$reservedCount = 0;
$boundCount = 0;
$structCount = 0;
$classCounts = [];
$structInternal = '';

$provenance = 'scripts/khronos/vk.xml (see scripts/khronos/README.md)';

// ---- command tier -------------------------------------------------------
foreach (VK_FEATURES as $feature => $class) {
    $bucket = $scope['commands'][$class];
    $stem = 'vk-' . strtolower(substr($class, 2));   // VK10 -> vk-10
    $classPath = "VK\\{$class}";
    $n = count($bucket['names']);
    $classCounts[$classPath] = $n;

    $h = headerBanner("{$stem}.h — Vulkan\\{$classPath} bound 1:1.", "{$provenance}, {$feature} ({$n} commands)")
        . guardOpen($stem)
        . "#include <php.h>\n\n"
        . "/*@audit feature {$classPath} {$feature} {$n} */\n\n";
    $c = headerBanner("{$stem}.c — one call through the Bridge loader per binding.", "{$provenance}, {$feature}")
        . "#include \"{$stem}.h\"\n"
        . "#include \"phpvk-platform.h\"\n"
        . "#include \"phpvk-bridge.h\"\n"
        . "#include \"phpvk-support.h\"\n\n";

    foreach ($bucket['names'] as $name) {
        $command = $reg['commands'][$name];
        $reason = reservationFor($command, $types);
        if ($reason !== null) {
            $h .= renderReserved($classPath, $command, $reason) . "\n\n";
            $reservedCount++;
            continue;
        }
        $level = vkCommandLevel($command, $types);
        $r = renderCommand($classPath, $class, $command, $types, $level);
        $h .= "{$r['annotation']}\n{$r['proto']}\n\n";
        $c .= "{$r['body']}\n";
        $boundRows[] = "    {\"{$name}\", " . levelConstant($level) . '},';
        $boundCount++;
    }

    $h .= "#endif\n";
    $files["src/{$stem}.h"] = $h;
    $files["src/{$stem}.c"] = $c;
}

foreach (VK_EXTENSIONS as $extension => $class) {
    if ($class === null) {
        continue;   // structs only; no command class
    }
    $bucket = $scope['commands'][$class];
    $stem = 'vk-ext-' . strtolower($class);
    $classPath = "Ext\\{$class}";
    $n = count($bucket['names']);
    $classCounts[$classPath] = $n;

    $h = headerBanner("{$stem}.h — Vulkan\\{$classPath} bound 1:1.", "{$provenance}, {$extension} ({$n} commands)")
        . guardOpen($stem)
        . "#include <php.h>\n\n"
        . "/*@audit extension {$classPath} {$extension} {$n} */\n\n";
    $c = headerBanner("{$stem}.c — one call through the Bridge loader per binding.", "{$provenance}, {$extension}")
        . "#include \"{$stem}.h\"\n"
        . "#include \"phpvk-platform.h\"\n"
        . "#include \"phpvk-bridge.h\"\n"
        . "#include \"phpvk-support.h\"\n\n";

    foreach ($bucket['names'] as $name) {
        $command = $reg['commands'][$name];
        $reason = reservationFor($command, $types);
        if ($reason !== null) {
            $h .= renderReserved($classPath, $command, $reason) . "\n\n";
            $reservedCount++;
            continue;
        }
        $level = vkCommandLevel($command, $types);
        $r = renderCommand($classPath, $class, $command, $types, $level);
        $h .= "{$r['annotation']}\n{$r['proto']}\n\n";
        $c .= "{$r['body']}\n";
        $boundRows[] = "    {\"{$name}\", " . levelConstant($level) . '},';
        $boundCount++;
    }

    $h .= "#endif\n";
    $files["src/{$stem}.h"] = $h;
    $files["src/{$stem}.c"] = $c;
}

// ---- struct tier --------------------------------------------------------
/*
 * One file per bucket. A struct belongs to the bucket that first required it
 * — or, for one reached only by value from another struct, to the bucket of
 * the struct that reached it. Cross-file references resolve through
 * vk-struct-internal.h, which declares every fill/read pair.
 */
$structFiles = [];
foreach (VK_FEATURES as $class) {
    $structFiles['vk-struct-' . strtolower(substr($class, 2))] = $scope['structs'][$class]['names'];
}
$extStructNames = [];
foreach (VK_EXTENSIONS as $extension => $class) {
    $key = $class ?? 'EXT:' . $extension;
    $extStructNames = array_merge($extStructNames, $scope['structs'][$key]['names']);
}
$structFiles['vk-struct-ext'] = $extStructNames;

$structOrder = [];

foreach ($structFiles as $stem => $names) {
    $h = headerBanner("{$stem}.h — Vulkan\\Struct\\<Name> flat pack/unpack.", $provenance)
        . guardOpen($stem)
        . "#include <php.h>\n\n";
    $c = headerBanner("{$stem}.c — one fill/read pair per struct; no Vulkan call is made here.", $provenance)
        . "#include \"{$stem}.h\"\n"
        . "#include \"vk-struct-internal.h\"\n"
        . "#include \"phpvk-platform.h\"\n"
        . "#include \"phpvk-bridge.h\"\n"
        . "#include \"phpvk-support.h\"\n\n"
        . "#include <string.h>\n#include <stdlib.h>\n\n";

    foreach ($names as $name) {
        $r = renderStruct($name, $types);
        $h .= $r['decls'];
        $c .= $r['impl'];
        $structInternal .= $r['internal'];
        $structOrder[] = $name;
        $structCount++;
    }

    $h .= "#endif\n";
    $files["src/{$stem}.h"] = $h;
    $files["src/{$stem}.c"] = $c;
}

$files['src/vk-struct-asserts.c'] = renderLayoutAsserts($structOrder, $types, $root, $provenance);

$files['src/vk-struct-internal.h'] = headerBanner(
    'vk-struct-internal.h — the struct tier\'s internal fill/read pairs.',
    $provenance
) . "/*\n"
    . " * These are not bindings: they carry no binding annotation and are\n"
    . " * not reachable from PHP. They exist so a struct in one generated file\n"
    . " * can be nested by value inside a struct in another. The parity guard\n"
    . " * and gen-zep both list this header as non-binding for that reason.\n"
    . " */\n\n"
    . guardOpen('vk-struct-internal')
    . "#include <php.h>\n#include \"phpvk-platform.h\"\n\n"
    . $structInternal
    . "\n#endif\n";

// ---- registry -----------------------------------------------------------
$files['src/phpvk-registry.h'] = headerBanner(
    'phpvk-registry.h — every bound command and the loader level it resolves at.',
    $provenance
) . guardOpen('phpvk-registry')
    . "typedef struct {\n    const char *name;\n    int level;\n} phpvk_entry_row;\n\n"
    . "extern const phpvk_entry_row phpvk_entry_table[];\n"
    . "extern const int phpvk_entry_table_size;\n\n"
    . "/* The level a name resolves at; PHPVK_LEVEL_GLOBAL for an unknown name. */\n"
    . "int phpvk_registry_level(const char *name);\n\n"
    . "#endif\n";

$files['src/phpvk-registry.c'] = headerBanner(
    'phpvk-registry.c — the level table Bridge::isAvailable and Bridge::procAddress read.',
    $provenance
) . "#include \"phpvk-registry.h\"\n#include \"phpvk-bridge.h\"\n\n#include <string.h>\n\n"
    . "const phpvk_entry_row phpvk_entry_table[] = {\n"
    . implode("\n", $boundRows) . "\n};\n\n"
    . "const int phpvk_entry_table_size =\n"
    . "    (int) (sizeof(phpvk_entry_table) / sizeof(phpvk_entry_table[0]));\n\n"
    . "int phpvk_registry_level(const char *name)\n"
    . "{\n"
    . "    int i;\n\n"
    . "    if (!name) {\n        return PHPVK_LEVEL_GLOBAL;\n    }\n"
    . "    for (i = 0; i < phpvk_entry_table_size; i++) {\n"
    . "        if (strcmp(phpvk_entry_table[i].name, name) == 0) {\n"
    . "            return phpvk_entry_table[i].level;\n"
    . "        }\n"
    . "    }\n\n"
    . "    return PHPVK_LEVEL_GLOBAL;\n"
    . "}\n";

// ---- config.json extra-sources ------------------------------------------
$configPath = "{$root}/config.json";
$config = json_decode((string) file_get_contents($configPath), true);
if (!is_array($config)) {
    fail('config.json is not valid JSON');
}
$sources = ['src/phpvk-support.c', 'src/phpvk-bridge.c'];
foreach (array_keys($files) as $rel) {
    if (str_ends_with($rel, '.c')) {
        $sources[] = $rel;
    }
}
sort($sources);
$config['extra-sources'] = array_values(array_unique($sources));
$files['config.json'] = json_encode($config, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";

// ---- write / check ------------------------------------------------------
$written = 0;
$diffs = [];
foreach ($files as $rel => $contents) {
    $path = "{$root}/{$rel}";
    $existing = is_file($path) ? file_get_contents($path) : null;
    if ($existing === $contents) {
        continue;
    }
    if ($check) {
        $diffs[] = $rel;
        continue;
    }
    if (!is_dir(dirname($path))) {
        mkdir(dirname($path), 0755, true);
    }
    file_put_contents($path, $contents);
    $written++;
}

/* Prune generated files this run no longer produces. */
$pruned = [];
foreach (glob("{$root}/src/vk-*.[ch]") ?: [] as $path) {
    $rel = 'src/' . basename($path);
    if (isset($files[$rel])) {
        continue;
    }
    $head = (string) file_get_contents($path, false, null, 0, 400);
    if (!str_contains($head, GENERATED_MARK)) {
        continue;
    }
    if ($check) {
        $diffs[] = $rel . ' (stale)';
        continue;
    }
    unlink($path);
    $pruned[] = $rel;
}

printf("%-26s %10s %9s\n", 'class', 'commands', 'structs');
foreach (VK_FEATURES as $feature => $class) {
    printf(
        "%-26s %10d %9d\n",
        "VK\\{$class}",
        count($scope['commands'][$class]['names']),
        count($scope['structs'][$class]['names'])
    );
}
foreach (VK_EXTENSIONS as $extension => $class) {
    $key = $class ?? 'EXT:' . $extension;
    printf(
        "%-26s %10d %9d\n",
        $class !== null ? "Ext\\{$class}" : "({$extension})",
        count($scope['commands'][$key]['names']),
        count($scope['structs'][$key]['names'])
    );
}

echo 'files=' . count($files) . " written={$written} pruned=" . count($pruned)
    . " commands=" . ($boundCount + $reservedCount)
    . " bound={$boundCount} reserved={$reservedCount} structs={$structCount}\n";

if ($check) {
    if ($diffs !== []) {
        foreach ($diffs as $d) {
            fwrite(STDERR, "gen-vk-src: {$d} differs from what the registry produces\n");
        }
        fwrite(STDERR, 'GEN_SRC_DRIFT (' . count($diffs) . ")\n");
        exit(1);
    }
    echo "GEN_SRC_CLEAN\n";
    exit(0);
}

echo "GEN_SRC_OK\n";
