#!/usr/bin/env php
<?php
/**
 * gen-zep.php — generate every .zep file and every Zephir optimizer from the
 * @zep / @zep-construct / @reserved annotations in src/*.h. The annotations
 * are the single source of truth; nothing under vulkan/ or optimizers/ is
 * hand-written.
 *
 * Almost every annotation it reads was itself written by
 * scripts/gen-vk-src.php out of the vendored Khronos headers; the Bridge's
 * are the only hand-written ones.
 *
 * Annotation grammar (one line, immediately above its C prototype):
 *
 *   /*@zep VK\VK10 vkDestroyInstance(int instance, int pAllocator) -> void * /
 *   void phpvk_vk10_vkdestroyinstance(zval *instance, zval *pAllocator);
 *
 *   /*@zep Struct\VkApplicationInfo size() -> int * /
 *   zend_long phpvk_struct_vkapplicationinfo_size(void);
 *
 *   /*@reserved VK\VK10 void vkFoo(PFN_vkVoidFunction cb) — callback * /
 *
 * Class path -> PHP class:
 *   VK\VK10                 -> namespace Vulkan\VK\VK10, class VK10
 *                             (file vulkan/vk/vk10/vk10.zep)
 *   Ext\KHRSurface          -> namespace Vulkan\Ext\KHRSurface, class KHRSurface
 *                             (file vulkan/ext/khrsurface/khrsurface.zep)
 *   Struct\VkApplicationInfo -> namespace Vulkan\Struct\VkApplicationInfo,
 *                             class VkApplicationInfo
 *                             (file vulkan/struct/vkapplicationinfo/vkapplicationinfo.zep)
 *   Bridge\Bridge           -> namespace Vulkan\Bridge, class Bridge (the
 *                             duplicate tail collapses; file vulkan/bridge/bridge.zep)
 *
 * Return shapes:
 *   int / bool → C returns zend_long, optimizer emits a CompiledExpression
 *                (bool is unwrapped in the .zep as `return r == 1;`)
 *   double     → C returns double, CompiledExpression
 *   void       → C returns void, optimizer prints a statement
 *   string / array / var → C returns void with a leading `zval *return_value`,
 *                optimizer writes into the call's symbol variable
 *
 * The generator cross-checks every annotation against its C prototype (return
 * shape and arity) and exits non-zero on any drift.
 */

declare(strict_types=1);

const GENERATED_MARK = 'GENERATED by scripts/gen-zep.php';

/** Zephir reserved words: method or parameter names matching these get a trailing underscore. */
const ZEP_RESERVED = [
    'abstract', 'array', 'as', 'bool', 'boolean', 'break', 'callable', 'case',
    'catch', 'char', 'class', 'const', 'continue', 'default', 'deprecated',
    'do', 'double', 'echo', 'else', 'elseif', 'empty', 'extends', 'false',
    'fetch', 'final', 'finally', 'float', 'for', 'function', 'if',
    'implements', 'in', 'inline', 'instanceof', 'int', 'integer', 'interface',
    'internal', 'isset', 'let', 'likely', 'list', 'long', 'loop', 'namespace',
    'new', 'null', 'object', 'print', 'private', 'protected', 'public',
    'require', 'resource', 'return', 'reverse', 'scoped', 'static', 'string',
    'switch', 'this', 'throw', 'true', 'try', 'typeof', 'uchar', 'uint',
    'ulong', 'unlikely', 'unset', 'use', 'var', 'void', 'while',
];

const PARAM_TYPES = ['int', 'double', 'bool', 'string', 'var', 'array'];
const RETURN_TYPES = ['int', 'double', 'bool', 'string', 'var', 'array', 'void'];

function fail(string $msg): never
{
    fwrite(STDERR, "gen-zep: {$msg}\n");
    exit(1);
}

function escapeReserved(string $name): string
{
    if (in_array(strtolower($name), ZEP_RESERVED, true)) {
        return $name . '_';
    }

    // Zephir lexes an all-caps identifier as a constant token, so it cannot sit
    // in a method or parameter position. PHP resolves method names
    // case-insensitively, so an all-caps original still reaches the emitted name.
    if (preg_match('/^[A-Z][A-Z0-9_]*$/', $name)) {
        $lower = strtolower($name);

        return strlen($lower) > 1 ? ucfirst($lower) : $lower;
    }

    return $name;
}

function studly(string $snake): string
{
    return str_replace(' ', '', ucwords(str_replace('_', ' ', $snake)));
}

/**
 * @return array{namespace: string, class: string, zepPath: string}
 */
function resolveClassPath(string $annotationPath): array
{
    $segments = explode('\\', $annotationPath);
    if (count($segments) < 2) {
        fail("class path '{$annotationPath}' must have at least two segments");
    }
    $class = end($segments);
    // Duplicate tail collapses: Bridge\Bridge → namespace Vulkan\Bridge.
    $nsSegments = $segments;
    if (count($segments) >= 2 && $segments[count($segments) - 1] === $segments[count($segments) - 2]) {
        array_pop($nsSegments);
    }
    $namespace = 'Vulkan\\' . implode('\\', $nsSegments);
    $dir = implode('/', array_map('strtolower', $nsSegments));
    $zepPath = 'vulkan/' . $dir . '/' . strtolower($class) . '.zep';

    return ['namespace' => $namespace, 'class' => $class, 'zepPath' => $zepPath];
}

/**
 * Parse one header file into bound methods and reserved lines.
 *
 * @return array{methods: list<array<string, mixed>>, reserved: list<array{classPath: string, text: string}>}
 */
function parseHeader(string $path): array
{
    $lines = file($path, FILE_IGNORE_NEW_LINES);
    if ($lines === false) {
        fail("cannot read {$path}");
    }

    $headerRef = 'src/' . pathinfo($path, PATHINFO_FILENAME);
    $methods = [];
    $reserved = [];
    $total = count($lines);

    for ($i = 0; $i < $total; $i++) {
        $line = $lines[$i];

        if (preg_match('#/\*\s*@reserved\s+([A-Za-z0-9_\\\\]+)\s+(.*?)\s*\*/#', $line, $m)) {
            $reserved[] = ['classPath' => $m[1], 'text' => $m[2]];
            continue;
        }

        if (!preg_match('#/\*\s*@zep(?:-construct)?\s+([A-Za-z0-9_\\\\]+)\s+(\w+)\s*\(([^)]*)\)\s*->\s*(\w+)\s*\*/#', $line, $m)) {
            if (str_contains($line, '@zep')) {
                fail("{$path}:" . ($i + 1) . " malformed @zep annotation: {$line}");
            }
            continue;
        }

        [, $classPath, $method, $paramSrc, $returnType] = $m;

        if (!in_array($returnType, RETURN_TYPES, true)) {
            fail("{$path}:" . ($i + 1) . " unknown return type '{$returnType}'");
        }

        $params = [];
        if (trim($paramSrc) !== '') {
            foreach (explode(',', $paramSrc) as $p) {
                $parts = preg_split('/\s+/', trim($p));
                if (count($parts) !== 2 || !in_array($parts[0], PARAM_TYPES, true)) {
                    fail("{$path}:" . ($i + 1) . " bad parameter '" . trim($p) . "' (expected '<type> <name>')");
                }
                $params[] = ['type' => $parts[0], 'name' => escapeReserved($parts[1])];
            }
        }

        // The C prototype must be the next non-empty line.
        $proto = null;
        for ($j = $i + 1; $j < $total; $j++) {
            if (trim($lines[$j]) !== '') {
                $proto = $lines[$j];
                $i = $j;
                break;
            }
        }
        if ($proto === null || !preg_match('/^\s*(zend_long|double|void)\s+(phpvk_[a-z0-9_]+)\s*\(([^)]*)\)\s*;/', $proto, $pm)) {
            fail("{$path}: @zep for '{$method}' is not followed by a parseable C prototype (line " . ($i + 1) . ')');
        }
        [, $cReturn, $symbol, $cParamSrc] = $pm;

        $cParams = trim($cParamSrc) === '' || trim($cParamSrc) === 'void'
            ? []
            : array_map('trim', explode(',', $cParamSrc));
        $hasReturnValueArg = $cParams !== [] && str_contains($cParams[0], 'return_value');
        $cArity = count($cParams) - ($hasReturnValueArg ? 1 : 0);

        // Cross-check the annotation against the prototype.
        $expectedCReturn = match ($returnType) {
            'int', 'bool' => 'zend_long',
            'double' => 'double',
            default => 'void',
        };
        if ($cReturn !== $expectedCReturn) {
            fail("{$symbol}: @zep return '{$returnType}' expects C '{$expectedCReturn}', found '{$cReturn}'");
        }
        $needsSymbolWrite = in_array($returnType, ['string', 'array', 'var'], true);
        if ($needsSymbolWrite !== $hasReturnValueArg) {
            fail("{$symbol}: @zep return '{$returnType}' " . ($needsSymbolWrite
                ? 'requires a leading zval *return_value parameter'
                : 'must not take a return_value parameter'));
        }
        if ($cArity !== count($params)) {
            fail("{$symbol}: @zep declares " . count($params) . " parameter(s), C prototype has {$cArity}");
        }

        $methods[] = [
            'classPath' => $classPath,
            'method' => escapeReserved($method),
            'params' => $params,
            'returnType' => $returnType,
            'symbol' => $symbol,
            'bareCall' => preg_replace('/^phpvk_/', '', $symbol),
            'header' => $headerRef,
        ];
    }

    return ['methods' => $methods, 'reserved' => $reserved];
}

function renderZepMethod(array $m): string
{
    $sig = implode(', ', array_map(
        static fn (array $p): string => "{$p['type']} {$p['name']}",
        $m['params']
    ));
    $args = implode(', ', array_column($m['params'], 'name'));
    $call = "{$m['bareCall']}({$args})";

    $body = match ($m['returnType']) {
        'int', 'double' => "        return {$call};",
        'bool' => "        int r;\n\n        let r = {$call};\n\n        return r == 1;",
        'void' => "        {$call};",
        default => "        var result;\n\n        let result = {$call};\n\n        return result;",
    };

    return "    public static function {$m['method']}({$sig}) -> {$m['returnType']}\n"
        . "    {\n{$body}\n    }";
}

function renderZepClass(array $info, array $methods, array $reserved): string
{
    $out = "// " . GENERATED_MARK . " — DO NOT EDIT.\n";
    $out .= "// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.\n\n";
    $out .= "namespace {$info['namespace']};\n\n";
    $out .= "class {$info['class']}\n{\n";
    $out .= implode("\n\n", array_map('renderZepMethod', $methods));
    if ($reserved !== []) {
        $out .= "\n\n    // ---- @reserved (not bound; see src/*.h) ----\n";
        foreach ($reserved as $r) {
            $out .= "    // @reserved {$r['text']}\n";
        }
    }
    $out .= "\n}\n";

    return $out;
}

function renderOptimizer(array $m): string
{
    $optimizerClass = studly($m['bareCall']) . 'Optimizer';
    $arity = count($m['params']);
    $arityWord = $arity === 0 ? 'zero parameters' : ($arity === 1 ? 'exactly one parameter' : "exactly {$arity} parameters");

    $arityCheck = $arity === 0
        ? "        if (isset(\$expression['parameters']) && count(\$expression['parameters']) !== 0) {\n"
        . "            throw new CompilerException(\"'{$m['bareCall']}' requires {$arityWord}\", \$expression);\n"
        . "        }\n"
        : "        if (!isset(\$expression['parameters']) || count(\$expression['parameters']) !== {$arity}) {\n"
        . "            throw new CompilerException(\"'{$m['bareCall']}' requires {$arityWord}\", \$expression);\n"
        . "        }\n";

    $resolve = $arity > 0
        ? "        \$resolvedParams = \$call->getReadOnlyResolvedParams(\$expression['parameters'], \$context, \$expression);\n"
        : '';
    $argList = $arity > 0
        ? implode(" . ', ' . ", array_map(static fn (int $i): string => "\$resolvedParams[{$i}]", range(0, $arity - 1)))
        : '';

    $body = match ($m['returnType']) {
        'int', 'bool' => $resolve
            . "\n        return new CompiledExpression(\n"
            . "            'int',\n"
            . "            '{$m['symbol']}(' . " . ($argList !== '' ? $argList . " . " : '') . "')',\n"
            . "            \$expression\n"
            . "        );",
        'double' => $resolve
            . "\n        return new CompiledExpression(\n"
            . "            'double',\n"
            . "            '{$m['symbol']}(' . " . ($argList !== '' ? $argList . " . " : '') . "')',\n"
            . "            \$expression\n"
            . "        );",
        'void' => $resolve
            . "\n        \$context->codePrinter->output('{$m['symbol']}(' . " . ($argList !== '' ? $argList . " . " : '') . "');');\n"
            . "\n        return new CompiledExpression('null', 'null', \$expression);",
        default => renderSymbolWriteBody($m, $resolve, $argList),
    };

    return "<?php\n\n"
        . "/* " . GENERATED_MARK . " — DO NOT EDIT. */\n\n"
        . "namespace Zephir\\Optimizers\\FunctionCall;\n\n"
        . "use Zephir\\Call;\n"
        . "use Zephir\\CompilationContext;\n"
        . "use Zephir\\CompiledExpression;\n"
        . "use Zephir\\Exception\\CompilerException;\n"
        . "use Zephir\\Optimizers\\OptimizerAbstract;\n\n"
        . "class {$optimizerClass} extends OptimizerAbstract\n"
        . "{\n"
        . "    public function optimize(array \$expression, Call \$call, CompilationContext \$context)\n"
        . "    {\n"
        . $arityCheck
        . "\n        \$context->headersManager->add('{$m['header']}');\n\n"
        . $body . "\n"
        . "    }\n"
        . "}\n";
}

function renderSymbolWriteBody(array $m, string $resolve, string $argList): string
{
    $dynamicType = match ($m['returnType']) {
        'string' => 'string',
        'array' => 'array',
        default => 'undefined',
    };
    $kernelString = $m['returnType'] === 'string'
        ? "        \$context->headersManager->add('kernel/string');\n"
        : '';
    $callArgs = $argList !== '' ? "\$symbol . ', ' . {$argList}" : '$symbol';

    return "        \$call->processExpectedReturn(\$context);\n\n"
        . "        \$symbolVariable = \$call->getSymbolVariable(true, \$context);\n"
        . "        \$this->checkNotVariableString(\$symbolVariable, \$expression);\n\n"
        . $kernelString
        . "        \$symbolVariable->setDynamicTypes('{$dynamicType}');\n\n"
        . "        \$this->checkInitSymbolVariable(\$call, \$symbolVariable, \$context);\n\n"
        . "        \$symbol = \$context->backend->getVariableCode(\$symbolVariable);\n\n"
        . $resolve
        . "\n        \$context->codePrinter->output('{$m['symbol']}(' . {$callArgs} . ');');\n"
        . "\n        return new CompiledExpression('variable', \$symbolVariable->getRealName(), \$expression);";
}

function writeFileEnsuringDir(string $path, string $contents): bool
{
    $dir = dirname($path);
    if (!is_dir($dir) && !mkdir($dir, 0755, true)) {
        fail("cannot create directory {$dir}");
    }
    $existing = is_file($path) ? file_get_contents($path) : null;
    if ($existing === $contents) {
        return false;
    }
    if (file_put_contents($path, $contents) === false) {
        fail("cannot write {$path}");
    }

    return true;
}

/** Remove previously generated files that this run no longer produces. */
function pruneStale(string $root, array $keptPaths): array
{
    $pruned = [];
    $candidates = array_merge(
        glob("{$root}/vulkan/*/*.zep") ?: [],
        glob("{$root}/vulkan/*/*/*.zep") ?: [],
        glob("{$root}/optimizers/*Optimizer.php") ?: [],
    );
    foreach ($candidates as $file) {
        $relative = substr($file, strlen($root) + 1);
        if (isset($keptPaths[$relative])) {
            continue;
        }
        $head = (string) file_get_contents($file, false, null, 0, 256);
        if (str_contains($head, GENERATED_MARK)) {
            unlink($file);
            $pruned[] = $relative;
        }
    }

    return $pruned;
}

// ---- main ----

// Optional root override (used by the drift-guard self-test); defaults to the package root.
$root = isset($argv[1]) ? rtrim($argv[1], '/') : dirname(__DIR__);
if (!is_dir($root)) {
    fail("root '{$root}' is not a directory");
}
$headers = glob("{$root}/src/*.h") ?: [];
if ($headers === []) {
    fail("no headers found in {$root}/src");
}

$allMethods = [];
$allReserved = [];
foreach ($headers as $header) {
    $parsed = parseHeader($header);
    $allMethods = array_merge($allMethods, $parsed['methods']);
    $allReserved = array_merge($allReserved, $parsed['reserved']);
}

if ($allMethods === []) {
    fail('no @zep annotations found in any header');
}

// Duplicate symbol / duplicate method guard.
$seenSymbols = [];
$seenMethods = [];
foreach ($allMethods as $m) {
    if (isset($seenSymbols[$m['symbol']])) {
        fail("duplicate C symbol '{$m['symbol']}'");
    }
    $seenSymbols[$m['symbol']] = true;
    $methodKey = $m['classPath'] . '::' . $m['method'];
    if (isset($seenMethods[$methodKey])) {
        fail("duplicate method '{$methodKey}'");
    }
    $seenMethods[$methodKey] = true;
}

// Group by class, preserving header order.
$byClass = [];
foreach ($allMethods as $m) {
    $byClass[$m['classPath']]['methods'][] = $m;
}
foreach ($allReserved as $r) {
    $byClass[$r['classPath']]['reserved'][] = $r;
}

$written = [];
$kept = [];
$classCount = 0;
$optimizerCount = 0;

foreach ($byClass as $classPath => $group) {
    $methods = $group['methods'] ?? [];
    $reserved = $group['reserved'] ?? [];
    if ($methods === [] && $reserved !== []) {
        fail("class '{$classPath}' has only @reserved lines and no @zep methods; nothing to generate a class from");
    }
    $info = resolveClassPath($classPath);
    $zep = renderZepClass($info, $methods, $reserved);
    if (writeFileEnsuringDir("{$root}/{$info['zepPath']}", $zep)) {
        $written[] = $info['zepPath'];
    }
    $kept[$info['zepPath']] = true;
    $classCount++;

    foreach ($methods as $m) {
        $optimizerPath = 'optimizers/' . studly($m['bareCall']) . 'Optimizer.php';
        if (writeFileEnsuringDir("{$root}/{$optimizerPath}", renderOptimizer($m))) {
            $written[] = $optimizerPath;
        }
        $kept[$optimizerPath] = true;
        $optimizerCount++;
    }
}

$pruned = pruneStale($root, $kept);

foreach ($byClass as $classPath => $group) {
    $bound = count($group['methods'] ?? []);
    $res = count($group['reserved'] ?? []);
    echo sprintf("%-40s bound=%-4d reserved=%-4d\n", $classPath, $bound, $res);
}
echo "\nclasses={$classCount} methods=" . count($allMethods) . " optimizers={$optimizerCount}"
    . ' written=' . count($written) . ' pruned=' . count($pruned) . "\n";
foreach ($pruned as $p) {
    echo "pruned: {$p}\n";
}
echo "GEN_OK\n";
