
extern zend_class_entry *vulkan_struct_vkpipelineinputassemblystatecreateinfo_vkpipelineinputassemblystatecreateinfo_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkPipelineInputAssemblyStateCreateInfo_VkPipelineInputAssemblyStateCreateInfo);

PHP_METHOD(Vulkan_Struct_VkPipelineInputAssemblyStateCreateInfo_VkPipelineInputAssemblyStateCreateInfo, pack);
PHP_METHOD(Vulkan_Struct_VkPipelineInputAssemblyStateCreateInfo_VkPipelineInputAssemblyStateCreateInfo, packInto);
PHP_METHOD(Vulkan_Struct_VkPipelineInputAssemblyStateCreateInfo_VkPipelineInputAssemblyStateCreateInfo, unpack);
PHP_METHOD(Vulkan_Struct_VkPipelineInputAssemblyStateCreateInfo_VkPipelineInputAssemblyStateCreateInfo, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkpipelineinputassemblystatecreateinfo_vkpipelineinputassemblystatecreateinfo_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkpipelineinputassemblystatecreateinfo_vkpipelineinputassemblystatecreateinfo_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkpipelineinputassemblystatecreateinfo_vkpipelineinputassemblystatecreateinfo_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkpipelineinputassemblystatecreateinfo_vkpipelineinputassemblystatecreateinfo_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkpipelineinputassemblystatecreateinfo_vkpipelineinputassemblystatecreateinfo_method_entry) {
	PHP_ME(Vulkan_Struct_VkPipelineInputAssemblyStateCreateInfo_VkPipelineInputAssemblyStateCreateInfo, pack, arginfo_vulkan_struct_vkpipelineinputassemblystatecreateinfo_vkpipelineinputassemblystatecreateinfo_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPipelineInputAssemblyStateCreateInfo_VkPipelineInputAssemblyStateCreateInfo, packInto, arginfo_vulkan_struct_vkpipelineinputassemblystatecreateinfo_vkpipelineinputassemblystatecreateinfo_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPipelineInputAssemblyStateCreateInfo_VkPipelineInputAssemblyStateCreateInfo, unpack, arginfo_vulkan_struct_vkpipelineinputassemblystatecreateinfo_vkpipelineinputassemblystatecreateinfo_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkPipelineInputAssemblyStateCreateInfo_VkPipelineInputAssemblyStateCreateInfo, size, arginfo_vulkan_struct_vkpipelineinputassemblystatecreateinfo_vkpipelineinputassemblystatecreateinfo_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
