// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Vulkan\Struct\VkDeviceQueueInfo2;

class VkDeviceQueueInfo2
{
    public static function pack(array members) -> int
    {
        return struct_vkdevicequeueinfo2_pack(members);
    }

    public static function packInto(int ptr, array members) -> void
    {
        struct_vkdevicequeueinfo2_packinto(ptr, members);
    }

    public static function unpack(int ptr) -> array
    {
        var result;

        let result = struct_vkdevicequeueinfo2_unpack(ptr);

        return result;
    }

    public static function size() -> int
    {
        return struct_vkdevicequeueinfo2_size();
    }
}
