
extern zend_class_entry *vulkan_struct_vkimportmetaliosurfaceinfoext_vkimportmetaliosurfaceinfoext_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkImportMetalIOSurfaceInfoEXT_VkImportMetalIOSurfaceInfoEXT);

PHP_METHOD(Vulkan_Struct_VkImportMetalIOSurfaceInfoEXT_VkImportMetalIOSurfaceInfoEXT, pack);
PHP_METHOD(Vulkan_Struct_VkImportMetalIOSurfaceInfoEXT_VkImportMetalIOSurfaceInfoEXT, packInto);
PHP_METHOD(Vulkan_Struct_VkImportMetalIOSurfaceInfoEXT_VkImportMetalIOSurfaceInfoEXT, unpack);
PHP_METHOD(Vulkan_Struct_VkImportMetalIOSurfaceInfoEXT_VkImportMetalIOSurfaceInfoEXT, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkimportmetaliosurfaceinfoext_vkimportmetaliosurfaceinfoext_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkimportmetaliosurfaceinfoext_vkimportmetaliosurfaceinfoext_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkimportmetaliosurfaceinfoext_vkimportmetaliosurfaceinfoext_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkimportmetaliosurfaceinfoext_vkimportmetaliosurfaceinfoext_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkimportmetaliosurfaceinfoext_vkimportmetaliosurfaceinfoext_method_entry) {
	PHP_ME(Vulkan_Struct_VkImportMetalIOSurfaceInfoEXT_VkImportMetalIOSurfaceInfoEXT, pack, arginfo_vulkan_struct_vkimportmetaliosurfaceinfoext_vkimportmetaliosurfaceinfoext_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkImportMetalIOSurfaceInfoEXT_VkImportMetalIOSurfaceInfoEXT, packInto, arginfo_vulkan_struct_vkimportmetaliosurfaceinfoext_vkimportmetaliosurfaceinfoext_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkImportMetalIOSurfaceInfoEXT_VkImportMetalIOSurfaceInfoEXT, unpack, arginfo_vulkan_struct_vkimportmetaliosurfaceinfoext_vkimportmetaliosurfaceinfoext_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkImportMetalIOSurfaceInfoEXT_VkImportMetalIOSurfaceInfoEXT, size, arginfo_vulkan_struct_vkimportmetaliosurfaceinfoext_vkimportmetaliosurfaceinfoext_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
