#ifndef VULKAN_STRUCTS_H
#define VULKAN_STRUCTS_H

#include "runtime.h"

typedef bool (*vulkan_from_fn)(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
typedef void (*vulkan_to_fn)(const void *raw, zval *rv);

extern zend_class_entry *vulkan_ce_VkApplicationInfo;
extern zend_class_entry *vulkan_ce_VkInstanceCreateInfo;
extern zend_class_entry *vulkan_ce_VkDeviceQueueCreateInfo;
extern zend_class_entry *vulkan_ce_VkPhysicalDeviceFeatures;
extern zend_class_entry *vulkan_ce_VkPhysicalDeviceFeatures2;
extern zend_class_entry *vulkan_ce_VkPhysicalDevicePortabilitySubsetFeaturesKHR;
extern zend_class_entry *vulkan_ce_VkDeviceCreateInfo;
extern zend_class_entry *vulkan_ce_VkPhysicalDeviceLimits;
extern zend_class_entry *vulkan_ce_VkPhysicalDeviceSparseProperties;
extern zend_class_entry *vulkan_ce_VkPhysicalDeviceProperties;
extern zend_class_entry *vulkan_ce_VkExtent3D;
extern zend_class_entry *vulkan_ce_VkQueueFamilyProperties;
extern zend_class_entry *vulkan_ce_VkMemoryType;
extern zend_class_entry *vulkan_ce_VkMemoryHeap;
extern zend_class_entry *vulkan_ce_VkPhysicalDeviceMemoryProperties;
extern zend_class_entry *vulkan_ce_VkFormatProperties;
extern zend_class_entry *vulkan_ce_VkExtensionProperties;
extern zend_class_entry *vulkan_ce_VkInstance;
extern zend_class_entry *vulkan_ce_VkPhysicalDevice;
extern zend_class_entry *vulkan_ce_VkDevice;
extern zend_class_entry *vulkan_ce_VkQueue;

bool vulkan_pnext(zend_object *obj, const void **out, vulkan_scratch *scratch, HashTable *visited);

bool vk_VkApplicationInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkApplicationInfo_to(const void *raw, zval *rv);
bool vk_VkInstanceCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkInstanceCreateInfo_to(const void *raw, zval *rv);
bool vk_VkDeviceQueueCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkDeviceQueueCreateInfo_to(const void *raw, zval *rv);
bool vk_VkPhysicalDeviceFeatures_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPhysicalDeviceFeatures_to(const void *raw, zval *rv);
bool vk_VkPhysicalDeviceFeatures2_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPhysicalDeviceFeatures2_to(const void *raw, zval *rv);
bool vk_VkPhysicalDevicePortabilitySubsetFeaturesKHR_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPhysicalDevicePortabilitySubsetFeaturesKHR_to(const void *raw, zval *rv);
/* Writes an output pNext chain back onto the objects that produced it, leaving each pNext link as the caller set it. */
void vulkan_store_pnext_chain(zend_object *obj, const void *raw);
bool vk_VkDeviceCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkDeviceCreateInfo_to(const void *raw, zval *rv);
bool vk_VkPhysicalDeviceLimits_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPhysicalDeviceLimits_to(const void *raw, zval *rv);
bool vk_VkPhysicalDeviceSparseProperties_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPhysicalDeviceSparseProperties_to(const void *raw, zval *rv);
bool vk_VkPhysicalDeviceProperties_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPhysicalDeviceProperties_to(const void *raw, zval *rv);
bool vk_VkExtent3D_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkExtent3D_to(const void *raw, zval *rv);
bool vk_VkQueueFamilyProperties_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkQueueFamilyProperties_to(const void *raw, zval *rv);
bool vk_VkMemoryType_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkMemoryType_to(const void *raw, zval *rv);
bool vk_VkMemoryHeap_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkMemoryHeap_to(const void *raw, zval *rv);
bool vk_VkPhysicalDeviceMemoryProperties_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPhysicalDeviceMemoryProperties_to(const void *raw, zval *rv);
bool vk_VkFormatProperties_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkFormatProperties_to(const void *raw, zval *rv);
bool vk_VkExtensionProperties_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkExtensionProperties_to(const void *raw, zval *rv);
bool vk_VkMemoryAllocateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkMemoryAllocateInfo_to(const void *raw, zval *rv);
bool vk_VkMappedMemoryRange_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkMappedMemoryRange_to(const void *raw, zval *rv);
bool vk_VkBufferCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkBufferCreateInfo_to(const void *raw, zval *rv);
bool vk_VkMemoryRequirements_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkMemoryRequirements_to(const void *raw, zval *rv);
bool vk_VkImageCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkImageCreateInfo_to(const void *raw, zval *rv);
bool vk_VkComponentMapping_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkComponentMapping_to(const void *raw, zval *rv);
bool vk_VkImageSubresourceRange_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkImageSubresourceRange_to(const void *raw, zval *rv);
bool vk_VkImageViewCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkImageViewCreateInfo_to(const void *raw, zval *rv);
bool vk_VkSamplerCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkSamplerCreateInfo_to(const void *raw, zval *rv);

extern zend_class_entry *vulkan_ce_VkMemoryAllocateInfo;
extern zend_class_entry *vulkan_ce_VkMappedMemoryRange;
extern zend_class_entry *vulkan_ce_VkBufferCreateInfo;
extern zend_class_entry *vulkan_ce_VkMemoryRequirements;
extern zend_class_entry *vulkan_ce_VkImageCreateInfo;
extern zend_class_entry *vulkan_ce_VkComponentMapping;
extern zend_class_entry *vulkan_ce_VkImageSubresourceRange;
extern zend_class_entry *vulkan_ce_VkImageViewCreateInfo;
extern zend_class_entry *vulkan_ce_VkSamplerCreateInfo;
extern zend_class_entry *vulkan_ce_VkDeviceMemory;
extern zend_class_entry *vulkan_ce_VkBuffer;
extern zend_class_entry *vulkan_ce_VkImage;
extern zend_class_entry *vulkan_ce_VkImageView;
extern zend_class_entry *vulkan_ce_VkSampler;

bool vk_VkAttachmentDescription_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkAttachmentDescription_to(const void *raw, zval *rv);
bool vk_VkAttachmentReference_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkAttachmentReference_to(const void *raw, zval *rv);
bool vk_VkSubpassDescription_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkSubpassDescription_to(const void *raw, zval *rv);
bool vk_VkSubpassDependency_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkSubpassDependency_to(const void *raw, zval *rv);
bool vk_VkRenderPassCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkRenderPassCreateInfo_to(const void *raw, zval *rv);
bool vk_VkFramebufferCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkFramebufferCreateInfo_to(const void *raw, zval *rv);
bool vk_VkShaderModuleCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkShaderModuleCreateInfo_to(const void *raw, zval *rv);
bool vk_VkPushConstantRange_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPushConstantRange_to(const void *raw, zval *rv);
bool vk_VkPipelineLayoutCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPipelineLayoutCreateInfo_to(const void *raw, zval *rv);
bool vk_VkPipelineShaderStageCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPipelineShaderStageCreateInfo_to(const void *raw, zval *rv);
bool vk_VkVertexInputBindingDescription_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkVertexInputBindingDescription_to(const void *raw, zval *rv);
bool vk_VkVertexInputAttributeDescription_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkVertexInputAttributeDescription_to(const void *raw, zval *rv);
bool vk_VkPipelineVertexInputStateCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPipelineVertexInputStateCreateInfo_to(const void *raw, zval *rv);
bool vk_VkPipelineInputAssemblyStateCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPipelineInputAssemblyStateCreateInfo_to(const void *raw, zval *rv);
bool vk_VkPipelineViewportStateCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPipelineViewportStateCreateInfo_to(const void *raw, zval *rv);
bool vk_VkPipelineRasterizationStateCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPipelineRasterizationStateCreateInfo_to(const void *raw, zval *rv);
bool vk_VkPipelineMultisampleStateCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPipelineMultisampleStateCreateInfo_to(const void *raw, zval *rv);
bool vk_VkStencilOpState_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkStencilOpState_to(const void *raw, zval *rv);
bool vk_VkPipelineDepthStencilStateCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPipelineDepthStencilStateCreateInfo_to(const void *raw, zval *rv);
bool vk_VkPipelineColorBlendAttachmentState_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPipelineColorBlendAttachmentState_to(const void *raw, zval *rv);
bool vk_VkPipelineColorBlendStateCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPipelineColorBlendStateCreateInfo_to(const void *raw, zval *rv);
bool vk_VkPipelineDynamicStateCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPipelineDynamicStateCreateInfo_to(const void *raw, zval *rv);
bool vk_VkPipelineTessellationStateCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPipelineTessellationStateCreateInfo_to(const void *raw, zval *rv);
bool vk_VkGraphicsPipelineCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkGraphicsPipelineCreateInfo_to(const void *raw, zval *rv);
bool vk_VkDescriptorSetLayoutBinding_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkDescriptorSetLayoutBinding_to(const void *raw, zval *rv);
bool vk_VkDescriptorSetLayoutCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkDescriptorSetLayoutCreateInfo_to(const void *raw, zval *rv);
bool vk_VkDescriptorPoolSize_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkDescriptorPoolSize_to(const void *raw, zval *rv);
bool vk_VkDescriptorPoolCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkDescriptorPoolCreateInfo_to(const void *raw, zval *rv);
bool vk_VkDescriptorSetAllocateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkDescriptorSetAllocateInfo_to(const void *raw, zval *rv);
bool vk_VkDescriptorImageInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkDescriptorImageInfo_to(const void *raw, zval *rv);
bool vk_VkWriteDescriptorSet_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkWriteDescriptorSet_to(const void *raw, zval *rv);
bool vk_VkViewport_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkViewport_to(const void *raw, zval *rv);
bool vk_VkOffset2D_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkOffset2D_to(const void *raw, zval *rv);
bool vk_VkExtent2D_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkExtent2D_to(const void *raw, zval *rv);
bool vk_VkRect2D_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkRect2D_to(const void *raw, zval *rv);
extern zend_class_entry *vulkan_ce_VkAttachmentDescription;
extern zend_class_entry *vulkan_ce_VkAttachmentReference;
extern zend_class_entry *vulkan_ce_VkSubpassDescription;
extern zend_class_entry *vulkan_ce_VkSubpassDependency;
extern zend_class_entry *vulkan_ce_VkRenderPassCreateInfo;
extern zend_class_entry *vulkan_ce_VkFramebufferCreateInfo;
extern zend_class_entry *vulkan_ce_VkShaderModuleCreateInfo;
extern zend_class_entry *vulkan_ce_VkPushConstantRange;
extern zend_class_entry *vulkan_ce_VkPipelineLayoutCreateInfo;
extern zend_class_entry *vulkan_ce_VkPipelineShaderStageCreateInfo;
extern zend_class_entry *vulkan_ce_VkVertexInputBindingDescription;
extern zend_class_entry *vulkan_ce_VkVertexInputAttributeDescription;
extern zend_class_entry *vulkan_ce_VkPipelineVertexInputStateCreateInfo;
extern zend_class_entry *vulkan_ce_VkPipelineInputAssemblyStateCreateInfo;
extern zend_class_entry *vulkan_ce_VkPipelineViewportStateCreateInfo;
extern zend_class_entry *vulkan_ce_VkPipelineRasterizationStateCreateInfo;
extern zend_class_entry *vulkan_ce_VkPipelineMultisampleStateCreateInfo;
extern zend_class_entry *vulkan_ce_VkStencilOpState;
extern zend_class_entry *vulkan_ce_VkPipelineDepthStencilStateCreateInfo;
extern zend_class_entry *vulkan_ce_VkPipelineColorBlendAttachmentState;
extern zend_class_entry *vulkan_ce_VkPipelineColorBlendStateCreateInfo;
extern zend_class_entry *vulkan_ce_VkPipelineDynamicStateCreateInfo;
extern zend_class_entry *vulkan_ce_VkPipelineTessellationStateCreateInfo;
extern zend_class_entry *vulkan_ce_VkGraphicsPipelineCreateInfo;
extern zend_class_entry *vulkan_ce_VkDescriptorSetLayoutBinding;
extern zend_class_entry *vulkan_ce_VkDescriptorSetLayoutCreateInfo;
extern zend_class_entry *vulkan_ce_VkDescriptorPoolSize;
extern zend_class_entry *vulkan_ce_VkDescriptorPoolCreateInfo;
extern zend_class_entry *vulkan_ce_VkDescriptorSetAllocateInfo;
extern zend_class_entry *vulkan_ce_VkDescriptorImageInfo;
extern zend_class_entry *vulkan_ce_VkWriteDescriptorSet;
extern zend_class_entry *vulkan_ce_VkViewport;
extern zend_class_entry *vulkan_ce_VkOffset2D;
extern zend_class_entry *vulkan_ce_VkExtent2D;
extern zend_class_entry *vulkan_ce_VkRect2D;
extern zend_class_entry *vulkan_ce_VkRenderPass;
extern zend_class_entry *vulkan_ce_VkFramebuffer;
extern zend_class_entry *vulkan_ce_VkShaderModule;
extern zend_class_entry *vulkan_ce_VkPipelineLayout;
extern zend_class_entry *vulkan_ce_VkPipeline;
extern zend_class_entry *vulkan_ce_VkDescriptorSetLayout;
extern zend_class_entry *vulkan_ce_VkDescriptorPool;
extern zend_class_entry *vulkan_ce_VkDescriptorSet;

bool vk_VkCommandPoolCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkCommandPoolCreateInfo_to(const void *raw, zval *rv);
bool vk_VkCommandBufferAllocateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkCommandBufferAllocateInfo_to(const void *raw, zval *rv);
bool vk_VkCommandBufferInheritanceInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkCommandBufferInheritanceInfo_to(const void *raw, zval *rv);
bool vk_VkCommandBufferBeginInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkCommandBufferBeginInfo_to(const void *raw, zval *rv);
bool vk_VkClearColorValue_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkClearColorValue_to(const void *raw, zval *rv);
bool vk_VkClearDepthStencilValue_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkClearDepthStencilValue_to(const void *raw, zval *rv);
bool vk_VkClearValue_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkClearValue_to(const void *raw, zval *rv);
bool vk_VkRenderPassBeginInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkRenderPassBeginInfo_to(const void *raw, zval *rv);
bool vk_VkOffset3D_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkOffset3D_to(const void *raw, zval *rv);
bool vk_VkImageSubresourceLayers_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkImageSubresourceLayers_to(const void *raw, zval *rv);
bool vk_VkBufferImageCopy_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkBufferImageCopy_to(const void *raw, zval *rv);
bool vk_VkImageBlit_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkImageBlit_to(const void *raw, zval *rv);
bool vk_VkMemoryBarrier_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkMemoryBarrier_to(const void *raw, zval *rv);
bool vk_VkImageMemoryBarrier_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkImageMemoryBarrier_to(const void *raw, zval *rv);
bool vk_VkSubmitInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkSubmitInfo_to(const void *raw, zval *rv);
bool vk_VkFenceCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkFenceCreateInfo_to(const void *raw, zval *rv);
bool vk_VkSemaphoreCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkSemaphoreCreateInfo_to(const void *raw, zval *rv);
bool vk_VkClearAttachment_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkClearAttachment_to(const void *raw, zval *rv);
bool vk_VkClearRect_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkClearRect_to(const void *raw, zval *rv);
extern zend_class_entry *vulkan_ce_VkCommandPoolCreateInfo;
extern zend_class_entry *vulkan_ce_VkCommandBufferAllocateInfo;
extern zend_class_entry *vulkan_ce_VkCommandBufferInheritanceInfo;
extern zend_class_entry *vulkan_ce_VkCommandBufferBeginInfo;
extern zend_class_entry *vulkan_ce_VkClearColorValue;
extern zend_class_entry *vulkan_ce_VkClearDepthStencilValue;
extern zend_class_entry *vulkan_ce_VkClearValue;
extern zend_class_entry *vulkan_ce_VkRenderPassBeginInfo;
extern zend_class_entry *vulkan_ce_VkOffset3D;
extern zend_class_entry *vulkan_ce_VkImageSubresourceLayers;
extern zend_class_entry *vulkan_ce_VkBufferImageCopy;
extern zend_class_entry *vulkan_ce_VkImageBlit;
extern zend_class_entry *vulkan_ce_VkMemoryBarrier;
extern zend_class_entry *vulkan_ce_VkImageMemoryBarrier;
extern zend_class_entry *vulkan_ce_VkSubmitInfo;
extern zend_class_entry *vulkan_ce_VkFenceCreateInfo;
extern zend_class_entry *vulkan_ce_VkSemaphoreCreateInfo;
extern zend_class_entry *vulkan_ce_VkClearAttachment;
extern zend_class_entry *vulkan_ce_VkClearRect;
extern zend_class_entry *vulkan_ce_VkCommandPool;
extern zend_class_entry *vulkan_ce_VkCommandBuffer;
extern zend_class_entry *vulkan_ce_VkFence;
extern zend_class_entry *vulkan_ce_VkSemaphore;

bool vk_VkSurfaceFormatKHR_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkSurfaceFormatKHR_to(const void *raw, zval *rv);
bool vk_VkSurfaceCapabilitiesKHR_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkSurfaceCapabilitiesKHR_to(const void *raw, zval *rv);
bool vk_VkSwapchainCreateInfoKHR_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkSwapchainCreateInfoKHR_to(const void *raw, zval *rv);
bool vk_VkPresentInfoKHR_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkPresentInfoKHR_to(const void *raw, zval *rv);
extern zend_class_entry *vulkan_ce_VkSurfaceFormatKHR;
extern zend_class_entry *vulkan_ce_VkSurfaceCapabilitiesKHR;
extern zend_class_entry *vulkan_ce_VkSwapchainCreateInfoKHR;
extern zend_class_entry *vulkan_ce_VkPresentInfoKHR;

bool vk_VkRectLayerKHR_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
bool vk_VkPresentRegionKHR_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
bool vk_VkPresentRegionsKHR_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
bool vk_VkPresentIdKHR_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
bool vk_VkPhysicalDevicePresentIdFeaturesKHR_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
bool vk_VkPhysicalDevicePresentWaitFeaturesKHR_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
bool vk_VkXYColorEXT_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
bool vk_VkHdrMetadataEXT_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
extern zend_class_entry *vulkan_ce_VkRectLayerKHR;
extern zend_class_entry *vulkan_ce_VkPresentRegionKHR;
extern zend_class_entry *vulkan_ce_VkPresentRegionsKHR;
extern zend_class_entry *vulkan_ce_VkPresentIdKHR;
extern zend_class_entry *vulkan_ce_VkPhysicalDevicePresentIdFeaturesKHR;
extern zend_class_entry *vulkan_ce_VkPhysicalDevicePresentWaitFeaturesKHR;
extern zend_class_entry *vulkan_ce_VkXYColorEXT;
extern zend_class_entry *vulkan_ce_VkHdrMetadataEXT;
extern zend_class_entry *vulkan_ce_VkSurfaceKHR;
extern zend_class_entry *vulkan_ce_VkSwapchainKHR;

bool vk_VkExternalMemoryImageCreateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkExternalMemoryImageCreateInfo_to(const void *raw, zval *rv);
bool vk_VkMemoryDedicatedAllocateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkMemoryDedicatedAllocateInfo_to(const void *raw, zval *rv);
bool vk_VkExportMemoryAllocateInfo_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkExportMemoryAllocateInfo_to(const void *raw, zval *rv);
bool vk_VkMemoryGetFdInfoKHR_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkMemoryGetFdInfoKHR_to(const void *raw, zval *rv);
bool vk_VkImageDrmFormatModifierListCreateInfoEXT_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkImageDrmFormatModifierListCreateInfoEXT_to(const void *raw, zval *rv);
bool vk_VkImageDrmFormatModifierPropertiesEXT_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkImageDrmFormatModifierPropertiesEXT_to(const void *raw, zval *rv);
bool vk_VkImageSubresource_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkImageSubresource_to(const void *raw, zval *rv);
bool vk_VkSubresourceLayout_from(zend_object *obj, void *raw, vulkan_scratch *scratch, HashTable *visited);
void vk_VkSubresourceLayout_to(const void *raw, zval *rv);
extern zend_class_entry *vulkan_ce_VkExternalMemoryImageCreateInfo;
extern zend_class_entry *vulkan_ce_VkExportMemoryAllocateInfo;
extern zend_class_entry *vulkan_ce_VkMemoryDedicatedAllocateInfo;
extern zend_class_entry *vulkan_ce_VkMemoryGetFdInfoKHR;
extern zend_class_entry *vulkan_ce_VkImageDrmFormatModifierListCreateInfoEXT;
extern zend_class_entry *vulkan_ce_VkImageDrmFormatModifierPropertiesEXT;
extern zend_class_entry *vulkan_ce_VkImageSubresource;
extern zend_class_entry *vulkan_ce_VkSubresourceLayout;

#endif
