/*
 * vk-13.h — Vulkan\VK\VK13 bound 1:1.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_VERSION_1_3 (37 commands)
 */

#ifndef PHPVK_VK_13_H
#define PHPVK_VK_13_H

#include <php.h>

/*@audit feature VK\VK13 VK_VERSION_1_3 37 */

/*@zep VK\VK13 vkGetPhysicalDeviceToolProperties(int physicalDevice, int pToolCount, int pToolProperties) -> int */
zend_long phpvk_vk13_vkgetphysicaldevicetoolproperties(zval *physicalDevice, zval *pToolCount, zval *pToolProperties);

/*@zep VK\VK13 vkCreatePrivateDataSlot(int device, int pCreateInfo, int pAllocator, int pPrivateDataSlot) -> int */
zend_long phpvk_vk13_vkcreateprivatedataslot(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pPrivateDataSlot);

/*@zep VK\VK13 vkDestroyPrivateDataSlot(int device, int privateDataSlot, int pAllocator) -> void */
void phpvk_vk13_vkdestroyprivatedataslot(zval *device, zval *privateDataSlot, zval *pAllocator);

/*@zep VK\VK13 vkSetPrivateData(int device, int objectType, int objectHandle, int privateDataSlot, int data) -> int */
zend_long phpvk_vk13_vksetprivatedata(zval *device, zval *objectType, zval *objectHandle, zval *privateDataSlot, zval *data);

/*@zep VK\VK13 vkGetPrivateData(int device, int objectType, int objectHandle, int privateDataSlot, int pData) -> void */
void phpvk_vk13_vkgetprivatedata(zval *device, zval *objectType, zval *objectHandle, zval *privateDataSlot, zval *pData);

/*@zep VK\VK13 vkCmdPipelineBarrier2(int commandBuffer, int pDependencyInfo) -> void */
void phpvk_vk13_vkcmdpipelinebarrier2(zval *commandBuffer, zval *pDependencyInfo);

/*@zep VK\VK13 vkCmdWriteTimestamp2(int commandBuffer, int stage, int queryPool, int query) -> void */
void phpvk_vk13_vkcmdwritetimestamp2(zval *commandBuffer, zval *stage, zval *queryPool, zval *query);

/*@zep VK\VK13 vkQueueSubmit2(int queue, int submitCount, int pSubmits, int fence) -> int */
zend_long phpvk_vk13_vkqueuesubmit2(zval *queue, zval *submitCount, zval *pSubmits, zval *fence);

/*@zep VK\VK13 vkCmdCopyBuffer2(int commandBuffer, int pCopyBufferInfo) -> void */
void phpvk_vk13_vkcmdcopybuffer2(zval *commandBuffer, zval *pCopyBufferInfo);

/*@zep VK\VK13 vkCmdCopyImage2(int commandBuffer, int pCopyImageInfo) -> void */
void phpvk_vk13_vkcmdcopyimage2(zval *commandBuffer, zval *pCopyImageInfo);

/*@zep VK\VK13 vkCmdCopyBufferToImage2(int commandBuffer, int pCopyBufferToImageInfo) -> void */
void phpvk_vk13_vkcmdcopybuffertoimage2(zval *commandBuffer, zval *pCopyBufferToImageInfo);

/*@zep VK\VK13 vkCmdCopyImageToBuffer2(int commandBuffer, int pCopyImageToBufferInfo) -> void */
void phpvk_vk13_vkcmdcopyimagetobuffer2(zval *commandBuffer, zval *pCopyImageToBufferInfo);

/*@zep VK\VK13 vkGetDeviceBufferMemoryRequirements(int device, int pInfo, int pMemoryRequirements) -> void */
void phpvk_vk13_vkgetdevicebuffermemoryrequirements(zval *device, zval *pInfo, zval *pMemoryRequirements);

/*@zep VK\VK13 vkGetDeviceImageMemoryRequirements(int device, int pInfo, int pMemoryRequirements) -> void */
void phpvk_vk13_vkgetdeviceimagememoryrequirements(zval *device, zval *pInfo, zval *pMemoryRequirements);

/*@zep VK\VK13 vkGetDeviceImageSparseMemoryRequirements(int device, int pInfo, int pSparseMemoryRequirementCount, int pSparseMemoryRequirements) -> void */
void phpvk_vk13_vkgetdeviceimagesparsememoryrequirements(zval *device, zval *pInfo, zval *pSparseMemoryRequirementCount, zval *pSparseMemoryRequirements);

/*@zep VK\VK13 vkCmdSetEvent2(int commandBuffer, int event, int pDependencyInfo) -> void */
void phpvk_vk13_vkcmdsetevent2(zval *commandBuffer, zval *event, zval *pDependencyInfo);

/*@zep VK\VK13 vkCmdResetEvent2(int commandBuffer, int event, int stageMask) -> void */
void phpvk_vk13_vkcmdresetevent2(zval *commandBuffer, zval *event, zval *stageMask);

/*@zep VK\VK13 vkCmdWaitEvents2(int commandBuffer, int eventCount, int pEvents, int pDependencyInfos) -> void */
void phpvk_vk13_vkcmdwaitevents2(zval *commandBuffer, zval *eventCount, zval *pEvents, zval *pDependencyInfos);

/*@zep VK\VK13 vkCmdBlitImage2(int commandBuffer, int pBlitImageInfo) -> void */
void phpvk_vk13_vkcmdblitimage2(zval *commandBuffer, zval *pBlitImageInfo);

/*@zep VK\VK13 vkCmdResolveImage2(int commandBuffer, int pResolveImageInfo) -> void */
void phpvk_vk13_vkcmdresolveimage2(zval *commandBuffer, zval *pResolveImageInfo);

/*@zep VK\VK13 vkCmdBeginRendering(int commandBuffer, int pRenderingInfo) -> void */
void phpvk_vk13_vkcmdbeginrendering(zval *commandBuffer, zval *pRenderingInfo);

/*@zep VK\VK13 vkCmdEndRendering(int commandBuffer) -> void */
void phpvk_vk13_vkcmdendrendering(zval *commandBuffer);

/*@zep VK\VK13 vkCmdSetCullMode(int commandBuffer, int cullMode) -> void */
void phpvk_vk13_vkcmdsetcullmode(zval *commandBuffer, zval *cullMode);

/*@zep VK\VK13 vkCmdSetFrontFace(int commandBuffer, int frontFace) -> void */
void phpvk_vk13_vkcmdsetfrontface(zval *commandBuffer, zval *frontFace);

/*@zep VK\VK13 vkCmdSetPrimitiveTopology(int commandBuffer, int primitiveTopology) -> void */
void phpvk_vk13_vkcmdsetprimitivetopology(zval *commandBuffer, zval *primitiveTopology);

/*@zep VK\VK13 vkCmdSetViewportWithCount(int commandBuffer, int viewportCount, int pViewports) -> void */
void phpvk_vk13_vkcmdsetviewportwithcount(zval *commandBuffer, zval *viewportCount, zval *pViewports);

/*@zep VK\VK13 vkCmdSetScissorWithCount(int commandBuffer, int scissorCount, int pScissors) -> void */
void phpvk_vk13_vkcmdsetscissorwithcount(zval *commandBuffer, zval *scissorCount, zval *pScissors);

/*@zep VK\VK13 vkCmdBindVertexBuffers2(int commandBuffer, int firstBinding, int bindingCount, int pBuffers, int pOffsets, int pSizes, int pStrides) -> void */
void phpvk_vk13_vkcmdbindvertexbuffers2(zval *commandBuffer, zval *firstBinding, zval *bindingCount, zval *pBuffers, zval *pOffsets, zval *pSizes, zval *pStrides);

/*@zep VK\VK13 vkCmdSetDepthTestEnable(int commandBuffer, bool depthTestEnable) -> void */
void phpvk_vk13_vkcmdsetdepthtestenable(zval *commandBuffer, zval *depthTestEnable);

/*@zep VK\VK13 vkCmdSetDepthWriteEnable(int commandBuffer, bool depthWriteEnable) -> void */
void phpvk_vk13_vkcmdsetdepthwriteenable(zval *commandBuffer, zval *depthWriteEnable);

/*@zep VK\VK13 vkCmdSetDepthCompareOp(int commandBuffer, int depthCompareOp) -> void */
void phpvk_vk13_vkcmdsetdepthcompareop(zval *commandBuffer, zval *depthCompareOp);

/*@zep VK\VK13 vkCmdSetDepthBoundsTestEnable(int commandBuffer, bool depthBoundsTestEnable) -> void */
void phpvk_vk13_vkcmdsetdepthboundstestenable(zval *commandBuffer, zval *depthBoundsTestEnable);

/*@zep VK\VK13 vkCmdSetStencilTestEnable(int commandBuffer, bool stencilTestEnable) -> void */
void phpvk_vk13_vkcmdsetstenciltestenable(zval *commandBuffer, zval *stencilTestEnable);

/*@zep VK\VK13 vkCmdSetStencilOp(int commandBuffer, int faceMask, int failOp, int passOp, int depthFailOp, int compareOp) -> void */
void phpvk_vk13_vkcmdsetstencilop(zval *commandBuffer, zval *faceMask, zval *failOp, zval *passOp, zval *depthFailOp, zval *compareOp);

/*@zep VK\VK13 vkCmdSetRasterizerDiscardEnable(int commandBuffer, bool rasterizerDiscardEnable) -> void */
void phpvk_vk13_vkcmdsetrasterizerdiscardenable(zval *commandBuffer, zval *rasterizerDiscardEnable);

/*@zep VK\VK13 vkCmdSetDepthBiasEnable(int commandBuffer, bool depthBiasEnable) -> void */
void phpvk_vk13_vkcmdsetdepthbiasenable(zval *commandBuffer, zval *depthBiasEnable);

/*@zep VK\VK13 vkCmdSetPrimitiveRestartEnable(int commandBuffer, bool primitiveRestartEnable) -> void */
void phpvk_vk13_vkcmdsetprimitiverestartenable(zval *commandBuffer, zval *primitiveRestartEnable);

#endif
