/*
 * vk-10.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_VERSION_1_0
 */

#include "vk-10.h"
#include "phpvk-platform.h"
#include "phpvk-bridge.h"
#include "phpvk-support.h"

zend_long phpvk_vk10_vkcreateinstance(zval *pCreateInfo, zval *pAllocator, zval *pInstance)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateInstance fn = (PFN_vkCreateInstance) phpvk_entry("vkCreateInstance", &slot, PHPVK_LEVEL_GLOBAL);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((const VkInstanceCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkInstance *) phpvk_arg_ptr(pInstance));
}

void phpvk_vk10_vkdestroyinstance(zval *instance, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyInstance fn = (PFN_vkDestroyInstance) phpvk_entry("vkDestroyInstance", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return;
    }

    fn((VkInstance) phpvk_arg_ptr(instance), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkenumeratephysicaldevices(zval *instance, zval *pPhysicalDeviceCount, zval *pPhysicalDevices)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkEnumeratePhysicalDevices fn = (PFN_vkEnumeratePhysicalDevices) phpvk_entry("vkEnumeratePhysicalDevices", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkInstance) phpvk_arg_ptr(instance), (uint32_t *) phpvk_arg_ptr(pPhysicalDeviceCount), (VkPhysicalDevice *) phpvk_arg_ptr(pPhysicalDevices));
}

void phpvk_vk10_vkgetphysicaldevicefeatures(zval *physicalDevice, zval *pFeatures)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetPhysicalDeviceFeatures fn = (PFN_vkGetPhysicalDeviceFeatures) phpvk_entry("vkGetPhysicalDeviceFeatures", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return;
    }

    fn((VkPhysicalDevice) phpvk_arg_ptr(physicalDevice), (VkPhysicalDeviceFeatures *) phpvk_arg_ptr(pFeatures));
}

void phpvk_vk10_vkgetphysicaldeviceformatproperties(zval *physicalDevice, zval *format, zval *pFormatProperties)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetPhysicalDeviceFormatProperties fn = (PFN_vkGetPhysicalDeviceFormatProperties) phpvk_entry("vkGetPhysicalDeviceFormatProperties", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return;
    }

    fn((VkPhysicalDevice) phpvk_arg_ptr(physicalDevice), (VkFormat) phpvk_arg_long(format), (VkFormatProperties *) phpvk_arg_ptr(pFormatProperties));
}

zend_long phpvk_vk10_vkgetphysicaldeviceimageformatproperties(zval *physicalDevice, zval *format, zval *type, zval *tiling, zval *usage, zval *flags, zval *pImageFormatProperties)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetPhysicalDeviceImageFormatProperties fn = (PFN_vkGetPhysicalDeviceImageFormatProperties) phpvk_entry("vkGetPhysicalDeviceImageFormatProperties", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkPhysicalDevice) phpvk_arg_ptr(physicalDevice), (VkFormat) phpvk_arg_long(format), (VkImageType) phpvk_arg_long(type), (VkImageTiling) phpvk_arg_long(tiling), (VkImageUsageFlags) phpvk_arg_long(usage), (VkImageCreateFlags) phpvk_arg_long(flags), (VkImageFormatProperties *) phpvk_arg_ptr(pImageFormatProperties));
}

void phpvk_vk10_vkgetphysicaldeviceproperties(zval *physicalDevice, zval *pProperties)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetPhysicalDeviceProperties fn = (PFN_vkGetPhysicalDeviceProperties) phpvk_entry("vkGetPhysicalDeviceProperties", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return;
    }

    fn((VkPhysicalDevice) phpvk_arg_ptr(physicalDevice), (VkPhysicalDeviceProperties *) phpvk_arg_ptr(pProperties));
}

void phpvk_vk10_vkgetphysicaldevicequeuefamilyproperties(zval *physicalDevice, zval *pQueueFamilyPropertyCount, zval *pQueueFamilyProperties)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetPhysicalDeviceQueueFamilyProperties fn = (PFN_vkGetPhysicalDeviceQueueFamilyProperties) phpvk_entry("vkGetPhysicalDeviceQueueFamilyProperties", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return;
    }

    fn((VkPhysicalDevice) phpvk_arg_ptr(physicalDevice), (uint32_t *) phpvk_arg_ptr(pQueueFamilyPropertyCount), (VkQueueFamilyProperties *) phpvk_arg_ptr(pQueueFamilyProperties));
}

void phpvk_vk10_vkgetphysicaldevicememoryproperties(zval *physicalDevice, zval *pMemoryProperties)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetPhysicalDeviceMemoryProperties fn = (PFN_vkGetPhysicalDeviceMemoryProperties) phpvk_entry("vkGetPhysicalDeviceMemoryProperties", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return;
    }

    fn((VkPhysicalDevice) phpvk_arg_ptr(physicalDevice), (VkPhysicalDeviceMemoryProperties *) phpvk_arg_ptr(pMemoryProperties));
}

zend_long phpvk_vk10_vkgetinstanceprocaddr(zval *instance, zval *pName)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetInstanceProcAddr fn = (PFN_vkGetInstanceProcAddr) phpvk_entry("vkGetInstanceProcAddr", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((VkInstance) phpvk_arg_ptr(instance), (const char *) phpvk_arg_string(pName));
}

zend_long phpvk_vk10_vkgetdeviceprocaddr(zval *device, zval *pName)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetDeviceProcAddr fn = (PFN_vkGetDeviceProcAddr) phpvk_entry("vkGetDeviceProcAddr", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) (uintptr_t) fn((VkDevice) phpvk_arg_ptr(device), (const char *) phpvk_arg_string(pName));
}

zend_long phpvk_vk10_vkcreatedevice(zval *physicalDevice, zval *pCreateInfo, zval *pAllocator, zval *pDevice)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateDevice fn = (PFN_vkCreateDevice) phpvk_entry("vkCreateDevice", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkPhysicalDevice) phpvk_arg_ptr(physicalDevice), (const VkDeviceCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkDevice *) phpvk_arg_ptr(pDevice));
}

void phpvk_vk10_vkdestroydevice(zval *device, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyDevice fn = (PFN_vkDestroyDevice) phpvk_entry("vkDestroyDevice", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkenumerateinstanceextensionproperties(zval *pLayerName, zval *pPropertyCount, zval *pProperties)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkEnumerateInstanceExtensionProperties fn = (PFN_vkEnumerateInstanceExtensionProperties) phpvk_entry("vkEnumerateInstanceExtensionProperties", &slot, PHPVK_LEVEL_GLOBAL);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((const char *) phpvk_arg_string(pLayerName), (uint32_t *) phpvk_arg_ptr(pPropertyCount), (VkExtensionProperties *) phpvk_arg_ptr(pProperties));
}

zend_long phpvk_vk10_vkenumeratedeviceextensionproperties(zval *physicalDevice, zval *pLayerName, zval *pPropertyCount, zval *pProperties)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkEnumerateDeviceExtensionProperties fn = (PFN_vkEnumerateDeviceExtensionProperties) phpvk_entry("vkEnumerateDeviceExtensionProperties", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkPhysicalDevice) phpvk_arg_ptr(physicalDevice), (const char *) phpvk_arg_string(pLayerName), (uint32_t *) phpvk_arg_ptr(pPropertyCount), (VkExtensionProperties *) phpvk_arg_ptr(pProperties));
}

zend_long phpvk_vk10_vkenumerateinstancelayerproperties(zval *pPropertyCount, zval *pProperties)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkEnumerateInstanceLayerProperties fn = (PFN_vkEnumerateInstanceLayerProperties) phpvk_entry("vkEnumerateInstanceLayerProperties", &slot, PHPVK_LEVEL_GLOBAL);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((uint32_t *) phpvk_arg_ptr(pPropertyCount), (VkLayerProperties *) phpvk_arg_ptr(pProperties));
}

zend_long phpvk_vk10_vkenumeratedevicelayerproperties(zval *physicalDevice, zval *pPropertyCount, zval *pProperties)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkEnumerateDeviceLayerProperties fn = (PFN_vkEnumerateDeviceLayerProperties) phpvk_entry("vkEnumerateDeviceLayerProperties", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkPhysicalDevice) phpvk_arg_ptr(physicalDevice), (uint32_t *) phpvk_arg_ptr(pPropertyCount), (VkLayerProperties *) phpvk_arg_ptr(pProperties));
}

void phpvk_vk10_vkgetdevicequeue(zval *device, zval *queueFamilyIndex, zval *queueIndex, zval *pQueue)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetDeviceQueue fn = (PFN_vkGetDeviceQueue) phpvk_entry("vkGetDeviceQueue", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (uint32_t) phpvk_arg_long(queueFamilyIndex), (uint32_t) phpvk_arg_long(queueIndex), (VkQueue *) phpvk_arg_ptr(pQueue));
}

zend_long phpvk_vk10_vkqueuesubmit(zval *queue, zval *submitCount, zval *pSubmits, zval *fence)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkQueueSubmit fn = (PFN_vkQueueSubmit) phpvk_entry("vkQueueSubmit", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkQueue) phpvk_arg_ptr(queue), (uint32_t) phpvk_arg_long(submitCount), (const VkSubmitInfo *) phpvk_arg_ptr(pSubmits), (VkFence) (uintptr_t) phpvk_arg_u64(fence));
}

zend_long phpvk_vk10_vkqueuewaitidle(zval *queue)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkQueueWaitIdle fn = (PFN_vkQueueWaitIdle) phpvk_entry("vkQueueWaitIdle", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkQueue) phpvk_arg_ptr(queue));
}

zend_long phpvk_vk10_vkdevicewaitidle(zval *device)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDeviceWaitIdle fn = (PFN_vkDeviceWaitIdle) phpvk_entry("vkDeviceWaitIdle", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device));
}

zend_long phpvk_vk10_vkallocatememory(zval *device, zval *pAllocateInfo, zval *pAllocator, zval *pMemory)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkAllocateMemory fn = (PFN_vkAllocateMemory) phpvk_entry("vkAllocateMemory", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkMemoryAllocateInfo *) phpvk_arg_ptr(pAllocateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkDeviceMemory *) phpvk_arg_ptr(pMemory));
}

void phpvk_vk10_vkfreememory(zval *device, zval *memory, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkFreeMemory fn = (PFN_vkFreeMemory) phpvk_entry("vkFreeMemory", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkDeviceMemory) (uintptr_t) phpvk_arg_u64(memory), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkmapmemory(zval *device, zval *memory, zval *offset, zval *size, zval *flags, zval *ppData)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkMapMemory fn = (PFN_vkMapMemory) phpvk_entry("vkMapMemory", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkDeviceMemory) (uintptr_t) phpvk_arg_u64(memory), (VkDeviceSize) phpvk_arg_u64(offset), (VkDeviceSize) phpvk_arg_u64(size), (VkMemoryMapFlags) phpvk_arg_long(flags), (void **) phpvk_arg_ptr(ppData));
}

void phpvk_vk10_vkunmapmemory(zval *device, zval *memory)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkUnmapMemory fn = (PFN_vkUnmapMemory) phpvk_entry("vkUnmapMemory", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkDeviceMemory) (uintptr_t) phpvk_arg_u64(memory));
}

zend_long phpvk_vk10_vkflushmappedmemoryranges(zval *device, zval *memoryRangeCount, zval *pMemoryRanges)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkFlushMappedMemoryRanges fn = (PFN_vkFlushMappedMemoryRanges) phpvk_entry("vkFlushMappedMemoryRanges", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (uint32_t) phpvk_arg_long(memoryRangeCount), (const VkMappedMemoryRange *) phpvk_arg_ptr(pMemoryRanges));
}

zend_long phpvk_vk10_vkinvalidatemappedmemoryranges(zval *device, zval *memoryRangeCount, zval *pMemoryRanges)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkInvalidateMappedMemoryRanges fn = (PFN_vkInvalidateMappedMemoryRanges) phpvk_entry("vkInvalidateMappedMemoryRanges", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (uint32_t) phpvk_arg_long(memoryRangeCount), (const VkMappedMemoryRange *) phpvk_arg_ptr(pMemoryRanges));
}

void phpvk_vk10_vkgetdevicememorycommitment(zval *device, zval *memory, zval *pCommittedMemoryInBytes)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetDeviceMemoryCommitment fn = (PFN_vkGetDeviceMemoryCommitment) phpvk_entry("vkGetDeviceMemoryCommitment", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkDeviceMemory) (uintptr_t) phpvk_arg_u64(memory), (VkDeviceSize *) phpvk_arg_ptr(pCommittedMemoryInBytes));
}

zend_long phpvk_vk10_vkbindbuffermemory(zval *device, zval *buffer, zval *memory, zval *memoryOffset)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkBindBufferMemory fn = (PFN_vkBindBufferMemory) phpvk_entry("vkBindBufferMemory", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkBuffer) (uintptr_t) phpvk_arg_u64(buffer), (VkDeviceMemory) (uintptr_t) phpvk_arg_u64(memory), (VkDeviceSize) phpvk_arg_u64(memoryOffset));
}

zend_long phpvk_vk10_vkbindimagememory(zval *device, zval *image, zval *memory, zval *memoryOffset)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkBindImageMemory fn = (PFN_vkBindImageMemory) phpvk_entry("vkBindImageMemory", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkImage) (uintptr_t) phpvk_arg_u64(image), (VkDeviceMemory) (uintptr_t) phpvk_arg_u64(memory), (VkDeviceSize) phpvk_arg_u64(memoryOffset));
}

void phpvk_vk10_vkgetbuffermemoryrequirements(zval *device, zval *buffer, zval *pMemoryRequirements)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetBufferMemoryRequirements fn = (PFN_vkGetBufferMemoryRequirements) phpvk_entry("vkGetBufferMemoryRequirements", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkBuffer) (uintptr_t) phpvk_arg_u64(buffer), (VkMemoryRequirements *) phpvk_arg_ptr(pMemoryRequirements));
}

void phpvk_vk10_vkgetimagememoryrequirements(zval *device, zval *image, zval *pMemoryRequirements)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetImageMemoryRequirements fn = (PFN_vkGetImageMemoryRequirements) phpvk_entry("vkGetImageMemoryRequirements", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkImage) (uintptr_t) phpvk_arg_u64(image), (VkMemoryRequirements *) phpvk_arg_ptr(pMemoryRequirements));
}

void phpvk_vk10_vkgetimagesparsememoryrequirements(zval *device, zval *image, zval *pSparseMemoryRequirementCount, zval *pSparseMemoryRequirements)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetImageSparseMemoryRequirements fn = (PFN_vkGetImageSparseMemoryRequirements) phpvk_entry("vkGetImageSparseMemoryRequirements", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkImage) (uintptr_t) phpvk_arg_u64(image), (uint32_t *) phpvk_arg_ptr(pSparseMemoryRequirementCount), (VkSparseImageMemoryRequirements *) phpvk_arg_ptr(pSparseMemoryRequirements));
}

void phpvk_vk10_vkgetphysicaldevicesparseimageformatproperties(zval *physicalDevice, zval *format, zval *type, zval *samples, zval *usage, zval *tiling, zval *pPropertyCount, zval *pProperties)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetPhysicalDeviceSparseImageFormatProperties fn = (PFN_vkGetPhysicalDeviceSparseImageFormatProperties) phpvk_entry("vkGetPhysicalDeviceSparseImageFormatProperties", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return;
    }

    fn((VkPhysicalDevice) phpvk_arg_ptr(physicalDevice), (VkFormat) phpvk_arg_long(format), (VkImageType) phpvk_arg_long(type), (VkSampleCountFlagBits) phpvk_arg_long(samples), (VkImageUsageFlags) phpvk_arg_long(usage), (VkImageTiling) phpvk_arg_long(tiling), (uint32_t *) phpvk_arg_ptr(pPropertyCount), (VkSparseImageFormatProperties *) phpvk_arg_ptr(pProperties));
}

zend_long phpvk_vk10_vkqueuebindsparse(zval *queue, zval *bindInfoCount, zval *pBindInfo, zval *fence)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkQueueBindSparse fn = (PFN_vkQueueBindSparse) phpvk_entry("vkQueueBindSparse", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkQueue) phpvk_arg_ptr(queue), (uint32_t) phpvk_arg_long(bindInfoCount), (const VkBindSparseInfo *) phpvk_arg_ptr(pBindInfo), (VkFence) (uintptr_t) phpvk_arg_u64(fence));
}

zend_long phpvk_vk10_vkcreatefence(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pFence)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateFence fn = (PFN_vkCreateFence) phpvk_entry("vkCreateFence", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkFenceCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkFence *) phpvk_arg_ptr(pFence));
}

void phpvk_vk10_vkdestroyfence(zval *device, zval *fence, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyFence fn = (PFN_vkDestroyFence) phpvk_entry("vkDestroyFence", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkFence) (uintptr_t) phpvk_arg_u64(fence), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkresetfences(zval *device, zval *fenceCount, zval *pFences)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkResetFences fn = (PFN_vkResetFences) phpvk_entry("vkResetFences", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (uint32_t) phpvk_arg_long(fenceCount), (const VkFence *) phpvk_arg_ptr(pFences));
}

zend_long phpvk_vk10_vkgetfencestatus(zval *device, zval *fence)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetFenceStatus fn = (PFN_vkGetFenceStatus) phpvk_entry("vkGetFenceStatus", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkFence) (uintptr_t) phpvk_arg_u64(fence));
}

zend_long phpvk_vk10_vkwaitforfences(zval *device, zval *fenceCount, zval *pFences, zval *waitAll, zval *timeout)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkWaitForFences fn = (PFN_vkWaitForFences) phpvk_entry("vkWaitForFences", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (uint32_t) phpvk_arg_long(fenceCount), (const VkFence *) phpvk_arg_ptr(pFences), (VkBool32) phpvk_arg_bool(waitAll), (uint64_t) phpvk_arg_u64(timeout));
}

zend_long phpvk_vk10_vkcreatesemaphore(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pSemaphore)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateSemaphore fn = (PFN_vkCreateSemaphore) phpvk_entry("vkCreateSemaphore", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkSemaphoreCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkSemaphore *) phpvk_arg_ptr(pSemaphore));
}

void phpvk_vk10_vkdestroysemaphore(zval *device, zval *semaphore, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroySemaphore fn = (PFN_vkDestroySemaphore) phpvk_entry("vkDestroySemaphore", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkSemaphore) (uintptr_t) phpvk_arg_u64(semaphore), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkcreatequerypool(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pQueryPool)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateQueryPool fn = (PFN_vkCreateQueryPool) phpvk_entry("vkCreateQueryPool", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkQueryPoolCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkQueryPool *) phpvk_arg_ptr(pQueryPool));
}

void phpvk_vk10_vkdestroyquerypool(zval *device, zval *queryPool, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyQueryPool fn = (PFN_vkDestroyQueryPool) phpvk_entry("vkDestroyQueryPool", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkQueryPool) (uintptr_t) phpvk_arg_u64(queryPool), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkgetquerypoolresults(zval *device, zval *queryPool, zval *firstQuery, zval *queryCount, zval *dataSize, zval *pData, zval *stride, zval *flags)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetQueryPoolResults fn = (PFN_vkGetQueryPoolResults) phpvk_entry("vkGetQueryPoolResults", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkQueryPool) (uintptr_t) phpvk_arg_u64(queryPool), (uint32_t) phpvk_arg_long(firstQuery), (uint32_t) phpvk_arg_long(queryCount), (size_t) phpvk_arg_u64(dataSize), (void *) phpvk_arg_ptr(pData), (VkDeviceSize) phpvk_arg_u64(stride), (VkQueryResultFlags) phpvk_arg_long(flags));
}

zend_long phpvk_vk10_vkcreatebuffer(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pBuffer)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateBuffer fn = (PFN_vkCreateBuffer) phpvk_entry("vkCreateBuffer", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkBufferCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkBuffer *) phpvk_arg_ptr(pBuffer));
}

void phpvk_vk10_vkdestroybuffer(zval *device, zval *buffer, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyBuffer fn = (PFN_vkDestroyBuffer) phpvk_entry("vkDestroyBuffer", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkBuffer) (uintptr_t) phpvk_arg_u64(buffer), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkcreateimage(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pImage)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateImage fn = (PFN_vkCreateImage) phpvk_entry("vkCreateImage", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkImageCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkImage *) phpvk_arg_ptr(pImage));
}

void phpvk_vk10_vkdestroyimage(zval *device, zval *image, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyImage fn = (PFN_vkDestroyImage) phpvk_entry("vkDestroyImage", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkImage) (uintptr_t) phpvk_arg_u64(image), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

void phpvk_vk10_vkgetimagesubresourcelayout(zval *device, zval *image, zval *pSubresource, zval *pLayout)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetImageSubresourceLayout fn = (PFN_vkGetImageSubresourceLayout) phpvk_entry("vkGetImageSubresourceLayout", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkImage) (uintptr_t) phpvk_arg_u64(image), (const VkImageSubresource *) phpvk_arg_ptr(pSubresource), (VkSubresourceLayout *) phpvk_arg_ptr(pLayout));
}

zend_long phpvk_vk10_vkcreateimageview(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pView)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateImageView fn = (PFN_vkCreateImageView) phpvk_entry("vkCreateImageView", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkImageViewCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkImageView *) phpvk_arg_ptr(pView));
}

void phpvk_vk10_vkdestroyimageview(zval *device, zval *imageView, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyImageView fn = (PFN_vkDestroyImageView) phpvk_entry("vkDestroyImageView", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkImageView) (uintptr_t) phpvk_arg_u64(imageView), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkcreatecommandpool(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pCommandPool)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateCommandPool fn = (PFN_vkCreateCommandPool) phpvk_entry("vkCreateCommandPool", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkCommandPoolCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkCommandPool *) phpvk_arg_ptr(pCommandPool));
}

void phpvk_vk10_vkdestroycommandpool(zval *device, zval *commandPool, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyCommandPool fn = (PFN_vkDestroyCommandPool) phpvk_entry("vkDestroyCommandPool", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkCommandPool) (uintptr_t) phpvk_arg_u64(commandPool), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkresetcommandpool(zval *device, zval *commandPool, zval *flags)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkResetCommandPool fn = (PFN_vkResetCommandPool) phpvk_entry("vkResetCommandPool", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkCommandPool) (uintptr_t) phpvk_arg_u64(commandPool), (VkCommandPoolResetFlags) phpvk_arg_long(flags));
}

zend_long phpvk_vk10_vkallocatecommandbuffers(zval *device, zval *pAllocateInfo, zval *pCommandBuffers)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkAllocateCommandBuffers fn = (PFN_vkAllocateCommandBuffers) phpvk_entry("vkAllocateCommandBuffers", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkCommandBufferAllocateInfo *) phpvk_arg_ptr(pAllocateInfo), (VkCommandBuffer *) phpvk_arg_ptr(pCommandBuffers));
}

void phpvk_vk10_vkfreecommandbuffers(zval *device, zval *commandPool, zval *commandBufferCount, zval *pCommandBuffers)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkFreeCommandBuffers fn = (PFN_vkFreeCommandBuffers) phpvk_entry("vkFreeCommandBuffers", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkCommandPool) (uintptr_t) phpvk_arg_u64(commandPool), (uint32_t) phpvk_arg_long(commandBufferCount), (const VkCommandBuffer *) phpvk_arg_ptr(pCommandBuffers));
}

zend_long phpvk_vk10_vkbegincommandbuffer(zval *commandBuffer, zval *pBeginInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkBeginCommandBuffer fn = (PFN_vkBeginCommandBuffer) phpvk_entry("vkBeginCommandBuffer", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkCommandBufferBeginInfo *) phpvk_arg_ptr(pBeginInfo));
}

zend_long phpvk_vk10_vkendcommandbuffer(zval *commandBuffer)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkEndCommandBuffer fn = (PFN_vkEndCommandBuffer) phpvk_entry("vkEndCommandBuffer", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer));
}

zend_long phpvk_vk10_vkresetcommandbuffer(zval *commandBuffer, zval *flags)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkResetCommandBuffer fn = (PFN_vkResetCommandBuffer) phpvk_entry("vkResetCommandBuffer", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkCommandBufferResetFlags) phpvk_arg_long(flags));
}

void phpvk_vk10_vkcmdcopybuffer(zval *commandBuffer, zval *srcBuffer, zval *dstBuffer, zval *regionCount, zval *pRegions)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdCopyBuffer fn = (PFN_vkCmdCopyBuffer) phpvk_entry("vkCmdCopyBuffer", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBuffer) (uintptr_t) phpvk_arg_u64(srcBuffer), (VkBuffer) (uintptr_t) phpvk_arg_u64(dstBuffer), (uint32_t) phpvk_arg_long(regionCount), (const VkBufferCopy *) phpvk_arg_ptr(pRegions));
}

void phpvk_vk10_vkcmdcopyimage(zval *commandBuffer, zval *srcImage, zval *srcImageLayout, zval *dstImage, zval *dstImageLayout, zval *regionCount, zval *pRegions)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdCopyImage fn = (PFN_vkCmdCopyImage) phpvk_entry("vkCmdCopyImage", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkImage) (uintptr_t) phpvk_arg_u64(srcImage), (VkImageLayout) phpvk_arg_long(srcImageLayout), (VkImage) (uintptr_t) phpvk_arg_u64(dstImage), (VkImageLayout) phpvk_arg_long(dstImageLayout), (uint32_t) phpvk_arg_long(regionCount), (const VkImageCopy *) phpvk_arg_ptr(pRegions));
}

void phpvk_vk10_vkcmdcopybuffertoimage(zval *commandBuffer, zval *srcBuffer, zval *dstImage, zval *dstImageLayout, zval *regionCount, zval *pRegions)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdCopyBufferToImage fn = (PFN_vkCmdCopyBufferToImage) phpvk_entry("vkCmdCopyBufferToImage", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBuffer) (uintptr_t) phpvk_arg_u64(srcBuffer), (VkImage) (uintptr_t) phpvk_arg_u64(dstImage), (VkImageLayout) phpvk_arg_long(dstImageLayout), (uint32_t) phpvk_arg_long(regionCount), (const VkBufferImageCopy *) phpvk_arg_ptr(pRegions));
}

void phpvk_vk10_vkcmdcopyimagetobuffer(zval *commandBuffer, zval *srcImage, zval *srcImageLayout, zval *dstBuffer, zval *regionCount, zval *pRegions)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdCopyImageToBuffer fn = (PFN_vkCmdCopyImageToBuffer) phpvk_entry("vkCmdCopyImageToBuffer", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkImage) (uintptr_t) phpvk_arg_u64(srcImage), (VkImageLayout) phpvk_arg_long(srcImageLayout), (VkBuffer) (uintptr_t) phpvk_arg_u64(dstBuffer), (uint32_t) phpvk_arg_long(regionCount), (const VkBufferImageCopy *) phpvk_arg_ptr(pRegions));
}

void phpvk_vk10_vkcmdupdatebuffer(zval *commandBuffer, zval *dstBuffer, zval *dstOffset, zval *dataSize, zval *pData)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdUpdateBuffer fn = (PFN_vkCmdUpdateBuffer) phpvk_entry("vkCmdUpdateBuffer", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBuffer) (uintptr_t) phpvk_arg_u64(dstBuffer), (VkDeviceSize) phpvk_arg_u64(dstOffset), (VkDeviceSize) phpvk_arg_u64(dataSize), (const void *) phpvk_arg_ptr(pData));
}

void phpvk_vk10_vkcmdfillbuffer(zval *commandBuffer, zval *dstBuffer, zval *dstOffset, zval *size, zval *data)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdFillBuffer fn = (PFN_vkCmdFillBuffer) phpvk_entry("vkCmdFillBuffer", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBuffer) (uintptr_t) phpvk_arg_u64(dstBuffer), (VkDeviceSize) phpvk_arg_u64(dstOffset), (VkDeviceSize) phpvk_arg_u64(size), (uint32_t) phpvk_arg_long(data));
}

void phpvk_vk10_vkcmdpipelinebarrier(zval *commandBuffer, zval *srcStageMask, zval *dstStageMask, zval *dependencyFlags, zval *memoryBarrierCount, zval *pMemoryBarriers, zval *bufferMemoryBarrierCount, zval *pBufferMemoryBarriers, zval *imageMemoryBarrierCount, zval *pImageMemoryBarriers)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdPipelineBarrier fn = (PFN_vkCmdPipelineBarrier) phpvk_entry("vkCmdPipelineBarrier", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkPipelineStageFlags) phpvk_arg_long(srcStageMask), (VkPipelineStageFlags) phpvk_arg_long(dstStageMask), (VkDependencyFlags) phpvk_arg_long(dependencyFlags), (uint32_t) phpvk_arg_long(memoryBarrierCount), (const VkMemoryBarrier *) phpvk_arg_ptr(pMemoryBarriers), (uint32_t) phpvk_arg_long(bufferMemoryBarrierCount), (const VkBufferMemoryBarrier *) phpvk_arg_ptr(pBufferMemoryBarriers), (uint32_t) phpvk_arg_long(imageMemoryBarrierCount), (const VkImageMemoryBarrier *) phpvk_arg_ptr(pImageMemoryBarriers));
}

void phpvk_vk10_vkcmdbeginquery(zval *commandBuffer, zval *queryPool, zval *query, zval *flags)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdBeginQuery fn = (PFN_vkCmdBeginQuery) phpvk_entry("vkCmdBeginQuery", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkQueryPool) (uintptr_t) phpvk_arg_u64(queryPool), (uint32_t) phpvk_arg_long(query), (VkQueryControlFlags) phpvk_arg_long(flags));
}

void phpvk_vk10_vkcmdendquery(zval *commandBuffer, zval *queryPool, zval *query)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdEndQuery fn = (PFN_vkCmdEndQuery) phpvk_entry("vkCmdEndQuery", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkQueryPool) (uintptr_t) phpvk_arg_u64(queryPool), (uint32_t) phpvk_arg_long(query));
}

void phpvk_vk10_vkcmdresetquerypool(zval *commandBuffer, zval *queryPool, zval *firstQuery, zval *queryCount)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdResetQueryPool fn = (PFN_vkCmdResetQueryPool) phpvk_entry("vkCmdResetQueryPool", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkQueryPool) (uintptr_t) phpvk_arg_u64(queryPool), (uint32_t) phpvk_arg_long(firstQuery), (uint32_t) phpvk_arg_long(queryCount));
}

void phpvk_vk10_vkcmdwritetimestamp(zval *commandBuffer, zval *pipelineStage, zval *queryPool, zval *query)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdWriteTimestamp fn = (PFN_vkCmdWriteTimestamp) phpvk_entry("vkCmdWriteTimestamp", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkPipelineStageFlagBits) phpvk_arg_long(pipelineStage), (VkQueryPool) (uintptr_t) phpvk_arg_u64(queryPool), (uint32_t) phpvk_arg_long(query));
}

void phpvk_vk10_vkcmdcopyquerypoolresults(zval *commandBuffer, zval *queryPool, zval *firstQuery, zval *queryCount, zval *dstBuffer, zval *dstOffset, zval *stride, zval *flags)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdCopyQueryPoolResults fn = (PFN_vkCmdCopyQueryPoolResults) phpvk_entry("vkCmdCopyQueryPoolResults", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkQueryPool) (uintptr_t) phpvk_arg_u64(queryPool), (uint32_t) phpvk_arg_long(firstQuery), (uint32_t) phpvk_arg_long(queryCount), (VkBuffer) (uintptr_t) phpvk_arg_u64(dstBuffer), (VkDeviceSize) phpvk_arg_u64(dstOffset), (VkDeviceSize) phpvk_arg_u64(stride), (VkQueryResultFlags) phpvk_arg_long(flags));
}

void phpvk_vk10_vkcmdexecutecommands(zval *commandBuffer, zval *commandBufferCount, zval *pCommandBuffers)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdExecuteCommands fn = (PFN_vkCmdExecuteCommands) phpvk_entry("vkCmdExecuteCommands", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (uint32_t) phpvk_arg_long(commandBufferCount), (const VkCommandBuffer *) phpvk_arg_ptr(pCommandBuffers));
}

zend_long phpvk_vk10_vkcreateevent(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pEvent)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateEvent fn = (PFN_vkCreateEvent) phpvk_entry("vkCreateEvent", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkEventCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkEvent *) phpvk_arg_ptr(pEvent));
}

void phpvk_vk10_vkdestroyevent(zval *device, zval *event, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyEvent fn = (PFN_vkDestroyEvent) phpvk_entry("vkDestroyEvent", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkEvent) (uintptr_t) phpvk_arg_u64(event), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkgeteventstatus(zval *device, zval *event)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetEventStatus fn = (PFN_vkGetEventStatus) phpvk_entry("vkGetEventStatus", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkEvent) (uintptr_t) phpvk_arg_u64(event));
}

zend_long phpvk_vk10_vksetevent(zval *device, zval *event)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkSetEvent fn = (PFN_vkSetEvent) phpvk_entry("vkSetEvent", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkEvent) (uintptr_t) phpvk_arg_u64(event));
}

zend_long phpvk_vk10_vkresetevent(zval *device, zval *event)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkResetEvent fn = (PFN_vkResetEvent) phpvk_entry("vkResetEvent", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkEvent) (uintptr_t) phpvk_arg_u64(event));
}

zend_long phpvk_vk10_vkcreatebufferview(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pView)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateBufferView fn = (PFN_vkCreateBufferView) phpvk_entry("vkCreateBufferView", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkBufferViewCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkBufferView *) phpvk_arg_ptr(pView));
}

void phpvk_vk10_vkdestroybufferview(zval *device, zval *bufferView, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyBufferView fn = (PFN_vkDestroyBufferView) phpvk_entry("vkDestroyBufferView", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkBufferView) (uintptr_t) phpvk_arg_u64(bufferView), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkcreateshadermodule(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pShaderModule)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateShaderModule fn = (PFN_vkCreateShaderModule) phpvk_entry("vkCreateShaderModule", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkShaderModuleCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkShaderModule *) phpvk_arg_ptr(pShaderModule));
}

void phpvk_vk10_vkdestroyshadermodule(zval *device, zval *shaderModule, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyShaderModule fn = (PFN_vkDestroyShaderModule) phpvk_entry("vkDestroyShaderModule", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkShaderModule) (uintptr_t) phpvk_arg_u64(shaderModule), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkcreatepipelinecache(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pPipelineCache)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreatePipelineCache fn = (PFN_vkCreatePipelineCache) phpvk_entry("vkCreatePipelineCache", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkPipelineCacheCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkPipelineCache *) phpvk_arg_ptr(pPipelineCache));
}

void phpvk_vk10_vkdestroypipelinecache(zval *device, zval *pipelineCache, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyPipelineCache fn = (PFN_vkDestroyPipelineCache) phpvk_entry("vkDestroyPipelineCache", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkPipelineCache) (uintptr_t) phpvk_arg_u64(pipelineCache), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkgetpipelinecachedata(zval *device, zval *pipelineCache, zval *pDataSize, zval *pData)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetPipelineCacheData fn = (PFN_vkGetPipelineCacheData) phpvk_entry("vkGetPipelineCacheData", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkPipelineCache) (uintptr_t) phpvk_arg_u64(pipelineCache), (size_t *) phpvk_arg_ptr(pDataSize), (void *) phpvk_arg_ptr(pData));
}

zend_long phpvk_vk10_vkmergepipelinecaches(zval *device, zval *dstCache, zval *srcCacheCount, zval *pSrcCaches)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkMergePipelineCaches fn = (PFN_vkMergePipelineCaches) phpvk_entry("vkMergePipelineCaches", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkPipelineCache) (uintptr_t) phpvk_arg_u64(dstCache), (uint32_t) phpvk_arg_long(srcCacheCount), (const VkPipelineCache *) phpvk_arg_ptr(pSrcCaches));
}

zend_long phpvk_vk10_vkcreatecomputepipelines(zval *device, zval *pipelineCache, zval *createInfoCount, zval *pCreateInfos, zval *pAllocator, zval *pPipelines)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateComputePipelines fn = (PFN_vkCreateComputePipelines) phpvk_entry("vkCreateComputePipelines", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkPipelineCache) (uintptr_t) phpvk_arg_u64(pipelineCache), (uint32_t) phpvk_arg_long(createInfoCount), (const VkComputePipelineCreateInfo *) phpvk_arg_ptr(pCreateInfos), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkPipeline *) phpvk_arg_ptr(pPipelines));
}

void phpvk_vk10_vkdestroypipeline(zval *device, zval *pipeline, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyPipeline fn = (PFN_vkDestroyPipeline) phpvk_entry("vkDestroyPipeline", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkPipeline) (uintptr_t) phpvk_arg_u64(pipeline), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkcreatepipelinelayout(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pPipelineLayout)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreatePipelineLayout fn = (PFN_vkCreatePipelineLayout) phpvk_entry("vkCreatePipelineLayout", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkPipelineLayoutCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkPipelineLayout *) phpvk_arg_ptr(pPipelineLayout));
}

void phpvk_vk10_vkdestroypipelinelayout(zval *device, zval *pipelineLayout, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyPipelineLayout fn = (PFN_vkDestroyPipelineLayout) phpvk_entry("vkDestroyPipelineLayout", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkPipelineLayout) (uintptr_t) phpvk_arg_u64(pipelineLayout), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkcreatesampler(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pSampler)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateSampler fn = (PFN_vkCreateSampler) phpvk_entry("vkCreateSampler", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkSamplerCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkSampler *) phpvk_arg_ptr(pSampler));
}

void phpvk_vk10_vkdestroysampler(zval *device, zval *sampler, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroySampler fn = (PFN_vkDestroySampler) phpvk_entry("vkDestroySampler", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkSampler) (uintptr_t) phpvk_arg_u64(sampler), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkcreatedescriptorsetlayout(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pSetLayout)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateDescriptorSetLayout fn = (PFN_vkCreateDescriptorSetLayout) phpvk_entry("vkCreateDescriptorSetLayout", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkDescriptorSetLayoutCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkDescriptorSetLayout *) phpvk_arg_ptr(pSetLayout));
}

void phpvk_vk10_vkdestroydescriptorsetlayout(zval *device, zval *descriptorSetLayout, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyDescriptorSetLayout fn = (PFN_vkDestroyDescriptorSetLayout) phpvk_entry("vkDestroyDescriptorSetLayout", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkDescriptorSetLayout) (uintptr_t) phpvk_arg_u64(descriptorSetLayout), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkcreatedescriptorpool(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pDescriptorPool)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateDescriptorPool fn = (PFN_vkCreateDescriptorPool) phpvk_entry("vkCreateDescriptorPool", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkDescriptorPoolCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkDescriptorPool *) phpvk_arg_ptr(pDescriptorPool));
}

void phpvk_vk10_vkdestroydescriptorpool(zval *device, zval *descriptorPool, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyDescriptorPool fn = (PFN_vkDestroyDescriptorPool) phpvk_entry("vkDestroyDescriptorPool", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkDescriptorPool) (uintptr_t) phpvk_arg_u64(descriptorPool), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkresetdescriptorpool(zval *device, zval *descriptorPool, zval *flags)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkResetDescriptorPool fn = (PFN_vkResetDescriptorPool) phpvk_entry("vkResetDescriptorPool", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkDescriptorPool) (uintptr_t) phpvk_arg_u64(descriptorPool), (VkDescriptorPoolResetFlags) phpvk_arg_long(flags));
}

zend_long phpvk_vk10_vkallocatedescriptorsets(zval *device, zval *pAllocateInfo, zval *pDescriptorSets)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkAllocateDescriptorSets fn = (PFN_vkAllocateDescriptorSets) phpvk_entry("vkAllocateDescriptorSets", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkDescriptorSetAllocateInfo *) phpvk_arg_ptr(pAllocateInfo), (VkDescriptorSet *) phpvk_arg_ptr(pDescriptorSets));
}

zend_long phpvk_vk10_vkfreedescriptorsets(zval *device, zval *descriptorPool, zval *descriptorSetCount, zval *pDescriptorSets)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkFreeDescriptorSets fn = (PFN_vkFreeDescriptorSets) phpvk_entry("vkFreeDescriptorSets", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkDescriptorPool) (uintptr_t) phpvk_arg_u64(descriptorPool), (uint32_t) phpvk_arg_long(descriptorSetCount), (const VkDescriptorSet *) phpvk_arg_ptr(pDescriptorSets));
}

void phpvk_vk10_vkupdatedescriptorsets(zval *device, zval *descriptorWriteCount, zval *pDescriptorWrites, zval *descriptorCopyCount, zval *pDescriptorCopies)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkUpdateDescriptorSets fn = (PFN_vkUpdateDescriptorSets) phpvk_entry("vkUpdateDescriptorSets", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (uint32_t) phpvk_arg_long(descriptorWriteCount), (const VkWriteDescriptorSet *) phpvk_arg_ptr(pDescriptorWrites), (uint32_t) phpvk_arg_long(descriptorCopyCount), (const VkCopyDescriptorSet *) phpvk_arg_ptr(pDescriptorCopies));
}

void phpvk_vk10_vkcmdbindpipeline(zval *commandBuffer, zval *pipelineBindPoint, zval *pipeline)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdBindPipeline fn = (PFN_vkCmdBindPipeline) phpvk_entry("vkCmdBindPipeline", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkPipelineBindPoint) phpvk_arg_long(pipelineBindPoint), (VkPipeline) (uintptr_t) phpvk_arg_u64(pipeline));
}

void phpvk_vk10_vkcmdbinddescriptorsets(zval *commandBuffer, zval *pipelineBindPoint, zval *layout, zval *firstSet, zval *descriptorSetCount, zval *pDescriptorSets, zval *dynamicOffsetCount, zval *pDynamicOffsets)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdBindDescriptorSets fn = (PFN_vkCmdBindDescriptorSets) phpvk_entry("vkCmdBindDescriptorSets", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkPipelineBindPoint) phpvk_arg_long(pipelineBindPoint), (VkPipelineLayout) (uintptr_t) phpvk_arg_u64(layout), (uint32_t) phpvk_arg_long(firstSet), (uint32_t) phpvk_arg_long(descriptorSetCount), (const VkDescriptorSet *) phpvk_arg_ptr(pDescriptorSets), (uint32_t) phpvk_arg_long(dynamicOffsetCount), (const uint32_t *) phpvk_arg_ptr(pDynamicOffsets));
}

void phpvk_vk10_vkcmdclearcolorimage(zval *commandBuffer, zval *image, zval *imageLayout, zval *pColor, zval *rangeCount, zval *pRanges)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdClearColorImage fn = (PFN_vkCmdClearColorImage) phpvk_entry("vkCmdClearColorImage", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkImage) (uintptr_t) phpvk_arg_u64(image), (VkImageLayout) phpvk_arg_long(imageLayout), (const VkClearColorValue *) phpvk_arg_ptr(pColor), (uint32_t) phpvk_arg_long(rangeCount), (const VkImageSubresourceRange *) phpvk_arg_ptr(pRanges));
}

void phpvk_vk10_vkcmddispatch(zval *commandBuffer, zval *groupCountX, zval *groupCountY, zval *groupCountZ)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdDispatch fn = (PFN_vkCmdDispatch) phpvk_entry("vkCmdDispatch", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (uint32_t) phpvk_arg_long(groupCountX), (uint32_t) phpvk_arg_long(groupCountY), (uint32_t) phpvk_arg_long(groupCountZ));
}

void phpvk_vk10_vkcmddispatchindirect(zval *commandBuffer, zval *buffer, zval *offset)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdDispatchIndirect fn = (PFN_vkCmdDispatchIndirect) phpvk_entry("vkCmdDispatchIndirect", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBuffer) (uintptr_t) phpvk_arg_u64(buffer), (VkDeviceSize) phpvk_arg_u64(offset));
}

void phpvk_vk10_vkcmdsetevent(zval *commandBuffer, zval *event, zval *stageMask)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetEvent fn = (PFN_vkCmdSetEvent) phpvk_entry("vkCmdSetEvent", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkEvent) (uintptr_t) phpvk_arg_u64(event), (VkPipelineStageFlags) phpvk_arg_long(stageMask));
}

void phpvk_vk10_vkcmdresetevent(zval *commandBuffer, zval *event, zval *stageMask)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdResetEvent fn = (PFN_vkCmdResetEvent) phpvk_entry("vkCmdResetEvent", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkEvent) (uintptr_t) phpvk_arg_u64(event), (VkPipelineStageFlags) phpvk_arg_long(stageMask));
}

void phpvk_vk10_vkcmdwaitevents(zval *commandBuffer, zval *eventCount, zval *pEvents, zval *srcStageMask, zval *dstStageMask, zval *memoryBarrierCount, zval *pMemoryBarriers, zval *bufferMemoryBarrierCount, zval *pBufferMemoryBarriers, zval *imageMemoryBarrierCount, zval *pImageMemoryBarriers)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdWaitEvents fn = (PFN_vkCmdWaitEvents) phpvk_entry("vkCmdWaitEvents", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (uint32_t) phpvk_arg_long(eventCount), (const VkEvent *) phpvk_arg_ptr(pEvents), (VkPipelineStageFlags) phpvk_arg_long(srcStageMask), (VkPipelineStageFlags) phpvk_arg_long(dstStageMask), (uint32_t) phpvk_arg_long(memoryBarrierCount), (const VkMemoryBarrier *) phpvk_arg_ptr(pMemoryBarriers), (uint32_t) phpvk_arg_long(bufferMemoryBarrierCount), (const VkBufferMemoryBarrier *) phpvk_arg_ptr(pBufferMemoryBarriers), (uint32_t) phpvk_arg_long(imageMemoryBarrierCount), (const VkImageMemoryBarrier *) phpvk_arg_ptr(pImageMemoryBarriers));
}

void phpvk_vk10_vkcmdpushconstants(zval *commandBuffer, zval *layout, zval *stageFlags, zval *offset, zval *size, zval *pValues)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdPushConstants fn = (PFN_vkCmdPushConstants) phpvk_entry("vkCmdPushConstants", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkPipelineLayout) (uintptr_t) phpvk_arg_u64(layout), (VkShaderStageFlags) phpvk_arg_long(stageFlags), (uint32_t) phpvk_arg_long(offset), (uint32_t) phpvk_arg_long(size), (const void *) phpvk_arg_ptr(pValues));
}

zend_long phpvk_vk10_vkcreategraphicspipelines(zval *device, zval *pipelineCache, zval *createInfoCount, zval *pCreateInfos, zval *pAllocator, zval *pPipelines)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateGraphicsPipelines fn = (PFN_vkCreateGraphicsPipelines) phpvk_entry("vkCreateGraphicsPipelines", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkPipelineCache) (uintptr_t) phpvk_arg_u64(pipelineCache), (uint32_t) phpvk_arg_long(createInfoCount), (const VkGraphicsPipelineCreateInfo *) phpvk_arg_ptr(pCreateInfos), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkPipeline *) phpvk_arg_ptr(pPipelines));
}

zend_long phpvk_vk10_vkcreateframebuffer(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pFramebuffer)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateFramebuffer fn = (PFN_vkCreateFramebuffer) phpvk_entry("vkCreateFramebuffer", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkFramebufferCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkFramebuffer *) phpvk_arg_ptr(pFramebuffer));
}

void phpvk_vk10_vkdestroyframebuffer(zval *device, zval *framebuffer, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyFramebuffer fn = (PFN_vkDestroyFramebuffer) phpvk_entry("vkDestroyFramebuffer", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkFramebuffer) (uintptr_t) phpvk_arg_u64(framebuffer), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_vk10_vkcreaterenderpass(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pRenderPass)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateRenderPass fn = (PFN_vkCreateRenderPass) phpvk_entry("vkCreateRenderPass", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkRenderPassCreateInfo *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkRenderPass *) phpvk_arg_ptr(pRenderPass));
}

void phpvk_vk10_vkdestroyrenderpass(zval *device, zval *renderPass, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroyRenderPass fn = (PFN_vkDestroyRenderPass) phpvk_entry("vkDestroyRenderPass", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkRenderPass) (uintptr_t) phpvk_arg_u64(renderPass), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

void phpvk_vk10_vkgetrenderareagranularity(zval *device, zval *renderPass, zval *pGranularity)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetRenderAreaGranularity fn = (PFN_vkGetRenderAreaGranularity) phpvk_entry("vkGetRenderAreaGranularity", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkRenderPass) (uintptr_t) phpvk_arg_u64(renderPass), (VkExtent2D *) phpvk_arg_ptr(pGranularity));
}

void phpvk_vk10_vkcmdsetviewport(zval *commandBuffer, zval *firstViewport, zval *viewportCount, zval *pViewports)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetViewport fn = (PFN_vkCmdSetViewport) phpvk_entry("vkCmdSetViewport", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (uint32_t) phpvk_arg_long(firstViewport), (uint32_t) phpvk_arg_long(viewportCount), (const VkViewport *) phpvk_arg_ptr(pViewports));
}

void phpvk_vk10_vkcmdsetscissor(zval *commandBuffer, zval *firstScissor, zval *scissorCount, zval *pScissors)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetScissor fn = (PFN_vkCmdSetScissor) phpvk_entry("vkCmdSetScissor", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (uint32_t) phpvk_arg_long(firstScissor), (uint32_t) phpvk_arg_long(scissorCount), (const VkRect2D *) phpvk_arg_ptr(pScissors));
}

void phpvk_vk10_vkcmdsetlinewidth(zval *commandBuffer, zval *lineWidth)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetLineWidth fn = (PFN_vkCmdSetLineWidth) phpvk_entry("vkCmdSetLineWidth", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (float) phpvk_arg_double(lineWidth));
}

void phpvk_vk10_vkcmdsetdepthbias(zval *commandBuffer, zval *depthBiasConstantFactor, zval *depthBiasClamp, zval *depthBiasSlopeFactor)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetDepthBias fn = (PFN_vkCmdSetDepthBias) phpvk_entry("vkCmdSetDepthBias", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (float) phpvk_arg_double(depthBiasConstantFactor), (float) phpvk_arg_double(depthBiasClamp), (float) phpvk_arg_double(depthBiasSlopeFactor));
}

void phpvk_vk10_vkcmdsetblendconstants(zval *commandBuffer, zval *blendConstants)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetBlendConstants fn = (PFN_vkCmdSetBlendConstants) phpvk_entry("vkCmdSetBlendConstants", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const float *) phpvk_arg_ptr(blendConstants));
}

void phpvk_vk10_vkcmdsetdepthbounds(zval *commandBuffer, zval *minDepthBounds, zval *maxDepthBounds)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetDepthBounds fn = (PFN_vkCmdSetDepthBounds) phpvk_entry("vkCmdSetDepthBounds", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (float) phpvk_arg_double(minDepthBounds), (float) phpvk_arg_double(maxDepthBounds));
}

void phpvk_vk10_vkcmdsetstencilcomparemask(zval *commandBuffer, zval *faceMask, zval *compareMask)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetStencilCompareMask fn = (PFN_vkCmdSetStencilCompareMask) phpvk_entry("vkCmdSetStencilCompareMask", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkStencilFaceFlags) phpvk_arg_long(faceMask), (uint32_t) phpvk_arg_long(compareMask));
}

void phpvk_vk10_vkcmdsetstencilwritemask(zval *commandBuffer, zval *faceMask, zval *writeMask)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetStencilWriteMask fn = (PFN_vkCmdSetStencilWriteMask) phpvk_entry("vkCmdSetStencilWriteMask", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkStencilFaceFlags) phpvk_arg_long(faceMask), (uint32_t) phpvk_arg_long(writeMask));
}

void phpvk_vk10_vkcmdsetstencilreference(zval *commandBuffer, zval *faceMask, zval *reference)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetStencilReference fn = (PFN_vkCmdSetStencilReference) phpvk_entry("vkCmdSetStencilReference", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkStencilFaceFlags) phpvk_arg_long(faceMask), (uint32_t) phpvk_arg_long(reference));
}

void phpvk_vk10_vkcmdbindindexbuffer(zval *commandBuffer, zval *buffer, zval *offset, zval *indexType)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdBindIndexBuffer fn = (PFN_vkCmdBindIndexBuffer) phpvk_entry("vkCmdBindIndexBuffer", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBuffer) (uintptr_t) phpvk_arg_u64(buffer), (VkDeviceSize) phpvk_arg_u64(offset), (VkIndexType) phpvk_arg_long(indexType));
}

void phpvk_vk10_vkcmdbindvertexbuffers(zval *commandBuffer, zval *firstBinding, zval *bindingCount, zval *pBuffers, zval *pOffsets)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdBindVertexBuffers fn = (PFN_vkCmdBindVertexBuffers) phpvk_entry("vkCmdBindVertexBuffers", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (uint32_t) phpvk_arg_long(firstBinding), (uint32_t) phpvk_arg_long(bindingCount), (const VkBuffer *) phpvk_arg_ptr(pBuffers), (const VkDeviceSize *) phpvk_arg_ptr(pOffsets));
}

void phpvk_vk10_vkcmddraw(zval *commandBuffer, zval *vertexCount, zval *instanceCount, zval *firstVertex, zval *firstInstance)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdDraw fn = (PFN_vkCmdDraw) phpvk_entry("vkCmdDraw", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (uint32_t) phpvk_arg_long(vertexCount), (uint32_t) phpvk_arg_long(instanceCount), (uint32_t) phpvk_arg_long(firstVertex), (uint32_t) phpvk_arg_long(firstInstance));
}

void phpvk_vk10_vkcmddrawindexed(zval *commandBuffer, zval *indexCount, zval *instanceCount, zval *firstIndex, zval *vertexOffset, zval *firstInstance)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdDrawIndexed fn = (PFN_vkCmdDrawIndexed) phpvk_entry("vkCmdDrawIndexed", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (uint32_t) phpvk_arg_long(indexCount), (uint32_t) phpvk_arg_long(instanceCount), (uint32_t) phpvk_arg_long(firstIndex), (int32_t) phpvk_arg_long(vertexOffset), (uint32_t) phpvk_arg_long(firstInstance));
}

void phpvk_vk10_vkcmddrawindirect(zval *commandBuffer, zval *buffer, zval *offset, zval *drawCount, zval *stride)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdDrawIndirect fn = (PFN_vkCmdDrawIndirect) phpvk_entry("vkCmdDrawIndirect", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBuffer) (uintptr_t) phpvk_arg_u64(buffer), (VkDeviceSize) phpvk_arg_u64(offset), (uint32_t) phpvk_arg_long(drawCount), (uint32_t) phpvk_arg_long(stride));
}

void phpvk_vk10_vkcmddrawindexedindirect(zval *commandBuffer, zval *buffer, zval *offset, zval *drawCount, zval *stride)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdDrawIndexedIndirect fn = (PFN_vkCmdDrawIndexedIndirect) phpvk_entry("vkCmdDrawIndexedIndirect", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBuffer) (uintptr_t) phpvk_arg_u64(buffer), (VkDeviceSize) phpvk_arg_u64(offset), (uint32_t) phpvk_arg_long(drawCount), (uint32_t) phpvk_arg_long(stride));
}

void phpvk_vk10_vkcmdblitimage(zval *commandBuffer, zval *srcImage, zval *srcImageLayout, zval *dstImage, zval *dstImageLayout, zval *regionCount, zval *pRegions, zval *filter)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdBlitImage fn = (PFN_vkCmdBlitImage) phpvk_entry("vkCmdBlitImage", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkImage) (uintptr_t) phpvk_arg_u64(srcImage), (VkImageLayout) phpvk_arg_long(srcImageLayout), (VkImage) (uintptr_t) phpvk_arg_u64(dstImage), (VkImageLayout) phpvk_arg_long(dstImageLayout), (uint32_t) phpvk_arg_long(regionCount), (const VkImageBlit *) phpvk_arg_ptr(pRegions), (VkFilter) phpvk_arg_long(filter));
}

void phpvk_vk10_vkcmdcleardepthstencilimage(zval *commandBuffer, zval *image, zval *imageLayout, zval *pDepthStencil, zval *rangeCount, zval *pRanges)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdClearDepthStencilImage fn = (PFN_vkCmdClearDepthStencilImage) phpvk_entry("vkCmdClearDepthStencilImage", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkImage) (uintptr_t) phpvk_arg_u64(image), (VkImageLayout) phpvk_arg_long(imageLayout), (const VkClearDepthStencilValue *) phpvk_arg_ptr(pDepthStencil), (uint32_t) phpvk_arg_long(rangeCount), (const VkImageSubresourceRange *) phpvk_arg_ptr(pRanges));
}

void phpvk_vk10_vkcmdclearattachments(zval *commandBuffer, zval *attachmentCount, zval *pAttachments, zval *rectCount, zval *pRects)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdClearAttachments fn = (PFN_vkCmdClearAttachments) phpvk_entry("vkCmdClearAttachments", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (uint32_t) phpvk_arg_long(attachmentCount), (const VkClearAttachment *) phpvk_arg_ptr(pAttachments), (uint32_t) phpvk_arg_long(rectCount), (const VkClearRect *) phpvk_arg_ptr(pRects));
}

void phpvk_vk10_vkcmdresolveimage(zval *commandBuffer, zval *srcImage, zval *srcImageLayout, zval *dstImage, zval *dstImageLayout, zval *regionCount, zval *pRegions)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdResolveImage fn = (PFN_vkCmdResolveImage) phpvk_entry("vkCmdResolveImage", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkImage) (uintptr_t) phpvk_arg_u64(srcImage), (VkImageLayout) phpvk_arg_long(srcImageLayout), (VkImage) (uintptr_t) phpvk_arg_u64(dstImage), (VkImageLayout) phpvk_arg_long(dstImageLayout), (uint32_t) phpvk_arg_long(regionCount), (const VkImageResolve *) phpvk_arg_ptr(pRegions));
}

void phpvk_vk10_vkcmdbeginrenderpass(zval *commandBuffer, zval *pRenderPassBegin, zval *contents)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdBeginRenderPass fn = (PFN_vkCmdBeginRenderPass) phpvk_entry("vkCmdBeginRenderPass", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkRenderPassBeginInfo *) phpvk_arg_ptr(pRenderPassBegin), (VkSubpassContents) phpvk_arg_long(contents));
}

void phpvk_vk10_vkcmdnextsubpass(zval *commandBuffer, zval *contents)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdNextSubpass fn = (PFN_vkCmdNextSubpass) phpvk_entry("vkCmdNextSubpass", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkSubpassContents) phpvk_arg_long(contents));
}

void phpvk_vk10_vkcmdendrenderpass(zval *commandBuffer)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdEndRenderPass fn = (PFN_vkCmdEndRenderPass) phpvk_entry("vkCmdEndRenderPass", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer));
}

