/*
 * vk-12.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_VERSION_1_2
 */

#include "vk-12.h"
#include "phpvk-platform.h"
#include "phpvk-bridge.h"
#include "phpvk-support.h"

void phpvk_vk12_vkresetquerypool(zval *device, zval *queryPool, zval *firstQuery, zval *queryCount)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkResetQueryPool fn = (PFN_vkResetQueryPool) phpvk_entry("vkResetQueryPool", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkQueryPool) (uintptr_t) phpvk_arg_u64(queryPool), (uint32_t) phpvk_arg_long(firstQuery), (uint32_t) phpvk_arg_long(queryCount));
}

zend_long phpvk_vk12_vkgetsemaphorecountervalue(zval *device, zval *semaphore, zval *pValue)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetSemaphoreCounterValue fn = (PFN_vkGetSemaphoreCounterValue) phpvk_entry("vkGetSemaphoreCounterValue", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkSemaphore) (uintptr_t) phpvk_arg_u64(semaphore), (uint64_t *) phpvk_arg_ptr(pValue));
}

zend_long phpvk_vk12_vkwaitsemaphores(zval *device, zval *pWaitInfo, zval *timeout)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkWaitSemaphores fn = (PFN_vkWaitSemaphores) phpvk_entry("vkWaitSemaphores", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkSemaphoreWaitInfo *) phpvk_arg_ptr(pWaitInfo), (uint64_t) phpvk_arg_u64(timeout));
}

zend_long phpvk_vk12_vksignalsemaphore(zval *device, zval *pSignalInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkSignalSemaphore fn = (PFN_vkSignalSemaphore) phpvk_entry("vkSignalSemaphore", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkSemaphoreSignalInfo *) phpvk_arg_ptr(pSignalInfo));
}

zend_long phpvk_vk12_vkgetbufferdeviceaddress(zval *device, zval *pInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetBufferDeviceAddress fn = (PFN_vkGetBufferDeviceAddress) phpvk_entry("vkGetBufferDeviceAddress", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkBufferDeviceAddressInfo *) phpvk_arg_ptr(pInfo));
}

zend_long phpvk_vk12_vkgetbufferopaquecaptureaddress(zval *device, zval *pInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetBufferOpaqueCaptureAddress fn = (PFN_vkGetBufferOpaqueCaptureAddress) phpvk_entry("vkGetBufferOpaqueCaptureAddress", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkBufferDeviceAddressInfo *) phpvk_arg_ptr(pInfo));
}

zend_long phpvk_vk12_vkgetdevicememoryopaquecaptureaddress(zval *device, zval *pInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetDeviceMemoryOpaqueCaptureAddress fn = (PFN_vkGetDeviceMemoryOpaqueCaptureAddress) phpvk_entry("vkGetDeviceMemoryOpaqueCaptureAddress", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkDeviceMemoryOpaqueCaptureAddressInfo *) phpvk_arg_ptr(pInfo));
}

void phpvk_vk12_vkcmddrawindirectcount(zval *commandBuffer, zval *buffer, zval *offset, zval *countBuffer, zval *countBufferOffset, zval *maxDrawCount, zval *stride)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdDrawIndirectCount fn = (PFN_vkCmdDrawIndirectCount) phpvk_entry("vkCmdDrawIndirectCount", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBuffer) (uintptr_t) phpvk_arg_u64(buffer), (VkDeviceSize) phpvk_arg_u64(offset), (VkBuffer) (uintptr_t) phpvk_arg_u64(countBuffer), (VkDeviceSize) phpvk_arg_u64(countBufferOffset), (uint32_t) phpvk_arg_long(maxDrawCount), (uint32_t) phpvk_arg_long(stride));
}

void phpvk_vk12_vkcmddrawindexedindirectcount(zval *commandBuffer, zval *buffer, zval *offset, zval *countBuffer, zval *countBufferOffset, zval *maxDrawCount, zval *stride)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdDrawIndexedIndirectCount fn = (PFN_vkCmdDrawIndexedIndirectCount) phpvk_entry("vkCmdDrawIndexedIndirectCount", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBuffer) (uintptr_t) phpvk_arg_u64(buffer), (VkDeviceSize) phpvk_arg_u64(offset), (VkBuffer) (uintptr_t) phpvk_arg_u64(countBuffer), (VkDeviceSize) phpvk_arg_u64(countBufferOffset), (uint32_t) phpvk_arg_long(maxDrawCount), (uint32_t) phpvk_arg_long(stride));
}

zend_long phpvk_vk12_vkcreaterenderpass2(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pRenderPass)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateRenderPass2 fn = (PFN_vkCreateRenderPass2) phpvk_entry("vkCreateRenderPass2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkRenderPassCreateInfo2 *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkRenderPass *) phpvk_arg_ptr(pRenderPass));
}

void phpvk_vk12_vkcmdbeginrenderpass2(zval *commandBuffer, zval *pRenderPassBegin, zval *pSubpassBeginInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdBeginRenderPass2 fn = (PFN_vkCmdBeginRenderPass2) phpvk_entry("vkCmdBeginRenderPass2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkRenderPassBeginInfo *) phpvk_arg_ptr(pRenderPassBegin), (const VkSubpassBeginInfo *) phpvk_arg_ptr(pSubpassBeginInfo));
}

void phpvk_vk12_vkcmdnextsubpass2(zval *commandBuffer, zval *pSubpassBeginInfo, zval *pSubpassEndInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdNextSubpass2 fn = (PFN_vkCmdNextSubpass2) phpvk_entry("vkCmdNextSubpass2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkSubpassBeginInfo *) phpvk_arg_ptr(pSubpassBeginInfo), (const VkSubpassEndInfo *) phpvk_arg_ptr(pSubpassEndInfo));
}

void phpvk_vk12_vkcmdendrenderpass2(zval *commandBuffer, zval *pSubpassEndInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdEndRenderPass2 fn = (PFN_vkCmdEndRenderPass2) phpvk_entry("vkCmdEndRenderPass2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkSubpassEndInfo *) phpvk_arg_ptr(pSubpassEndInfo));
}

