/*
 * vk-14.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_VERSION_1_4
 */

#include "vk-14.h"
#include "phpvk-platform.h"
#include "phpvk-bridge.h"
#include "phpvk-support.h"

zend_long phpvk_vk14_vkmapmemory2(zval *device, zval *pMemoryMapInfo, zval *ppData)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkMapMemory2 fn = (PFN_vkMapMemory2) phpvk_entry("vkMapMemory2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkMemoryMapInfo *) phpvk_arg_ptr(pMemoryMapInfo), (void **) phpvk_arg_ptr(ppData));
}

zend_long phpvk_vk14_vkunmapmemory2(zval *device, zval *pMemoryUnmapInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkUnmapMemory2 fn = (PFN_vkUnmapMemory2) phpvk_entry("vkUnmapMemory2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkMemoryUnmapInfo *) phpvk_arg_ptr(pMemoryUnmapInfo));
}

void phpvk_vk14_vkgetdeviceimagesubresourcelayout(zval *device, zval *pInfo, zval *pLayout)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetDeviceImageSubresourceLayout fn = (PFN_vkGetDeviceImageSubresourceLayout) phpvk_entry("vkGetDeviceImageSubresourceLayout", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (const VkDeviceImageSubresourceInfo *) phpvk_arg_ptr(pInfo), (VkSubresourceLayout2 *) phpvk_arg_ptr(pLayout));
}

void phpvk_vk14_vkgetimagesubresourcelayout2(zval *device, zval *image, zval *pSubresource, zval *pLayout)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetImageSubresourceLayout2 fn = (PFN_vkGetImageSubresourceLayout2) phpvk_entry("vkGetImageSubresourceLayout2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkImage) (uintptr_t) phpvk_arg_u64(image), (const VkImageSubresource2 *) phpvk_arg_ptr(pSubresource), (VkSubresourceLayout2 *) phpvk_arg_ptr(pLayout));
}

zend_long phpvk_vk14_vkcopymemorytoimage(zval *device, zval *pCopyMemoryToImageInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCopyMemoryToImage fn = (PFN_vkCopyMemoryToImage) phpvk_entry("vkCopyMemoryToImage", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkCopyMemoryToImageInfo *) phpvk_arg_ptr(pCopyMemoryToImageInfo));
}

zend_long phpvk_vk14_vkcopyimagetomemory(zval *device, zval *pCopyImageToMemoryInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCopyImageToMemory fn = (PFN_vkCopyImageToMemory) phpvk_entry("vkCopyImageToMemory", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkCopyImageToMemoryInfo *) phpvk_arg_ptr(pCopyImageToMemoryInfo));
}

zend_long phpvk_vk14_vkcopyimagetoimage(zval *device, zval *pCopyImageToImageInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCopyImageToImage fn = (PFN_vkCopyImageToImage) phpvk_entry("vkCopyImageToImage", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkCopyImageToImageInfo *) phpvk_arg_ptr(pCopyImageToImageInfo));
}

zend_long phpvk_vk14_vktransitionimagelayout(zval *device, zval *transitionCount, zval *pTransitions)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkTransitionImageLayout fn = (PFN_vkTransitionImageLayout) phpvk_entry("vkTransitionImageLayout", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (uint32_t) phpvk_arg_long(transitionCount), (const VkHostImageLayoutTransitionInfo *) phpvk_arg_ptr(pTransitions));
}

void phpvk_vk14_vkcmdpushdescriptorset(zval *commandBuffer, zval *pipelineBindPoint, zval *layout, zval *set, zval *descriptorWriteCount, zval *pDescriptorWrites)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdPushDescriptorSet fn = (PFN_vkCmdPushDescriptorSet) phpvk_entry("vkCmdPushDescriptorSet", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkPipelineBindPoint) phpvk_arg_long(pipelineBindPoint), (VkPipelineLayout) (uintptr_t) phpvk_arg_u64(layout), (uint32_t) phpvk_arg_long(set), (uint32_t) phpvk_arg_long(descriptorWriteCount), (const VkWriteDescriptorSet *) phpvk_arg_ptr(pDescriptorWrites));
}

void phpvk_vk14_vkcmdpushdescriptorsetwithtemplate(zval *commandBuffer, zval *descriptorUpdateTemplate, zval *layout, zval *set, zval *pData)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdPushDescriptorSetWithTemplate fn = (PFN_vkCmdPushDescriptorSetWithTemplate) phpvk_entry("vkCmdPushDescriptorSetWithTemplate", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkDescriptorUpdateTemplate) (uintptr_t) phpvk_arg_u64(descriptorUpdateTemplate), (VkPipelineLayout) (uintptr_t) phpvk_arg_u64(layout), (uint32_t) phpvk_arg_long(set), (const void *) phpvk_arg_ptr(pData));
}

void phpvk_vk14_vkcmdbinddescriptorsets2(zval *commandBuffer, zval *pBindDescriptorSetsInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdBindDescriptorSets2 fn = (PFN_vkCmdBindDescriptorSets2) phpvk_entry("vkCmdBindDescriptorSets2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkBindDescriptorSetsInfo *) phpvk_arg_ptr(pBindDescriptorSetsInfo));
}

void phpvk_vk14_vkcmdpushconstants2(zval *commandBuffer, zval *pPushConstantsInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdPushConstants2 fn = (PFN_vkCmdPushConstants2) phpvk_entry("vkCmdPushConstants2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkPushConstantsInfo *) phpvk_arg_ptr(pPushConstantsInfo));
}

void phpvk_vk14_vkcmdpushdescriptorset2(zval *commandBuffer, zval *pPushDescriptorSetInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdPushDescriptorSet2 fn = (PFN_vkCmdPushDescriptorSet2) phpvk_entry("vkCmdPushDescriptorSet2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkPushDescriptorSetInfo *) phpvk_arg_ptr(pPushDescriptorSetInfo));
}

void phpvk_vk14_vkcmdpushdescriptorsetwithtemplate2(zval *commandBuffer, zval *pPushDescriptorSetWithTemplateInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdPushDescriptorSetWithTemplate2 fn = (PFN_vkCmdPushDescriptorSetWithTemplate2) phpvk_entry("vkCmdPushDescriptorSetWithTemplate2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkPushDescriptorSetWithTemplateInfo *) phpvk_arg_ptr(pPushDescriptorSetWithTemplateInfo));
}

void phpvk_vk14_vkcmdsetlinestipple(zval *commandBuffer, zval *lineStippleFactor, zval *lineStipplePattern)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetLineStipple fn = (PFN_vkCmdSetLineStipple) phpvk_entry("vkCmdSetLineStipple", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (uint32_t) phpvk_arg_long(lineStippleFactor), (uint16_t) phpvk_arg_long(lineStipplePattern));
}

void phpvk_vk14_vkcmdbindindexbuffer2(zval *commandBuffer, zval *buffer, zval *offset, zval *size, zval *indexType)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdBindIndexBuffer2 fn = (PFN_vkCmdBindIndexBuffer2) phpvk_entry("vkCmdBindIndexBuffer2", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (VkBuffer) (uintptr_t) phpvk_arg_u64(buffer), (VkDeviceSize) phpvk_arg_u64(offset), (VkDeviceSize) phpvk_arg_u64(size), (VkIndexType) phpvk_arg_long(indexType));
}

void phpvk_vk14_vkgetrenderingareagranularity(zval *device, zval *pRenderingAreaInfo, zval *pGranularity)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetRenderingAreaGranularity fn = (PFN_vkGetRenderingAreaGranularity) phpvk_entry("vkGetRenderingAreaGranularity", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (const VkRenderingAreaInfo *) phpvk_arg_ptr(pRenderingAreaInfo), (VkExtent2D *) phpvk_arg_ptr(pGranularity));
}

void phpvk_vk14_vkcmdsetrenderingattachmentlocations(zval *commandBuffer, zval *pLocationInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetRenderingAttachmentLocations fn = (PFN_vkCmdSetRenderingAttachmentLocations) phpvk_entry("vkCmdSetRenderingAttachmentLocations", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkRenderingAttachmentLocationInfo *) phpvk_arg_ptr(pLocationInfo));
}

void phpvk_vk14_vkcmdsetrenderinginputattachmentindices(zval *commandBuffer, zval *pInputAttachmentIndexInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCmdSetRenderingInputAttachmentIndices fn = (PFN_vkCmdSetRenderingInputAttachmentIndices) phpvk_entry("vkCmdSetRenderingInputAttachmentIndices", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkCommandBuffer) phpvk_arg_ptr(commandBuffer), (const VkRenderingInputAttachmentIndexInfo *) phpvk_arg_ptr(pInputAttachmentIndexInfo));
}

