/*
 * vk-ext-khrwaylandsurface.h — Vulkan\Ext\KHRWaylandSurface bound 1:1.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_KHR_wayland_surface (2 commands)
 */

#ifndef PHPVK_VK_EXT_KHRWAYLANDSURFACE_H
#define PHPVK_VK_EXT_KHRWAYLANDSURFACE_H

#include <php.h>

/*@audit extension Ext\KHRWaylandSurface VK_KHR_wayland_surface 2 */

/*@zep Ext\KHRWaylandSurface vkCreateWaylandSurfaceKHR(int instance, int pCreateInfo, int pAllocator, int pSurface) -> int */
zend_long phpvk_khrwaylandsurface_vkcreatewaylandsurfacekhr(zval *instance, zval *pCreateInfo, zval *pAllocator, zval *pSurface);

/*@zep Ext\KHRWaylandSurface vkGetPhysicalDeviceWaylandPresentationSupportKHR(int physicalDevice, int queueFamilyIndex, int display) -> bool */
zend_long phpvk_khrwaylandsurface_vkgetphysicaldevicewaylandpresentationsupportkhr(zval *physicalDevice, zval *queueFamilyIndex, zval *display);

#endif
