/*
 * vk-ext-khrswapchain.h — Vulkan\Ext\KHRSwapchain bound 1:1.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_KHR_swapchain (9 commands)
 */

#ifndef PHPVK_VK_EXT_KHRSWAPCHAIN_H
#define PHPVK_VK_EXT_KHRSWAPCHAIN_H

#include <php.h>

/*@audit extension Ext\KHRSwapchain VK_KHR_swapchain 9 */

/*@zep Ext\KHRSwapchain vkCreateSwapchainKHR(int device, int pCreateInfo, int pAllocator, int pSwapchain) -> int */
zend_long phpvk_khrswapchain_vkcreateswapchainkhr(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pSwapchain);

/*@zep Ext\KHRSwapchain vkDestroySwapchainKHR(int device, int swapchain, int pAllocator) -> void */
void phpvk_khrswapchain_vkdestroyswapchainkhr(zval *device, zval *swapchain, zval *pAllocator);

/*@zep Ext\KHRSwapchain vkGetSwapchainImagesKHR(int device, int swapchain, int pSwapchainImageCount, int pSwapchainImages) -> int */
zend_long phpvk_khrswapchain_vkgetswapchainimageskhr(zval *device, zval *swapchain, zval *pSwapchainImageCount, zval *pSwapchainImages);

/*@zep Ext\KHRSwapchain vkAcquireNextImageKHR(int device, int swapchain, int timeout, int semaphore, int fence, int pImageIndex) -> int */
zend_long phpvk_khrswapchain_vkacquirenextimagekhr(zval *device, zval *swapchain, zval *timeout, zval *semaphore, zval *fence, zval *pImageIndex);

/*@zep Ext\KHRSwapchain vkQueuePresentKHR(int queue, int pPresentInfo) -> int */
zend_long phpvk_khrswapchain_vkqueuepresentkhr(zval *queue, zval *pPresentInfo);

/*@zep Ext\KHRSwapchain vkGetDeviceGroupPresentCapabilitiesKHR(int device, int pDeviceGroupPresentCapabilities) -> int */
zend_long phpvk_khrswapchain_vkgetdevicegrouppresentcapabilitieskhr(zval *device, zval *pDeviceGroupPresentCapabilities);

/*@zep Ext\KHRSwapchain vkGetDeviceGroupSurfacePresentModesKHR(int device, int surface, int pModes) -> int */
zend_long phpvk_khrswapchain_vkgetdevicegroupsurfacepresentmodeskhr(zval *device, zval *surface, zval *pModes);

/*@zep Ext\KHRSwapchain vkGetPhysicalDevicePresentRectanglesKHR(int physicalDevice, int surface, int pRectCount, int pRects) -> int */
zend_long phpvk_khrswapchain_vkgetphysicaldevicepresentrectangleskhr(zval *physicalDevice, zval *surface, zval *pRectCount, zval *pRects);

/*@zep Ext\KHRSwapchain vkAcquireNextImage2KHR(int device, int pAcquireInfo, int pImageIndex) -> int */
zend_long phpvk_khrswapchain_vkacquirenextimage2khr(zval *device, zval *pAcquireInfo, zval *pImageIndex);

#endif
