/*
 * vk-ext-extmetalsurface.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_EXT_metal_surface
 */

#include "vk-ext-extmetalsurface.h"
#include "phpvk-platform.h"
#include "phpvk-bridge.h"
#include "phpvk-support.h"

zend_long phpvk_extmetalsurface_vkcreatemetalsurfaceext(zval *instance, zval *pCreateInfo, zval *pAllocator, zval *pSurface)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateMetalSurfaceEXT fn = (PFN_vkCreateMetalSurfaceEXT) phpvk_entry("vkCreateMetalSurfaceEXT", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkInstance) phpvk_arg_ptr(instance), (const VkMetalSurfaceCreateInfoEXT *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkSurfaceKHR *) phpvk_arg_ptr(pSurface));
}

