/*
 * vk-ext-extmetalobjects.h — Vulkan\Ext\EXTMetalObjects bound 1:1.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_EXT_metal_objects (1 commands)
 */

#ifndef PHPVK_VK_EXT_EXTMETALOBJECTS_H
#define PHPVK_VK_EXT_EXTMETALOBJECTS_H

#include <php.h>

/*@audit extension Ext\EXTMetalObjects VK_EXT_metal_objects 1 */

/*@zep Ext\EXTMetalObjects vkExportMetalObjectsEXT(int device, int pMetalObjectsInfo) -> void */
void phpvk_extmetalobjects_vkexportmetalobjectsext(zval *device, zval *pMetalObjectsInfo);

#endif
