/*
 * vk-ext-khrswapchain.c — one call through the Bridge loader per binding.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md), VK_KHR_swapchain
 */

#include "vk-ext-khrswapchain.h"
#include "phpvk-platform.h"
#include "phpvk-bridge.h"
#include "phpvk-support.h"

zend_long phpvk_khrswapchain_vkcreateswapchainkhr(zval *device, zval *pCreateInfo, zval *pAllocator, zval *pSwapchain)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkCreateSwapchainKHR fn = (PFN_vkCreateSwapchainKHR) phpvk_entry("vkCreateSwapchainKHR", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkSwapchainCreateInfoKHR *) phpvk_arg_ptr(pCreateInfo), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator), (VkSwapchainKHR *) phpvk_arg_ptr(pSwapchain));
}

void phpvk_khrswapchain_vkdestroyswapchainkhr(zval *device, zval *swapchain, zval *pAllocator)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkDestroySwapchainKHR fn = (PFN_vkDestroySwapchainKHR) phpvk_entry("vkDestroySwapchainKHR", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return;
    }

    fn((VkDevice) phpvk_arg_ptr(device), (VkSwapchainKHR) (uintptr_t) phpvk_arg_u64(swapchain), (const VkAllocationCallbacks *) phpvk_arg_ptr(pAllocator));
}

zend_long phpvk_khrswapchain_vkgetswapchainimageskhr(zval *device, zval *swapchain, zval *pSwapchainImageCount, zval *pSwapchainImages)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetSwapchainImagesKHR fn = (PFN_vkGetSwapchainImagesKHR) phpvk_entry("vkGetSwapchainImagesKHR", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkSwapchainKHR) (uintptr_t) phpvk_arg_u64(swapchain), (uint32_t *) phpvk_arg_ptr(pSwapchainImageCount), (VkImage *) phpvk_arg_ptr(pSwapchainImages));
}

zend_long phpvk_khrswapchain_vkacquirenextimagekhr(zval *device, zval *swapchain, zval *timeout, zval *semaphore, zval *fence, zval *pImageIndex)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkAcquireNextImageKHR fn = (PFN_vkAcquireNextImageKHR) phpvk_entry("vkAcquireNextImageKHR", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkSwapchainKHR) (uintptr_t) phpvk_arg_u64(swapchain), (uint64_t) phpvk_arg_u64(timeout), (VkSemaphore) (uintptr_t) phpvk_arg_u64(semaphore), (VkFence) (uintptr_t) phpvk_arg_u64(fence), (uint32_t *) phpvk_arg_ptr(pImageIndex));
}

zend_long phpvk_khrswapchain_vkqueuepresentkhr(zval *queue, zval *pPresentInfo)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkQueuePresentKHR fn = (PFN_vkQueuePresentKHR) phpvk_entry("vkQueuePresentKHR", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkQueue) phpvk_arg_ptr(queue), (const VkPresentInfoKHR *) phpvk_arg_ptr(pPresentInfo));
}

zend_long phpvk_khrswapchain_vkgetdevicegrouppresentcapabilitieskhr(zval *device, zval *pDeviceGroupPresentCapabilities)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetDeviceGroupPresentCapabilitiesKHR fn = (PFN_vkGetDeviceGroupPresentCapabilitiesKHR) phpvk_entry("vkGetDeviceGroupPresentCapabilitiesKHR", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkDeviceGroupPresentCapabilitiesKHR *) phpvk_arg_ptr(pDeviceGroupPresentCapabilities));
}

zend_long phpvk_khrswapchain_vkgetdevicegroupsurfacepresentmodeskhr(zval *device, zval *surface, zval *pModes)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetDeviceGroupSurfacePresentModesKHR fn = (PFN_vkGetDeviceGroupSurfacePresentModesKHR) phpvk_entry("vkGetDeviceGroupSurfacePresentModesKHR", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (VkSurfaceKHR) (uintptr_t) phpvk_arg_u64(surface), (VkDeviceGroupPresentModeFlagsKHR *) phpvk_arg_ptr(pModes));
}

zend_long phpvk_khrswapchain_vkgetphysicaldevicepresentrectangleskhr(zval *physicalDevice, zval *surface, zval *pRectCount, zval *pRects)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkGetPhysicalDevicePresentRectanglesKHR fn = (PFN_vkGetPhysicalDevicePresentRectanglesKHR) phpvk_entry("vkGetPhysicalDevicePresentRectanglesKHR", &slot, PHPVK_LEVEL_INSTANCE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkPhysicalDevice) phpvk_arg_ptr(physicalDevice), (VkSurfaceKHR) (uintptr_t) phpvk_arg_u64(surface), (uint32_t *) phpvk_arg_ptr(pRectCount), (VkRect2D *) phpvk_arg_ptr(pRects));
}

zend_long phpvk_khrswapchain_vkacquirenextimage2khr(zval *device, zval *pAcquireInfo, zval *pImageIndex)
{
    static phpvk_slot slot = PHPVK_SLOT_INIT;
    PFN_vkAcquireNextImage2KHR fn = (PFN_vkAcquireNextImage2KHR) phpvk_entry("vkAcquireNextImage2KHR", &slot, PHPVK_LEVEL_DEVICE);

    if (!fn) {
        return 0;
    }

    return (zend_long) fn((VkDevice) phpvk_arg_ptr(device), (const VkAcquireNextImageInfoKHR *) phpvk_arg_ptr(pAcquireInfo), (uint32_t *) phpvk_arg_ptr(pImageIndex));
}

