/*
 * vk-struct-10.h — Vulkan\Struct\<Name> flat pack/unpack.
 *
 * GENERATED by scripts/gen-vk-src.php — DO NOT EDIT.
 * Source of truth: scripts/khronos/vk.xml (see scripts/khronos/README.md)
 */

#ifndef PHPVK_VK_STRUCT_10_H
#define PHPVK_VK_STRUCT_10_H

#include <php.h>

/*@zep Struct\VkExtent2D pack(array members) -> int */
zend_long phpvk_struct_vkextent2d_pack(zval *members);

/*@zep Struct\VkExtent2D packInto(int ptr, array members) -> void */
void phpvk_struct_vkextent2d_packinto(zval *ptr, zval *members);

/*@zep Struct\VkExtent2D unpack(int ptr) -> array */
void phpvk_struct_vkextent2d_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkExtent2D size() -> int */
zend_long phpvk_struct_vkextent2d_size(void);

/*@zep Struct\VkExtent3D pack(array members) -> int */
zend_long phpvk_struct_vkextent3d_pack(zval *members);

/*@zep Struct\VkExtent3D packInto(int ptr, array members) -> void */
void phpvk_struct_vkextent3d_packinto(zval *ptr, zval *members);

/*@zep Struct\VkExtent3D unpack(int ptr) -> array */
void phpvk_struct_vkextent3d_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkExtent3D size() -> int */
zend_long phpvk_struct_vkextent3d_size(void);

/*@zep Struct\VkOffset2D pack(array members) -> int */
zend_long phpvk_struct_vkoffset2d_pack(zval *members);

/*@zep Struct\VkOffset2D packInto(int ptr, array members) -> void */
void phpvk_struct_vkoffset2d_packinto(zval *ptr, zval *members);

/*@zep Struct\VkOffset2D unpack(int ptr) -> array */
void phpvk_struct_vkoffset2d_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkOffset2D size() -> int */
zend_long phpvk_struct_vkoffset2d_size(void);

/*@zep Struct\VkOffset3D pack(array members) -> int */
zend_long phpvk_struct_vkoffset3d_pack(zval *members);

/*@zep Struct\VkOffset3D packInto(int ptr, array members) -> void */
void phpvk_struct_vkoffset3d_packinto(zval *ptr, zval *members);

/*@zep Struct\VkOffset3D unpack(int ptr) -> array */
void phpvk_struct_vkoffset3d_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkOffset3D size() -> int */
zend_long phpvk_struct_vkoffset3d_size(void);

/*@zep Struct\VkRect2D pack(array members) -> int */
zend_long phpvk_struct_vkrect2d_pack(zval *members);

/*@zep Struct\VkRect2D packInto(int ptr, array members) -> void */
void phpvk_struct_vkrect2d_packinto(zval *ptr, zval *members);

/*@zep Struct\VkRect2D unpack(int ptr) -> array */
void phpvk_struct_vkrect2d_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkRect2D size() -> int */
zend_long phpvk_struct_vkrect2d_size(void);

/*@zep Struct\VkBaseInStructure pack(array members) -> int */
zend_long phpvk_struct_vkbaseinstructure_pack(zval *members);

/*@zep Struct\VkBaseInStructure packInto(int ptr, array members) -> void */
void phpvk_struct_vkbaseinstructure_packinto(zval *ptr, zval *members);

/*@zep Struct\VkBaseInStructure unpack(int ptr) -> array */
void phpvk_struct_vkbaseinstructure_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkBaseInStructure size() -> int */
zend_long phpvk_struct_vkbaseinstructure_size(void);

/*@zep Struct\VkBaseOutStructure pack(array members) -> int */
zend_long phpvk_struct_vkbaseoutstructure_pack(zval *members);

/*@zep Struct\VkBaseOutStructure packInto(int ptr, array members) -> void */
void phpvk_struct_vkbaseoutstructure_packinto(zval *ptr, zval *members);

/*@zep Struct\VkBaseOutStructure unpack(int ptr) -> array */
void phpvk_struct_vkbaseoutstructure_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkBaseOutStructure size() -> int */
zend_long phpvk_struct_vkbaseoutstructure_size(void);

/*@zep Struct\VkAllocationCallbacks pack(array members) -> int */
zend_long phpvk_struct_vkallocationcallbacks_pack(zval *members);

/*@zep Struct\VkAllocationCallbacks packInto(int ptr, array members) -> void */
void phpvk_struct_vkallocationcallbacks_packinto(zval *ptr, zval *members);

/*@zep Struct\VkAllocationCallbacks unpack(int ptr) -> array */
void phpvk_struct_vkallocationcallbacks_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkAllocationCallbacks size() -> int */
zend_long phpvk_struct_vkallocationcallbacks_size(void);

/*@zep Struct\VkApplicationInfo pack(array members) -> int */
zend_long phpvk_struct_vkapplicationinfo_pack(zval *members);

/*@zep Struct\VkApplicationInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkapplicationinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkApplicationInfo unpack(int ptr) -> array */
void phpvk_struct_vkapplicationinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkApplicationInfo size() -> int */
zend_long phpvk_struct_vkapplicationinfo_size(void);

/*@zep Struct\VkFormatProperties pack(array members) -> int */
zend_long phpvk_struct_vkformatproperties_pack(zval *members);

/*@zep Struct\VkFormatProperties packInto(int ptr, array members) -> void */
void phpvk_struct_vkformatproperties_packinto(zval *ptr, zval *members);

/*@zep Struct\VkFormatProperties unpack(int ptr) -> array */
void phpvk_struct_vkformatproperties_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkFormatProperties size() -> int */
zend_long phpvk_struct_vkformatproperties_size(void);

/*@zep Struct\VkImageFormatProperties pack(array members) -> int */
zend_long phpvk_struct_vkimageformatproperties_pack(zval *members);

/*@zep Struct\VkImageFormatProperties packInto(int ptr, array members) -> void */
void phpvk_struct_vkimageformatproperties_packinto(zval *ptr, zval *members);

/*@zep Struct\VkImageFormatProperties unpack(int ptr) -> array */
void phpvk_struct_vkimageformatproperties_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkImageFormatProperties size() -> int */
zend_long phpvk_struct_vkimageformatproperties_size(void);

/*@zep Struct\VkInstanceCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkinstancecreateinfo_pack(zval *members);

/*@zep Struct\VkInstanceCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkinstancecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkInstanceCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkinstancecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkInstanceCreateInfo size() -> int */
zend_long phpvk_struct_vkinstancecreateinfo_size(void);

/*@zep Struct\VkMemoryHeap pack(array members) -> int */
zend_long phpvk_struct_vkmemoryheap_pack(zval *members);

/*@zep Struct\VkMemoryHeap packInto(int ptr, array members) -> void */
void phpvk_struct_vkmemoryheap_packinto(zval *ptr, zval *members);

/*@zep Struct\VkMemoryHeap unpack(int ptr) -> array */
void phpvk_struct_vkmemoryheap_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkMemoryHeap size() -> int */
zend_long phpvk_struct_vkmemoryheap_size(void);

/*@zep Struct\VkMemoryType pack(array members) -> int */
zend_long phpvk_struct_vkmemorytype_pack(zval *members);

/*@zep Struct\VkMemoryType packInto(int ptr, array members) -> void */
void phpvk_struct_vkmemorytype_packinto(zval *ptr, zval *members);

/*@zep Struct\VkMemoryType unpack(int ptr) -> array */
void phpvk_struct_vkmemorytype_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkMemoryType size() -> int */
zend_long phpvk_struct_vkmemorytype_size(void);

/*@zep Struct\VkPhysicalDeviceFeatures pack(array members) -> int */
zend_long phpvk_struct_vkphysicaldevicefeatures_pack(zval *members);

/*@zep Struct\VkPhysicalDeviceFeatures packInto(int ptr, array members) -> void */
void phpvk_struct_vkphysicaldevicefeatures_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPhysicalDeviceFeatures unpack(int ptr) -> array */
void phpvk_struct_vkphysicaldevicefeatures_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPhysicalDeviceFeatures size() -> int */
zend_long phpvk_struct_vkphysicaldevicefeatures_size(void);

/*@zep Struct\VkPhysicalDeviceLimits pack(array members) -> int */
zend_long phpvk_struct_vkphysicaldevicelimits_pack(zval *members);

/*@zep Struct\VkPhysicalDeviceLimits packInto(int ptr, array members) -> void */
void phpvk_struct_vkphysicaldevicelimits_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPhysicalDeviceLimits unpack(int ptr) -> array */
void phpvk_struct_vkphysicaldevicelimits_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPhysicalDeviceLimits size() -> int */
zend_long phpvk_struct_vkphysicaldevicelimits_size(void);

/*@zep Struct\VkPhysicalDeviceMemoryProperties pack(array members) -> int */
zend_long phpvk_struct_vkphysicaldevicememoryproperties_pack(zval *members);

/*@zep Struct\VkPhysicalDeviceMemoryProperties packInto(int ptr, array members) -> void */
void phpvk_struct_vkphysicaldevicememoryproperties_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPhysicalDeviceMemoryProperties unpack(int ptr) -> array */
void phpvk_struct_vkphysicaldevicememoryproperties_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPhysicalDeviceMemoryProperties size() -> int */
zend_long phpvk_struct_vkphysicaldevicememoryproperties_size(void);

/*@zep Struct\VkPhysicalDeviceSparseProperties pack(array members) -> int */
zend_long phpvk_struct_vkphysicaldevicesparseproperties_pack(zval *members);

/*@zep Struct\VkPhysicalDeviceSparseProperties packInto(int ptr, array members) -> void */
void phpvk_struct_vkphysicaldevicesparseproperties_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPhysicalDeviceSparseProperties unpack(int ptr) -> array */
void phpvk_struct_vkphysicaldevicesparseproperties_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPhysicalDeviceSparseProperties size() -> int */
zend_long phpvk_struct_vkphysicaldevicesparseproperties_size(void);

/*@zep Struct\VkPhysicalDeviceProperties pack(array members) -> int */
zend_long phpvk_struct_vkphysicaldeviceproperties_pack(zval *members);

/*@zep Struct\VkPhysicalDeviceProperties packInto(int ptr, array members) -> void */
void phpvk_struct_vkphysicaldeviceproperties_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPhysicalDeviceProperties unpack(int ptr) -> array */
void phpvk_struct_vkphysicaldeviceproperties_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPhysicalDeviceProperties size() -> int */
zend_long phpvk_struct_vkphysicaldeviceproperties_size(void);

/*@zep Struct\VkQueueFamilyProperties pack(array members) -> int */
zend_long phpvk_struct_vkqueuefamilyproperties_pack(zval *members);

/*@zep Struct\VkQueueFamilyProperties packInto(int ptr, array members) -> void */
void phpvk_struct_vkqueuefamilyproperties_packinto(zval *ptr, zval *members);

/*@zep Struct\VkQueueFamilyProperties unpack(int ptr) -> array */
void phpvk_struct_vkqueuefamilyproperties_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkQueueFamilyProperties size() -> int */
zend_long phpvk_struct_vkqueuefamilyproperties_size(void);

/*@zep Struct\VkDeviceQueueCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkdevicequeuecreateinfo_pack(zval *members);

/*@zep Struct\VkDeviceQueueCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkdevicequeuecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkDeviceQueueCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkdevicequeuecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkDeviceQueueCreateInfo size() -> int */
zend_long phpvk_struct_vkdevicequeuecreateinfo_size(void);

/*@zep Struct\VkDeviceCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkdevicecreateinfo_pack(zval *members);

/*@zep Struct\VkDeviceCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkdevicecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkDeviceCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkdevicecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkDeviceCreateInfo size() -> int */
zend_long phpvk_struct_vkdevicecreateinfo_size(void);

/*@zep Struct\VkExtensionProperties pack(array members) -> int */
zend_long phpvk_struct_vkextensionproperties_pack(zval *members);

/*@zep Struct\VkExtensionProperties packInto(int ptr, array members) -> void */
void phpvk_struct_vkextensionproperties_packinto(zval *ptr, zval *members);

/*@zep Struct\VkExtensionProperties unpack(int ptr) -> array */
void phpvk_struct_vkextensionproperties_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkExtensionProperties size() -> int */
zend_long phpvk_struct_vkextensionproperties_size(void);

/*@zep Struct\VkLayerProperties pack(array members) -> int */
zend_long phpvk_struct_vklayerproperties_pack(zval *members);

/*@zep Struct\VkLayerProperties packInto(int ptr, array members) -> void */
void phpvk_struct_vklayerproperties_packinto(zval *ptr, zval *members);

/*@zep Struct\VkLayerProperties unpack(int ptr) -> array */
void phpvk_struct_vklayerproperties_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkLayerProperties size() -> int */
zend_long phpvk_struct_vklayerproperties_size(void);

/*@zep Struct\VkSubmitInfo pack(array members) -> int */
zend_long phpvk_struct_vksubmitinfo_pack(zval *members);

/*@zep Struct\VkSubmitInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vksubmitinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkSubmitInfo unpack(int ptr) -> array */
void phpvk_struct_vksubmitinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkSubmitInfo size() -> int */
zend_long phpvk_struct_vksubmitinfo_size(void);

/*@zep Struct\VkMappedMemoryRange pack(array members) -> int */
zend_long phpvk_struct_vkmappedmemoryrange_pack(zval *members);

/*@zep Struct\VkMappedMemoryRange packInto(int ptr, array members) -> void */
void phpvk_struct_vkmappedmemoryrange_packinto(zval *ptr, zval *members);

/*@zep Struct\VkMappedMemoryRange unpack(int ptr) -> array */
void phpvk_struct_vkmappedmemoryrange_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkMappedMemoryRange size() -> int */
zend_long phpvk_struct_vkmappedmemoryrange_size(void);

/*@zep Struct\VkMemoryAllocateInfo pack(array members) -> int */
zend_long phpvk_struct_vkmemoryallocateinfo_pack(zval *members);

/*@zep Struct\VkMemoryAllocateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkmemoryallocateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkMemoryAllocateInfo unpack(int ptr) -> array */
void phpvk_struct_vkmemoryallocateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkMemoryAllocateInfo size() -> int */
zend_long phpvk_struct_vkmemoryallocateinfo_size(void);

/*@zep Struct\VkMemoryRequirements pack(array members) -> int */
zend_long phpvk_struct_vkmemoryrequirements_pack(zval *members);

/*@zep Struct\VkMemoryRequirements packInto(int ptr, array members) -> void */
void phpvk_struct_vkmemoryrequirements_packinto(zval *ptr, zval *members);

/*@zep Struct\VkMemoryRequirements unpack(int ptr) -> array */
void phpvk_struct_vkmemoryrequirements_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkMemoryRequirements size() -> int */
zend_long phpvk_struct_vkmemoryrequirements_size(void);

/*@zep Struct\VkImageSubresource pack(array members) -> int */
zend_long phpvk_struct_vkimagesubresource_pack(zval *members);

/*@zep Struct\VkImageSubresource packInto(int ptr, array members) -> void */
void phpvk_struct_vkimagesubresource_packinto(zval *ptr, zval *members);

/*@zep Struct\VkImageSubresource unpack(int ptr) -> array */
void phpvk_struct_vkimagesubresource_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkImageSubresource size() -> int */
zend_long phpvk_struct_vkimagesubresource_size(void);

/*@zep Struct\VkSparseImageFormatProperties pack(array members) -> int */
zend_long phpvk_struct_vksparseimageformatproperties_pack(zval *members);

/*@zep Struct\VkSparseImageFormatProperties packInto(int ptr, array members) -> void */
void phpvk_struct_vksparseimageformatproperties_packinto(zval *ptr, zval *members);

/*@zep Struct\VkSparseImageFormatProperties unpack(int ptr) -> array */
void phpvk_struct_vksparseimageformatproperties_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkSparseImageFormatProperties size() -> int */
zend_long phpvk_struct_vksparseimageformatproperties_size(void);

/*@zep Struct\VkSparseImageMemoryBind pack(array members) -> int */
zend_long phpvk_struct_vksparseimagememorybind_pack(zval *members);

/*@zep Struct\VkSparseImageMemoryBind packInto(int ptr, array members) -> void */
void phpvk_struct_vksparseimagememorybind_packinto(zval *ptr, zval *members);

/*@zep Struct\VkSparseImageMemoryBind unpack(int ptr) -> array */
void phpvk_struct_vksparseimagememorybind_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkSparseImageMemoryBind size() -> int */
zend_long phpvk_struct_vksparseimagememorybind_size(void);

/*@zep Struct\VkSparseImageMemoryBindInfo pack(array members) -> int */
zend_long phpvk_struct_vksparseimagememorybindinfo_pack(zval *members);

/*@zep Struct\VkSparseImageMemoryBindInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vksparseimagememorybindinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkSparseImageMemoryBindInfo unpack(int ptr) -> array */
void phpvk_struct_vksparseimagememorybindinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkSparseImageMemoryBindInfo size() -> int */
zend_long phpvk_struct_vksparseimagememorybindinfo_size(void);

/*@zep Struct\VkSparseImageMemoryRequirements pack(array members) -> int */
zend_long phpvk_struct_vksparseimagememoryrequirements_pack(zval *members);

/*@zep Struct\VkSparseImageMemoryRequirements packInto(int ptr, array members) -> void */
void phpvk_struct_vksparseimagememoryrequirements_packinto(zval *ptr, zval *members);

/*@zep Struct\VkSparseImageMemoryRequirements unpack(int ptr) -> array */
void phpvk_struct_vksparseimagememoryrequirements_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkSparseImageMemoryRequirements size() -> int */
zend_long phpvk_struct_vksparseimagememoryrequirements_size(void);

/*@zep Struct\VkSparseMemoryBind pack(array members) -> int */
zend_long phpvk_struct_vksparsememorybind_pack(zval *members);

/*@zep Struct\VkSparseMemoryBind packInto(int ptr, array members) -> void */
void phpvk_struct_vksparsememorybind_packinto(zval *ptr, zval *members);

/*@zep Struct\VkSparseMemoryBind unpack(int ptr) -> array */
void phpvk_struct_vksparsememorybind_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkSparseMemoryBind size() -> int */
zend_long phpvk_struct_vksparsememorybind_size(void);

/*@zep Struct\VkSparseBufferMemoryBindInfo pack(array members) -> int */
zend_long phpvk_struct_vksparsebuffermemorybindinfo_pack(zval *members);

/*@zep Struct\VkSparseBufferMemoryBindInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vksparsebuffermemorybindinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkSparseBufferMemoryBindInfo unpack(int ptr) -> array */
void phpvk_struct_vksparsebuffermemorybindinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkSparseBufferMemoryBindInfo size() -> int */
zend_long phpvk_struct_vksparsebuffermemorybindinfo_size(void);

/*@zep Struct\VkSparseImageOpaqueMemoryBindInfo pack(array members) -> int */
zend_long phpvk_struct_vksparseimageopaquememorybindinfo_pack(zval *members);

/*@zep Struct\VkSparseImageOpaqueMemoryBindInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vksparseimageopaquememorybindinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkSparseImageOpaqueMemoryBindInfo unpack(int ptr) -> array */
void phpvk_struct_vksparseimageopaquememorybindinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkSparseImageOpaqueMemoryBindInfo size() -> int */
zend_long phpvk_struct_vksparseimageopaquememorybindinfo_size(void);

/*@zep Struct\VkBindSparseInfo pack(array members) -> int */
zend_long phpvk_struct_vkbindsparseinfo_pack(zval *members);

/*@zep Struct\VkBindSparseInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkbindsparseinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkBindSparseInfo unpack(int ptr) -> array */
void phpvk_struct_vkbindsparseinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkBindSparseInfo size() -> int */
zend_long phpvk_struct_vkbindsparseinfo_size(void);

/*@zep Struct\VkFenceCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkfencecreateinfo_pack(zval *members);

/*@zep Struct\VkFenceCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkfencecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkFenceCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkfencecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkFenceCreateInfo size() -> int */
zend_long phpvk_struct_vkfencecreateinfo_size(void);

/*@zep Struct\VkSemaphoreCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vksemaphorecreateinfo_pack(zval *members);

/*@zep Struct\VkSemaphoreCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vksemaphorecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkSemaphoreCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vksemaphorecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkSemaphoreCreateInfo size() -> int */
zend_long phpvk_struct_vksemaphorecreateinfo_size(void);

/*@zep Struct\VkQueryPoolCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkquerypoolcreateinfo_pack(zval *members);

/*@zep Struct\VkQueryPoolCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkquerypoolcreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkQueryPoolCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkquerypoolcreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkQueryPoolCreateInfo size() -> int */
zend_long phpvk_struct_vkquerypoolcreateinfo_size(void);

/*@zep Struct\VkBufferCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkbuffercreateinfo_pack(zval *members);

/*@zep Struct\VkBufferCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkbuffercreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkBufferCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkbuffercreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkBufferCreateInfo size() -> int */
zend_long phpvk_struct_vkbuffercreateinfo_size(void);

/*@zep Struct\VkImageCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkimagecreateinfo_pack(zval *members);

/*@zep Struct\VkImageCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkimagecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkImageCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkimagecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkImageCreateInfo size() -> int */
zend_long phpvk_struct_vkimagecreateinfo_size(void);

/*@zep Struct\VkSubresourceLayout pack(array members) -> int */
zend_long phpvk_struct_vksubresourcelayout_pack(zval *members);

/*@zep Struct\VkSubresourceLayout packInto(int ptr, array members) -> void */
void phpvk_struct_vksubresourcelayout_packinto(zval *ptr, zval *members);

/*@zep Struct\VkSubresourceLayout unpack(int ptr) -> array */
void phpvk_struct_vksubresourcelayout_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkSubresourceLayout size() -> int */
zend_long phpvk_struct_vksubresourcelayout_size(void);

/*@zep Struct\VkComponentMapping pack(array members) -> int */
zend_long phpvk_struct_vkcomponentmapping_pack(zval *members);

/*@zep Struct\VkComponentMapping packInto(int ptr, array members) -> void */
void phpvk_struct_vkcomponentmapping_packinto(zval *ptr, zval *members);

/*@zep Struct\VkComponentMapping unpack(int ptr) -> array */
void phpvk_struct_vkcomponentmapping_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkComponentMapping size() -> int */
zend_long phpvk_struct_vkcomponentmapping_size(void);

/*@zep Struct\VkImageSubresourceRange pack(array members) -> int */
zend_long phpvk_struct_vkimagesubresourcerange_pack(zval *members);

/*@zep Struct\VkImageSubresourceRange packInto(int ptr, array members) -> void */
void phpvk_struct_vkimagesubresourcerange_packinto(zval *ptr, zval *members);

/*@zep Struct\VkImageSubresourceRange unpack(int ptr) -> array */
void phpvk_struct_vkimagesubresourcerange_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkImageSubresourceRange size() -> int */
zend_long phpvk_struct_vkimagesubresourcerange_size(void);

/*@zep Struct\VkImageViewCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkimageviewcreateinfo_pack(zval *members);

/*@zep Struct\VkImageViewCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkimageviewcreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkImageViewCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkimageviewcreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkImageViewCreateInfo size() -> int */
zend_long phpvk_struct_vkimageviewcreateinfo_size(void);

/*@zep Struct\VkCommandPoolCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkcommandpoolcreateinfo_pack(zval *members);

/*@zep Struct\VkCommandPoolCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkcommandpoolcreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkCommandPoolCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkcommandpoolcreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkCommandPoolCreateInfo size() -> int */
zend_long phpvk_struct_vkcommandpoolcreateinfo_size(void);

/*@zep Struct\VkCommandBufferAllocateInfo pack(array members) -> int */
zend_long phpvk_struct_vkcommandbufferallocateinfo_pack(zval *members);

/*@zep Struct\VkCommandBufferAllocateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkcommandbufferallocateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkCommandBufferAllocateInfo unpack(int ptr) -> array */
void phpvk_struct_vkcommandbufferallocateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkCommandBufferAllocateInfo size() -> int */
zend_long phpvk_struct_vkcommandbufferallocateinfo_size(void);

/*@zep Struct\VkCommandBufferInheritanceInfo pack(array members) -> int */
zend_long phpvk_struct_vkcommandbufferinheritanceinfo_pack(zval *members);

/*@zep Struct\VkCommandBufferInheritanceInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkcommandbufferinheritanceinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkCommandBufferInheritanceInfo unpack(int ptr) -> array */
void phpvk_struct_vkcommandbufferinheritanceinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkCommandBufferInheritanceInfo size() -> int */
zend_long phpvk_struct_vkcommandbufferinheritanceinfo_size(void);

/*@zep Struct\VkCommandBufferBeginInfo pack(array members) -> int */
zend_long phpvk_struct_vkcommandbufferbegininfo_pack(zval *members);

/*@zep Struct\VkCommandBufferBeginInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkcommandbufferbegininfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkCommandBufferBeginInfo unpack(int ptr) -> array */
void phpvk_struct_vkcommandbufferbegininfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkCommandBufferBeginInfo size() -> int */
zend_long phpvk_struct_vkcommandbufferbegininfo_size(void);

/*@zep Struct\VkBufferCopy pack(array members) -> int */
zend_long phpvk_struct_vkbuffercopy_pack(zval *members);

/*@zep Struct\VkBufferCopy packInto(int ptr, array members) -> void */
void phpvk_struct_vkbuffercopy_packinto(zval *ptr, zval *members);

/*@zep Struct\VkBufferCopy unpack(int ptr) -> array */
void phpvk_struct_vkbuffercopy_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkBufferCopy size() -> int */
zend_long phpvk_struct_vkbuffercopy_size(void);

/*@zep Struct\VkImageSubresourceLayers pack(array members) -> int */
zend_long phpvk_struct_vkimagesubresourcelayers_pack(zval *members);

/*@zep Struct\VkImageSubresourceLayers packInto(int ptr, array members) -> void */
void phpvk_struct_vkimagesubresourcelayers_packinto(zval *ptr, zval *members);

/*@zep Struct\VkImageSubresourceLayers unpack(int ptr) -> array */
void phpvk_struct_vkimagesubresourcelayers_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkImageSubresourceLayers size() -> int */
zend_long phpvk_struct_vkimagesubresourcelayers_size(void);

/*@zep Struct\VkBufferImageCopy pack(array members) -> int */
zend_long phpvk_struct_vkbufferimagecopy_pack(zval *members);

/*@zep Struct\VkBufferImageCopy packInto(int ptr, array members) -> void */
void phpvk_struct_vkbufferimagecopy_packinto(zval *ptr, zval *members);

/*@zep Struct\VkBufferImageCopy unpack(int ptr) -> array */
void phpvk_struct_vkbufferimagecopy_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkBufferImageCopy size() -> int */
zend_long phpvk_struct_vkbufferimagecopy_size(void);

/*@zep Struct\VkImageCopy pack(array members) -> int */
zend_long phpvk_struct_vkimagecopy_pack(zval *members);

/*@zep Struct\VkImageCopy packInto(int ptr, array members) -> void */
void phpvk_struct_vkimagecopy_packinto(zval *ptr, zval *members);

/*@zep Struct\VkImageCopy unpack(int ptr) -> array */
void phpvk_struct_vkimagecopy_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkImageCopy size() -> int */
zend_long phpvk_struct_vkimagecopy_size(void);

/*@zep Struct\VkBufferMemoryBarrier pack(array members) -> int */
zend_long phpvk_struct_vkbuffermemorybarrier_pack(zval *members);

/*@zep Struct\VkBufferMemoryBarrier packInto(int ptr, array members) -> void */
void phpvk_struct_vkbuffermemorybarrier_packinto(zval *ptr, zval *members);

/*@zep Struct\VkBufferMemoryBarrier unpack(int ptr) -> array */
void phpvk_struct_vkbuffermemorybarrier_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkBufferMemoryBarrier size() -> int */
zend_long phpvk_struct_vkbuffermemorybarrier_size(void);

/*@zep Struct\VkImageMemoryBarrier pack(array members) -> int */
zend_long phpvk_struct_vkimagememorybarrier_pack(zval *members);

/*@zep Struct\VkImageMemoryBarrier packInto(int ptr, array members) -> void */
void phpvk_struct_vkimagememorybarrier_packinto(zval *ptr, zval *members);

/*@zep Struct\VkImageMemoryBarrier unpack(int ptr) -> array */
void phpvk_struct_vkimagememorybarrier_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkImageMemoryBarrier size() -> int */
zend_long phpvk_struct_vkimagememorybarrier_size(void);

/*@zep Struct\VkMemoryBarrier pack(array members) -> int */
zend_long phpvk_struct_vkmemorybarrier_pack(zval *members);

/*@zep Struct\VkMemoryBarrier packInto(int ptr, array members) -> void */
void phpvk_struct_vkmemorybarrier_packinto(zval *ptr, zval *members);

/*@zep Struct\VkMemoryBarrier unpack(int ptr) -> array */
void phpvk_struct_vkmemorybarrier_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkMemoryBarrier size() -> int */
zend_long phpvk_struct_vkmemorybarrier_size(void);

/*@zep Struct\VkDispatchIndirectCommand pack(array members) -> int */
zend_long phpvk_struct_vkdispatchindirectcommand_pack(zval *members);

/*@zep Struct\VkDispatchIndirectCommand packInto(int ptr, array members) -> void */
void phpvk_struct_vkdispatchindirectcommand_packinto(zval *ptr, zval *members);

/*@zep Struct\VkDispatchIndirectCommand unpack(int ptr) -> array */
void phpvk_struct_vkdispatchindirectcommand_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkDispatchIndirectCommand size() -> int */
zend_long phpvk_struct_vkdispatchindirectcommand_size(void);

/*@zep Struct\VkPipelineCacheHeaderVersionOne pack(array members) -> int */
zend_long phpvk_struct_vkpipelinecacheheaderversionone_pack(zval *members);

/*@zep Struct\VkPipelineCacheHeaderVersionOne packInto(int ptr, array members) -> void */
void phpvk_struct_vkpipelinecacheheaderversionone_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPipelineCacheHeaderVersionOne unpack(int ptr) -> array */
void phpvk_struct_vkpipelinecacheheaderversionone_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPipelineCacheHeaderVersionOne size() -> int */
zend_long phpvk_struct_vkpipelinecacheheaderversionone_size(void);

/*@zep Struct\VkEventCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkeventcreateinfo_pack(zval *members);

/*@zep Struct\VkEventCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkeventcreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkEventCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkeventcreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkEventCreateInfo size() -> int */
zend_long phpvk_struct_vkeventcreateinfo_size(void);

/*@zep Struct\VkBufferViewCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkbufferviewcreateinfo_pack(zval *members);

/*@zep Struct\VkBufferViewCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkbufferviewcreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkBufferViewCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkbufferviewcreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkBufferViewCreateInfo size() -> int */
zend_long phpvk_struct_vkbufferviewcreateinfo_size(void);

/*@zep Struct\VkShaderModuleCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkshadermodulecreateinfo_pack(zval *members);

/*@zep Struct\VkShaderModuleCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkshadermodulecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkShaderModuleCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkshadermodulecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkShaderModuleCreateInfo size() -> int */
zend_long phpvk_struct_vkshadermodulecreateinfo_size(void);

/*@zep Struct\VkPipelineCacheCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkpipelinecachecreateinfo_pack(zval *members);

/*@zep Struct\VkPipelineCacheCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkpipelinecachecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPipelineCacheCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkpipelinecachecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPipelineCacheCreateInfo size() -> int */
zend_long phpvk_struct_vkpipelinecachecreateinfo_size(void);

/*@zep Struct\VkSpecializationMapEntry pack(array members) -> int */
zend_long phpvk_struct_vkspecializationmapentry_pack(zval *members);

/*@zep Struct\VkSpecializationMapEntry packInto(int ptr, array members) -> void */
void phpvk_struct_vkspecializationmapentry_packinto(zval *ptr, zval *members);

/*@zep Struct\VkSpecializationMapEntry unpack(int ptr) -> array */
void phpvk_struct_vkspecializationmapentry_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkSpecializationMapEntry size() -> int */
zend_long phpvk_struct_vkspecializationmapentry_size(void);

/*@zep Struct\VkSpecializationInfo pack(array members) -> int */
zend_long phpvk_struct_vkspecializationinfo_pack(zval *members);

/*@zep Struct\VkSpecializationInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkspecializationinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkSpecializationInfo unpack(int ptr) -> array */
void phpvk_struct_vkspecializationinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkSpecializationInfo size() -> int */
zend_long phpvk_struct_vkspecializationinfo_size(void);

/*@zep Struct\VkPipelineShaderStageCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkpipelineshaderstagecreateinfo_pack(zval *members);

/*@zep Struct\VkPipelineShaderStageCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkpipelineshaderstagecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPipelineShaderStageCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkpipelineshaderstagecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPipelineShaderStageCreateInfo size() -> int */
zend_long phpvk_struct_vkpipelineshaderstagecreateinfo_size(void);

/*@zep Struct\VkComputePipelineCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkcomputepipelinecreateinfo_pack(zval *members);

/*@zep Struct\VkComputePipelineCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkcomputepipelinecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkComputePipelineCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkcomputepipelinecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkComputePipelineCreateInfo size() -> int */
zend_long phpvk_struct_vkcomputepipelinecreateinfo_size(void);

/*@zep Struct\VkPushConstantRange pack(array members) -> int */
zend_long phpvk_struct_vkpushconstantrange_pack(zval *members);

/*@zep Struct\VkPushConstantRange packInto(int ptr, array members) -> void */
void phpvk_struct_vkpushconstantrange_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPushConstantRange unpack(int ptr) -> array */
void phpvk_struct_vkpushconstantrange_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPushConstantRange size() -> int */
zend_long phpvk_struct_vkpushconstantrange_size(void);

/*@zep Struct\VkPipelineLayoutCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkpipelinelayoutcreateinfo_pack(zval *members);

/*@zep Struct\VkPipelineLayoutCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkpipelinelayoutcreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPipelineLayoutCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkpipelinelayoutcreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPipelineLayoutCreateInfo size() -> int */
zend_long phpvk_struct_vkpipelinelayoutcreateinfo_size(void);

/*@zep Struct\VkSamplerCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vksamplercreateinfo_pack(zval *members);

/*@zep Struct\VkSamplerCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vksamplercreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkSamplerCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vksamplercreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkSamplerCreateInfo size() -> int */
zend_long phpvk_struct_vksamplercreateinfo_size(void);

/*@zep Struct\VkCopyDescriptorSet pack(array members) -> int */
zend_long phpvk_struct_vkcopydescriptorset_pack(zval *members);

/*@zep Struct\VkCopyDescriptorSet packInto(int ptr, array members) -> void */
void phpvk_struct_vkcopydescriptorset_packinto(zval *ptr, zval *members);

/*@zep Struct\VkCopyDescriptorSet unpack(int ptr) -> array */
void phpvk_struct_vkcopydescriptorset_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkCopyDescriptorSet size() -> int */
zend_long phpvk_struct_vkcopydescriptorset_size(void);

/*@zep Struct\VkDescriptorBufferInfo pack(array members) -> int */
zend_long phpvk_struct_vkdescriptorbufferinfo_pack(zval *members);

/*@zep Struct\VkDescriptorBufferInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkdescriptorbufferinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkDescriptorBufferInfo unpack(int ptr) -> array */
void phpvk_struct_vkdescriptorbufferinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkDescriptorBufferInfo size() -> int */
zend_long phpvk_struct_vkdescriptorbufferinfo_size(void);

/*@zep Struct\VkDescriptorImageInfo pack(array members) -> int */
zend_long phpvk_struct_vkdescriptorimageinfo_pack(zval *members);

/*@zep Struct\VkDescriptorImageInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkdescriptorimageinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkDescriptorImageInfo unpack(int ptr) -> array */
void phpvk_struct_vkdescriptorimageinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkDescriptorImageInfo size() -> int */
zend_long phpvk_struct_vkdescriptorimageinfo_size(void);

/*@zep Struct\VkDescriptorPoolSize pack(array members) -> int */
zend_long phpvk_struct_vkdescriptorpoolsize_pack(zval *members);

/*@zep Struct\VkDescriptorPoolSize packInto(int ptr, array members) -> void */
void phpvk_struct_vkdescriptorpoolsize_packinto(zval *ptr, zval *members);

/*@zep Struct\VkDescriptorPoolSize unpack(int ptr) -> array */
void phpvk_struct_vkdescriptorpoolsize_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkDescriptorPoolSize size() -> int */
zend_long phpvk_struct_vkdescriptorpoolsize_size(void);

/*@zep Struct\VkDescriptorPoolCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkdescriptorpoolcreateinfo_pack(zval *members);

/*@zep Struct\VkDescriptorPoolCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkdescriptorpoolcreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkDescriptorPoolCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkdescriptorpoolcreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkDescriptorPoolCreateInfo size() -> int */
zend_long phpvk_struct_vkdescriptorpoolcreateinfo_size(void);

/*@zep Struct\VkDescriptorSetAllocateInfo pack(array members) -> int */
zend_long phpvk_struct_vkdescriptorsetallocateinfo_pack(zval *members);

/*@zep Struct\VkDescriptorSetAllocateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkdescriptorsetallocateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkDescriptorSetAllocateInfo unpack(int ptr) -> array */
void phpvk_struct_vkdescriptorsetallocateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkDescriptorSetAllocateInfo size() -> int */
zend_long phpvk_struct_vkdescriptorsetallocateinfo_size(void);

/*@zep Struct\VkDescriptorSetLayoutBinding pack(array members) -> int */
zend_long phpvk_struct_vkdescriptorsetlayoutbinding_pack(zval *members);

/*@zep Struct\VkDescriptorSetLayoutBinding packInto(int ptr, array members) -> void */
void phpvk_struct_vkdescriptorsetlayoutbinding_packinto(zval *ptr, zval *members);

/*@zep Struct\VkDescriptorSetLayoutBinding unpack(int ptr) -> array */
void phpvk_struct_vkdescriptorsetlayoutbinding_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkDescriptorSetLayoutBinding size() -> int */
zend_long phpvk_struct_vkdescriptorsetlayoutbinding_size(void);

/*@zep Struct\VkDescriptorSetLayoutCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkdescriptorsetlayoutcreateinfo_pack(zval *members);

/*@zep Struct\VkDescriptorSetLayoutCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkdescriptorsetlayoutcreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkDescriptorSetLayoutCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkdescriptorsetlayoutcreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkDescriptorSetLayoutCreateInfo size() -> int */
zend_long phpvk_struct_vkdescriptorsetlayoutcreateinfo_size(void);

/*@zep Struct\VkWriteDescriptorSet pack(array members) -> int */
zend_long phpvk_struct_vkwritedescriptorset_pack(zval *members);

/*@zep Struct\VkWriteDescriptorSet packInto(int ptr, array members) -> void */
void phpvk_struct_vkwritedescriptorset_packinto(zval *ptr, zval *members);

/*@zep Struct\VkWriteDescriptorSet unpack(int ptr) -> array */
void phpvk_struct_vkwritedescriptorset_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkWriteDescriptorSet size() -> int */
zend_long phpvk_struct_vkwritedescriptorset_size(void);

/*@zep Struct\VkClearColorValue pack(array members) -> int */
zend_long phpvk_struct_vkclearcolorvalue_pack(zval *members);

/*@zep Struct\VkClearColorValue packInto(int ptr, array members) -> void */
void phpvk_struct_vkclearcolorvalue_packinto(zval *ptr, zval *members);

/*@zep Struct\VkClearColorValue unpack(int ptr) -> array */
void phpvk_struct_vkclearcolorvalue_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkClearColorValue size() -> int */
zend_long phpvk_struct_vkclearcolorvalue_size(void);

/*@zep Struct\VkDrawIndexedIndirectCommand pack(array members) -> int */
zend_long phpvk_struct_vkdrawindexedindirectcommand_pack(zval *members);

/*@zep Struct\VkDrawIndexedIndirectCommand packInto(int ptr, array members) -> void */
void phpvk_struct_vkdrawindexedindirectcommand_packinto(zval *ptr, zval *members);

/*@zep Struct\VkDrawIndexedIndirectCommand unpack(int ptr) -> array */
void phpvk_struct_vkdrawindexedindirectcommand_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkDrawIndexedIndirectCommand size() -> int */
zend_long phpvk_struct_vkdrawindexedindirectcommand_size(void);

/*@zep Struct\VkDrawIndirectCommand pack(array members) -> int */
zend_long phpvk_struct_vkdrawindirectcommand_pack(zval *members);

/*@zep Struct\VkDrawIndirectCommand packInto(int ptr, array members) -> void */
void phpvk_struct_vkdrawindirectcommand_packinto(zval *ptr, zval *members);

/*@zep Struct\VkDrawIndirectCommand unpack(int ptr) -> array */
void phpvk_struct_vkdrawindirectcommand_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkDrawIndirectCommand size() -> int */
zend_long phpvk_struct_vkdrawindirectcommand_size(void);

/*@zep Struct\VkStencilOpState pack(array members) -> int */
zend_long phpvk_struct_vkstencilopstate_pack(zval *members);

/*@zep Struct\VkStencilOpState packInto(int ptr, array members) -> void */
void phpvk_struct_vkstencilopstate_packinto(zval *ptr, zval *members);

/*@zep Struct\VkStencilOpState unpack(int ptr) -> array */
void phpvk_struct_vkstencilopstate_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkStencilOpState size() -> int */
zend_long phpvk_struct_vkstencilopstate_size(void);

/*@zep Struct\VkVertexInputAttributeDescription pack(array members) -> int */
zend_long phpvk_struct_vkvertexinputattributedescription_pack(zval *members);

/*@zep Struct\VkVertexInputAttributeDescription packInto(int ptr, array members) -> void */
void phpvk_struct_vkvertexinputattributedescription_packinto(zval *ptr, zval *members);

/*@zep Struct\VkVertexInputAttributeDescription unpack(int ptr) -> array */
void phpvk_struct_vkvertexinputattributedescription_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkVertexInputAttributeDescription size() -> int */
zend_long phpvk_struct_vkvertexinputattributedescription_size(void);

/*@zep Struct\VkVertexInputBindingDescription pack(array members) -> int */
zend_long phpvk_struct_vkvertexinputbindingdescription_pack(zval *members);

/*@zep Struct\VkVertexInputBindingDescription packInto(int ptr, array members) -> void */
void phpvk_struct_vkvertexinputbindingdescription_packinto(zval *ptr, zval *members);

/*@zep Struct\VkVertexInputBindingDescription unpack(int ptr) -> array */
void phpvk_struct_vkvertexinputbindingdescription_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkVertexInputBindingDescription size() -> int */
zend_long phpvk_struct_vkvertexinputbindingdescription_size(void);

/*@zep Struct\VkViewport pack(array members) -> int */
zend_long phpvk_struct_vkviewport_pack(zval *members);

/*@zep Struct\VkViewport packInto(int ptr, array members) -> void */
void phpvk_struct_vkviewport_packinto(zval *ptr, zval *members);

/*@zep Struct\VkViewport unpack(int ptr) -> array */
void phpvk_struct_vkviewport_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkViewport size() -> int */
zend_long phpvk_struct_vkviewport_size(void);

/*@zep Struct\VkPipelineColorBlendAttachmentState pack(array members) -> int */
zend_long phpvk_struct_vkpipelinecolorblendattachmentstate_pack(zval *members);

/*@zep Struct\VkPipelineColorBlendAttachmentState packInto(int ptr, array members) -> void */
void phpvk_struct_vkpipelinecolorblendattachmentstate_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPipelineColorBlendAttachmentState unpack(int ptr) -> array */
void phpvk_struct_vkpipelinecolorblendattachmentstate_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPipelineColorBlendAttachmentState size() -> int */
zend_long phpvk_struct_vkpipelinecolorblendattachmentstate_size(void);

/*@zep Struct\VkPipelineColorBlendStateCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkpipelinecolorblendstatecreateinfo_pack(zval *members);

/*@zep Struct\VkPipelineColorBlendStateCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkpipelinecolorblendstatecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPipelineColorBlendStateCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkpipelinecolorblendstatecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPipelineColorBlendStateCreateInfo size() -> int */
zend_long phpvk_struct_vkpipelinecolorblendstatecreateinfo_size(void);

/*@zep Struct\VkPipelineDepthStencilStateCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkpipelinedepthstencilstatecreateinfo_pack(zval *members);

/*@zep Struct\VkPipelineDepthStencilStateCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkpipelinedepthstencilstatecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPipelineDepthStencilStateCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkpipelinedepthstencilstatecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPipelineDepthStencilStateCreateInfo size() -> int */
zend_long phpvk_struct_vkpipelinedepthstencilstatecreateinfo_size(void);

/*@zep Struct\VkPipelineDynamicStateCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkpipelinedynamicstatecreateinfo_pack(zval *members);

/*@zep Struct\VkPipelineDynamicStateCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkpipelinedynamicstatecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPipelineDynamicStateCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkpipelinedynamicstatecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPipelineDynamicStateCreateInfo size() -> int */
zend_long phpvk_struct_vkpipelinedynamicstatecreateinfo_size(void);

/*@zep Struct\VkPipelineInputAssemblyStateCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkpipelineinputassemblystatecreateinfo_pack(zval *members);

/*@zep Struct\VkPipelineInputAssemblyStateCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkpipelineinputassemblystatecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPipelineInputAssemblyStateCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkpipelineinputassemblystatecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPipelineInputAssemblyStateCreateInfo size() -> int */
zend_long phpvk_struct_vkpipelineinputassemblystatecreateinfo_size(void);

/*@zep Struct\VkPipelineMultisampleStateCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkpipelinemultisamplestatecreateinfo_pack(zval *members);

/*@zep Struct\VkPipelineMultisampleStateCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkpipelinemultisamplestatecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPipelineMultisampleStateCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkpipelinemultisamplestatecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPipelineMultisampleStateCreateInfo size() -> int */
zend_long phpvk_struct_vkpipelinemultisamplestatecreateinfo_size(void);

/*@zep Struct\VkPipelineRasterizationStateCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkpipelinerasterizationstatecreateinfo_pack(zval *members);

/*@zep Struct\VkPipelineRasterizationStateCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkpipelinerasterizationstatecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPipelineRasterizationStateCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkpipelinerasterizationstatecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPipelineRasterizationStateCreateInfo size() -> int */
zend_long phpvk_struct_vkpipelinerasterizationstatecreateinfo_size(void);

/*@zep Struct\VkPipelineTessellationStateCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkpipelinetessellationstatecreateinfo_pack(zval *members);

/*@zep Struct\VkPipelineTessellationStateCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkpipelinetessellationstatecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPipelineTessellationStateCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkpipelinetessellationstatecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPipelineTessellationStateCreateInfo size() -> int */
zend_long phpvk_struct_vkpipelinetessellationstatecreateinfo_size(void);

/*@zep Struct\VkPipelineVertexInputStateCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkpipelinevertexinputstatecreateinfo_pack(zval *members);

/*@zep Struct\VkPipelineVertexInputStateCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkpipelinevertexinputstatecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPipelineVertexInputStateCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkpipelinevertexinputstatecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPipelineVertexInputStateCreateInfo size() -> int */
zend_long phpvk_struct_vkpipelinevertexinputstatecreateinfo_size(void);

/*@zep Struct\VkPipelineViewportStateCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkpipelineviewportstatecreateinfo_pack(zval *members);

/*@zep Struct\VkPipelineViewportStateCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkpipelineviewportstatecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkPipelineViewportStateCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkpipelineviewportstatecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkPipelineViewportStateCreateInfo size() -> int */
zend_long phpvk_struct_vkpipelineviewportstatecreateinfo_size(void);

/*@zep Struct\VkGraphicsPipelineCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkgraphicspipelinecreateinfo_pack(zval *members);

/*@zep Struct\VkGraphicsPipelineCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkgraphicspipelinecreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkGraphicsPipelineCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkgraphicspipelinecreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkGraphicsPipelineCreateInfo size() -> int */
zend_long phpvk_struct_vkgraphicspipelinecreateinfo_size(void);

/*@zep Struct\VkAttachmentDescription pack(array members) -> int */
zend_long phpvk_struct_vkattachmentdescription_pack(zval *members);

/*@zep Struct\VkAttachmentDescription packInto(int ptr, array members) -> void */
void phpvk_struct_vkattachmentdescription_packinto(zval *ptr, zval *members);

/*@zep Struct\VkAttachmentDescription unpack(int ptr) -> array */
void phpvk_struct_vkattachmentdescription_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkAttachmentDescription size() -> int */
zend_long phpvk_struct_vkattachmentdescription_size(void);

/*@zep Struct\VkAttachmentReference pack(array members) -> int */
zend_long phpvk_struct_vkattachmentreference_pack(zval *members);

/*@zep Struct\VkAttachmentReference packInto(int ptr, array members) -> void */
void phpvk_struct_vkattachmentreference_packinto(zval *ptr, zval *members);

/*@zep Struct\VkAttachmentReference unpack(int ptr) -> array */
void phpvk_struct_vkattachmentreference_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkAttachmentReference size() -> int */
zend_long phpvk_struct_vkattachmentreference_size(void);

/*@zep Struct\VkFramebufferCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkframebuffercreateinfo_pack(zval *members);

/*@zep Struct\VkFramebufferCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkframebuffercreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkFramebufferCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkframebuffercreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkFramebufferCreateInfo size() -> int */
zend_long phpvk_struct_vkframebuffercreateinfo_size(void);

/*@zep Struct\VkSubpassDependency pack(array members) -> int */
zend_long phpvk_struct_vksubpassdependency_pack(zval *members);

/*@zep Struct\VkSubpassDependency packInto(int ptr, array members) -> void */
void phpvk_struct_vksubpassdependency_packinto(zval *ptr, zval *members);

/*@zep Struct\VkSubpassDependency unpack(int ptr) -> array */
void phpvk_struct_vksubpassdependency_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkSubpassDependency size() -> int */
zend_long phpvk_struct_vksubpassdependency_size(void);

/*@zep Struct\VkSubpassDescription pack(array members) -> int */
zend_long phpvk_struct_vksubpassdescription_pack(zval *members);

/*@zep Struct\VkSubpassDescription packInto(int ptr, array members) -> void */
void phpvk_struct_vksubpassdescription_packinto(zval *ptr, zval *members);

/*@zep Struct\VkSubpassDescription unpack(int ptr) -> array */
void phpvk_struct_vksubpassdescription_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkSubpassDescription size() -> int */
zend_long phpvk_struct_vksubpassdescription_size(void);

/*@zep Struct\VkRenderPassCreateInfo pack(array members) -> int */
zend_long phpvk_struct_vkrenderpasscreateinfo_pack(zval *members);

/*@zep Struct\VkRenderPassCreateInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkrenderpasscreateinfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkRenderPassCreateInfo unpack(int ptr) -> array */
void phpvk_struct_vkrenderpasscreateinfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkRenderPassCreateInfo size() -> int */
zend_long phpvk_struct_vkrenderpasscreateinfo_size(void);

/*@zep Struct\VkClearDepthStencilValue pack(array members) -> int */
zend_long phpvk_struct_vkcleardepthstencilvalue_pack(zval *members);

/*@zep Struct\VkClearDepthStencilValue packInto(int ptr, array members) -> void */
void phpvk_struct_vkcleardepthstencilvalue_packinto(zval *ptr, zval *members);

/*@zep Struct\VkClearDepthStencilValue unpack(int ptr) -> array */
void phpvk_struct_vkcleardepthstencilvalue_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkClearDepthStencilValue size() -> int */
zend_long phpvk_struct_vkcleardepthstencilvalue_size(void);

/*@zep Struct\VkClearRect pack(array members) -> int */
zend_long phpvk_struct_vkclearrect_pack(zval *members);

/*@zep Struct\VkClearRect packInto(int ptr, array members) -> void */
void phpvk_struct_vkclearrect_packinto(zval *ptr, zval *members);

/*@zep Struct\VkClearRect unpack(int ptr) -> array */
void phpvk_struct_vkclearrect_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkClearRect size() -> int */
zend_long phpvk_struct_vkclearrect_size(void);

/*@zep Struct\VkClearValue pack(array members) -> int */
zend_long phpvk_struct_vkclearvalue_pack(zval *members);

/*@zep Struct\VkClearValue packInto(int ptr, array members) -> void */
void phpvk_struct_vkclearvalue_packinto(zval *ptr, zval *members);

/*@zep Struct\VkClearValue unpack(int ptr) -> array */
void phpvk_struct_vkclearvalue_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkClearValue size() -> int */
zend_long phpvk_struct_vkclearvalue_size(void);

/*@zep Struct\VkClearAttachment pack(array members) -> int */
zend_long phpvk_struct_vkclearattachment_pack(zval *members);

/*@zep Struct\VkClearAttachment packInto(int ptr, array members) -> void */
void phpvk_struct_vkclearattachment_packinto(zval *ptr, zval *members);

/*@zep Struct\VkClearAttachment unpack(int ptr) -> array */
void phpvk_struct_vkclearattachment_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkClearAttachment size() -> int */
zend_long phpvk_struct_vkclearattachment_size(void);

/*@zep Struct\VkImageBlit pack(array members) -> int */
zend_long phpvk_struct_vkimageblit_pack(zval *members);

/*@zep Struct\VkImageBlit packInto(int ptr, array members) -> void */
void phpvk_struct_vkimageblit_packinto(zval *ptr, zval *members);

/*@zep Struct\VkImageBlit unpack(int ptr) -> array */
void phpvk_struct_vkimageblit_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkImageBlit size() -> int */
zend_long phpvk_struct_vkimageblit_size(void);

/*@zep Struct\VkImageResolve pack(array members) -> int */
zend_long phpvk_struct_vkimageresolve_pack(zval *members);

/*@zep Struct\VkImageResolve packInto(int ptr, array members) -> void */
void phpvk_struct_vkimageresolve_packinto(zval *ptr, zval *members);

/*@zep Struct\VkImageResolve unpack(int ptr) -> array */
void phpvk_struct_vkimageresolve_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkImageResolve size() -> int */
zend_long phpvk_struct_vkimageresolve_size(void);

/*@zep Struct\VkRenderPassBeginInfo pack(array members) -> int */
zend_long phpvk_struct_vkrenderpassbegininfo_pack(zval *members);

/*@zep Struct\VkRenderPassBeginInfo packInto(int ptr, array members) -> void */
void phpvk_struct_vkrenderpassbegininfo_packinto(zval *ptr, zval *members);

/*@zep Struct\VkRenderPassBeginInfo unpack(int ptr) -> array */
void phpvk_struct_vkrenderpassbegininfo_unpack(zval *return_value, zval *ptr);

/*@zep Struct\VkRenderPassBeginInfo size() -> int */
zend_long phpvk_struct_vkrenderpassbegininfo_size(void);

#endif
