
extern zend_class_entry *vulkan_struct_vkapplicationinfo_vkapplicationinfo_ce;

ZEPHIR_INIT_CLASS(Vulkan_Struct_VkApplicationInfo_VkApplicationInfo);

PHP_METHOD(Vulkan_Struct_VkApplicationInfo_VkApplicationInfo, pack);
PHP_METHOD(Vulkan_Struct_VkApplicationInfo_VkApplicationInfo, packInto);
PHP_METHOD(Vulkan_Struct_VkApplicationInfo_VkApplicationInfo, unpack);
PHP_METHOD(Vulkan_Struct_VkApplicationInfo_VkApplicationInfo, size);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkapplicationinfo_vkapplicationinfo_pack, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkapplicationinfo_vkapplicationinfo_packinto, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, members, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkapplicationinfo_vkapplicationinfo_unpack, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_vulkan_struct_vkapplicationinfo_vkapplicationinfo_size, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(vulkan_struct_vkapplicationinfo_vkapplicationinfo_method_entry) {
	PHP_ME(Vulkan_Struct_VkApplicationInfo_VkApplicationInfo, pack, arginfo_vulkan_struct_vkapplicationinfo_vkapplicationinfo_pack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkApplicationInfo_VkApplicationInfo, packInto, arginfo_vulkan_struct_vkapplicationinfo_vkapplicationinfo_packinto, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkApplicationInfo_VkApplicationInfo, unpack, arginfo_vulkan_struct_vkapplicationinfo_vkapplicationinfo_unpack, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Vulkan_Struct_VkApplicationInfo_VkApplicationInfo, size, arginfo_vulkan_struct_vkapplicationinfo_vkapplicationinfo_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
