// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Vulkan\Ext\KHRSurface;

class KHRSurface
{
    public static function vkDestroySurfaceKHR(int instance, int surface, int pAllocator) -> void
    {
        khrsurface_vkdestroysurfacekhr(instance, surface, pAllocator);
    }

    public static function vkGetPhysicalDeviceSurfaceSupportKHR(int physicalDevice, int queueFamilyIndex, int surface, int pSupported) -> int
    {
        return khrsurface_vkgetphysicaldevicesurfacesupportkhr(physicalDevice, queueFamilyIndex, surface, pSupported);
    }

    public static function vkGetPhysicalDeviceSurfaceCapabilitiesKHR(int physicalDevice, int surface, int pSurfaceCapabilities) -> int
    {
        return khrsurface_vkgetphysicaldevicesurfacecapabilitieskhr(physicalDevice, surface, pSurfaceCapabilities);
    }

    public static function vkGetPhysicalDeviceSurfaceFormatsKHR(int physicalDevice, int surface, int pSurfaceFormatCount, int pSurfaceFormats) -> int
    {
        return khrsurface_vkgetphysicaldevicesurfaceformatskhr(physicalDevice, surface, pSurfaceFormatCount, pSurfaceFormats);
    }

    public static function vkGetPhysicalDeviceSurfacePresentModesKHR(int physicalDevice, int surface, int pPresentModeCount, int pPresentModes) -> int
    {
        return khrsurface_vkgetphysicaldevicesurfacepresentmodeskhr(physicalDevice, surface, pPresentModeCount, pPresentModes);
    }
}
