// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Vulkan\VK\VK11;

class VK11
{
    public static function vkEnumerateInstanceVersion(int pApiVersion) -> int
    {
        return vk11_vkenumerateinstanceversion(pApiVersion);
    }

    public static function vkBindBufferMemory2(int device, int bindInfoCount, int pBindInfos) -> int
    {
        return vk11_vkbindbuffermemory2(device, bindInfoCount, pBindInfos);
    }

    public static function vkBindImageMemory2(int device, int bindInfoCount, int pBindInfos) -> int
    {
        return vk11_vkbindimagememory2(device, bindInfoCount, pBindInfos);
    }

    public static function vkGetDeviceGroupPeerMemoryFeatures(int device, int heapIndex, int localDeviceIndex, int remoteDeviceIndex, int pPeerMemoryFeatures) -> void
    {
        vk11_vkgetdevicegrouppeermemoryfeatures(device, heapIndex, localDeviceIndex, remoteDeviceIndex, pPeerMemoryFeatures);
    }

    public static function vkCmdSetDeviceMask(int commandBuffer, int deviceMask) -> void
    {
        vk11_vkcmdsetdevicemask(commandBuffer, deviceMask);
    }

    public static function vkEnumeratePhysicalDeviceGroups(int instance, int pPhysicalDeviceGroupCount, int pPhysicalDeviceGroupProperties) -> int
    {
        return vk11_vkenumeratephysicaldevicegroups(instance, pPhysicalDeviceGroupCount, pPhysicalDeviceGroupProperties);
    }

    public static function vkGetImageMemoryRequirements2(int device, int pInfo, int pMemoryRequirements) -> void
    {
        vk11_vkgetimagememoryrequirements2(device, pInfo, pMemoryRequirements);
    }

    public static function vkGetBufferMemoryRequirements2(int device, int pInfo, int pMemoryRequirements) -> void
    {
        vk11_vkgetbuffermemoryrequirements2(device, pInfo, pMemoryRequirements);
    }

    public static function vkGetImageSparseMemoryRequirements2(int device, int pInfo, int pSparseMemoryRequirementCount, int pSparseMemoryRequirements) -> void
    {
        vk11_vkgetimagesparsememoryrequirements2(device, pInfo, pSparseMemoryRequirementCount, pSparseMemoryRequirements);
    }

    public static function vkGetPhysicalDeviceFeatures2(int physicalDevice, int pFeatures) -> void
    {
        vk11_vkgetphysicaldevicefeatures2(physicalDevice, pFeatures);
    }

    public static function vkGetPhysicalDeviceProperties2(int physicalDevice, int pProperties) -> void
    {
        vk11_vkgetphysicaldeviceproperties2(physicalDevice, pProperties);
    }

    public static function vkGetPhysicalDeviceFormatProperties2(int physicalDevice, int format, int pFormatProperties) -> void
    {
        vk11_vkgetphysicaldeviceformatproperties2(physicalDevice, format, pFormatProperties);
    }

    public static function vkGetPhysicalDeviceImageFormatProperties2(int physicalDevice, int pImageFormatInfo, int pImageFormatProperties) -> int
    {
        return vk11_vkgetphysicaldeviceimageformatproperties2(physicalDevice, pImageFormatInfo, pImageFormatProperties);
    }

    public static function vkGetPhysicalDeviceQueueFamilyProperties2(int physicalDevice, int pQueueFamilyPropertyCount, int pQueueFamilyProperties) -> void
    {
        vk11_vkgetphysicaldevicequeuefamilyproperties2(physicalDevice, pQueueFamilyPropertyCount, pQueueFamilyProperties);
    }

    public static function vkGetPhysicalDeviceMemoryProperties2(int physicalDevice, int pMemoryProperties) -> void
    {
        vk11_vkgetphysicaldevicememoryproperties2(physicalDevice, pMemoryProperties);
    }

    public static function vkGetPhysicalDeviceSparseImageFormatProperties2(int physicalDevice, int pFormatInfo, int pPropertyCount, int pProperties) -> void
    {
        vk11_vkgetphysicaldevicesparseimageformatproperties2(physicalDevice, pFormatInfo, pPropertyCount, pProperties);
    }

    public static function vkTrimCommandPool(int device, int commandPool, int flags) -> void
    {
        vk11_vktrimcommandpool(device, commandPool, flags);
    }

    public static function vkGetDeviceQueue2(int device, int pQueueInfo, int pQueue) -> void
    {
        vk11_vkgetdevicequeue2(device, pQueueInfo, pQueue);
    }

    public static function vkGetPhysicalDeviceExternalBufferProperties(int physicalDevice, int pExternalBufferInfo, int pExternalBufferProperties) -> void
    {
        vk11_vkgetphysicaldeviceexternalbufferproperties(physicalDevice, pExternalBufferInfo, pExternalBufferProperties);
    }

    public static function vkGetPhysicalDeviceExternalFenceProperties(int physicalDevice, int pExternalFenceInfo, int pExternalFenceProperties) -> void
    {
        vk11_vkgetphysicaldeviceexternalfenceproperties(physicalDevice, pExternalFenceInfo, pExternalFenceProperties);
    }

    public static function vkGetPhysicalDeviceExternalSemaphoreProperties(int physicalDevice, int pExternalSemaphoreInfo, int pExternalSemaphoreProperties) -> void
    {
        vk11_vkgetphysicaldeviceexternalsemaphoreproperties(physicalDevice, pExternalSemaphoreInfo, pExternalSemaphoreProperties);
    }

    public static function vkCmdDispatchBase(int commandBuffer, int baseGroupX, int baseGroupY, int baseGroupZ, int groupCountX, int groupCountY, int groupCountZ) -> void
    {
        vk11_vkcmddispatchbase(commandBuffer, baseGroupX, baseGroupY, baseGroupZ, groupCountX, groupCountY, groupCountZ);
    }

    public static function vkCreateDescriptorUpdateTemplate(int device, int pCreateInfo, int pAllocator, int pDescriptorUpdateTemplate) -> int
    {
        return vk11_vkcreatedescriptorupdatetemplate(device, pCreateInfo, pAllocator, pDescriptorUpdateTemplate);
    }

    public static function vkDestroyDescriptorUpdateTemplate(int device, int descriptorUpdateTemplate, int pAllocator) -> void
    {
        vk11_vkdestroydescriptorupdatetemplate(device, descriptorUpdateTemplate, pAllocator);
    }

    public static function vkUpdateDescriptorSetWithTemplate(int device, int descriptorSet, int descriptorUpdateTemplate, int pData) -> void
    {
        vk11_vkupdatedescriptorsetwithtemplate(device, descriptorSet, descriptorUpdateTemplate, pData);
    }

    public static function vkGetDescriptorSetLayoutSupport(int device, int pCreateInfo, int pSupport) -> void
    {
        vk11_vkgetdescriptorsetlayoutsupport(device, pCreateInfo, pSupport);
    }

    public static function vkCreateSamplerYcbcrConversion(int device, int pCreateInfo, int pAllocator, int pYcbcrConversion) -> int
    {
        return vk11_vkcreatesamplerycbcrconversion(device, pCreateInfo, pAllocator, pYcbcrConversion);
    }

    public static function vkDestroySamplerYcbcrConversion(int device, int ycbcrConversion, int pAllocator) -> void
    {
        vk11_vkdestroysamplerycbcrconversion(device, ycbcrConversion, pAllocator);
    }
}
